### ISSUE TITLE
Betaflight Configurator (Make users life easier)

### ISSUE THREAD

**Issue by borisbstyle** [betaflight/betaflight-configurator#1]
@skaman82 
You mentioned a while back you were willing to help me out with betaflight configurator? I added you in the configurator dev team with full write access.

**Comment by skaman82** [comment]
@borisbstyle Thanks. Any news on the betaflight logo? Do you have it in vector format?

**Comment by blckmn** [comment]
@daggad from RCGroups gave me this link:
https://www.dropbox.com/sh/88fpe7x353aojto/AACwbM73vmyGABqAkeZhHfuba?dl=0

for getting some stickers made up.

**Comment by skaman82** [comment]
@blckmn Thanks. Sadly it is not a vector format so I created a new logo I will use it if @borisbstyle likes it.

<img width="852" alt="bildschirmfoto 2016-06-11 um 12 32 07" src="https://cloud.githubusercontent.com/assets/11768024/15984565/c05bfde4-2fd0-11e6-951d-6290325182c8.png">

**Comment by skaman82** [comment]
@borisbstyle Logo files for further use

[BF_LogoFiles.zip](https://github.com/betaflight/betaflight-configurator/files/310977/BF_LogoFiles.zip)
![bf_logo](https://cloud.githubusercontent.com/assets/11768024/15993754/31ae6d86-30f0-11e6-830a-06d473a78d71.jpg)

**Comment by blckmn** [comment]
@skaman82 for the bee on the white background what does it look like with some black on its body?

**Comment by skaman82** [comment]
@blckmn something like this?
<img width="639" alt="bildschirmfoto 2016-06-12 um 23 03 24" src="https://cloud.githubusercontent.com/assets/11768024/15993808/f2a18694-30f1-11e6-914b-a7b3787fb285.png">

**Comment by borisbstyle** [comment]
Yeah that last bee looks better!
Op 12 jun. 2016 23:04 schreef "Albert Kravcov" <notifications@github.com>:

**Comment by skaman82** [comment]
Ok, will update the configurator tomorrow

Von meinem iPhone gesendet

**Comment by blckmn** [comment]
That's great. Awesome work.

**Comment by skaman82** [comment]
Updated logo files:
[Betaflight Logo.zip](https://github.com/betaflight/betaflight-configurator/files/311451/Betaflight.Logo.zip)
![bf_logo](https://cloud.githubusercontent.com/assets/11768024/16001422/2683b49a-3152-11e6-9d61-3c5c66e4adb5.png)

**Comment by JoeEurisko** [comment]
Awesome work,

Any way I can contribute to the development of the configurator?

**Comment by skaman82** [comment]
@JoeEurisko of cours you can, how are your JS/C skills?

**Comment by joehannouch** [comment]
@skaman82 Sorry just switched profiles,
I'm a game developer proficient in C++ and C# and long time web developer (front end).
I'm interested helping in both development and UX / UI as i've been a technical artist for quite some time.

Cheers

**Comment by skaman82** [comment]
@JoeEurisko Great to hear. Could you maybe help to create a new backup/restore tab? See: https://github.com/betaflight/betaflight-configurator/issues/9

**Comment by joehannouch** [comment]
@skaman82 Working on the backup/restore tab would be quite simple as an interface / css, but I would need some help when it comes to the functionality (backing up, saving prefs, etc.) where can i read about this? (i've swiftly read backup_restore.js, is that the way to go?)

**Comment by nathantsoi** [comment]
dude, @skaman82. nice work. this looks way better than my ponies :)

**Comment by RipperDrone** [comment]
Hi guys: Why don't you rename Betaflight to B-Flight or BFlight? Can be an acronym for BetaFlight, BorsFlight or Bee Flight which makes it fit to the wonderful logo that you created.

What do you think?

**Comment by devinpearson** [comment]
@ripperdrone the name change was discussed at length in https://github.com/betaflight/betaflight/issues/422 and was decided that it should remain the same

Some ideas I would like to see is s way to write recipes/scripts  or common setups to reduce redoing some of the config each upgrade. More like the setting up sbus and turning on telemetry or modes like beeper and failsafe

Moving the commonly used tabs up the list and maybe a summary tab where anything you would tweak while tuning was on one page

**Comment by RipperDrone** [comment]
@devinpearson understood, just thought I'd put my opinion in to try give merits to BorisB as the main promoter of BetaFlight by brnding his initial(s) into the product name.

Having a flex configurator which reads at runtime from a script style file which config elements and options to display is a very neat idea.

**Comment by Yamaford** [comment]
Didn't really want to start a new issue for a suggestion but what do you think of adding a new tab for experimental settings that may or may not pan out? If they become permanent they could then be moved over to the proper tab. This would be a good place to look for new features without constantly modifying the other tabs once the dust settles.

**Comment by borisbstyle** [comment]
there will be a pop up tab. No need to modify the existing one
Op 23 jun. 2016 00:44 schreef "Yamaford" <notifications@github.com>:
