### ISSUE TITLE
Todo: Change or remove the tracking routine

### ISSUE THREAD

**Issue by skaman82** [betaflight/betaflight-configurator#10]
The configurator has a build in analytics tracking. This should be changed or removed.

**Comment by nathantsoi** [comment]
i shouldda read the issue first :) https://github.com/betaflight/betaflight-configurator/pull/12

**Comment by KiteAnton** [comment]
I agree, it should be removed for now.  And as you (@nathansoi) mentioned in the pull requests as it is now the data is not available to us anyway.

**Comment by skaman82** [comment]
I think @borisbstyle should decide: 
• if he wants to keep the tracking but change it to another account 
• make tracking result accessible 
• or remove tracking entirely
