### ISSUE TITLE
Add raceflight selection mode and rates

### ISSUE THREAD

**Issue by IllusionFpv** [betaflight/betaflight-configurator#1005]
Hi, I'm trying raceflight rates but I need to set it on CLI, Can you add rate selection(betaflight-raceflight) on configurator?
Thanks

**Comment by mikeller** [comment]
Hi @IllusionFpv. The plan is to rework the way rates are set in Betaflight and make them parametrisable (like they already are on the TX). And then, in a next step, different ways to precalculate the parameters for 'Betaflgiht', 'RaceFlight', will be added to the configurator.
