### ISSUE TITLE
JETIEXBUS Serial Receiver Provider not working

### ISSUE THREAD

**Issue by paulboes73** [betaflight/betaflight-configurator#1008]
During set up in the configurator when selecting serial receiver provider as JETIEXBUS the configurator will reboot and set values to null in the receiver section.  When going to the receiver tab, nothing shows up.  I'm using Configurator 10.2.0 and betaflight 3.3.1.

**Comment by mikeller** [comment]
@paulboes73: What flight controller are you using?

**Comment by paulboes73** [comment]
betaflight f3 flight controller

**Comment by paulboes73** [comment]
Tested 3.2.5 build and there is no issue.

**Comment by mikeller** [comment]
JETIEXBUS has had to be removed from the standard builds for F3 targets to make room in the flash for other new features that were added, sorry.

If you want to use JETIEXBUS on the BETAFLIGHTF3, you'll have to do a custom build, enabling JETIEXBUS and disabling other RX protocols.

**Comment by paulboes73** [comment]
Will JETIEXBUS work for f4 and f7 boards?

**Comment by mikeller** [comment]
@paulboes73: Yes. F4 and F7 have more flash space and do not require the removal of features to make the firmware fit (as of now).
