### ISSUE TITLE
No warning for full destination drive when saving BB log

### ISSUE THREAD

**Issue by flint723** [betaflight/betaflight-configurator#1011]
I apologize if this has been addressed, I didn't find anything in a quick search of issues.

To reproduce: take a flash drive, fill it full, and try to save BB log from firmware via configurator, to full external flash drive via PC.  I'm using Configurator 10.2.0 with W10 1709 64 bit for this.  And 8gb usb flash drive formatted in fat32.

It creates the file and the progress bar proceeds normally, however if the drive is full the file will be 0kb.  If there was some available space it will save however much data until the drive is full, then the rest of the data is lost.

Not usually a big deal to lose a log or two before I realize the logs aren't saving, I need to manage my BB log flash drive better.  But maybe would be nice if there was some warning if the destination drive was full.

**Comment by mikeller** [comment]
Do I understand this right that you are trying to write a log file on the flight controller (i.e. the log file is written by the firmware)?
