### ISSUE TITLE
Add gyro_cal_on_first_arm

### ISSUE THREAD

**Issue by etracer65** [betaflight/betaflight-configurator#102]
Currently only available in the CLI.  Probably should go on the Configuration tab but I'm not sure where.

**Comment by mikeller** [comment]
This parameter is currently not available in MSP. We'll probably best defer the implementation of this until parameter groups have been implemented in firmware and configurator, instead of adding this to MSP.

**Comment by borisbstyle** [comment]
Yes this will have to wait
