### ISSUE TITLE
Add vbat_pid_compensation

### ISSUE THREAD

**Issue by etracer65** [betaflight/betaflight-configurator#103]
Another CLI-only parameter.  Probably should be on the Configuration tab in the "Battery Voltage" section.

**Comment by borisbstyle** [comment]
@mikeller
Can you add a checkbox for this perhaps?

**Comment by mikeller** [comment]
Next on my list. :-)

**Comment by mikeller** [comment]
@borisbstyle: Do you have a short explanation for this that we could use as a help text?
