### ISSUE TITLE
Pwm frequency separated from PID. SPF3 3.3.2

### ISSUE THREAD

**Issue by watageek** [betaflight/betaflight-configurator#1032]
Betaflight configurator 10.2.0 .exe
Win 10
SPFracing F3 4K/4K accel off ver: 3.3.2
DShot600 RS20AliteS

On betaflight configurator
-configuration tab
If i choose oneshot125, PWM separated from PID and 4k. SAVE

If I revert to dshot600 the PWM frequency stay in configuration tab

with oneshot125
I need to first change to 2k, SAVE
untick PWM separated from motor
SAVE

change protocol to DShot600, 4K, SAVE

**Comment by richard-scott** [comment]
Update your Configurator, that issue has been fixed.

**Comment by richard-scott** [comment]
https://github.com/betaflight/betaflight-configurator/pull/685

**Comment by mikeller** [comment]
Thanks @richard-scott, I thought it was, but couldn't find the issue.

**Comment by watageek** [comment]
Thanks
