### ISSUE TITLE
CPU Load

### ISSUE THREAD

**Issue by Faduf** [betaflight/betaflight-configurator#1038]
I'm testing the current developpment version of betaflight and its configurator. I remarked that the CPU load is different in the footer bar than the value given by the tasks command in the CLI. 

Which one is correct?

![capture d ecran de 2018-06-02 10-25-12](https://user-images.githubusercontent.com/17528067/40872514-b23fce0e-664f-11e8-8b14-97f67b943825.png)

**Comment by McGiverGim** [comment]
It seems that the correct one is the bottom bar: https://github.com/betaflight/betaflight/issues/6147
