### ISSUE TITLE
On pid page transition and level swapped.

### ISSUE THREAD

**Issue by grahamwho** [betaflight/betaflight-configurator#105]
In the gui in the new configurator,  level p and horizon transition are swapped. So if you had 16 for level strength 16 for horizon strength and 100 for transition the gui shows horizon 16, level 100, transition 16. Its right in the dump, but it could potentially confuse somebody who wasn't paying attention and obviously needs to be fixed. 
BTW the new configurator looks great guys, keep up the good work.

**Comment by grahamwho** [comment]
![rcgroupspierror](https://cloud.githubusercontent.com/assets/11497055/16743866/f8788ae8-4773-11e6-9fec-ba8015790179.jpg)

**Comment by mikeller** [comment]
Well spotted, fixed in #100.
