### ISSUE TITLE
Betaflight f4 osd tab empty

### ISSUE THREAD

**Issue by fpv-life** [betaflight/betaflight-configurator#1053]
Hello, I am running a betaflight f4 FC and I cannot seem to get the OSD working. When i start the drone the betaflight logo shows up on camera, but when I use betaflight osd tab it is empty like in the picture. I have not setup any OSD buttons and I arm the drone via switch. Any ideas?
![zajeta slika](https://user-images.githubusercontent.com/40304752/41485787-387a5754-70e2-11e8-9e3d-15e30bcc7c7f.PNG)

**Comment by fujin** [comment]
[Update your configurator to 10.2.0](https://github.com/betaflight/betaflight-configurator/releases/download/10.2.0/betaflight-configurator-installer_10.2.0_win32.exe)
