### ISSUE TITLE
Slow startup of standalone app on windows 10

### ISSUE THREAD

**Issue by frozenskys** [betaflight/betaflight-configurator#1056]
Startup time for the standalone configurator on my windows 10 machine (8 Core + 16Gb RAM + SSD) is around 2-3 minutes. After some research this seems to be an issue with packaged NWJS apps - https://github.com/nwjs/nw.js/issues/514 is one example. 

A change to the gulp.js file to add `zip: false` to the `nwBuilderOptions` object improves the startup speed to a couple of seconds. However this does move the slowness to the installer, and increases the install size...

**Comment by mikeller** [comment]
@frozenskys: Can you test if this solves the problem for you:

https://drive.google.com/file/d/1gOywQfEwb_d9FrYiAxNa31zPkmeDUc3m/view?usp=sharing

**Comment by frozenskys** [comment]
@mikeller Yup that's much better :)
Thanks!
