### ISSUE TITLE
In Filter Settings tab, some values do not reset to defaults when toggled off and back on

### ISSUE THREAD

**Issue by flint723** [betaflight/betaflight-configurator#1059]
Two of the fields do not remember BF default values if they are toggled off **and saved**.  Upon re-enabling the value is not default.

Gyro Lowpass 2 cutoff frequency
- default is 300, it returns 500 when re-enabling

Dterm Lowpass 2 cutoff frequency
- default is 200, it returns 300 when re-enabling

This is on standalone 64 bit windows configurator 10.3.0 build 223, I see there is a new one from 30 mins before I typed this.  I will check it here soon.
Edit: 224 is the same.

Unrelated but I think the toggles for Gyro Lowpass 1 cutoff frequency and Dterm Lowpass 1 cutoff frequency should be removed from GUI.  We don't want people accidentally turning those off.

**Comment by McGiverGim** [comment]
I will check it tomorrow...
