### ISSUE TITLE
Motors Tab Addition

### ISSUE THREAD

**Issue by JaYp247** [betaflight/betaflight-configurator#1060]
For current sensor calibration it would be nice to see a current meter on the the Motors tab of the configurator.

**Comment by McGiverGim** [comment]
If I'm not wrong, this was added some time ago. Could you check the capture here https://github.com/betaflight/betaflight-configurator/pull/973 ?

**Comment by JaYp247** [comment]
I never noticed it. You guys are awesome. Keep it up.

Sincere Thanks,
Michael Muehr
mmuehr31@gmail.com

**Comment by mikeller** [comment]
@JaYp247: If this solves your problem, can you please close this issue?

**Comment by JaYp247** [comment]
Issue resolved. Thank you.
