### ISSUE TITLE
Revolt OSD Arm Issue 3.4 RC2

### ISSUE THREAD

**Issue by drfelegis** [betaflight/betaflight-configurator#1061]
With 3.4 RC1 I had to raise gyro_calib_noise_limit to 60 to get the quad to arm. Now flashed RC2 and the quad won't arm again. Tried increasing the noise limit but no go this time. Flashed back to RC1 and flying again.

**Comment by drfelegis** [comment]
Also noticed my CPU load increase about 4% with RC2

**Comment by mikeller** [comment]
@drfelegis: What kind of load do you usually get?

**Comment by drfelegis** [comment]
28-29, now at 33%

**Comment by drfelegis** [comment]
Closing this issue because I posted int the config tab! Posting in the fw section
