### ISSUE TITLE
Build Type select for firmware flasher intermittent issue

### ISSUE THREAD

**Issue by richard-scott** [betaflight/betaflight-configurator#1063]
I'm testing with an SP Racing F7 Dual FC and when I try and flash it seems like the "Development" dropdown gets populated with the "Release" list of boards when BFC first starts. The BFC remembers I had selected a "Development" build type last time I ran the app, but it doesn't seem to load the correct list of boards on the nexxt run.

Here is the list when I first open BFC:

![2018-06-18 19_55_39-greenshot](https://user-images.githubusercontent.com/5149834/41556201-ee2c60dc-7331-11e8-85e6-65ba2eb08e96.png)

And this is the list after I change "Development" to "Release" and back to "Development".

![2018-06-18 19_57_08-greenshot](https://user-images.githubusercontent.com/5149834/41556206-f4c4fc6a-7331-11e8-9e8a-22bbf472f44c.png)

As you can see, SPRACINGF7DUAL is not in the first screenshot, but is in the second one.

**Comment by McGiverGim** [comment]
@DieHertz can you help with this?

**Comment by DieHertz** [comment]
Yes, once I get home
