### ISSUE TITLE
DSHOT Beacon Beeper Not working

### ISSUE THREAD

**Issue by estevanb** [betaflight/betaflight-configurator#1067]
I am using Matek F722D, Betaflight 3.4 RC2 with DAL RC 4in1 ESC (BLHeli 32) dshot beeper stopped working. I have tried CLI  "set beeper_dshot_beacon_tone = 1" + "save".
When activating beeper, LED on FC blinks but motors don´t sound.

**Comment by mikeller** [comment]
Read the release notes at https://github.com/betaflight/betaflight/releases/tag/v3.4.0-RC2.
