### ISSUE TITLE
Native Betaflight Configurator 10.2.0 - GPU Load at 100% and PC hangs

### ISSUE THREAD

**Issue by N4V1G4T0R** [betaflight/betaflight-configurator#1068]
Hello,

i have an issue that bugs me for a while now.

Wenn I connect a FC, the GPU load (not CPU nor MPU!) goes to 100% and the PC hangs occasionally. The PC hangs so bad, that even the mouse cursor won't work. It takes several minutes for the PC to recover. Then the animated Copter is gone. When I plug in the FC again, I see the cleanflight cube, instead of the animated copter, but no hanging anymore. Same issue with cleanflight by the way.

I already uninstalled all configurators on my PC and cleaned up the registry bevor reinstalling. No luck.

Windows 64 bit
Native Betaflight Configurator 10.2.0
Nvidia GPU

**Comment by mikeller** [comment]
@N4V1G4T0R: Not much we can do about this, unfortunately. We are using the NW.js toolkit to build the standalone application, which is essentially the internals of Chrome, without the browser. Any quirks that this toolkit has will be affecting the configurator. The next release of the configurator is just days away, and it is built with a newer version of NW.js, so hopefully this will fix the problems for you.

**Comment by N4V1G4T0R** [comment]
thanks for the fast reply. ok, I will check out the new release.

**Comment by N4V1G4T0R** [comment]
issue seems to be solved with the new configuartor (10.3)
