### ISSUE TITLE
High CPU usage when FC is connected

### ISSUE THREAD

**Issue by mikeller** [betaflight/betaflight-configurator#107]
Just noticed this today, but the configurator causes very high CPU load as soon as an FC is connected, to the point where other apps are noticeably slowed down. I did a quick check, and this is the case with Cleanflight configurator as well.

Will look into adding some sleep into the update loop to make it behave a bit nicer.

**Comment by borisbstyle** [comment]
Yeah noticed that for a long while. Been like that for long
Op 11 jul. 2016 22:20 schreef "Michael Keller" <notifications@github.com>:
