### ISSUE TITLE
Not open configurator linux

### ISSUE THREAD

**Issue by samuelrettore** [betaflight/betaflight-configurator#1074]
I use debian linux 9 and configurator not open 

![captura de tela de 2018-06-23 13-41-59](https://user-images.githubusercontent.com/5874205/41811724-4e1c0382-76eb-11e8-941b-683dd6da6166.png)

**Comment by binlan** [comment]
its triggert by the translation file. i fixed it for the german version with spaces.
`locales/pt/messages.json:        "message": "Tamanho da imagem inválida; era esperado $1x$2 ao invés de $3x$4"`
`locales/de/messages.json:        "message": "Ungültige Bildgröße; Es wird $1 x $2 statt $3 x $4 erwartet"`

is there a better way to fix it?

**Comment by mikeller** [comment]
Duplicates #1074.
