### ISSUE TITLE
OSD preview, crosshair not in center

### ISSUE THREAD

**Issue by Snake675** [betaflight/betaflight-configurator#1078]
![unbenannt](https://user-images.githubusercontent.com/32170531/41817298-62e0f3e2-7798-11e8-9116-3624b79055e7.PNG)

**Comment by mikeller** [comment]
The position of the crosshairs is adjustable. If they are set up to be out of center for your configuration, they will show as out of center in the preview. Just adjust them to wherever you want them.

**Comment by Snake675** [comment]
Yes. In reality (video feed) it is in the center, but in the preview of the Conigurator it is not.

**Comment by mikeller** [comment]
A `diff` would help to diagnose this...

**Comment by McGiverGim** [comment]
Exactly, we need to know at least at which version are you.

**Comment by Snake675** [comment]
Ok. I updated the Configurator from 10.3.0 to 10.3.1 and it's still there. The version of Betaflight is
DYSF4PRO (DYS4) 3.3.3 May 31 2018 / 13:00:53 (3565182d3) MSP API: 1.38. I tried to move the crosshair (little circle) into the center, but you can't.

diff

# version
# Betaflight / DYSF4PRO (DYS4) 3.3.3 May 31 2018 / 13:00:53 (3565182d3) MSP API: 1.38

# name
name Frog A

# resources
resource MOTOR 5 NONE
resource SONAR_TRIGGER 1 NONE
resource LED_STRIP 1 NONE
resource CAMERA_CONTROL 1 A01

# mixer

# servo

# servo mix


# feature
feature -RX_PARALLEL_PWM
feature RX_SERIAL
feature TELEMETRY
feature AIRMODE
feature ESC_SENSOR
feature ANTI_GRAVITY
feature DYNAMIC_FILTER

# beeper
beeper -GYRO_CALIBRATED
beeper -DISARMING
beeper -ARMING
beeper -ARMING_GPS_FIX
beeper -BAT_LOW
beeper -GPS_STATUS
beeper -ACC_CALIBRATION
beeper -ACC_CALIBRATION_FAIL
beeper -READY_BEEP
beeper -DISARM_REPEAT
beeper -ARMED
beeper -SYSTEM_INIT
beeper -ON_USB
beeper -CRASH FLIP
beeper -CAM_CONNECTION_OPEN
beeper -CAM_CONNECTION_CLOSED

# map

# serial
serial 0 64 115200 57600 0 115200
serial 2 1024 115200 115200 0 115200
serial 5 2048 115200 57600 0 115200

# led

# color

# mode_color

# aux
aux 0 0 0 900 1300 0
aux 1 1 2 900 1300 0
aux 2 1 2 1700 2100 0
aux 3 13 1 900 1300 0
aux 4 13 1 1700 2100 0
aux 5 26 4 1700 2100 0
aux 6 31 4 900 1300 0

# adjrange

# rxrange

# vtx

# rxfail
rxfail 5 s 1000

# master
set moron_threshold = 60
set mag_hardware = NONE
set baro_hardware = NONE
set rssi_channel = 16
set serialrx_provider = FPORT
set serialrx_halfduplex = ON
set motor_pwm_protocol = DSHOT1200
set bat_capacity = 1500
set current_meter = ESC
set battery_meter = ESC
set vbat_scale = 107
set pid_process_denom = 1
set osd_warnings = 19
set osd_cap_alarm = 1500
set osd_vbat_pos = 2497
set osd_rssi_pos = 2066
set osd_flymode_pos = 2059
set osd_vtx_channel_pos = 2072
set osd_crosshairs_pos = 2282
set osd_current_pos = 2518
set osd_mah_drawn_pos = 2552
set osd_craft_name_pos = 2049
set osd_warnings_pos = 2313
set osd_avg_cell_voltage_pos = 2529
set osd_disarmed_pos = 2539
set osd_esc_tmp_pos = 2106
set osd_esc_rpm_pos = 2080
set osd_core_temp_pos = 2138
set osd_stat_max_spd = OFF
set osd_stat_endbatt = ON
set osd_stat_bb_no = OFF
set osd_stat_tim_2 = OFF
set debug_mode = NOTCH
set vtx_band = 1
set vtx_power = 2
set vtx_freq = 5865
set camera_control_ref_voltage = 277
set camera_control_key_delay = 125

# profile
profile 0

set setpoint_relax_ratio = 1
set dterm_setpoint_weight = 100

# rateprofile
rateprofile 0

set roll_expo = 25
set pitch_expo = 25
set yaw_expo = 25

#

**Comment by McGiverGim** [comment]
Yes, only 3.4 let move the crosshair. I will look into this later.

**Comment by Snake675** [comment]
Moving the crosshair, hmm. How do you know, its in the center of the screen?

**Comment by McGiverGim** [comment]
No, I have reproduced your issue. With 3.3 the crosshair is not in the center of the screen. With 3.4 it seems to work right.

**Comment by McGiverGim** [comment]
The problem is that the new configurator is "reading" what the firmware sends, and it seems that the firmware sends in versions older than 3.3 was not correct. 

Can you verify if this happens for others locked elements like the artificial horizon and sidebars?

**Comment by mikeller** [comment]
I think I remember there being a pull request to change the origin for the elements that are more than 'just text' to be centered on the element.

**Comment by Snake675** [comment]
Ok. But does this make sense in case of the crosshair, sidebars and artificial horizon? Dont you want them to be in the center always? Possably you want to change the distance of the sidebars to each other?

**Comment by mikeller** [comment]
@Snake675: My comment wasn't meant as 'it is how it is, we won't change that', just as a pointer to why it is as it is, to make fixing it easier.

**Comment by McGiverGim** [comment]
@Snake675 I have made a fix, what system are you using? I can build a configurator for you to test if now it works as expected.

**Comment by Snake675** [comment]
Ok. I am using windwos 10.

**Comment by McGiverGim** [comment]
@Snake675 test with this version please: https://drive.google.com/drive/folders/1vQk_PYmmdvIx7Q1L-KL6138k42wdyRHQ

Thanks!
