### ISSUE TITLE
Configurator doesn't open

### ISSUE THREAD

**Issue by dns-rui** [betaflight/betaflight-configurator#1087]
Configurator 10.3 doesn't open on Win10.
A error message is displayed saying "Failed to load extension of: C:\Program Files (x86)\Betaflight\Betaflight-Configurator. Variable $1x$ used but not defined."
Already tried to uninstall, re-install, restart PC, without results.

**Comment by McGiverGim** [comment]
Has been fixed in master. The version 10.3.1 will be out soon.

**Comment by mikeller** [comment]
Duplicates #1073.
