### ISSUE TITLE
OSD not displaying on screen

### ISSUE THREAD

**Issue by Tbeal79** [betaflight/betaflight-configurator#1088]
just updated to 10.3 on here, then updated my jbf4 after i did the update to the 3.3.3. set it all up, went out to fly it and i have no osd on the screen at all.
i even come back in to make sure it was all on and everything, all is good as to the setup, but when i plug it in i get nothing on the screen, i have video but it displays nothing at all, i know its there bc i tryed to get into it and you can, but you cant get out of it bc you cant see what you are doing in there, so you have to unplug it to restart it.
not sure what is going on with that

**Comment by McGiverGim** [comment]
Start pasting a `diff` please.

**Comment by Tbeal79** [comment]
Ok I'll have to get one

Sent from Yahoo Mail on Android 
 
  On Wed, Jun 27, 2018 at 2:51 AM, Míguel Ángel Mulero Martínez<notifications@github.com> wrote:   
Start pasting a diff please.

**Comment by mikeller** [comment]
@Tbeal79: This sounds like a firmware problem, and not a configurator problem. Can you please close this, and open an issue (and supply all of the requested information) on https://github.com/betaflight/betaflight/issues?

**Comment by Tbeal79** [comment]
sure thing
