### ISSUE TITLE
Which code editor to be used to Debug the Betaflight Configurator source code?

### ISSUE THREAD

**Issue by VenkatalakshmiHB** [betaflight/betaflight-configurator#1090]
I am using Visual Studio 2017, is that the right way to go or is there any other alternative?

Thanks in advance!

**Comment by mikeller** [comment]
Usually it's easiest to use the 'Inspector' that is built into NW.js (the same as is in Chrome). Just start the configurator with `npm start` to use a build that is based on the 'debug' flavour of NW.js.

**Comment by fujin** [comment]
Emacs (spacemacs), Vim, Atom, VS Studio/Code, etc. Whatever you like.
