### ISSUE TITLE
NODE.JS  NPM START ERROR

### ISSUE THREAD

**Issue by dinizhobby** [betaflight/betaflight-configurator#1097]
C:\Arquivos de Programas\nodejs>npm install
up to date in 0.781s

C:\Arquivos de Programas\nodejs>npm start
npm ERR! path C:\Arquivos de Programas\nodejs\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Arquivos de Programa
s\nodejs\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mcdiniz\AppData\Roaming\npm-cache\_logs\2018-07-01T23_30_5
2_122Z-debug.log

C:\Arquivos de Programas\nodejs>

**Comment by mikeller** [comment]
> C:\Arquivos de Programas\nodejs>npm install

This does not look like you are running this in the directory where you've cloned the betaflight-configurator repository into - this will not work this way.
