### ISSUE TITLE
Configurator 10.3.1 ACC, Gyro problem

### ISSUE THREAD

**Issue by jpopillion** [betaflight/betaflight-configurator#1102]
I'm running Betaflight 3.4 rc5 for SP Racing F7 Dual FC.  on Configurator 10.3.0 I was able to disable the ACC to boost CPU performance and the Gyro's still worked.  On 10.3.1 when I disable the ACC the Gyro's stop responding and I cannot ARM the quad.  I have validated this on 3 seperate SP Racing F7 Dual boards running 3 different release candidates. They all react the same.

**Comment by McGiverGim** [comment]
If you disable it using CLI and you have the same problem then is a firmware problem and not a configurator problem. Have you tried it?

**Comment by jpopillion** [comment]
I have not I'll give that a try
