### ISSUE TITLE
Welcome Page - Blackbox link needs updating

### ISSUE THREAD

**Issue by wes1007** [betaflight/betaflight-configurator#1104]
Minor issue. the Link to download Betaflight Blackbox is pointing to the chrome app. When downloading the chrome app it says its out of date and points to https://github.com/betaflight/blackbox-log-viewer/releases/tag/3.0.0

**Comment by mikeller** [comment]
@wes1007: Well spotted. This has been fixed for the next release in https://github.com/betaflight/betaflight-configurator/pull/1095.

**Comment by McGiverGim** [comment]
I close this, it has been fixed.
