### ISSUE TITLE
Dterm setpoint weight GUI slider bar bug

### ISSUE THREAD

**Issue by quiljw01** [betaflight/betaflight-configurator#1105]
slider bar normally maxes out at 2.55.  But recently i notice it glitches out on higher values and visually resets toward the left.  Once this happens it allows you to choose up to value of 20.  And flies dangerously strange at this value.  it's easy to work around after you notice it flies bad, but if you don't notice, it can cause lots of headaches.

Jrod

![d setpoint weight bug max 20](https://user-images.githubusercontent.com/16867583/42405741-c643809a-8160-11e8-92d3-95cc2fefe37d.jpg)

**Comment by McGiverGim** [comment]
Betaflight 3.4 let's values until 20 to this element. Is not a bug. Some users wanted bigger values. You can use the same values as before without problem.
