### ISSUE TITLE
3/64 AV engines report malware in 10.3.1 win32 installer

### ISSUE THREAD

**Issue by caffeinatedgoat** [betaflight/betaflight-configurator#1107]
I realize this is likely due to the way it's packaged but perhaps it could be addressed as it's not a great look.

Link: https://www.virustotal.com/#/file/81cf9ce646df6fc221409dece4b5d27e5fb2dc7409837ec614661c5ba6ef839d/detection

**Comment by McGiverGim** [comment]
Yes, this happens with each new version of the configurator/blackbox that we release. Not too much that we can do to fix it. :-(

**Comment by mikeller** [comment]
Yeah, always the same for every release. I suspect the only way we could possibly improve this is if we spent money on a code signing certificate - signed applications seem to be given a lot of negative bias by most virus scanners.
To me, this looks a lot like an elaborate protection money extortion scheme - in particular if applied to an open source project.

**Comment by frozenskys** [comment]
Have seen this before with projects I have used NSIS - AV software dosen't seem to like it, and can generate a lot of false positives. The page is a little out of date (2017) but there is a list here : [NSIS False Positives](http://nsis.sourceforge.net/mediawiki/index.php?title=NSIS_False_Positives&oldid=24969)

**Comment by McGiverGim** [comment]
I think remember that in one of my tests, the installer generated from windows gave AV warnings, but the same windows installer generated from Linux didn't.

**Comment by mikeller** [comment]
@McGiverGim: That's good to know - until now I built the Windows installer under Windows, believing this to be less risky. But if building on linux results in an installer that is less prone to be flagged as a virus, then that seems to be a better option.

@caffeinatedgoat: Can you test this binary to see if it results in less detections: https://drive.google.com/file/d/1DL5MQF6kQFxUeXzboj3dupaFw7Duw8u5/view?usp=sharing

**Comment by McGiverGim** [comment]
@mikeller I uploaded your file to virustotal and only 1 engine detected it as a virus, in opposite to the original file, that is detected by 3 engines as a virus.

Here you have the results:
https://www.virustotal.com/#/file/ecd41169ec999ef37b68696265f96f95c7c21efdd98d49103fbf8cba550b0b3f/detection

**Comment by mikeller** [comment]
Thanks @McGiverGim. I replaced the released .exe with the one built on linux - if this results in less problems with virus scanners then that's a win.
