### ISSUE TITLE
No softserial in GUI

### ISSUE THREAD

**Issue by 0crap** [betaflight/betaflight-configurator#1108]
Using a Matek F405-STD and enable softserial in CLI, it will not show on the Ports page.
By default it shows:
-USB VCP
-UART1
-UART2
-UART3
-UART4
-UART5

**Comment by McGiverGim** [comment]
Do you assign it with the `resource` command to some pin? Without this it will not appear.

**Comment by 0crap** [comment]
No, no "resource" command used.
If I recall correctly it will also not show by simply enable softserial in Configuration tab.

**Comment by McGiverGim** [comment]
Usually yes. You must select what pins are you using for the soft-serial feature. If not Betaflight ignores which pins are you using for that. 
Check if that was the problem, and if right, please close this issue ;)

**Comment by 0crap** [comment]
Thx, I'll do when back at home.

**Comment by 0crap** [comment]
Works exactly as you said.
My misunderstanding.
Thx!
