### ISSUE TITLE
OSD Logo replacement does not work

### ISSUE THREAD

**Issue by presidenten** [betaflight/betaflight-configurator#1110]
I have a png-file that is accepted into the configurator and shows up correctly when selecting it.

I upload the image, upload the font. But when I start my quad, I still get the default Betaflight logo. 
I have tried digital font and default font.

I have also tried uploading a generated mcm-font from https://bflogo.ekezet.com/

But I always get the betaflight logo.

Using:
Hglrc f4 v5 pro (target Omnibus F4)
Betaflight 3.4
Betaflight configurator 10.3.1

**Comment by mikeller** [comment]
Interesting. Just for a test, can you try selecting a different font, and uploading that, and then check if the different font is used in the OSD?

**Comment by presidenten** [comment]
Huh! Look at that. Fonts do not seem to change for me.
Font before:
![image](https://user-images.githubusercontent.com/3883897/42722366-33132280-874b-11e8-87bf-cb35f34d9584.png)

Uploading betaflight font with new splash:
![image](https://user-images.githubusercontent.com/3883897/42722377-3e7950ae-874b-11e8-8c86-a3926e43765f.png)

Logo after:
![image](https://user-images.githubusercontent.com/3883897/42722379-470fe80e-874b-11e8-8a9f-7d7489681f0f.png)

Font after (not betaflight font):
![image](https://user-images.githubusercontent.com/3883897/42722380-50659458-874b-11e8-849a-9f0378adebdf.png)

**Comment by mikeller** [comment]
If uploading the font does not work either then I suspect that this is a hardware problem with your OSD chip not being writable. Unfortunately, there are bad clones of the chip used for the OSD out there, and HGLRC is a manufacturer known for bad quality products, so I suspect you'll have to change boards if you want to get this to work. The good news is: It'll still fly the same even without a custom boot logo! :-)

**Comment by presidenten** [comment]
I just want to verify that @mikeller was right. I flashed a xrotor f4 g2 and lo and behold, the fonts changed and to logo was added :-)

![image](https://user-images.githubusercontent.com/3883897/43197100-6b511dba-900a-11e8-9844-91d7f379c50d.png)

**Comment by lazerknight** [comment]
I have found a fix for your issue. When you are flashing your osd with either the bmp file or mcm font file. just make sure you have a battery plugged in. The 5v USB power isn't enough power. Had this issue on my Iflight mini f4.
