### ISSUE TITLE
Betaflight-configurator .deb package install error

### ISSUE THREAD

**Issue by martinglass** [betaflight/betaflight-configurator#1112]
Tried to install the .deb on Ubuntu 14.04 LTS and got this failure error message. Any ideas ?

 dpkg-deb: error: archive '/home/ubuntu/Downloads/betaflight-configurator_10.3.1_amd64.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
dpkg: error processing archive /home/ubuntu/Downloads/betaflight-configurator_10.3.1_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2

**Comment by mikeller** [comment]
Looks like this is a bug in ubuntu: https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627
