### ISSUE TITLE
[Feature Request] blheli-configurator on a tab in BFC

### ISSUE THREAD

**Issue by binlan** [betaflight/betaflight-configurator#1120]
wouldnt it be nice to have [blheli-configurator/blheli-configurator]() on a tab or somehow else integrated in bf-configurator. beside the fact that it would be convenient, it would save same space on our disks as well.

**Comment by mikeller** [comment]
We looked into this at some stage, but then it was decided that having separate apps would be preferable, because not everybody who uses BLHeli ESCs uses Betaflight, so forcing them to install the Betaflight configurator, and follow its update cycle, does not make much sense.
