### ISSUE TITLE
GPS datas aren(t export in CSV file

### ISSUE THREAD

**Issue by LeDoudou** [betaflight/betaflight-configurator#1136]
Does it possible to add GPS raws datas into .CSV files ? (Betaflight 3.4)

The datas below seems to be recorded : 
==============================

#ifdef USE_GPS
// GPS position/vel frame
static const blackboxConditionalFieldDefinition_t blackboxGpsGFields[] = {
    {"time",              -1, UNSIGNED, PREDICT(LAST_MAIN_FRAME_TIME), ENCODING(UNSIGNED_VB), CONDITION(NOT_LOGGING_EVERY_FRAME)},
    {"GPS_numSat",        -1, UNSIGNED, PREDICT(0),          ENCODING(UNSIGNED_VB), CONDITION(ALWAYS)},
    {"GPS_coord",          0, SIGNED,   PREDICT(HOME_COORD), ENCODING(SIGNED_VB),   CONDITION(ALWAYS)},
    {"GPS_coord",          1, SIGNED,   PREDICT(HOME_COORD), ENCODING(SIGNED_VB),   CONDITION(ALWAYS)},
    {"GPS_altitude",      -1, UNSIGNED, PREDICT(0),          ENCODING(UNSIGNED_VB), CONDITION(ALWAYS)},
    {"GPS_speed",         -1, UNSIGNED, PREDICT(0),          ENCODING(UNSIGNED_VB), CONDITION(ALWAYS)},
    {"GPS_ground_course", -1, UNSIGNED, PREDICT(0),          ENCODING(UNSIGNED_VB), CONDITION(ALWAYS)}
};

// GPS home frame
static const blackboxSimpleFieldDefinition_t blackboxGpsHFields[] = {
    {"GPS_home",           0, SIGNED,   PREDICT(0),          ENCODING(SIGNED_VB)},
    {"GPS_home",           1, SIGNED,   PREDICT(0),          ENCODING(SIGNED_VB)}
};
#endif

**Comment by mikeller** [comment]
@LeDoudou: This is already possible:

![image](https://user-images.githubusercontent.com/4742747/43349888-3ff33794-9257-11e8-94cc-1f8adfabde66.png)

**Comment by LeDoudou** [comment]
Hello @mikeller thanks.
Does the message means : 
 1. I connect my battery
 2. I start betaflight and select msp_raw_gps
 3. I don't go out of this tab, I just disconnect the usb cable and start to flight ?

**Comment by mikeller** [comment]
@LeDoudou: No, you need to stay connected to the configurator, otherwise the configurator won't be able to record logs, obviously.

**Comment by LeDoudou** [comment]
Sorry, but I would like to record GPS datas of the flight

**Comment by mikeller** [comment]
@LeDoudou: The Betaflight configurator won't be able to do this, since it needs a connection to the flight controller to be able to receive data.

**Comment by LeDoudou** [comment]
I think there's a misunderstanding.

Does it possible to : 
 1. Record gps datas in the blackbox during the flight.
 2. Be able to watch (or export) this datas in Betaflight Blackbox Explorer ?
