### ISSUE TITLE
[bug] configurator 10.4 hangs on "Ports" tab

### ISSUE THREAD

**Issue by libwtf** [betaflight/betaflight-configurator#1151]
configurator 10.4 from http://andwho.sytes.net:8080/job/BorisB_BetaFlight_Configurator/ (build261) hangs when going to "Ports" tab, can't change tab until i disconnect (button, not powercycle) and reconnect, all other tabs work.
Betaflight Maintenance 3.5 (AKK - RDQ VTX Patch) from https://ci.betaflight.tech/job/Betaflight%20Maintenance%203.5%20(AKK%20-%20RDQ%20VTX%20Patch)/lastSuccessfulBuild/artifact/

> Firmware upgrade required. Serial port configurations of firmware < 1.8.0 is not supported.

i can set ports settings thru CLI.

![bfv10 4](https://user-images.githubusercontent.com/4175259/43991365-ad098ea4-9d6b-11e8-8cfc-b759b5f8f3f2.JPG)

thanks!

**Comment by carloscampos775** [comment]
Same Message Here

Firmware upgrade required. Serial port configurations of firmware < 1.8.0 is not support

Using a Betaflight F4

**Comment by mikeller** [comment]
Configurator 10.4.0 is not released yet. Please use an official build.

**Comment by FrozenDroid** [comment]
You could've mentioned that it was indeed a bug. I can see it was fixed in #1152.
We were pointed to that build server by JB.

**Comment by frozenskys** [comment]
@FrozenDroid It's not a really bug when that version of software isn't released - if you are using un-official developer builds (not beta or RC builds) of software it may or may not work. JB should have been clear in his video that these are not even beta quality builds (they are just built off the latest version of the code) - and that it may have incomplete\buggy changes so YMMV.

**Comment by mikeller** [comment]
@libwtf: I never said it was not a bug - I just stated that you were reporting a bug for a version that does not exist, and should consider using a released version unless you are specifically testing configurator and are willing to use known buggy software and are willing to risk your configuration being messed up. (In this case, can you please start attaching console output to your bug reports, this will make them a lot more useful.)
