### ISSUE TITLE
Latest BFC shows wrong ESC features if Dshot enabled

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/betaflight-configurator#1153]
on the screenshot we can see that if dshot enabled the seperated motor pwm and the stick values are displayed ... imho but with dshot enabled should this not be displayed

![zwischenablagebild](https://user-images.githubusercontent.com/29702171/43999672-78a5037c-9e11-11e8-82d9-21dbf09b97eb.jpg)

**Comment by mikeller** [comment]
Yes, there still is a bug. Do you have time to look into this?

**Comment by TheIsotopes** [comment]
nope, sorry :( ... pls make you this
