### ISSUE TITLE
Ports Menu in 10.4 not showing

### ISSUE THREAD

**Issue by Granger69** [betaflight/betaflight-configurator#1157]
Everything else works but ports tab does not show anything.  

![screenshot 2018-08-12 10 12 59](https://user-images.githubusercontent.com/38549377/44005242-b39545fc-9e2d-11e8-9a55-d5c3b78304e5.png)
![screenshot 2018-08-12 10 12 45](https://user-images.githubusercontent.com/38549377/44005243-b3bfaeb4-9e2d-11e8-8302-9d4addf56412.png)
![screenshot 2018-08-12 10 13 05](https://user-images.githubusercontent.com/38549377/44005244-b3edac74-9e2d-11e8-9097-b23ed191be4c.png)

**Comment by mikeller** [comment]
@Granger69, @TheIsotopes: If you are installing unreleased development versions you should expect them to be broken, and potentially damaging your configuration.

If you do not want this, please do not install untested and broken development versions.
