### ISSUE TITLE
[Feature Request] Show rssi channel on failsafe tab

### ISSUE THREAD

**Issue by fape** [betaflight/betaflight-configurator#1164]
I think would be great to show RSSI channel too on failsafe tab, not just modes.
 Eg:
<img src="https://user-images.githubusercontent.com/1052464/44112278-f5827402-a004-11e8-8209-1af258cac560.PNG" width="330" /> <img src="https://user-images.githubusercontent.com/1052464/44112286-fc470faa-a004-11e8-87ab-d6d8b46f2097.PNG" width="330" />

**Comment by timman2er** [comment]
should be closed.
