### ISSUE TITLE
Absolute Control and Iterm Rotation can be enabled at the same time

### ISSUE THREAD

**Issue by watageek** [betaflight/betaflight-configurator#1173]
![itermrotation_absolute control](https://user-images.githubusercontent.com/25552059/44294318-6da82c00-a263-11e8-89ad-59e3f06af5b1.PNG)

Could it be possible to turn the other OFF automatically?

**Comment by mikeller** [comment]
Absolute control and iterm rotation can be enabled at the same time. Not sure if such a combination makes much sense, but in the interest of allowing users to test,  feature combinations that are not impossible / dangerous should not be prevented by the firmware.

**Comment by watageek** [comment]
Makes sense.

Ok, now I wonder if I put both to OFF. 🤔

**Comment by watageek** [comment]
Issue solved.
https://github.com/betaflight/betaflight/pull/6621
