### ISSUE TITLE
suggest:?? may add a delayed reboot command to firmware ??

### ISSUE THREAD

**Issue by imzhuli** [betaflight/betaflight-configurator#1175]
Issue: 
on my computer ( win7 ) and I am using OMMIF4SD v3-v3.5, sometimes when reboot(or save& rebot) is triggered, betaflight-configurator reports 'failed to disconnect the flight controller', and I have to unplug & re-plug the usb so  as to reconnect.  It happens now and then, I guess it's not a bug.
on my other computer (arch linux, kept up to date), this does not happen. I believe that's because Linux does not strongly hold an fd to a device(comm).

A possible guess: 
the flight controller does not send or reponse a 'disconnect' command quickly enough before rebooting. (I am not sure about the usb protocol), so that configurator failed to close the com properly, and still holds a handle(windows) to that, which prevent reconnection.

Fix ??
I guess it's possible to add a delayed reboot command to make sure configurator disconnect controller properly before the controller reboots.

**Comment by mikeller** [comment]
I have never heard of this problem, and I am not sure if this problem actually exists with more recent versions of Windows, so I am not sure if it makes sense to modify the firmware for this.
