### ISSUE TITLE
 Betaflight mac disconnect my drone when I power up my controller

### ISSUE THREAD

**Issue by kiwo12345** [betaflight/betaflight-configurator#1189]
I am trying to setup my very first fpv drone. I have a hawk 5 and I followed this tutorial: https://www.youtube.com/watch?time_conti...lWMlzYdh54

My controller and drone seems to pair since my drone shows the green light constantly when I power up my Frsky q x7 controller.

But if i connect my drone to betaflight using mac I can see all tabs and settings. But as soon as I power up my controller and it connects to my drone betaflight disconnects my drone..
Why is this happening?

Also, if I power up my drone it will beep once, connect to my controller. then do a never stoping long beeep.

**Comment by mikeller** [comment]
@kiwo12345: GitHub is for questions and discussion around the **development** of the firmware and tools. For questions around the configuration and use of Betaflight, please visit [RCGroups](https://www.rcgroups.com/forums/search.php?query=hawk).
