### ISSUE TITLE
Firmware tab "expert mode" incorrectly defaults to last build type

### ISSUE THREAD

**Issue by etracer65** [betaflight/betaflight-configurator#1192]
When enabling "Expert mode" then build type drop-down selects the last entry in the list - currently "Maintenance 3.5 (AKK - RDQ VTX Patch)" - but the firmware drop-down contains the versions as if the first entry "Release" is selected.

This has led to confusion for people who wanted the 3.5 AKK version thinking they were downloading it but in reality getting the normal release.

It looks like the build type drop-down needs to select the first entry in the list.

**Comment by smoriarty21** [comment]
https://github.com/betaflight/betaflight-configurator/pull/1196
