### ISSUE TITLE
Possibility to separate roll and pitch rates in gui.

### ISSUE THREAD

**Issue by chaotixtech** [betaflight/betaflight-configurator#1198]
This is a feature request.
Could we show the rates for roll and pitch separately in the pid tab, maybe only once the expert mode is selected. There is another Facebook post questioning why it's not an option still and it reminded me that I've wanted to request this for a while. I am aware of the ability to assign individual roll and pitch rates in cli which is not reflected in the gui.

**Comment by timman2er** [comment]
should be closed.

**Comment by chaotixtech** [comment]
Thank you.
