### ISSUE TITLE
'Barometer' in sensors tab is not barometer, but estimated altitude

### ISSUE THREAD

**Issue by jflyper** [betaflight/betaflight-configurator#1204]
It has been "estimated altitude" for a long long time 🤣

**Comment by McGiverGim** [comment]
It only prints the result of the msp command. Is better to change the firmware or simply change the text in the configurator by ALT?

**Comment by jflyper** [comment]
I have a mixed thoughts about this. The MSP itself is `MSP_ALTITUDE` and the current semantics is correct, and as I originally realized this while I was looking at an alternative  altitude code mikeller wrote, I preferred to be altitude. However, as the purpose of the sensors tab is to show how each sensor is functioning, straight barometer readout should be correct...

**Comment by mikeller** [comment]
If anything we should have both - 'barometer' readout to check the sensor output, 'altitude' readout to check that the altitude estimation (with all sensors) is working correctly, probably _not_ in the 'Sensors' tab.

**Comment by timman2er** [comment]
If anything, why is it's value limited to be between -1 and 1 right now? The barometer could read way different values on the bench.

**Comment by jflyper** [comment]
@timman2er Graphs in sensors tab are auto scaling.
