### ISSUE TITLE
OSD does not show settings

### ISSUE THREAD

**Issue by flash-v** [betaflight/betaflight-configurator#1206]
![2018-09-29 11 25 52](https://user-images.githubusercontent.com/36044146/46241023-cd553380-c3da-11e8-8b42-abd2f945c489.png)

**Comment by flash-v** [comment]
Because I can't use on the last stable release for Mac OS (not run) and there is a need to compile firmware by myself from last code.

**Comment by jflyper** [comment]
I have no trouble running 10.4.0 on OSX 10.13.6.
What kind of "not run" symptom do you have?

**Comment by flash-v** [comment]
![2018-09-30 20 55 52](https://user-images.githubusercontent.com/36044146/46258360-860e9600-c4f3-11e8-8046-d1204e0ae1bf.png)

The program is corrupt and can not be opened. Move the program to the trash.

**Comment by jflyper** [comment]
Try downloading a fresh dmg if you haven't done so.

**Comment by flash-v** [comment]
Downloaded today, an hour ago.

**Comment by jflyper** [comment]
I think it has something to do with the permissions of files in the package.

What is your osx revision?

**Comment by flash-v** [comment]
10.13.6

**Comment by jflyper** [comment]
How is your osx Security & Privacy "Allow apps downloaded from:" configured?

**Comment by flash-v** [comment]
"App store and from established developers

**Comment by flash-v** [comment]
Yes, you were right. Now everything works. Thank you so much.

**Comment by mikeller** [comment]
@flash-v: If the issue is resolved, can you please close it?
