### ISSUE TITLE
Google MAPs load issue

### ISSUE THREAD

**Issue by fotoamg** [betaflight/betaflight-configurator#1209]
![image](https://user-images.githubusercontent.com/33158920/46482220-79d95000-c7f5-11e8-8451-1e9c14aaad39.png)
See map message...

**Comment by mikeller** [comment]
Tested, Google maps works fine for me on the GPS tab. Could it be that you have a personal firewall or similar that is blocking configurator from accessing Google maps?

**Comment by fotoamg** [comment]
Hi today it fixed itself, I have no firewall and antivirus sw. I changednothing since tha error occured first, could be a temporary issue as works now:
![image](https://user-images.githubusercontent.com/33158920/46582431-e26b3b80-ca46-11e8-9f8b-2d5316b0b8f9.png)

**Comment by mikeller** [comment]
Could have been an outage of Google (yes, even they have that).
