### ISSUE TITLE
Packet errors

### ISSUE THREAD

**Issue by mchaos** [betaflight/betaflight-configurator#1210]
All of a sudden I get all sorts of packet errors and things take forever to load

**Comment by mikeller** [comment]
Have you tried using a different USB cable?

**Comment by DieHertz** [comment]
Watch your CPU load, things will take forever to load when it's 100%.

**Comment by mchaos** [comment]
No... With this issue... I am not at 32/32. My cousin load in this
situation is less than 10 at 8/8/8....
