### ISSUE TITLE
can not write new font to osd

### ISSUE THREAD

**Issue by robschii** [betaflight/betaflight-configurator#1212]
when i want to flash a new font (digital) after this the configurator close. 
![image](https://user-images.githubusercontent.com/17159193/46630574-e4b3bf80-cb44-11e8-8169-4373da855e47.png)

omnibis f4  (Flame F4)

**Comment by robschii** [comment]
bf 3.5.1

**Comment by mikeller** [comment]
It is normal that the flight controller reboots and the connection drops after the font has been flashed. Do you see the progress bar during the flashing process? Have you checked if the new font has been uploaded?

**Comment by robschii** [comment]
The progress bar runs to 100%
Sometimes its reboot sometimes not.  But the font did not change.  The flame f4 is a new one because my old flame f4 which I use more than 1 year lost the osd completely. This was the reason to change the fc

**Comment by mikeller** [comment]
Could it be that the flame is a HGLRC product?

They are well known for crappy product quality, and in particular for using cheap and unreliable clones of the MAX7456 chip that is used for the OSD. Looks like the one on your second board is not fully functional - time to get a refund.

**Comment by robschii** [comment]
Okay, I was the opinion that hglrc was good quality...   

This flame I had bought with the other one long time ago... 😢

**Comment by timman2er** [comment]
should be closed then.

**Comment by skulldrones** [comment]
I had the same problem to change font in FuryF3 (Diatone): the font has not updated. Work well in BFC 10.3.1, but don't work in BFC 10.4.0.
