### ISSUE TITLE
Saving on failsafe tab disables GPS-Rescue Failsafe

### ISSUE THREAD

**Issue by Footr** [betaflight/betaflight-configurator#1225]
I activated GPS-Rescue failsafe via the CLI.  I then went to the failsafe tab to change pulse timings.  After I saved that change GPS-Rescue was replaced with "Land" when I checked the diff.

**Comment by McGiverGim** [comment]
The save in the failsafe has only the old two options. Until the GPS rescue is added to this tab this is an expected behavior because the value is saved in the same parameter. I will look if it has been added to MSP, if added then this tab can be updated.

**Comment by mikeller** [comment]
@McGiverGim: Even if we do not yet have support for the parameters for GPS rescue, we could always just add support for selecting the mode itself (to avoid resetting it when the user saves the tab), and add a note that the parameters have to be set in CLI.

**Comment by McGiverGim** [comment]
I will look into it next week if nobody does it before
