### ISSUE TITLE
The PID Tuning page shows transposed Horizon Strength & Transition values compared to Cleanflight

### ISSUE THREAD

**Issue by TonyLeyland** [betaflight/betaflight-configurator#123]
It seems the Horizon values "Strength" and "Transition" are transposed on the PID Tuning page. 
I double checked by firing up the latest CleanFlight Configurator on the same copter.

I know I have a strength value of 6 and a Transition value of 50 and Betaflight Configurator shows these values in opposite places to Cleanflight Configurator. 

I've attached the 2 GUI screens here for reference.

Thanks
Tony

![17-07-2016 9-38-47 am](https://cloud.githubusercontent.com/assets/15789664/16905456/85dd504c-4ce9-11e6-9593-e3484bd46f62.jpg)

![17-07-2016 9-37-02 am](https://cloud.githubusercontent.com/assets/15789664/16905457/8d03e21e-4ce9-11e6-9c7a-92c5df803d4b.jpg)

**Comment by mikeller** [comment]
Fixed in #100. Try updating to the latest version of the betaflight configurator.

**Comment by TonyLeyland** [comment]
Cool, thanks for letting me know. Looks like 1.6.4 was released only a short time ago. 

Everything looks great, cheers.
