### ISSUE TITLE
Windows 10 cannot build betaflight configurator 10.4.0/10.4.1 for win32/win64. Found solution.

### ISSUE THREAD

**Issue by melenefoti** [betaflight/betaflight-configurator#1239]
My dear friends, i was trying to compile 10.4.0 / 10.4.1 betaflight configurator on windows 10, but while executing "gupl release --win32 --win64" the compile was crashing on "getChangesetId".
So, i commented the line 64 "gulp.task('get-changeset-id', getChangesetId);"
and changed the line 66: var distBuild = gulp.series(dist_src, dist_locale, dist_libraries, dist_resources, getChangesetId);
with this var distBuild = gulp.series(dist_src, dist_locale, dist_libraries, dist_resources);

removed "getChangesetId" element.

now it is compiling properly.

I attach a screenshot of the error
![betaflight_gulp_error](https://user-images.githubusercontent.com/24563267/49104414-94282b00-f286-11e8-9ba2-7f1e6acf0ec2.png)
.

**Comment by mikeller** [comment]
@melenefoti: Looks like the git repository you are trying to build from is broken: 

![image](https://user-images.githubusercontent.com/4742747/49106529-46dca580-f2e8-11e8-970d-461faaa792df.png)

Try cloning the repository into a new directory, and building from there.

**Comment by melenefoti** [comment]
thank very much, you are right. fixed the problem. i am closing the issue.
