### ISSUE TITLE
Inav Configurator- fail to close serial port

### ISSUE THREAD

**Issue by Cyremiaepf** [betaflight/betaflight-configurator#1242]
Hello,

I'm actually working on a MATEK f405-STD and i have an issue when i plug it on inav. Every time i try to save a new preset and i need to reboot, there is a failure during the process:

 EEPROM saved

2018-12-02 @ 15:51:05 -- Device - Rebooting

2018-12-02 @ 15:51:06 -- Unrecoverable failure of serial connection, disconnecting...

2018-12-02 @ 15:51:06 -- Failed to close serial port

I used zadig and Impulse RC driver to set the drivers.

Any ideas of how to fix it ?

Thanks

**Comment by etracer65** [comment]
This is the github for the Betaflight Configurator - not iNav.

I think you want here:
https://github.com/iNavFlight/inav-configurator

**Comment by Cyremiaepf** [comment]
Sorry, thanks !
