### ISSUE TITLE
Flash progress bar message incorrectly displayed

### ISSUE THREAD

**Issue by jflyper** [betaflight/betaflight-configurator#1265]
This happened only once. The message should be "Erasing ...".

<img width="1136" alt="betaflight_configurator" src="https://user-images.githubusercontent.com/14850998/50738340-2c1a1c80-1216-11e9-87e8-de84b43d2dec.png">

**Comment by McGiverGim** [comment]
Strange. Without a way to reproduce it or the log with the error in the developers console will be difficult to fix

**Comment by jflyper** [comment]
Nah, I've restarted it. But the flashing process was successful. Will try to capture something next time.
