### ISSUE TITLE
Inability to flash firmware on recent build of 10.5.0

### ISSUE THREAD

**Issue by chaotixtech** [betaflight/betaflight-configurator#1266]
Wishing to try out some BF4.0 goodies I built the configurator for osx64 from the code as of 6/1/19.
My issue is that when using the firmware flash feature, after loading either locally or online the fc is dropped into DFU but no flash takes place. 
I have 10.4 installed from my own build which can flash the local or online files fine so there isn't a problem with my files.
Is there any further info I should include?

**Comment by mikeller** [comment]
Any stack traces / error messages printed into the debug console would be appreciated.
