### ISSUE TITLE
[Feature Request] support mode logic (AND/OR) in GUI

### ISSUE THREAD

**Issue by howels** [betaflight/betaflight-configurator#1270]
https://github.com/betaflight/betaflight/pull/4722 introduced ability to enable modes using the boolean AND of ranges; for instance "set camera OSD mode if copter AUX1 <1600 AND AUX3>1600" instead of using the default "OR" logic.

The CLI syntax changes from:
```CLI_COMMAND_DEF("aux", "configure modes", NULL, cliAux)```

To: 

```CLI_COMMAND_DEF("aux", "configure modes", "<index> <mode> <aux> <start> <end> <logic>", cliAux)```

However the GUI doesn't recognise this. It would make it much easier to configure multiple modes if the AND/OR logic was implemented in the GUI

**Comment by McGiverGim** [comment]
Is there an MSP implementation of this? I only see CLI changes in the PR

**Comment by mikeller** [comment]
@McGiverGim: I don't think MSP support for this has been added yet - that is part of the work that should be done.

**Comment by dthubereng** [comment]
That would require me to learn Java, correct? Or is it Javascript? Either of those are pretty non-existent in my repertoire at the moment. I'm not averse to diving in though.
    On Friday, January 11, 2019, 11:26:21 PM CST, Michael Keller <notifications@github.com> wrote:  
 
 
@dthubereng: You wouldn't have time to add UI support in configurator for this? 😉

**Comment by McGiverGim** [comment]
This needs C first adding the feature to MSP in the firmware, and later Javascript in the configurator.

**Comment by mikeller** [comment]
@dthubereng: As @McGiverGim says, in a first stage the new parameters will have to be added to the MSP protocol in the firmware (see `src/main/interface/msp.c`). And then the client side will have to be done, which is JavaScript.
Happy to support you if you want to have a go at it.

**Comment by dthubereng** [comment]
I will take a look at it.

**Comment by dthubereng** [comment]
Firmware is done (no PR yet). Working through the configurator changes now in order to test both. Question: any recommendations on dev environments for running compiled Javascript? I've been using VSCode, which is great on both my mac and windows machines for writing firmware, but I don't really use it for debugging (no debug hardware other than an actual FC). @mikeller?

**Comment by McGiverGim** [comment]
The debug is done from chrome, if you start in debug mode `gulp debug` you can use the developers console (right click with the mouse).

**Comment by mikeller** [comment]
@dthubereng: I mostly use the debug console as well, but I've heard good things about  debugging NW.js (which is the framework the configurator is built in) from VS Code. Try https://marketplace.visualstudio.com/items?itemName=ruakr.vsc-nwjs

**Comment by dthubereng** [comment]
I'm pretty much done with this, but need to check on a few things before I submit the PR. I've never done any html, css, or js/jquery so this has been quite an experience and I will gladly accept any critique. I also added the configuration for the linkedTo option but didn't realize the two (logic and linked) were somewhat unrelated and should have been two separate PRs. So, the change will be simply adding an extra MSP message and the supporting GUI. PR forthcoming...
