### ISSUE TITLE
No scroll bar on left-hand frame - can't access CLI on laptop screen

### ISSUE THREAD

**Issue by joshuabardwell** [betaflight/betaflight-configurator#129]
On my laptop, I can't access the CLI because the left-hand pane does not have a scroll bar. On the Cleanflight Configurator, there is a scroll bar that lets me access them.

![7-19-2016 11-40-21 am](https://cloud.githubusercontent.com/assets/8303366/16956319/f0c876ea-4da5-11e6-96d5-c194c6478f09.png)

![7-19-2016 11-44-20 am](https://cloud.githubusercontent.com/assets/8303366/16956378/3d6e2616-4da6-11e6-9a72-847ca78a9f2b.png)

**Comment by deepimpactio** [comment]
Use the force Jedi ;)

**Comment by borisbstyle** [comment]
You seem to have some issues wirmth graphics too as the 3D model doesnt show up. I have seen this issue with someone else too who had 2 video cards in his pc activated.

**Comment by KiteAnton** [comment]
I have the same problem when using an old laptop with not enough resolution. Since adding the OSD tab the CLI tab got below what would fit the screen. If you resize the entire betaflight window then the scrollbar will appear.

**Comment by joshuabardwell** [comment]
The 3D model is not showing up because I am using a custom mixer. Completely normal.

**Comment by KiteAnton** [comment]
@joshuabardwell I was more refering to my own laptop (it is a cheap 11" one from 2011) not yours :) 

I agree, resizing is not a solution just a workaround. It was more to give some tips to anyone trying to find the CLI until the bug is fixed. 

I will investigate this if I get some free time during the weekend now.

**Comment by skaman82** [comment]
Fixed in https://github.com/betaflight/betaflight-configurator/commit/c3b4cb82f30045b345d9459bc36acd65c4594a09
