### ISSUE TITLE
MacOS . dmg file corrupt

### ISSUE THREAD

**Issue by Samedwin** [betaflight/betaflight-configurator#1298]
The current 10.4 version MacOS .dmg file is corrupt and does not work.

**Comment by mikeller** [comment]
@Samedwin: Have you tried downloading it again? There were 2400 users using 10.4.0 on  MacOS last week, so it's most likely that the corruption occurred during download.

**Comment by Samedwin** [comment]
Thanks for the reply!

I tried it 4x.
Let me try on another computer.

Thanks so much for replying. I didn’t except that!

Sam

**Comment by LucasGFPV** [comment]
Im having the same problem, and it fails to open once downloaded
