### ISSUE TITLE
4.0 #1441 matek f405-ctr won't connect after save and reboot, some times

### ISSUE THREAD

**Issue by laurentopia** [betaflight/betaflight-configurator#1302]
After adding gps on uart 4 and smart audio on uart, save and reboot, the configurator remains on the port page, so I disconnect and reconnect to refresh and get a Failed to open serial port.
I press the DTFU button, then disconnect then reconnect the USB and press connect again, this time it works.
Not half the time I have to do this Heimlich maneuver to get BF to burp into connection.

**Comment by mikeller** [comment]
@laurentopia: Have you tried with a different USB cable?

**Comment by laurentopia** [comment]
it ended up working after I reflashed the board.
