### ISSUE TITLE
Option for dark theme / skin 

### ISSUE THREAD

**Issue by Protonus** [betaflight/betaflight-configurator#1306]
I run all of my software on dark mode or skins, use Dark Reader for Chrome, etc.  I would love to see such an option for Betaflight Configurator, as many of the configuration pages which are most of the screen space used, are still bright white backgrounds.   The color scheme used by the sidebar and header in the app have an excellent color scheme with light gray text and dark gray backgrounds.  Would love to see that same color scheme on the configuration pages as well! 

Thank you in advance for your consideration.

**Comment by Docteh** [comment]
Not sure if you got a notification about PR #1473 but its added to the current development version.

Side thought: can the check-boxes be recolored? I know they could be back in the ugly days of the internet.
