### ISSUE TITLE
change display_name in configuration tab

### ISSUE THREAD

**Issue by binlan** [betaflight/betaflight-configurator#1316]
hi,
this change https://github.com/betaflight/betaflight-configurator/commit/ab83c79315b759a53f2695cab4207e900e9e52d6 brings display_name to OSD. The description say "as set in configuration tab". But thats not possible yet. Its cli-only at the moment.
Either we should change at least the description or better bring that to the configuration tab. Is somewhere able to do this?

**Comment by McGiverGim** [comment]
Fixed in https://github.com/betaflight/betaflight-configurator/pull/1317 . I close this by the moment. To bring it to the configuration tab, we need and MSP command for it, that will not be possible until version 4.1 at least.
