### ISSUE TITLE
Dterm_Lowpass1 + Dyn_Dterm_Lowpass conflict

### ISSUE THREAD

**Issue by Bradw-17** [betaflight/betaflight-configurator#1320]
In the PID Tuning tab, under filters, enabling "dyn_dterm_lowpass" disables "dterm_lowpass1", and vice versa. Only "dterm_lowpass2" can be run along with the "dyn_dterm_lowpass".

**Comment by McGiverGim** [comment]
This is not a bug. The firmware disables the static filter if you enable the dynamic filter. In the help tooltip is explained.

**Comment by Bradw-17** [comment]
Ahh true, my bad. Chasing down a couple issues and I must have overlooked that fact. Thanks!
