### ISSUE TITLE
Pitch D Min value is  wrong

### ISSUE THREAD

**Issue by eumelOne** [betaflight/betaflight-configurator#1321]
The D Min value on the PIDs page is shown wrong. Value is "29" but shown as "0".  

![image](https://user-images.githubusercontent.com/20325481/54458350-ea50a980-4763-11e9-812f-968e9cba52a4.png)

![image](https://user-images.githubusercontent.com/20325481/54458367-f76d9880-4763-11e9-8eaa-a54835292f43.png)

**Comment by McGiverGim** [comment]
I will look into it, thanks!

**Comment by McGiverGim** [comment]
I've been looking at this and there is no bug. Your pitch D value is 28. D_Min must be lower than that, if not D_Min is deactivated, that is what is being shown in the tab.

**Comment by eumelOne** [comment]
Seems pretty logical to me. My brain is out of order due to a cold... Sorry for stealing your time and thx for your help!
