### ISSUE TITLE
1.6.4 does not work with BF F3 2.8.1

### ISSUE THREAD

**Issue by Hwurzburg** [betaflight/betaflight-configurator#133]
trying to access either the config or pid tabs locks up the configurator....CF config works fins....also F3 CPU utilization goes to 100% under this condition, normally is at 25% with 4KHz cycle times until these tabs are accessed and lockup occurs

**Comment by Hwurzburg** [comment]
NM...just noticed no back compatibility in this thing

**Comment by UserNotFound** [comment]
Damn chrome extension auto-update :(
