### ISSUE TITLE
Small adjustment on Receiver tab

### ISSUE THREAD

**Issue by 0crap** [betaflight/betaflight-configurator#1331]
Can it be made possible to add a value for "Derivative Cutoff Frequency" to be higher then 255 Hz?

The configurator currently does not allow values >255.

A value of 300 Hz is currently used when testing new features.
![Receiver tab](https://user-images.githubusercontent.com/31951195/55021618-5dc2a880-4ff9-11e9-9b7c-bb8a812e447d.jpg)

**Comment by McGiverGim** [comment]
The Configurator uses the values that the MSP for the current version supports. Values higher of 255 maybe are added for Betaflight 4.1 but if I'm not wrong, in 4.0, that is the next release, 255 is the maximum.

**Comment by 0crap** [comment]
Fair enough!

**Comment by 0crap** [comment]
@McGiverGim Is it OK to reopen this issue?
4.0 is out the door and it would be great if this issue can be fixed on the next release.

**Comment by McGiverGim** [comment]
At this moment the changes that incremented this value are not in master of Betaflight, if I'm not wrong. Are the changes in master?

**Comment by mikeller** [comment]
Yes, this is still an `uint8_t` in the firmware:

https://github.com/betaflight/betaflight/blob/197796873d31bfebb25f305ecec962ca13a28c33/src/main/pg/rx.h#L58
