### ISSUE TITLE
Feature Request: Mode toggle 

### ISSUE THREAD

**Issue by skyfpv** [betaflight/betaflight-configurator#1334]
Introduce a feature which would allow a mode to be toggled on and off when the criteria are satisfied, as opposed to only being on when the criteria are satisfied and off when they are not. This would be useful for use with momentary switches to "activate" and "deactivate" a mode. It will also be really handy for radios with buttons like the Taranis X-Lite Pro.

**Comment by McGiverGim** [comment]
I can't see the difference. You decide if you put the mode in the satisfied or not range to enable or disable it. Can you put an example?

**Comment by McGiverGim** [comment]
Ah! You want tiggle the mode when pressing a button... Understood.

**Comment by mikeller** [comment]
@skyfpv: I think what you are trying to do should rather be done on the TX side than on the flight controller: Just set up a 'sticky' logical switch with your button as the input and reset functions, and it will work just fine as an on / off flip flop switch:

![opentx_toggle_switch](https://user-images.githubusercontent.com/4742747/55282278-c74e0880-53a5-11e9-86e2-29701e727993.gif)

Doing this on the flight controller will lead to unintended consequences, and potentially be dangerous: If there is a momentary loss of connection it will be impossible for the flight controller to determine the correct state of the mode after the connection is re-established, as it will have no way to know if the pilot has pushed the button in the mean time.

**Comment by skyfpv** [comment]
@mikeller While I understand that this can be done radio side, I feel implementing it in software will be appreciated for users of more simplistic radios like the turnigy evolution for example. Also, there is no safety hazard which does not already exist, especially since the position of modes during RX loss can be set in the failsafe tab.

**Comment by mikeller** [comment]
@skyfpv: 

> I feel implementing it in software will be appreciated for users of more simplistic radios like the turnigy evolution for example.

I am not quite sure what you mean by this. Looking at the Turnigy Evolution I can not see any buttons, only switches. Do you have examples of the transmitters you want this to work with?
