### ISSUE TITLE
Feature request: Restore defaults button for PID tab

### ISSUE THREAD

**Issue by aowi7280** [betaflight/betaflight-configurator#1340]
It would be nice to have a button to restore defaults for the just the PIDs without defaulting all the settings. Maybe another Restore defaults button for the filters tab. That would let people experiment a little without having to reset the entire flight controller if things don't work right.

**Comment by spatzengr** [comment]
@McGiverGim , I would say this is accomplished with #1598 .

**Comment by McGiverGim** [comment]
True, I close this.
