### ISSUE TITLE
betaflight-configurator_10.5.0_macOS.dmg not flashing

### ISSUE THREAD

**Issue by CitybirdFPV** [betaflight/betaflight-configurator#1359]
Hi, downloaded betaflight-configurator_10.5.0_macOS.dmg and was unable to flash any boards on a macbook pro High Sierra 10.13.6
downloaded betaflight-configurator_10.4.0_macOS.dmg and flashing is working again.

**Comment by mikeller** [comment]
@CitybirdFPV: Has this been fixed by 10.5.1?

**Comment by CitybirdFPV** [comment]
@mikeller Yes. Thank you.
