### ISSUE TITLE
10.5.1- LED Strip Function State always shows "None"

### ISSUE THREAD

**Issue by Lord-Quake** [betaflight/betaflight-configurator#1367]
I have my LED State set at "Function" to "Arm State".
GREEN = unarmed
RED = armed
Every time I load up the configurator "Function" shows "None".
"Save" was done.
On the quad the LEDs function as intended.

Is this a bug in the configurator or is this by design or is there a specific issue I'm having?

**Comment by mikeller** [comment]
@Lord-Quake: Sounds like a bug. Can you specify a bit more of your configuration, configurator / firmware versions, CLI `diff`, hardware used?

**Comment by Lord-Quake** [comment]
Sure.

It's a HGLRC XJB-145 stock with two LEDs.
I'm running BF 4.0 and Configurator 10.5.1.
Flashed with full erase and I configured the quad from scratch.
The DIFF: [BTFL_cli_QC_4_20190414_073755.zip](https://github.com/betaflight/betaflight-configurator/files/3077049/BTFL_cli_QC_4_20190414_073755.zip)
Worked fine until I updated to the above mentioned versions.

**Comment by mikeller** [comment]
Just tried to reproduce with your configuration - for me this is working fine:

![image](https://user-images.githubusercontent.com/4742747/56089802-aed50680-5eec-11e9-82a3-d13cf3a73ce3.png)

Are you sure you are actually selecting one of the configured LEDs?

**Comment by Lord-Quake** [comment]
I'm really sorry for having you go through my lack of smartness.....
Setting up the LEDs is something you do once and then never really change again. Since this was done a year or two ago I had assumed that the state would show up automatically once the configs are loaded. I didn't realize you needed to select the LED in addition to have the actual setting show up. I shall continue exploring BF 4.0 with more brains.

I'm closing this in shame.

Thank you for the time and work you put into this great project!!
