### ISSUE TITLE
Spelling mistake in german translation

### ISSUE THREAD

**Issue by fersold** [betaflight/betaflight-configurator#1372]
It spells 'Speichtern' instead of 'Speichern' on the save button in the adjustments tab
![Betaflight spelling mistake github](https://user-images.githubusercontent.com/49594526/56083067-b4651a80-5e20-11e9-89b7-733d8840afa6.jpg)

**Comment by McGiverGim** [comment]
The translations are controlled in Crowdin https://crowdin.com/project/betaflight-configurator

You can suggest there all the typos you find, is easy. You can do it too in the #team_translation channel in Betaflight Slack chat.

**Comment by McGiverGim** [comment]
I've translated this to one of the proofreaders of German. He has fixed it in Crowdin.
