### ISSUE TITLE
Wrong values for OSD position of element "Right stick"

### ISSUE THREAD

**Issue by vinz486** [betaflight/betaflight-configurator#1379]
Hi,
board with target MATEKF411RX flashed (erasing all settings) with BF 4.0.0.

BF Configurator 10.5.1.

I was trying to move the "right stick position" element on the top right angle of screen but when releasing the drag-n-drop element was moving to the upper left corner. At the same time, "right position element" was itself enabled to all 3 OSD profiles, but I was manually activating only for profile 1.

When I made a dump of cli configuration I got a red line error (see screenshot).

![Schermata da 2019-04-14 13-53-23](https://user-images.githubusercontent.com/2494005/56092558-da8cc800-5ebd-11e9-8c8c-0912592d043c.png)
[BTFL_cli_B65_20190414_4.0.0.txt](https://github.com/betaflight/betaflight-configurator/files/3077318/BTFL_cli_B65_20190414_4.0.0.txt)

**Comment by mikeller** [comment]
@vinz486: This is a known issue, and will be fixed once #1324 is complete.
