### ISSUE TITLE
Failed to load remote firmware

### ISSUE THREAD

**Issue by alexander-io** [betaflight/betaflight-configurator#1397]
Attempting to use Load Firmware [Online] function to  download kakute f4 v2 firmware

**Comment by swilkens** [comment]
I can't replicate this, the firmware loads fine for me. A few questions:

- Which version of the configurator are you using? Latest is [10.5.1 (click)](https://github.com/betaflight/betaflight-configurator/releases/tag/10.5.1)

- Which firmware release are you trying to download? I tried 4.0.0 final, it was fine.

Could it be that you have a firewall of some kind?

As an alternative, you can manually download the hex file here: [betaflight_4.0.0_KAKUTEF7V2.hex](https://github.com/betaflight/betaflight/releases/download/4.0.0/betaflight_4.0.0_KAKUTEF7V2.hex)

And use Load Firmware [Local]
