### ISSUE TITLE
Gyro lowpass2 filter settings carry over to other profiles.

### ISSUE THREAD

**Issue by ian444** [betaflight/betaflight-configurator#1400]
Using Configurator 10.5.1 with BF 4.0.0 latest stable release, setting the gyro lowpass2 cutoff frequency in any profile copies it to the other two profiles, i.e. gyro lowpass2 filter cannot be set independently in any profile.

**Comment by McGiverGim** [comment]
The gyro filters are not attached to the profiles. All the filters situated in the left tab are not attached to the profiles. Only the right table filters are associated to the profiles.

**Comment by ian444** [comment]
OK thanks, sorry for using up valuable time.
