### ISSUE TITLE
DShot beacon not working: RX_SET / RX_LOST features swapped?

### ISSUE THREAD

**Issue by RipperDrone** [betaflight/betaflight-configurator#1409]
Latest Nightlies dated Apr 29 for BF and BFC on Aikon F4: 

RX_SET (switch based) Dshot beacon doesn't sound unless I activate RX_LOST beacon. It seems the 2 beacon features are swapped / mixed up.

It points to the BF side of code since CLI reports feature RX_SET correctly as enabled. Still no beep when flicking the associated transmitter switch until I invoke RX_LOST.

**Comment by RipperDrone** [comment]
I tried to trace the code in both BF and BFC, but due to lack of understanding I could not really narrow it down:

- RX_SET and RX_LOST seem to be defined consistently, no confusion here
- descriptors seem to be right in BFC's DShot beacon tab as well

Finally, I could not identify where values from the switches tab are being assigned to the RX_SET status flag. Maybe there is a bug in the code assigning the switch value to RX_LOST state rather than RX_SET?

Afraid I would need some help of whoever is more familiar with Java and style sheets... :-/

**Comment by mikeller** [comment]
@RipperDrone: Can you close this please?

**Comment by RipperDrone** [comment]
sure, sry.
