### ISSUE TITLE
Feature Request to disabling unneeded tabs

### ISSUE THREAD

**Issue by TheAngularity** [betaflight/betaflight-configurator#141]
would it be possible to disable some tabs if they have not been activated this feature in the configuration tab? The configurator would become clearer and you configure only what's needed.
This concerns gps, osd, transponder, led strip and blackbox.

**Comment by skaman82** [comment]
It would be nice if hidden tabs would show up automaticly on on feature activation (GPS, LED, Transponder and so on)

Von meinem iPhon gesendet

**Comment by KiteAnton** [comment]
Yes I think could make sense, as it is now there is limited space available for some laptops with small screens so not all tabs fit properly.

**Comment by borisbstyle** [comment]
Yes great idea!

**Comment by TheAngularity** [comment]
> - OSD Tab (if the hardware supports it)
> - LED, Blackbox, Transponder, GPS (if the feature is activated in the config tab)

And for Adjustments, Servos and Tethered Logging there is also determined a solution.

**Comment by nathantsoi** [comment]
This is a great idea :)

**Comment by mikeller** [comment]
Anybody already working on this?

**Comment by TheAngularity** [comment]
> Anybody already working on this?

I just had the idea, so no (insufficient programming knowledge) ;)

**Comment by mikeller** [comment]
All good, I'm happy to do it, I'm just trying to avoid doubling up on work that's already being done. And thanks for making the feature request,  @TheAngularity.

**Comment by TheAngularity** [comment]
@mikeller 

Thats nice, thx. I only make a quick & dirty solution for my self.

I'm insert this in serial_backend.js from line 266

```
	$('#tabs ul.mode-connected li.tab_servos').hide();
	$('#tabs ul.mode-connected li.tab_gps').hide();
	$('#tabs ul.mode-connected li.tab_osd').hide();
	$('#tabs ul.mode-connected li.tab_transponder').hide();
	$('#tabs ul.mode-connected li.tab_logging').hide();
```

**Comment by TheAngularity** [comment]
closed now ... see #142
