### ISSUE TITLE
Autocomplete broken on 'set <parameter name>'

### ISSUE THREAD

**Issue by mikeller** [betaflight/betaflight-configurator#1419]
When using configurator side autocomplete in CLI, using the valid syntax

```
set <parameter_name>
```

![image](https://user-images.githubusercontent.com/4742747/57187979-4907f780-6f4b-11e9-9caa-78523181bcdd.png)

to get the current setting for a parameter is broken.

When hitting [Enter] on this, configurator modifies the input to

```
set <parameter_name> =
```

![image](https://user-images.githubusercontent.com/4742747/57187998-8076a400-6f4b-11e9-8b25-b1a515a045cc.png)

One more [Enter] will then set the parameter to 0, which is unintuitive, and will reset the user's setting, without giving him a chance to recover, except for discarding all his changes with `exit`:

![image](https://user-images.githubusercontent.com/4742747/57188011-bddb3180-6f4b-11e9-98ca-9f7c61bb21df.png)

As a suggestion, if configurator side auto complete is used, do only send the `=` after a `set` command if there is an value following it, and just send `set <parameter name> otherwise.

**Comment by McGiverGim** [comment]
I didn't know you can use set in this way. I always used get for this.

**Comment by mikeller** [comment]
Yes, you can. And it's a lot more convenient, because this allows you to use the command cache to then `set <parameter name> = <new value>` in the subsequent command.

**Comment by McGiverGim** [comment]
@Cleric-K have you time to look at this?

**Comment by Cleric-K** [comment]
Hi, I was on the go last few days. I'll take a look at this later today.
Thanks for mentioning my nick, I'm not subscribed to all events in the repos so I was not aware of this issue.

So basically this would be usable only for _non_-lookup values, because for lookup values you immediately get the suggestions and pressing enter will send the first in the list (or would have to press `Esc` first to hide the suggestions).
Is this the desired behavior?

Another possibility would be to _not_ show the lookup suggestions unless `Tab` is pressed or at least one character is typed in. Although I personally enjoy the lookup values popping up immediately.

Yet another variant is just not to add the `=` automatically. But I suspect that not that many users use `set` to get values and thus would prefer the `=` to be added auto.

**Comment by mikeller** [comment]
@Cleric-K: Yeah, not sure what best to do here. I'd almost say add the `=` once the parameter name has been selected, but if the user then hits [Enter], strip the `=` again and send `set <parameter name>`, based on the assumption that sending `set <parameter name> =` does not make any sense, and will evaluate to sending 0 (even if this isn't a valid value).

**Comment by Cleric-K** [comment]
Yes, that's the clear part. The question is what to do in case of lookup parameters?

**Comment by mikeller** [comment]
Heh, even worse there. But I'd essentially go for not selecting one, and just to a `set <parameter name>` if the user doesn't click / type / scroll to select one - pre-selecting the first value does not add much I think.

**Comment by Cleric-K** [comment]
I'll take a look but from memory it was not easily doable to make a list with no selected item. The selected index is buried in the lib code and I didn't see provision for index _none_.

In that case maybe the solution would be to show lookup values only after `Tab` or first char in.

**Comment by Cleric-K** [comment]
I looked around and here're my thoughts:

* Variant 1 - removing `=` before sending

As we said, one way to go around the problem with the lookup values would be to show the suggestions only if at least a char is typed in or `Tab` is pressed. Unfortunately this has the following caveat: if the suggestion list is _not_ showing, then pressing `Enter` is not handled by the autocomplete lib (it handles events only if the popup is active). So the `Enter` goes straight to the cli handler. This means that if we want to remove the `=` we have to do it there, which makes the whole thing a little ugly.

As a work around we can still show the lookup suggestions but inject an empty first entry, thus pressing enter would be detectable.

Yet, we still have the problem that if `Esc` is pressed (to hide the suggestions) and then press `Enter`, the `=` will be sent verbatim. Thus we have slightly inconsistent behavior depending on whether suggestions are shown or not.

* Variant 2

We can insert additional suggestion step.
After selecting the param _name_ we can show a static two entry list:
`=`
`<show value>`

Selecting the first will continue as in the current implementation. Selecting the second will execute and perform the _get_.
-- The cons of this method is that additional step is added.
-- The pros is that we avoid the inconsistent behavior and the magical erasure of the `=`. As a bonus this will actually hint at users that getting values with the `set` command is actually possible.

Additionally we can implement the `set` command in a similar way as `get` - adding the incomplete input as first entry in the suggestion list. Pressing enter on that would not need to open the `=` step but just execute the getting. I don't know if that will be useful.

**Comment by mikeller** [comment]
I actually quite like the second variant. You are correct in that the current implementation simply shortcuts the `set <parameter name> version of the command, so there should be an additional step to add the `=`. Yes, it adds a step, but this is just because the current implementation is missing one. And overall the tab completion still improves the workflow drastically.

**Comment by McGiverGim** [comment]
This was fixed in #1424 and https://github.com/betaflight/betaflight-configurator/pull/1436 so I suppose that we can close this issue? Is something pending?

**Comment by Asizon** [comment]
Returning to this situation @mikeller , Why have two functions for the same thing? I think we should standardize this, `Set` command only to change information and not to show values, `Get` command to show information, I think it would be a clearer and more concise way. In this way it could also be shown again `=` in the set autocomplete, and use each command only for one function. Another possibility is to eliminate `Get` and use `Set` for everything?

**Comment by mikeller** [comment]
@Asizon: Not sure why you want to 'fix' what is not broken? The `set <value>` syntax is useful for discovery, i.e. you want to set the motor protocol to Dshot, you start typing `set motor`, then you stop because you are not sure what the exact name of the parameter is. So you hit [Enter], and you get

```
# set motor
[...]
motor_pwm_protocol = ONESHOT125
Allowed values: OFF, ONESHOT125, ONESHOT42, MULTISHOT, BRUSHED, DSHOT150, DSHOT300, DSHOT600, PROSHOT1000
[...]
```
