### ISSUE TITLE
Receiver tab is crashing

### ISSUE THREAD

**Issue by skaman82** [betaflight/betaflight-configurator#146]
<img width="1045" alt="bildschirmfoto 2016-07-26 um 19 07 00" src="https://cloud.githubusercontent.com/assets/11768024/17147716/3a8d16be-5364-11e6-92e9-3dae294799b6.png">

**Comment by mikeller** [comment]
Tried to reproduce this, but receiver tab loads fine for me in current master. Did you get any log info in the console? How did you get there?

**Comment by skaman82** [comment]
@mikeller  I just clicked on the Receiver tab. Console showing this:
<img width="1007" alt="bildschirmfoto 2016-07-26 um 21 16 17" src="https://cloud.githubusercontent.com/assets/11768024/17152035/5dde82bc-5376-11e6-998a-3a37a8ebf25e.png">

**Comment by mikeller** [comment]
Could be related to the changes I made in the firmware. See #147.
