### ISSUE TITLE
Save button moved places in Mac dev builds

### ISSUE THREAD

**Issue by bizmar** [betaflight/betaflight-configurator#1468]
Heads up, if this was not an intended change.

Save used to be the right most button, at the bottom right, of the window. Now in a lot of tabs it is has been swapped around. Not sure what commit did this, I noticed it in PID tuning after repeatedly refreshing my old settings instead of saving. (muscle memory is hard to brake even if you know the button moved 😅) I'm guessing it's like this on other platforms.

Tested on a MacBook Pro 2015, logical resolution 1440x900. Window resizing did not change button positions. 

As of #1439

<img width="1358" alt="Screenshot 2019-05-28 at 12 08 13" src="https://user-images.githubusercontent.com/4053708/58470568-3f387500-8142-11e9-98f6-19872cb6bbb4.png">
<img width="1358" alt="Screenshot 2019-05-28 at 12 08 19" src="https://user-images.githubusercontent.com/4053708/58470574-43fd2900-8142-11e9-8b18-8c819e017a4f.png">
<img width="1358" alt="Screenshot 2019-05-28 at 12 08 24" src="https://user-images.githubusercontent.com/4053708/58470582-48c1dd00-8142-11e9-8bfd-e47bdf941c02.png">
<img width="1358" alt="Screenshot 2019-05-28 at 12 08 36" src="https://user-images.githubusercontent.com/4053708/58470594-4f505480-8142-11e9-8210-9467d469d529.png">
may have been like this for a while ⬇️
<img width="1358" alt="Screenshot 2019-05-28 at 12 08 44" src="https://user-images.githubusercontent.com/4053708/58470602-54150880-8142-11e9-9181-660b6330b2d7.png">

**Comment by McGiverGim** [comment]
I will look into it. Thanks for reporting!
