### ISSUE TITLE
PID type is hidden in the PID Tab

### ISSUE THREAD

**Issue by skaman82** [betaflight/betaflight-configurator#147]
<img width="484" alt="bildschirmfoto 2016-07-26 um 19 06 42" src="https://cloud.githubusercontent.com/assets/11768024/17147734/50cbb2f0-5364-11e6-9123-31b8d1db69cf.png">

**Comment by mikeller** [comment]
Tried to reproduce this, but PID selection worked fine for me in master. Did you get an exception or other logs in the console? What steps did you take to get there?

**Comment by skaman82** [comment]
No errors in the console. But timeouts.
<img width="1014" alt="bildschirmfoto 2016-07-26 um 21 16 09" src="https://cloud.githubusercontent.com/assets/11768024/17152048/6c5cbd4a-5376-11e6-95df-1af0aafa8b16.png">

**Comment by mikeller** [comment]
Ha, could be related to the changes I made in https://github.com/betaflight/betaflight/pull/821. Have you tried updating your firmware?

**Comment by skaman82** [comment]
@mikeller will try that. I can compile the newest master at home (9 om and still at work). I am running a version from  3 Jul on my test board here.

**Comment by borisbstyle** [comment]
Probably your version is too old. Not worth trying to solve these things.
The pid controller order for example changed.

All unreleased versions dont count in terms of support.
3.0 is still not finished and more will be added. It is a huge one and
thats why it takes longer.
Before looking into issue always verify against the latest master.

**Comment by mikeller** [comment]
@skaman82: You should be able do download the latest build from http://andwho.sytes.net:8080/job/BorisB_BetaFlight/lastSuccessfulBuild/artifact/obj/
