### ISSUE TITLE
copy profiles values do not work for profile 3

### ISSUE THREAD

**Issue by rolo95** [betaflight/betaflight-configurator#1472]
Dear Betaflight Team,
im using BFC 10.5.1
on the PID Tuning Tab TAB if i want to copy profiles values to profile 3, nothing get copied
profiles 2 and 1 works when you copy from other profiles

But if i am on Profile 1 or 2 i canot copy to 3, seems like it works, but when you switch to profile 3 ,original values remain, so you need to move them manually

Also if im on profile 3 , i canot copy to 1 or 2
so nothing can get copied to profile 3 or from profile 3 to the others
i just confirmed it just now

**Comment by McGiverGim** [comment]
This is a known issue and has been fixed for version 4.0.3 of the firmware: https://github.com/betaflight/betaflight/pull/8331
