### ISSUE TITLE
Modi Tab is empty

### ISSUE THREAD

**Issue by Hawxxer** [betaflight/betaflight-configurator#1478]
Connecting the Eachine Trashcan to Betaflight 10.5.1 the "Modi" page shows only Arm also the gui getting unresponsive, so I need to reconnect to the quad.
Version 10.4.0 works fine.
![betaflight bug](https://user-images.githubusercontent.com/46371370/58991203-f3dc3180-87e7-11e9-851b-7b28730863c9.PNG)

**Comment by Hawxxer** [comment]
Tested on Windows and MacOS

**Comment by binlan** [comment]
https://www.youtube.com/watch?v=slmUbB-dZsw

**Comment by mikeller** [comment]
Duplicate of #1335.
