### ISSUE TITLE
Bottom bar has moved down

### ISSUE THREAD

**Issue by Docteh** [betaflight/betaflight-configurator#1489]
![image](https://user-images.githubusercontent.com/190571/59411142-6cef0200-8d6f-11e9-8e99-06c1a44daff4.png)

Some sort of CSS issue.  `div with class of content_toolbar` is being tucked underneath the `status-bar` instead of above.

My suggestion would be to add more padding to the bottom, like `padding: 10px 0 24px 0;` But that doesn't fix whatever caused this, and doesn't fix the cli tab.

https://github.com/betaflight/betaflight-configurator/blob/bb72a44f84ec0b403647f74554d01087c2c88104/src/css/main.css#L1042-L1051

**Comment by McGiverGim** [comment]
I'm trying to reproduce the problem without luck. Using the minimum size that the Configurator lets, my buttons are in place:
![image](https://user-images.githubusercontent.com/2673520/59423190-f46d5d00-8dd1-11e9-8f85-4644c8ba4ec7.png)

Can you explain step by step how to get to this issue?

**Comment by Docteh** [comment]
Thanks. I'll look into it and let you know. It could be

~~1) extra files~~
~~2) I'm using the x64 development version of NWJS 0.38.2~~
3) A [Byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark) in main.html that gets stripped somewhere in the gulp process. But wont get stripped if someone were use rsync or robocopy. 

```
[/Web/betaflight-configurator] # hexdump -C src/main.html
00000000  ef bb bf ef bb bf 3c 21  44 4f 43 54 59 50 45 20  |......<!DOCTYPE |
00000010  68 74 6d 6c 3e 0a 3c 68  74 6d 6c 3e 0a 3c 68 65  |html>.<html>.<he|
```
