### ISSUE TITLE
Todo: Docs Button should be updated 

### ISSUE THREAD

**Issue by skaman82** [betaflight/betaflight-configurator#15]
The documentation button refers to a non existing page. But I can't find any docs in the betaflight directory to link to

![bildschirmfoto 2016-06-17 um 19 54 54](https://cloud.githubusercontent.com/assets/11768024/16159862/6331670e-34c5-11e6-9f66-19aefa64d09e.png)

**Comment by nathantsoi** [comment]
done in https://github.com/betaflight/betaflight-configurator/pull/16
