### ISSUE TITLE
[FR] Add Blackbox debug modes to the Blackbox tab.

### ISSUE THREAD

**Issue by bizmar** [betaflight/betaflight-configurator#1502]
Add Blackbox debug modes to the Blackbox tab. Probably as a dropdown menu. Maybe incorporate or link to[ this wiki article](https://github.com/betaflight/betaflight/wiki/Debug-Modes). And maybe order the list the same way as it's in the article, but if that prevents it from being auto generated, then go for the least amount of future maintainability. :)

Maybe make Gyro_scaled the default, instead of none? (putting this here to start a discussion, please don't disregard the while request because of this part)

I'm requesting this addition because if I ask someone to make me a BB log, they have to go into 3 different tabs to set it up in a meaningful way.

**Comment by mikeller** [comment]
This will first have to be added to MSP in the firmware.

**Comment by etracer65** [comment]
We don't want to set a default `debug_mode`. Doing so will increase the log size and cause a performance hit (particularly for things related to the gyro).

**Comment by bizmar** [comment]
> We don't want to set a default `debug_mode`. Doing so will increase the log size and cause a performance hit (particularly for things related to the gyro).

Yes, it uses more resources but it also gives valuable data, and if logging with it enabled, actually affects flight performance... well, that raises big questions...

Having debug modes in the same tab will be enough for now. 😄
