### ISSUE TITLE
motor direction switch in latest win GUI missing !!!

### ISSUE THREAD

**Issue by yo8aiv** [betaflight/betaflight-configurator#1503]
as title says motor direction switch in GUI is missing
the interface is supposed to make life easyer right.

its annoying because when i fly low all the grass get's thrown as a salad in the camera lens so i prefer reversing motor rotation to avoid it.

![BFmotor_direction](https://user-images.githubusercontent.com/24196117/59981290-7561fb00-9601-11e9-9ae4-2ae0dff898da.jpg)

meaning i prefer having a graphical representation of how motor direction is set in the FC.
if this has been submitted just link the issue.

_**also** same thing i have seen missing in latest inav win GUI interface app aswell._

thanks.

**Comment by McGiverGim** [comment]
This is Betaflight, not iNav. Maybe wrong place to put the issue?

**Comment by yo8aiv** [comment]
sorry corrected .. sort of my way of expressing the issue (not my main language eng!!). But no its related to BF since the image is BF gui.

**Comment by mikeller** [comment]
@yo8aiv: As your screen shot shows, the option is clearly there in Betaflight configurator. I suspect that you are trying to use it with firmware that is too old, and does not support setting this option through the GUI. You have to update the firmware, or use the CLI to set this option `yaw_motors_reversed`.

**Comment by etracer65** [comment]
Maybe you're confused by the function of this switch? It just tells the firmware that you have reversed the direction of the motors. It does not cause the motors to be reversed.

**Comment by yo8aiv** [comment]
hello. thanks for your answers.
 yes i admit i got a bit confused with all the versions ... win and chrome.  
the fw wasn't too old was 3.5.3 wich had this enabled at the time i had everything configured. 
i will properly test everything and report back.

**Comment by yo8aiv** [comment]
Just a suggestion.  I knew that .. but may of my friends didn't . so can a HINT be added to that switch with this/your  phrase : 

>  It just tells the firmware that you have reversed the direction of the motors. It does not cause the motors to be reversed.
