### ISSUE TITLE
Battery calibration broken

### ISSUE THREAD

**Issue by mikeller** [betaflight/betaflight-configurator#1510]
Reproduction:

- open the battery tab

Experienced behaviour:

The battery tab is shown, but at the bottom of it elements of the battery calibration tab are showing as well:

![image](https://user-images.githubusercontent.com/4742747/60385036-e8bfad00-9ad8-11e9-809f-4937ced4921e.png)

Expected behaviour:

The battery tab is shown without extra elements.

@IvoFPV: Can you look into this please?

**Comment by IvoFPV** [comment]
I'll have a look right now
