### ISSUE TITLE
Failsafe stage2

### ISSUE THREAD

**Issue by skaman82** [betaflight/betaflight-configurator#152]
I can not enable stage2 in the failsafe settings. If I enable stage2 and click save nothing happens.  If I want to go to another tab after this, the configurator hangs. Following console error on save in the failsafe tab. Tested with lasest configurator/firmware master.

<img width="1009" alt="bildschirmfoto 2016-07-26 um 23 09 30" src="https://cloud.githubusercontent.com/assets/11768024/17155660/5938e09e-5386-11e6-9267-3ee1cc498ba4.png">

**Comment by mikeller** [comment]
Oops, didn't check that one when I switched over the features code to be more self contained. Will look into it.

**Comment by skaman82** [comment]
@mikeller just fixed the layout via https://github.com/betaflight/betaflight-configurator/commit/37164a2bbaccfcb344c3b88f0f60735a6fb3903b I think we can close this now

**Comment by mikeller** [comment]
Ha, you are a CSS wizard. Thanks!

**Comment by mikeller** [comment]
By the way, if you add 'Fixes #x' as a comment to your pull requests or commits, github will close ticket x automatically.
