### ISSUE TITLE
Connect F411 to iA6

### ISSUE THREAD

**Issue by moge11** [betaflight/betaflight-configurator#1532]
Hello,
I'm new to drones and my drone parts arrive in a couple of weeks, but I'd like to train in the meantime. I saw that you can install Betaflight on the F411 Discovery board and because I had one lying around, I thought I, why not try it. But I'm not able to connect my iA6 receiver to the board.

Thanks in advance

**Comment by mikeller** [comment]
@moge11: GitHub is for discussion and bug reports around _development_ of Betaflight. For help with configuring it, join our [Facebook group](https://www.facebook.com/groups/betaflightgroup/), [Slack](https://slack.betaflight.com/), or search in online resources like RCGroups.
