### ISSUE TITLE
Cannot get into receiver tab with Crossfire

### ISSUE THREAD

**Issue by jaysfann** [betaflight/betaflight-configurator#1543]
I upgraded my Betaflight Configurator and since I cant get the receiver tab to work with battery plugged into my quad using crossfire.
Im using a DYS F4 and F4pro board. Odd thing is that it worked on an older configurator and I cant remember which one it was. 
I also tried reflashing to the latest firmware and it didnt help. 
Another odd thing is that I have a quad with a different board that runs off of Uart 6 and its fine. 
The other 3 quads are using Uart 3.
Any suggestions

**Comment by Docteh** [comment]
Are you able to load the receiver tab without a battery?

What is the version of the betaflight configurator that you are using right now, like are you running `10.5.1` or did you upgrade to the `10.6.0` version that is currently under development?

Also what is running on the board? the output of `version` what is needed there.
