### ISSUE TITLE
10.5.1 on Ubuntu 18.04: Not getting left side menu nor welcome screen content

### ISSUE THREAD

**Issue by RRAlex** [betaflight/betaflight-configurator#1548]
As a follow up to #1541, I'm attaching what happens when I start betaflight-operator as a user that has the correct dialout group setup:

![betaflight-operator-user-issue](https://user-images.githubusercontent.com/3272818/62059657-a382be00-b1f1-11e9-9bf6-2082e9288a5f.png)

Knowing that it works as root, there has to be something else missing in term of access or other setting that makes the menu and the welcome page disappear?
What can I test? :)

cheers!

**Comment by mikeller** [comment]
@RRAlex: Can you please post logs in text form instead of as screenshots? Nobody wants to type your error messages in order to google them.

**Comment by Docteh** [comment]
Where exactly did you get that from? Is this the .deb or .rpm on the releases tab?

I get a screen like that when I break the javascript files, or forget to provide a version.json.

**Comment by RRAlex** [comment]
> Where exactly did you get that from? Is this the .deb or .rpm on the releases tab?
> 
> I get a screen like that when I break the javascript files, or forget to provide a version.json.

It's the deb from github, nothing out of the ordinary and didn't modify anything.

**Comment by Docteh** [comment]
When I do 
/opt/betaflight/betaflight-configurator/betaflight-configurator --password-store=basic

I only get an error about the component_loader, but the app does load. 

![image](https://user-images.githubusercontent.com/190571/62403629-76147800-b543-11e9-912f-c929ca838b6e.png)

I'd try removing the following
`~/.config/betaflight/betaflight-configurator`
`~/.cache/betaflight/betaflight-configurator`

And if that still doesn't work, maybe try and `cat /opt/betaflight/betaflight-configurator/version.json` as a user.

**Comment by mikeller** [comment]
@RRAlex: Googling your error message returns https://simpleit.rocks/linux/ubuntu/fixing-common-google-chrome-gpu-process-error-message-in-linux/ as the top result. I'd try using the advice given there, and run `/opt/betaflight/betaflight-configurator/betaflight-configurator --disable-gpu --disable-software-rasterizer`. It looks like your hardware does not have a GPU.

**Comment by RRAlex** [comment]
> @RRAlex: Googling your error message returns https://simpleit.rocks/linux/ubuntu/fixing-common-google-chrome-gpu-process-error-message-in-linux/ as the top result. I'd try using the advice given there, and run `/opt/betaflight/betaflight-configurator/betaflight-configurator --disable-gpu --disable-software-rasterizer`. It looks like your hardware does not have a GPU.

That didn't work, but interestingly I have the same behaviour (user not working, root working) on a Mint 19 machine. There must be something beside the dialout group that is missing...

**Comment by Docteh** [comment]
Does chrome itself work on these computers? 

If I had this happen, I'd copy /opt/betaflight/betaflight-configurator to somewhere in my user dir

Then grab an SDK build of NWJS https://nwjs.io/downloads/ and drop that on top of the copy of the configurator, and then try running the binary. I'm on windows today and its `nw.exe` so I'd guess it's just `nw`. Then when you're looking at that screen that doesn't load properly you can right click the window, select `Inspect`, and then take a look at the `Console` tab of the development tools.

**Comment by RRAlex** [comment]
Thanks for the trick :)

So, I'm getting this on the nwjs console:
`main.html:1 Error handling response: TypeError: Cannot read property 'userLanguageSelect' of undefined at chrome-extension://ajdoecjhplhoahggfmgflfnlechcljoc/js/localization.js:122:20`

... and:
`main.html:1 Unchecked runtime.lastError: IO error: .../000007.log: Unable to create sequential file (ChromeMethodBFE: 7::NewSequentialFile::5)`

First one made me wonder if this was because I wasn't in a known default locale, I tried:
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
... and launched the betaflight-configurator again, but that didn't help.

Do any of these errors sound familiar?
thanks!

**Comment by McGiverGim** [comment]
It seems the problem is here:
https://github.com/betaflight/betaflight-configurator/blob/0f04022b0c027930b6d662c76377b82f03c82605/src/js/localization.js#L122

But I don't know why exactly.

**Comment by McGiverGim** [comment]
You can change this for

`if (result && result.userLanguageSelect)`

And it will work. Can you test it?

**Comment by mikeller** [comment]
@RRAlex: This is highly odd. Can you describe what hardware (CPU, graphics adapter) it is that you are experiencing these problems on?

**Comment by RRAlex** [comment]
So... I managed to fix it.
One of the file in ~/.config/betaflight-configurator/ wasn't owned by my user because of previous attempts.
But I still thing there is something to fix:

When it started I was seeing a popup go under the (then broken) loading window and it didn't stay open long enough to be readable. It wasn't there when I alt-tab or minimized the other window.
So using a desktop recorder I managed to read it:
```
Your preferences cannot be read.
Some features will be unavailable and changes to preferences won't be saved.
[ ] Send feedback to help us fix this issue.
[ OK ]
```
Which made me check the preferences and fix them...

So I guess it's a user error at this point, but had I seen this popup stay open, I would have figured it out earlier!
Is it possible there is a bug with the warning disappearing as soon as the other window opens?

Cheers! :)

**Comment by mikeller** [comment]
@RRAlex: Ha, glad to hear that it's working. Getting messed up permissions on shared user-level config / cache files is one reason why it is not advisable to run pretty much anything as root in unix.

The disappearing error message that you are getting is usually caused by your preferences having been written by a newer version of NW.js, probably when you were trying out things in order to get this to work. Simply delete `~/config/betaflight-configurator/` to make it go away - there aren't many preferences that you'd want to keep in there anyway.

**Comment by RRAlex** [comment]
> The disappearing error message that you are getting is usually caused by your preferences having been written by a newer version of NW.js, probably when you were trying out things in order to get this to work. Simply delete `~/config/betaflight-configurator/` to make it go away - there aren't many preferences that you'd want to keep in there anyway.

Now that I know, I'll fix my other machine by chmod-ing it.
But that said, if someone else hits a corrupt/permission problem in that folder, (Which I had before the NW.js installation) they also might not be able to read the popup in time?
I'll close the issue, but this might need some testing for the warning to work as intended.
Cheers! :)

**Comment by mikeller** [comment]
@RRAlex: The warning is generated by NW.js, so you'll have to raise this with the NW.js maintainers to get it fixed.

**Comment by mikeller** [comment]
@RRAlex: Please read https://github.com/betaflight/betaflight-configurator/issues/1548#issuecomment-519036808.
