### ISSUE TITLE
[FR] Display Motor RPM in the Motors tab

### ISSUE THREAD

**Issue by bizmar** [betaflight/betaflight-configurator#1557]
Use ESC telemetry or Dshot RPM Feedback to display the current RPM per motor. 
Useful for diagnostics purposes, and for determining a good idle RPM for the new Dynamic Idle feature.

**Comment by McGiverGim** [comment]
Is there some MSP command that returns this value? If true, I can add it without problem.

**Comment by joelucid** [comment]
I don't think there is but it could be added easily. The info is available in rpm_filter.c where it gets set as rpm_filter debug. Would only need to get inverted into rpm from rps - if that's what we really want.

**Comment by mikeller** [comment]
I think this could be valuable as a verification that bidirectional Dshot is working correctly outside of CLI.

**Comment by Mateyhv** [comment]
Agree, that definitely would be a very nice addition to the configurator.

**Comment by McGiverGim** [comment]
This was added some weeks ago. I close this request.
