### ISSUE TITLE
Configurator hang up since build #247

### ISSUE THREAD

**Issue by Mode-1** [betaflight/betaflight-configurator#1562]
Hi, i'm using the betaflight-configurator_10.6.0_chromeos.zip-content with Chrome running at Win 7  64. No problem untill build #246. Since then the configurator hangs up showing only parts of the starting screen :
![Configurator not working V247](https://user-images.githubusercontent.com/36391977/62640918-d9871700-b942-11e9-9bef-9627c9d86b0a.PNG)

It looks like this when working until Build #246:

![Configurator working V246](https://user-images.githubusercontent.com/36391977/62640950-ead02380-b942-11e9-9cc6-28e3a207cc07.PNG)

Any clue ? Thanks :-)

**Comment by Docteh** [comment]
Hi, I'll get that fixed in https://github.com/betaflight/betaflight-configurator/pull/1560
