### ISSUE TITLE
Receiver tab is broken

### ISSUE THREAD

**Issue by atomgomba** [betaflight/betaflight-configurator#1572]
I'm using the Configurator on Ubuntu from the sources and cannot get the Receiver tab to work after commit 426e753b538103c94f8d92d228b24985d1850fd7. Channel values are not displayed and the bars aren't moving either. The things I've tried:

Complete rebuild:

```bash
rm -rf debug/ dist/ cache/ node_modules/
yarn install
yarn start
```

Complete rebuild and deleting contents of the local storage:

```bash
rm -rf ~/.config/betaflight-configurator
```

Only dropping back to commit 28d9bc36ecd71c2b1f9935d8ed03705e33220d95 fixes the problem. Though, I cannot see anything suspicious in the console. Below is a screenshot of what I see.

![Screenshot from 2019-08-10 16-55-19](https://user-images.githubusercontent.com/33358/62823259-b1402800-bb8f-11e9-9aa4-54d561d6a4aa.png)

**Comment by Docteh** [comment]
Hi, I've got a pending PR for this: https://github.com/betaflight/betaflight-configurator/pull/1570

Can you double check for me? if you scroll down to the bottom, and select a different refresh rate, the tab should start to update, no need for the patch.

#1570 moves the initial kickoff of updating the graphs to be below where they are defined.

**Comment by atomgomba** [comment]
It is fine now. Thanks!
