### ISSUE TITLE
Led Overlay, Larson Scanner reversed direction label:"Feature+Request"

### ISSUE THREAD

**Issue by m4R-T1n** [betaflight/betaflight-configurator#1586]
please can someone add an option to invert the running direction.
so you can adress 2 led strip next to each other running running mirrored.
like this :
![grafik](https://user-images.githubusercontent.com/54242887/63228061-4fff0100-c1ee-11e9-9b42-243898aa13bc.png)
thanks

**Comment by mikeller** [comment]
@m4R-T1n: I really can't see why there would be need for this, if you can simply wire your strips the right way to make this work:

![63228061-4fff0100-c1ee-11e9-9b42-243898aa13bc](https://user-images.githubusercontent.com/4742747/63261706-39cd6f80-c2d8-11e9-9cbe-ee4becec2c30.png)

**Comment by m4R-T1n** [comment]
not really, i can wire it like your drawing but then you have to rotate the led strip 180° to run the other way. but then the led stip has the mounting holes/ and chips mirrored.  
hope you understand the problem.
and if i wire like this booth strips will run starting from right to left
