### ISSUE TITLE
Motors stop after entering in CLI while running (for check dshot telemetry)

### ISSUE THREAD

**Issue by IllusionFpv** [betaflight/betaflight-configurator#1597]
The issue seems related https://github.com/betaflight/betaflight-configurator/pull/1329, `dump` and `get` commands stop motors.

**Comment by mikeller** [comment]
@IllusionFpv: Good point - #1329 introduced probing of CLI commands that is run when opening the CLI tab - looks like this probing is now causing the motors to stop. There are two possible workarounds:
- disable 'Advanced CLI AutoComplete' in the gear menu top right in configurator;
- when in CLI, use the `motor <motor number> <value>` command to spin the motors (`<motor number>` 0 based, 255 = all motors, `<value>` 'PWM' value, 1000 to 2000).
