### ISSUE TITLE
Motors start spinning in CLI

### ISSUE THREAD

**Issue by Jensi** [betaflight/betaflight-configurator#1603]
**Describe the bug**
Whyle copying in some "code" into the cli the motors startet spinning up to idle and stoped ~2sec later.

**To Reproduce**
I flashed my FC with BF 4.0.0 RC4
then i copied the CLI part for freestyle out of the "4.0 Tuning Notes" (https://github.com/betaflight/betaflight/wiki/4.0-Tuning-Notes) into the CLI and typed Enter.
While the "code" was executet the motors started spinning with ~idle throttle.

this (motors spinning up) also occurred while copying the "dump all" of my first FC (after setting everything up) to my second FC
both quads are fresh builds and exactly the same.

**Expected behavior**
I don't want spinning motors on my bench if i not force it ^^
I had the props off so everything was ok but someone will not...

**Flight controller configuration**
FC: Matek F722 SE
BF: 4.0.0 RC4
Rx: crossfire on RX2/TX2
VTx: smartaudio on TX3
Camera: RC micro swift 3 on RX4/TX4
ESC: Aikon 4in1 with Telemetry on RX6 (dshot1200)

**Comment by mikeller** [comment]
Looks like the existing warning is not strong enough:

```
Warning:
Some commands in CLI can result in arbitrary signals being sent on the motor output pins. This can cause motors to spin up if a battery is connected. Therefore it is highly recommended to make sure that no battery is connected before entering commands in CLI.
```

Maybe we could check if the flight controller reports that a battery is connected, and if so display a warning pop-up before entering the CLI tab?
