### ISSUE TITLE
Blank Fields in Video Transmitter tab

### ISSUE THREAD

**Issue by spatzengr** [betaflight/betaflight-configurator#1606]
See https://www.screencast.com/t/tekdJgh8KE for details on the issues I'm having.

![image](https://user-images.githubusercontent.com/25570978/63955907-7bd28000-ca53-11e9-8be8-23ffe87f46c8.png)

**Comment by McGiverGim** [comment]
Are you on latest master? If yes, can you post the diff that produces the problem?

**Comment by IvoFPV** [comment]
@spatzengr Could you try setting the vtx table via CLI before setting your smartaudio port? There seems to be an issue here. One guy on Slack had this happen and that fixed it.

**Comment by IvoFPV** [comment]
@spatzengr Oh, you are running the firmware nightly that doesn't have MSP support for this. You must run nightly build >1817
