### ISSUE TITLE
MSP RX control sticks window does not reflect dark mode setting

### ISSUE THREAD

**Issue by jflyper** [betaflight/betaflight-configurator#1609]
![betaflight-configurator_と_Betaflight_Configurator](https://user-images.githubusercontent.com/14850998/64079806-0a325480-cd27-11e9-95b3-5a9385e44181.jpg)

**Comment by IvoFPV** [comment]
I'll take a look.

**Comment by Anisotropic** [comment]
"Control sticks" is absent in my bf-configurator. How can I force to show this button? The receiver is powered on my connected quad, and taranis is binded and also powered.

**Comment by Anisotropic** [comment]
@IvoFPV I found solution how to pass darkTheme variable to separate window. Now working on it.

**Comment by McGiverGim** [comment]
> "Control sticks" is absent in my bf-configurator. How can I force to show this button? The receiver is powered on my connected quad, and taranis is binded and also powered.

You must select MSP as RX protocol.
