### ISSUE TITLE
Add Degree field to ACC sensor page

### ISSUE THREAD

**Issue by Ozzy33** [betaflight/betaflight-configurator#1620]
Would be nice to add accelerometer degrees to the sensor page (next to the G's numbers), like -90 to 0 to +90 degrees. Also add a calibrate ACC button on this page (like the setup tab has). TIA!
![BFC ACC Degree wanted](https://user-images.githubusercontent.com/10664034/64276568-2982da80-cefd-11e9-9a52-b5122ced6561.jpg)

**Comment by mikeller** [comment]
@Ozzy33: Ok, I can understand the 'degrees' output. But I am not sure about the 'calibrate ACC' button - having this in one place seems to be enough.

**Comment by Ozzy33** [comment]
Hi Mike, that would be fine! 
It would be nice to have 0.1 degree resolution if the numbers are not jumping all over (filtered data), if its moving around to much, then 1 degree would be fine too.
Thanks.

**Comment by Ozzy33** [comment]
Any updates on this feature? TIA!

**Comment by haslinghuis** [comment]
working on this:

See https://forums.parallax.com/discussion/114274/tri-axis-g-force-to-radius-and-degree-conversion-question

Added some formulas but it only settles if acc is stable

**Comment by Ozzy33** [comment]
Maybe a averaging filter?
And thanks for the update!
