### ISSUE TITLE
Future update requirements

### ISSUE THREAD

**Issue by unipheas** [betaflight/betaflight-configurator#1624]
> As a reminder, Mac software distributed outside the Mac App Store must be notarized by Apple in order to run on macOS Catalina. To make this transition easier ... , we’ve adjusted the notarization prerequisites until January 2020.  

https://developer.apple.com/news/?id=09032019a‬

**Comment by mikeller** [comment]
Thanks for letting us know, @unipheas.

**Comment by gretel** [comment]
did find a solution and posted it on the issue but got muted by, well, some authority. regards

**Comment by mikeller** [comment]
@gretel: If you are not willing to cooperate with the developers please stop posting here - thanks.

**Comment by gretel** [comment]
your definition of cooperation is not to be discussed. have a nice day.
