### ISSUE TITLE
10.6.0 - Gyro selection is not saved

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/betaflight-configurator#1625]
Found this on testing with SPRACINGH7Extrem ... If i put from `Both` to `First` or `Second` and then press `Save and Reboot` after the reboot it stays again on `Both`
Only `set gyro_to_use = xxx` is working

EDIT: same found with MATEKF722MINI ... imho an configurator issue

**Comment by mikeller** [comment]
@TheIsotopes: What firmware version are you using?

**Comment by TheIsotopes** [comment]
@mikeller just again tested with latest 4.1.0 firmware build#1861

**Comment by TheIsotopes** [comment]
tested #1629 ... working again
