### ISSUE TITLE
10.6.0 - Dynamic Notch Filter not saved

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/betaflight-configurator#1631]
All parameters from Dynamic Notch Filter (PID Tuning -> Filter Settings) will not saved after editing and click on save button ... only the associated cli commands work

found on Configurator `10.6.0 (fe08a783)` with BF 4.1.0 build#1861 on MATEKF722SE Target
also tested with MatekF405Mini and SPRacing H7 Extreme/Nano

**Comment by IvoFPV** [comment]
Confirmed. Looking into it.

**Comment by IvoFPV** [comment]
#1621 will fix it, just a problem with MSP because of addition of RPM filter related settings.
