### ISSUE TITLE
10.6.0 - Configuration Tab help icon failure

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/betaflight-configurator#1635]
If i'm click on the help icon from `Motor direction is reversed` or `Bidirectional DShot` the corresponding feature is activated / deactivated. 
Further by clicking the help icon of `Motor Idle Throttle Value` and `Motor poles`, the input fields are activated.
Other help icons do not do this, which I think this is correct.

**Comment by McGiverGim** [comment]
It sounds strange. I will look into it tomorrow if nobody does it before.
