### ISSUE TITLE
Configurator doesn't properly error when flashing firmware that is too big.

### ISSUE THREAD

**Issue by Docteh** [betaflight/betaflight-configurator#1682]
I think we should show an error at some point when I decide to flash firmware that is too large to fit, for example a F405 unified target onto F411 chip 😎.

I did this twice, with the 10.6.0-RC1 and the current master. Just hangs in the middle, and merely states that the USB device successfully closed.
![image](https://user-images.githubusercontent.com/190571/65384151-96ef8300-dcd3-11e9-88ea-1b0b3a0cb1f9.png)

![image](https://user-images.githubusercontent.com/190571/65383260-b2549100-dcc7-11e9-9ded-6813c6081d0b.png)

**Comment by mikeller** [comment]
Yep, I've been stung by this before too.

One thing I'd like to look into for a future configurator release is to add detection of the currently installed target when opening the firmware flasher tab, and then automatically pre-select the correct target, forcing the user to force-override if they want to flash a different target. This should cut down on how often flashing of incorrect firmware happens.
