### ISSUE TITLE
Mobile support?

### ISSUE THREAD

**Issue by Niek** [betaflight/betaflight-configurator#1685]
Has there been any effort to port the configurator to a mobile (Android and possibly iOS) app? It seems that either Cordova or Flutter would be the best approach. It'll basically be a webview with a thin wrapper around the chrome.* calls. As far as I can see the following Chrome Apps APIs need to be ported:
```javascript
chrome.runtime.lastError
chrome.storage.local.get/set/remove
chrome.app.window.create/current
chrome.fileSystem.*
chrome.usb.*
chrome.serial.*
chrome.sockets.tcp.*
```
For Cordova, the following plugins already exist, although most of them are not actively maintained anymore:
https://github.com/MobileChromeApps/cordova-plugin-chrome-apps-runtime
https://github.com/MobileChromeApps/cordova-plugin-chrome-apps-storage
https://github.com/MobileChromeApps/cordova-plugin-chrome-apps-fileSystem
https://github.com/MobileChromeApps/cordova-plugin-chrome-apps-usb
https://github.com/r1000ru/cordova-plugin-chrome-apps-serial
https://github.com/KoenLav/cordova-plugin-chrome-apps-sockets-tcp

For Flutter or another framework, it would require creating the Chrome Apps API wrapper from scratch.

**Comment by McGiverGim** [comment]
No, it has been talked several times but nobody has tried to do it. I don't have experience with it so I can't give an opinion.

It will be a great addition, but we need some requisites:
- The maintenance must be very low. We don't have too much time for it.
- It must use the sources of the standard Configurator, without the need of duplicate and modify each of them.

Do you have experience with this? Do you think is possible?

**Comment by Anisotropic** [comment]
@niek Have you tried "Speedy Bee" application by Runcam? It does work via cable as well.

**Comment by Mateyhv** [comment]
Yep, Speedy Bee works with Betaflight, Inav and Kiss and as a bonus you can change motors spinning direction, however it won't have the latest changes in Betaflight configurator

**Comment by Niek** [comment]
I am aware of Speedy Bee, but that's closed source (CMIIW) and doesn't have the full/latest Betaflight Configurator functionality.

I'll try to build something based in Flutter (since the Cordova libs are deprecated) using the existing source and see how far it'll come.

**Comment by McGiverGim** [comment]
Waiting your news about it 🤗

**Comment by Docteh** [comment]
flutter looks like it uses a slightly different language, but this might still be worth looking at if shipping standalone apps is possible. is "flutter for desktop" a thing?

**Comment by Niek** [comment]
Yes, flutter desktop was released recently. It's still in heavy development though and webviews are not yet supported. Ref: https://github.com/flutter/flutter/issues/31712 https://github.com/flutter/flutter/issues/31713 https://github.com/flutter/flutter/issues/31714

**Comment by McGiverGim** [comment]
@Niek have you worked on this? Only to know, if not the stale bot will close this if we don't take some action ;-)

**Comment by Niek** [comment]
I didn't have too much time to work on this, but there is some progress:

<img width="956" alt="flutter-bf-config" src="https://user-images.githubusercontent.com/213140/67786859-dac26e80-fa6f-11e9-8005-14c30bb854dc.png">

**Comment by hsuq510** [comment]
@Niek wrote you on slack also, are you using https://github.com/xseignard/cordovarduino.git? I cant connect with the device with VIP/PID aligned also.

**Comment by MaximeAmadasi** [comment]
I tried to port the configurator to android with Cordova and it works well. The main issue I found actually is the firmware flasher : the configurator detects dfu but is not able to flash the fc.
I created gulp tasks to build the cordova folder with the ressources of the classic configurator. Only the serial.js file is different. If you are interrested [https://github.com/MaximeAmadasi/betaflight-configurator/tree/cordova](url)

**Comment by Asizon** [comment]
@MaximeAmadasi woow very good neews, how I can try it?

**Comment by MaximeAmadasi** [comment]
You can try this apk https://github.com/MaximeAmadasi/betaflight-configurator/releases/tag/10.6.0
Actually yarn gulp cordova will build the cordova folder. But you need to install java jdk, android sdk and build manually with cordova command line. I try to find an easy way to build the app with gulp.
Moreover, I found an other bug, sometimes, after a "Save and reboot", you need to manually disconnect and reconnect the fc

**Comment by Niek** [comment]
Good job @MaximeAmadasi! The Cordova route is definitely quicker to implement (although not as cross-platform, I don't think there is enough iOS support in the plugins to make it work on Apple devices).

BTW I think the "plugins" dir should not be committed to the repo, as those should be installed by NPM (to keep the changes as minimal as possible).

**Comment by Niek** [comment]
I see release 10.7.0 has Android support (preview), is this a NWJS build for Android? I can't find any reference in this repo or NWJS.

**Comment by McGiverGim** [comment]
It will be merged and released AFTER 10.7.0.

**Comment by mikeller** [comment]
@Niek: It is a preview version built from https://github.com/betaflight/betaflight-configurator/tree/10.7.0-preview.

**Comment by Thunfisch2** [comment]
Would be great to see a iOS version, too! Or are there any technical restrictions due to iOS?

**Comment by WalcoFPV** [comment]
@Thunfisch2 It should be possible to make a ios version. But first we need to implement bluetooth connection in the configurator

**Comment by joevo2** [comment]
> @Thunfisch2 It should be possible to make a ios version. But first we need to implement bluetooth connection in the configurator

I saw that configurator seems to support Bluetooth already right. It’s more of a Cordova thing?

**Comment by joevo2** [comment]
> @molor No. There is no date. I began to work on it but I don't know when it will be finished

Glad to hear this! What kinda bluetooth module are you using on your FC to communicate with the app?
