### ISSUE TITLE
ESC/Motor protocol popup

### ISSUE THREAD

**Issue by 0crap** [betaflight/betaflight-configurator#1688]
Is DSHOT 900 and/or 1200 still in use?
It's not in my pull-down menu.
Using BF configurator 10.6.0-RC1.

![Popup](https://user-images.githubusercontent.com/31951195/65517626-55cdbd80-dee3-11e9-80db-6fe3fd79c0c3.jpg)

**Comment by Docteh** [comment]
Wow, I'd never even heard of DSHOT900, I saw that DSHOT1200 got removed on the firmware 

https://github.com/betaflight/betaflight/pull/8806

**Comment by 0crap** [comment]
Me either, I think that's always been a typo and should read Dshot600.
The complete bold printed part has been removed in the fix.
Seems like the proper decision.

**Comment by mikeller** [comment]
If I remember correctly there was Dshot900 for a short time, before Dshot1200 became a thing.
