### ISSUE TITLE
LedStrip ColorDefineSliders popup hides

### ISSUE THREAD

**Issue by scorpakascorp** [betaflight/betaflight-configurator#1697]
Hi all!
If I using a Configurator 10.6.0-RC1 and try to modify colors the big gap appears between selecting color box where I doubleclicking and popup window where color sliders are. And if I try to move mouse pointer to this popup it closes. So I can't change color settings from GUI but only from CLI.

![led_strip_colorPicker_faraway_issue_v10 6 0-RC1](https://user-images.githubusercontent.com/13813679/65814218-9aa96b00-e1e7-11e9-9485-da24e5dde0aa.png)

Also not all text are visible in dark theme and background too white.

**Comment by IvoFPV** [comment]
Yeah, it seems broken. I will look into it.
