### ISSUE TITLE
Język

### ISSUE THREAD

**Issue by SprytnyFPVFreestyle** [betaflight/betaflight-configurator#1704]
Witam.Czy zostanie dodany język polski do konfiguratora?

**Comment by IvoFPV** [comment]
>Hello. Will Polish be added to the configurator?

English please. Polish translation hasn't been updated and will not be added.
If you want to contribute so it gets added in future you can check out Crowdin where translations are made and join Betaflight's Slack to help you get started: 
https://crowdin.com/project/betaflight-configurator
http://slack.betaflight.com
