### ISSUE TITLE
VTX config enhancements

### ISSUE THREAD

**Issue by Niek** [betaflight/betaflight-configurator#1708]
In anticipation of BF 4.1 there are some videos surfacing describing the changes, specifically the need to configure the VTX tables manually. For example: https://youtu.be/eaSmoOPk9KY

In order to lower the friction of upgrading, would it be possible to consider these enhancements?
* If no VTX tables are set, auto detect the Smartconfig version in the VTX tab (based on sensors debug)
* Present the user a choice of location: US or EU (maybe pre-select based on the BF configurator language)
* Then, download and apply the correct VTX template so the user has some sensible defaults

CC @joshuabardwell, @spatzengr

**Comment by McGiverGim** [comment]
Hi, thanks for your suggestions.
- The first option, detect version, can be added if the MSP returns it. Now it does not. As you say the user needs to enable the debug mode to get it, it is not very clean. I prefer that someone adds the info to some real MSP command to publish it and not to use an ugly hack that will need to be maintained version by version.
-  The other two options, I tried to do a wizard to help with this, but the idea was rejected. The final objective seems to be that Betaflight must be far from templates and similar and the user must be totally aware of what he is configuring in the case of the VTX. But I suppose this can change.

Both options can be done, but I suspect none of them before 4.1.
