### ISSUE TITLE
Bug: Video-Transmitter page : erase all entries after "fast" clicking SAVE button several times

### ISSUE THREAD

**Issue by mrRobot62** [betaflight/betaflight-configurator#1717]
MAC-OS Mojave 10.14.6
BF 4.1RC5

**Scenario**:
Loading vtx data via "Load button" -> load successfully
Save data via SAVE button -> save successfully

Clicking SAVE-Button every 2-3 secs -> no problem -> screen is refreshed after every SAVE
Clicking SAVE-Button very fast (e.g. 2-3x per second) -> refreshing is slower as clicking, than all data are reinitialized and values are 0

I can reproduce this scenario several times on my MacBook

**Problem**:
I assume, there is a timing delay between SAVE and refresh screen, because saving data writes data into eprom afterwards the screen is refreshed with eprom data.

If user click save button twice - second click between saving into eprom and refreshing screen, than the internal data structure is not initialized with eprom data - so I assume they are 0

If this happens, all will be populated with 0 - 2nd/3rd SAVE destroy eprom data and user have to start again

**Solution**:
disable SAVE-Button as long as screen refresh is not finished.

Here is a short movie about this bug: 
https://drive.google.com/open?id=1ApmPCvpOoA9r6rZ8J4FQilGfo0vAre20

**Comment by IvoFPV** [comment]
Yeah, easy to reproduce. I will look into it.
