### ISSUE TITLE
Unable to install Configurator on MacOS (RC1 and RC2)

### ISSUE THREAD

**Issue by SuTeCH007** [betaflight/betaflight-configurator#1720]
"Betaflight Configurator.app" is corrupt and cannot be opened. You should remove the install file.

Chrome downloaded this disk image at 17:59 today from github.com.

![Screenshot at Oct 06 18-01-55](https://user-images.githubusercontent.com/1297646/66271927-e56c5800-e863-11e9-8800-6a0f8b88002b.png)

I tried it multiple times on multiple access points. Nothing. I don't have a problem with 10.5.x.

**Comment by IvoFPV** [comment]
https://github.com/betaflight/betaflight-configurator/issues/1675#issuecomment-533765371 This seems to fix the issue for now. Could you try that?

**Comment by SuTeCH007** [comment]
> [#1675 (comment)](https://github.com/betaflight/betaflight-configurator/issues/1675#issuecomment-533765371) This seems to fix the issue for now. Could you try that?

Yeah. That's it. Thanks. Now it's working.
