### ISSUE TITLE
Tooltip for RPM data occasionally remains popped up indefinitely

### ISSUE THREAD

**Issue by jflyper** [betaflight/betaflight-configurator#1731]
10.6.0-RC1, MacOS 10.13.6
Happens very frequently (but not always).
When it happens, there's no way to make it disappear other than quitting the app.

![Betaflight_Configurator](https://user-images.githubusercontent.com/14850998/66558691-f207ed80-eb8e-11e9-999d-043b34745f81.jpg)

**Comment by IvoFPV** [comment]
Get the 10.6.0-RC2 version, it has been fixed.

**Comment by McGiverGim** [comment]
Yes. This happens with others tooltips too, but the RPM one is more frequent.

We have tried with several changes here https://github.com/betaflight/betaflight-configurator/pull/1604 and here https://github.com/betaflight/betaflight-configurator/pull/1665 it seems without luck :(

**Comment by jflyper** [comment]
Hmm. RPM tooltip seems to be fixed with RC2.

(Btw, the RPM tooltip text should be "These numbers" instead of "This number", right?)

**Comment by mikeller** [comment]
> "These numbers" instead of "This number"

We definitely need add a translation from 'developer' to English. :wink:
