### ISSUE TITLE
Cant install on Catalina

### ISSUE THREAD

**Issue by Letzrock** [betaflight/betaflight-configurator#1735]
I tried using sudo spctl --master-disable and it still won't run.

**Comment by Docteh** [comment]
Is Catalina out yet? I've been waiting for it to be fully out to investigate the signing issues we've been seeing.

**Comment by Letzrock** [comment]
Yes I installed it 2 days ago

**Comment by mikeller** [comment]
Closing as duplicate of #1367 

@Letzrock: For next time, please have a look if there is an existing issue for your problem before opening a new one.

**Comment by philcal** [comment]
@mikeller
Issue #1367 has no mention of Catalina. It appears this is _not_ a duplicate of that issue.

**Comment by Docteh** [comment]
@philcal #1675 is probably worth a look

**Comment by mikeller** [comment]
@philcal: Sorry, my bad. No idea how I got to `#1367` when meaning to type #1675.
