### ISSUE TITLE
Languages select not available.

### ISSUE THREAD

**Issue by ApophysX** [betaflight/betaflight-configurator#1749]
Hello,

okay i have no issue, sorry. plz del...

**Comment by IvoFPV** [comment]
![image](https://user-images.githubusercontent.com/50072760/67003282-e8760c80-f0dd-11e9-87cc-2c1c1b4f781c.png)

**Comment by RipperDrone** [comment]
@ApophysX pls close this issue yourself then 🙂

**Comment by Docteh** [comment]
*click*
