### ISSUE TITLE
10.6.0 Installation on Windows 10 1903 very slow took over 15min

### ISSUE THREAD

**Issue by dako76** [betaflight/betaflight-configurator#1750]
Installation is very slow on Windows, Reboot pc and uninstall old version. Deleted old files same issue. I use Sophos Home as virus/firewall.

**Comment by IvoFPV** [comment]
This is an already known issue. For me it takes about 5 minutes to install. There is probably nothing you can do to fix it on your side.

**Comment by McGiverGim** [comment]
Deactivating the antivirus helps, but no fixes it. We will need to test again compressing the node stuff to see if it does not produce the old problem again.
