### ISSUE TITLE
Error in deb package

### ISSUE THREAD

**Issue by andreasschramel** [betaflight/betaflight-configurator#1766]
Unable to install betaflight-configurator_10.6.0_amd64.deb package under Ubuntu 19.10. 
The following error messages appear:
<pre><font color="#3465A4"><b>~/Downloads</b></font>$ sudo apt install ./betaflight-configurator_10.6.0_amd64.deb 
[sudo] password for andreas: 
Reading package lists... Error!
E: Problem parsing dependency 21 of betaflight-configurator:amd64=10.6.0
E: Error occurred while processing betaflight-configurator (NewVersion2)
E: Problem with MergeList /home/andreas/Downloads/betaflight-configurator_10.6.0_amd64.deb
E: The package lists or status file could not be parsed or opened.</pre>

**Comment by mikeller** [comment]
@andreasschramel: Try downloading the file again - AWS was having issues today, so it's possible that the file you downloaded was corrupted.

**Comment by andreasschramel** [comment]
@mikeller did not solve the problem, I still have the same output on the terminal.

**Comment by mikeller** [comment]
@andreasschramel: Wait a second - apt is intended to be used to install packages that are published through a repository, which betaflight configurator isn't.

Try this instead:

```
sudo dpkg -i ./betaflight-configurator_10.6.0_amd64.deb
```
