### ISSUE TITLE
10.7.0 - does not flash firmware anymore

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/betaflight-configurator#1772]
bfc 10.7.0 does not flash anymore since #1763  was merged 

@mikeller can you check what's wrong

![Zwischenablagebild](https://user-images.githubusercontent.com/29702171/67631802-4c958f00-f89b-11e9-96b2-d3541d4e3f3c.jpg)

**Comment by mikeller** [comment]
@TheIsotopes: Can you supply a bit more information on what operating system this is, what board you were connected to, and what firmware you were trying to flash?
I was using Betaflight configurator 10.7.0 built from latest master to flash a BEEROTORF4 with a STM32F405 target on linux just now, and it worked just fine.

**Comment by TheIsotopes** [comment]
@mikeller sry ... using Windows 10 (Version 1909 Build 18363.449)
no flashing with all my fc and the firmware does not matter

**Comment by mikeller** [comment]
Erg, looks like this the version of chrome that is bundled into 0.41.3 of the NW.js toolkit is broken in Windows:

```
reporting chrome error: The device is not in a configured state.
stm32usbdfu.js:107
```

Will need to investigate - for now use the released version of configurator.
