### ISSUE TITLE
Warning to update to 10.6.0 configurator when already using it.

### ISSUE THREAD

**Issue by SunshynRFF** [betaflight/betaflight-configurator#1778]
When I click on Betaflight and it loads, I get a notification message that there is a newer version of configurator and mine is outdated.  Has link to release page, which is where I downloaded and updated to 10.6.0 a month ago.  When I close warning, BF does not give me anymore notifications, or run any differently.  Only when I close BF completely out and re-open it do I get the notification.

![10-28-2019_164216](https://user-images.githubusercontent.com/56273101/67724685-ccac1980-f9ad-11e9-81b1-9c2e97936c9f.jpg)
![10-28-2019_180354](https://user-images.githubusercontent.com/56273101/67724698-d5045480-f9ad-11e9-8b99-c3ad01cdf2e5.jpg)

**Comment by mikeller** [comment]
@SunshynRFF: You are still using the 10.6.0-RC1 version of configurator:

![67724685-ccac1980-f9ad-11e9-81b1-9c2e97936c9f](https://user-images.githubusercontent.com/4742747/67725272-9f5f7a00-fa46-11e9-9c3d-94e36396f99e.jpg)

Try uninstalling configurator first, and then installing the 10.6.0 version.

**Comment by SunshynRFF** [comment]
Oh ok, I can do that, thank you!!

Jack ley
Sunshynff@yahoo.com
636-262-2152
