### ISSUE TITLE
Configurator 10.6.0 is corrupted on macOS

### ISSUE THREAD

**Issue by Kllngii** [betaflight/betaflight-configurator#1781]
I tried to install the new betaflight-configurator 10.6.0 on macOS 10.14.6 and it didn't work. I tried to download the file again. This time the installer worked, but I was unable to run the installed software.

**Comment by mikeller** [comment]
@Kllngii: Please read https://github.com/betaflight/betaflight-configurator#note-for-macos-x-users (also mentioned in the release notes for 10.6.0).

**Comment by annerajb** [comment]
Can we get proper signing/notary  of the binary so it can be installed on macs with gatekeeper enabled?

**Comment by mikeller** [comment]
@annerajb: We are looking into this. But in general, as long as Apple is not willing to introduce a way for community driven open source projects to get this done for free, I don't think supporting Apple by paying them money for this is the right approach.
