### ISSUE TITLE
Urgent: configurator not compatible with bf 2.8+

### ISSUE THREAD

**Issue by skaman82** [betaflight/betaflight-configurator#18]
Cofig tab is not saving changes. Tested with 

Serialrx
Motorstop
Ledstrip

Could mit get that Settings saved on naze32 rev6. 

Also noticed that the looptime was 1000 right after flashing. After trying to set some things in config tab and hitting the save button, looptime got down to 500.

**Comment by borisbstyle** [comment]
I fixed this in 2.8.1 by re-ordering the MSP structure. Also merged the dev into master

**Comment by borisbstyle** [comment]
I will close this issue as I opened seperate issues for things to solve for the first configurator
