### ISSUE TITLE
Modes Tab in 10.6.0 not working on Mac OS

### ISSUE THREAD

**Issue by DJStucks** [betaflight/betaflight-configurator#1805]
When working with my Emax Buzz, the modes tab freezes and the OSD is blank.  Anybody else having similar issues?

![image](https://user-images.githubusercontent.com/57381545/68175903-98010a80-ff37-11e9-9393-d2b9b2b07e76.png)
![image](https://user-images.githubusercontent.com/57381545/68175913-9fc0af00-ff37-11e9-8299-8f3a0af2dd7e.png)

**Comment by McGiverGim** [comment]
This happens usually with FC with beta versions of the firmware. Have you updated your FC to the latest stable version?

**Comment by DJStucks** [comment]
You're spot on.  I inadvertently had flashed the wrong version of firmware.  Thanks for making that troubleshoot easy.
