### ISSUE TITLE
Integrate community presets directly into the configurator

### ISSUE THREAD

**Issue by tenten8401** [betaflight/betaflight-configurator#1811]
It'd be awesome to have community presets from the [wiki page](https://github.com/betaflight/betaflight/wiki/Community-Presets) directly integrated into the configurator, similar to how iNav does it:
![iNav](https://quadmeup.com/wp-content/uploads/2017/01/presets.png)
It'd have the potential to get more people in the air with a nice flying quad quicker.
A disclaimer would be good to have though saying something along the lines of what the wiki page says at the top.

**Comment by IvoFPV** [comment]
I will be doing something like this to complement the new sliders after they are in.

**Comment by haslinghuis** [comment]
@limonspb is working on presets now
