### ISSUE TITLE
impossible d'installer bf 10.6.0 sur mac 

### ISSUE THREAD

**Issue by Dextorfpv123** [betaflight/betaflight-configurator#1815]
Message d'erreur fichier corrompu meme en utilisant sudo xattr -rd.

**Comment by Asizon** [comment]
Please, read complete instructions for mac installing in https://github.com/betaflight/betaflight-configurator/releases
'' Important information when upgrading''

**Comment by Asizon** [comment]
And use apropiate language please ;)
