### ISSUE TITLE
OSD Menu completely missing in 1.6.0

### ISSUE THREAD

**Issue by exocode** [betaflight/betaflight-configurator#1819]
Hi there, suddenly I updated from Betaflight 1.4.x to 1.6.0.
Using FURYF4OSD(FURYF4) BTFL 4.1.0

I am completely missing my OSD menu? Look
No matter if I switch to dark or expert mode... It's gone...

Is there a setting I have to do?

Look:

![Bildschirmfoto 2019-11-11 um 01 53 51](https://user-images.githubusercontent.com/1597621/68554124-8f706e80-0426-11ea-8513-b8339b0a21ca.png)

**Comment by mikeller** [comment]
@exocode: Did you by any chance reset your flight controller configuration to defaults, and not enable the 'OSD' feature in the Configuration tab?

**Comment by exocode** [comment]
you're completely right... sorry... It was reset..
(BTW @mikeller thanx for that super fast response)

![Bildschirmfoto 2019-11-11 um 02 01 08](https://user-images.githubusercontent.com/1597621/68554190-2ccba280-0427-11ea-8333-0e73bcb9c00a.png)
