### ISSUE TITLE
MacBook Pro won't detect drone

### ISSUE THREAD

**Issue by FreshCoastDon** [betaflight/betaflight-configurator#1828]
Hello,

This is my first post, so easy on the roasting please and thank you. Anyways, I was able to install Beta Flight Configurator 10.6.0 and the CP210X drivers fairly easy. When I have Beta Flight up and connect my drone via usb c cable, nothing happens. I have tried it as auto-connect and manually pushing connect to no avail. Any ideas on what may be causing this connection issue? I have also verified the cables, all are good. I have also tried a LiPo battery attached and not attached while connecting and nada. I can provide screen shots if you have any input as well.

**Comment by b3rgman** [comment]
I am having the same problem.  Do I need to specify a certain com port?

**Comment by FreshCoastDon** [comment]
I'm not sure myself... I'm going to try it on my work laptop and go from there until I can find a solution. My drone is kind of sitting here and I'm itching to fly it.

Anyone else in the community care to chime in? Thanks in advance...

**Comment by b3rgman** [comment]
I switched to Mac recently. It used to work for me on Windows.   I made sure the firewall has allowed the connections from BetaFlight as well as the CP210 driver.  I cant get it to pick up the driver.   My guess is its Catalina and I am not being promted for something.

**Comment by jokster945** [comment]
I'm having the exact same problem. Anyone have a fix yet?

**Comment by etracer65** [comment]
For modern flight controllers you don't need to install any drivers on MacOS. Try using a different USB cable - some are only charging cables and don't have the data lines connected.

**Comment by FreshCoastDon** [comment]
hey guys, I was finally able to connect my drone to my MAC. Thanks for the assists and tips here.

**Comment by iBreaker** [comment]
@FreshCoastDon  hi, I have the same problem. How to  fix this.?  thanks.

OSX 10.15.2

**Comment by kholder116** [comment]
> hey guys, I was finally able to connect my drone to my MAC. Thanks for the assists and tips here.

can you please tell us how you were finally able to connect to your MAC.... I'm ready to throw this drone out the window...   I feel as though I should never have upgraded to Betaflight 01.7.0, it was working perfectly before ..

**Comment by kholder116** [comment]
Has anyone else had this c- cable MAC not connecting to Betaflight issue and finally resolved it. If so , could you post what you did. 
 thanks.

**Comment by Brocknelson12** [comment]
Anyone had any success? It won't show up on my usb devices on my Mac and I can't connect through beta flight either

**Comment by etracer65** [comment]
@Brocknelson12 Works just fine. No problems connecting when using Mac. Most of the time the problem people have is a bad cable. You must use a real USB data cable and not just a charging cable like which came with your phone. If you try another cable and it still doesn't work, then try more cables.

**Comment by Brocknelson12** [comment]
Okay i tried with a cable that ive used to write to other devices(tinyduino) so i know its a data cable. I have mac OS Catalina 10.15.7. And DYS f4 pro v2. I have read that the new Driverkit only supports CP2102(for SILabs) and i am not sure that my flight controller uses that or not.

**Comment by mikeller** [comment]
@Brocknelson12: No, the DYSF4PRO uses VCP. This works just fine with MacOS Catalina if the correct cable is used.

**Comment by skywinder** [comment]
same issue on 10.7.0 have no idea how to fix..

**Comment by GerrieWell** [comment]
I was blocked by this too. My drone is mobula6, just connect it to my mac with many cable. The system repport doesn't show any new device. And I haven't any window device to try. The mobula6 is sucks!

**Comment by markjaquith** [comment]
I thought my USB-C to Micro USB adapter passed data, but I was wrong. So even if you've tried multiple cables, try something else. In the end, what worked was a USB-C to USB-A adapter, and then a USB-A to Micro USB cable.

**Comment by Revo-Lucien** [comment]
Tacking on the importance of making sure you have the right cable, I got the Foxeer f722 v4 which takes a USB-A. When I plugged the FC in the correct lights flashed on and it looked ready to go, but sure enough the mac wasn't detecting anything. After a lot of frustration I went to a shop and bought a brand new USB(A->C) cable and... it worked.

**Comment by christhomas** [comment]
sometimes when I flash betaflight my drone isn't detected anymore, so I have to downgrade it and I guess the problems get fixed up when more people notice, so try downgrading your version too. That sometimes helps

**Comment by SebiUNG** [comment]
Same for me, the USB cable was not passing data.

**Comment by nerdCopter** [comment]
any new computers that use USB-C only connections might now need "OTG" cables or USB-A to C adapters. just passing along what i've read.  i have no mac experience.  side-note: An adapter does work for me on a dell XPS with USB-C only, whereas a double-ended-usb-c did not.

**Comment by JulianSchmid** [comment]
It works for me only if I chain USB-C to A to C again with adapters. USB-C directly did not work.

**Comment by SDFfpv** [comment]
I used an adapter that I thought had data transfer but didn't. I would plug your drone straight into your computer.

**Comment by dev-mansonthomas** [comment]
My google search bring me here for the same issue, and being a beginner. Noticing that I had the same issue on my PC, I felt the issue was elsewhere. And I also noticed the microusb port in addition to the more visible USB-C port on my drone.

I'm using "NewBeeDrone AcroBee75 Pusher DJI O4 HD ELRS 2.4GHz 2S" as a first drone.

The drone has 2 ports : 
* on top of the drone, next to the batterie strap, at the rear of the drone, there's a MicroUSB port : **this is the correct drone**

![Image](https://github.com/user-attachments/assets/22b7cd00-05ea-47c2-bdf6-34b94bc2ab90)

* under the drone, an USB-C port : this one is I guess for the video module and it is **not** the correct port

![Image](https://github.com/user-attachments/assets/a029c215-cc8d-4fed-885f-00e56b236f4a)


Once connected, you need to change the device selection (above the auto-connect button) to something like /dev/tty.usbmodemxxxxxx

<img width="1115" alt="Image" src="https://github.com/user-attachments/assets/c9965e64-9afc-4292-bb4d-48ce7cb2587e" />
