### ISSUE TITLE
Betaflight in wrong language

### ISSUE THREAD

**Issue by jasqsr11919** [betaflight/betaflight-configurator#1829]
I followed Joshua Bardwell's link to this betaflight configurator and it installs the configurator in Indonesian for some reason. I am unable to figure out how to switch it to english. Thanks for the help!

**Comment by mikeller** [comment]
@jasqsr11919: Maybe you have to ask @joshuabardwell how to fix this in the version he is linking to then?

The currently released version of configurator has the language selector at the bottom of the startup page: 
![image](https://user-images.githubusercontent.com/4742747/69829502-17f36980-1285-11ea-84ff-9e217e0671cb.png)

**Comment by jasqsr11919** [comment]
oh wow ive been looking for this option since the release. it was weird. I downloaded every configurator before this and they all opened in english except this one. Thank you!
