### ISSUE TITLE
Derivative Method selection is broken

### ISSUE THREAD

**Issue by TheAngularity** [betaflight/betaflight-configurator#183]
@mikeller  @borisbstyle 
since last commits the Derivative Method selection box is not more seen

**Comment by mikeller** [comment]
Do you have 'Betaflight' PID controller selected? If so, it's by design, as the Derivative method only applies to 'Legacy'.

**Comment by TheAngularity** [comment]
aahhhh .... ok ... using betaflight pid .... on legacy it appears ... closed now ;-)

thx
