### ISSUE TITLE
BetaFlight 10.6.0 installer is still labeled as 10.4.0

### ISSUE THREAD

**Issue by NinjaSauce1** [betaflight/betaflight-configurator#1832]
I just installed BetaFlighjt 10.6.0 and as I was watching the files being installed, I noticed that they were all labeled as version 10.4.0. So I was a little worried....

I let the installation finish and it does install version 10.6.0, but pretty much every file is still labeled as version 10.4.0 (including the target folder and the icon name) 

I doubt that im the first person to point this out, but I couldnt find and posts.

I guess its not really a major problem - as long as it works and doesnt try to access outdated files from 10.4.0. I just wanted to make you guys aware. Im not sure how hard it is to correct the file names on the installation program, but maybe you can at least find the person responsible and give him a friendly beating.

![Screenshot (65)](https://user-images.githubusercontent.com/34603089/70355018-1e628200-183f-11ea-92c0-a3181fe28a8e.png)

**Comment by McGiverGim** [comment]
The Configurator does not add the version to the folder name. You add it when installed the 10.4 version and it simply installs the update on the same folder. If you uninstall the old version you will see that.
