### ISSUE TITLE
Installer Hangs on Uninstaller

### ISSUE THREAD

**Issue by tlebrell** [betaflight/betaflight-configurator#1834]
I can't get the 10.6.0 configurator installer to progress past the uninstaller. System is Win10 Home 64 on an i5 gaming box with 16GB RAM. I also ran as admin. I'm attempting to install onto the D: drive (mechanical) instead of the OS drive to save space on the SSD.

![BF Installer Hang](https://user-images.githubusercontent.com/45884529/70402788-316d8180-19fa-11ea-8490-7593e2423a13.PNG)

**Comment by Asizon** [comment]
Just wait for finishing, now de installation take some minuts.

**Comment by McGiverGim** [comment]
You have installed it directly in program files, without subfolder, I suppose by error. It is listing ALL the files from this folder for the uninstalling script.

**Comment by mikeller** [comment]
Ouch, that is going to be a while...

**Comment by Gordo5556** [comment]
I am experiencing the same issue currently. Has anyone found a solution to this?

**Comment by piotrva** [comment]
Same issue for me - hangs on same step and I am installing in default location. 
Windows 10
Tested on two separate machines - same effect...
![image](https://user-images.githubusercontent.com/5657414/140580751-80469916-e41c-48f6-a038-51ebfbcbefa0.png)

**Comment by 580** [comment]
Same issue here, Windows 11:
![image](https://user-images.githubusercontent.com/2892127/140608167-89412dd9-ce0f-4cc8-b3d1-ce5613bba2ca.png)

Left it for around 15 minutes, and installation completed.

**Comment by Cronople** [comment]
![image](https://user-images.githubusercontent.com/57852025/140973950-a6b8ce78-8e84-4d20-9a37-983e03b7e19f.png)

Same issue, window 10 Edu, 20H2 ver.

I'm trying to install from the same folder where betaflight is installed.

over 30 min. still installing...

**Comment by flyTib** [comment]
![Capture](https://user-images.githubusercontent.com/66412299/141976625-0b2d7b30-9b8a-45ac-b316-f741d979a41e.JPG)
same here

**Comment by Rubines** [comment]
same here insane :)

**Comment by gavnunns** [comment]
This problem still exists and should be reopened.  I have tried multiple windows machines and the result is the same, hangs indefinitely creating the uninstaller.

**Comment by Asizon** [comment]
@gavnunns did you try development 10.8.0 build? Is here where the issues are adressed.

**Comment by gavnunns** [comment]
@Asizon I was using 10.7.1
I will give 10.8.0 dev build a go later today.
Thanks for the suggestion ;)
