### ISSUE TITLE
Vide Transmiter tab freezes

### ISSUE THREAD

**Issue by kzurada** [betaflight/betaflight-configurator#1838]
Hi. The Video Transmiter freezes if you put number of power levels > 0 without labels on them. Then the tab shows very strange values with no save button and so the whole configutar freezes too. This applies to version of beta flight 4.1.1 with configurator 10.6

**Comment by McGiverGim** [comment]
I can't reproduce it with latest developer versions. I think remember some fixes were added to the Configurator since the release. Can you test the latest developer version to see if it is fixed? You can find it here: https://github.com/betaflight/betaflight-configurator-nightlies/releases

**Comment by szafranski** [comment]
I had the same issue. I even made a screen shot. Only way to get rid of that was to manually add vtx table by CLI, something like:

vtxtable powerlevels 4
vtxtable powervalues 0 1 2 3
vtxtable powerlabels 25 200 500 800


saving, and then tab started to act as it should. 

![video_transmitter_broken](https://user-images.githubusercontent.com/23621888/71640015-b73fbe00-2c82-11ea-830c-1bd2ec44d922.PNG)

**Comment by McGiverGim** [comment]
Again, if you can, test the actual developer version to see if it is fixed. I can't reproduce it with the developer version.

**Comment by szafranski** [comment]
Issue still present in 10.7 RC

![beta_beta](https://user-images.githubusercontent.com/23621888/71644016-dc9fec80-2cc1-11ea-9de4-b44a9de9bc8f.PNG)

**Comment by Asizon** [comment]
Unable to reproduce under Windows 10 system, all Video Transmitter tab work as expected.
![vtxtableee](https://user-images.githubusercontent.com/43983086/71644468-1f18f780-2cc9-11ea-9a09-007a425a39b8.jpg)

**Comment by szafranski** [comment]
Maybe this will help:

https://youtu.be/1q4aALY4gkU

**Comment by McGiverGim** [comment]
@szafranski I have reproduced your bug... is not because the power level tal is empty, is because is empty and you have it selected as actual power level in the upper part.

I will look into it for a fix...

**Comment by szafranski** [comment]
Ok, glad I helped. Cheers
