### ISSUE TITLE
Link to latest CP210x drivers 404s

### ISSUE THREAD

**Issue by CamHardy** [betaflight/betaflight-configurator#1844]
The current link to the CP210x drivers leads to a Silicon Labs webpage with the text: "Error 404 - Not Found". I had to manually search for the drivers via Google.

**Comment by CamHardy** [comment]
The link that worked for me was [https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers](url)

**Comment by homenpunk** [comment]
I am still having the same issue.

**Comment by mikeller** [comment]
@homenpunk: What version of configurator are you using?
