### ISSUE TITLE
Cannot uninstall betaflight

### ISSUE THREAD

**Issue by jon2912** [betaflight/betaflight-configurator#1855]
It worked for a while, now cannot connect to my fc. I thought I'd reinstall betaflight, but when I try to uninstall I get 
Betaflight Configurator Uninstall
C:\Program Files [x86]\Betaflight\Betaflight-Configurator\uninbf00.dat not found, unable to perform uninstall. Manually delete files.
with a big X in a red circle.

**Comment by McGiverGim** [comment]
Duplicated of https://github.com/betaflight/betaflight-configurator/issues/1854 take a look to the other thread, to see if it helps.

**Comment by mikeller** [comment]
Duplicate of #1854.
