### ISSUE TITLE
Video Transmitter Tab Blank

### ISSUE THREAD

**Issue by fOmey** [betaflight/betaflight-configurator#1860]
Title says it all, I can't see any fields on the video transmitter tab.. seems to have started happening after I had updated to 4.1.3? I _believe_ I was running 4.1.1 prior to this.

I immediately updated betaflight configurator thinking it would resolve the problem, however the issue persists... I couldn't tell you what my previous betaflight configurator version was tho.

I loaded in my VTX table txt file & saved it, I can see it was applied in the CLI.

![Capture](https://user-images.githubusercontent.com/5051561/72871130-31250d80-3d3e-11ea-8e24-15b1b6d23c33.JPG)

**Comment by McGiverGim** [comment]
As the message says, you must configure the kind of vtx you have in the ports tab.

**Comment by fOmey** [comment]
I'm such a bloody doofus.. I don't know how I missed that.

Thank you.
