### ISSUE TITLE
Add Pilot Name to the Configurator UI

### ISSUE THREAD

**Issue by bizmar** [betaflight/betaflight-configurator#1877]
BF has Craft Name and Pilot Name as an option in the CLI and separate OSD elements, it would be nice if I could set Pilot Name in the Personalization part of the Configuration tab. May need to be added to MSP first.

**Comment by etracer65** [comment]
To be clear, it's the "display name" not pilot name.

But this will be more difficult than it would appear. The display name is currently not included in the MSP. Also the preexisting MSP messages where it would make sense to add the display name were designed in a legacy way and cannot be added to for this. So it would take new messages to get/set the display name in the firmware.

**Comment by mikeller** [comment]
On the plus side, we support MSPv2 now, so we are not limited to 256 messages any more.
