### ISSUE TITLE
BF-configurator 10.6.0 display bug in "mode" menu french version

### ISSUE THREAD

**Issue by PascalRZ** [betaflight/betaflight-configurator#1884]
Hi all,
I have a permanent display bug in BF-configurator 10.6.0, in the "mode" menu. I use the french version. I can't set modes because I can't read their names, fully covered by "Ajouter un lien" and "Ajouter une plage". I can only read "Arm" because the option "Ajouter un lien" is not displayed (this option is not possible with the "Arm" mode).

See attached file:
![Bug_display_mode_menu](https://user-images.githubusercontent.com/18939208/74683187-67806c00-51c8-11ea-8bcc-7b50677600c4.jpg)

Best regards.
PascalRZ

**Comment by McGiverGim** [comment]
The problem is related a too long strings in a not too width monitor. We will inform the french translator/proofreader to see if he can make it shorter. I will look too into modify the CSS to make this not happen.

**Comment by PascalRZ** [comment]
Thank you :)
