### ISSUE TITLE
Remove Nodjs version restriction

### ISSUE THREAD

**Issue by sl1pkn07** [betaflight/betaflight-configurator#1890]
https://github.com/betaflight/betaflight-configurator/blob/f697ae83b8dc9e9168c72a5ed447f09edb2275bf/package.json#L39-L41

Hi please this nodejs version restriction. buld OK with nodejs 13.x

greetings

**Comment by mikeller** [comment]
@sl1pkn07: The _supported_ version of node for Betaflight configurator is 10. If you want to use an unsupported version feel free to remove this line in your local repository. Just keep in mind that you will not be getting any support if there are bugs in this setup.
