### ISSUE TITLE
Possible to bypass range checking on Receiver tab in RC Smoothing panel

### ISSUE THREAD

**Issue by etracer65** [betaflight/betaflight-configurator#1907]
Problem has existed since 10.6.

Related to https://github.com/betaflight/betaflight/issues/9559 and https://github.com/betaflight/betaflight/pull/9560

To replicate, enter an invalid value in a text entry field - like the "Auto Smoothness" field. Try entering 100 (valid range is 0-50). Before leaving the field click "Save". The invalid value will be send via MSP and afterwards the validation will correct the range.

Problem happens on every text entry field in that panel.

Some mitigation was applied to the firmware for the "Auto Smoothness" field as invalid values can lead to "flyaway" type events by corrupting the smoothing of the throttle channel.

**Comment by McGiverGim** [comment]
In theory this was fixed and merged. I close this. It can be opened again.
