### ISSUE TITLE
Yaw RC rate missing from adjustments

### ISSUE THREAD

**Issue by Yamaford** [betaflight/betaflight-configurator#192]
Was just about to set up my rates to inflight tune and noticed yaw rc not there.
Thanks

**Comment by KiteAnton** [comment]
Yaw RC rate is currently not supported in Betaflight FW, see available functions [here](https://github.com/betaflight/betaflight/blob/master/src/main/io/rc_controls.h#L177-L201). 

Until Yaw RC rate is added to betaflight fw there is really not much that can be done in the configurator. I will close this issue, please add an issue/PR to [betaflight repository](https://github.com/betaflight/betaflight-configurator) if you really need this feature and then this issue can be re-opened after it has been added to the FW.

**Comment by borisbstyle** [comment]
it can be added

2016-08-08 13:02 GMT+02:00 Anton Stålheim <notifications@github.com>:

**Comment by KiteAnton** [comment]
Ok I added a PR for this to betaflight, I can add it also for configurator when the change is merged.

**Comment by KiteAnton** [comment]
This is fixed by #195
