### ISSUE TITLE
Betaflight 10.6.0

### ISSUE THREAD

**Issue by danielharley1** [betaflight/betaflight-configurator#1944]
# If your issue looks like a hardware fault or a configuration problem please don't raise an issue here.

## If you believe there is an issue with the firmware itself please follow these steps:
1. Describe your problem; my Mac saying that this new version of Betaflight is damaged and it cannot be open
2. Include ways to reproduce the problem; downloading latest on Mac and trying to open file
3. Provide as much information as possible about your hardware and software, including:
- what hardware / software you are using; macOS Mojave (Version 10.14.6)
- the version of all the software used; 10.5.0
- how things are connected / wired up: N/A

Thanks :)

**Comment by mikeller** [comment]
Duplicate of #1675.
