### ISSUE TITLE
Feature request: current averaging on motors tab

### ISSUE THREAD

**Issue by DmitrySamoylov** [betaflight/betaflight-configurator#1945]
To calibrate current sensor you should fill the [form](https://docs.google.com/spreadsheets/d/1lkL-X_FT9x2oqrwQEctDsEUhgdY19upNGc78M6FfJXY/edit) but smaller current values are hard to read because amperage is jumping. It would be cool to have current averaged for like 10 samples (or configurable amout of samples). So I can set motor speed, wait a bit and see averaged current, fill it in the table and then set another speed and so on.

**Comment by klutvott123** [comment]
Have you tried adjusting `ibat_lpf_period`? Setting it to a high value should give you stable readings for what you're trying to do.

**Comment by DmitrySamoylov** [comment]
Yeah it worked thanks!
