### ISSUE TITLE
Link to latest CP210x drivers 404s

### ISSUE THREAD

**Issue by homenpunk** [betaflight/betaflight-configurator#1948]
I am running Mac OS.
Downloading the link from Beta flight as well as your site, gets the 404 message.
I tried going through your site, searching for the update, but still received the error message.

**Comment by Asizon** [comment]
As you can read in the other same issue, this problem is already fixed and included in Betaflight Configurator 10.7.0 ;)

**Comment by mikeller** [comment]
Duplicate of #1844.
