### ISSUE TITLE
Can’t choose target devices nor the firmware in firmware flasher

### ISSUE THREAD

**Issue by ongeschikt88** [betaflight/betaflight-configurator#1958]
On MacOS  I can’t flash firmware for the flight controller. In the tab firmware flasher there are no targets in the dropdown box. 

It happens every time when I try to flash firmware. I use the latest betaflight configurator. Even reinstalled betaflight but still doesn’t work.

What I expected to happen was the same as you can find in al videos you can find online

I have a mamba f722 flight controller

**Comment by jflyper** [comment]
Sounds like the configurator is not granted for Internet access; it keeps saying loading because it's continuously trying to fetch firmware metadata from GitHub which it can't.

**Comment by ongeschikt88** [comment]
Problem solved. Betaflight didn’t had access to internet. Thanks for the help!

Nico
