### ISSUE TITLE
broken configurator tabs

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/betaflight-configurator#1961]
@mikeller  since #1956 a few tabs are no longer displayed correctly

I found this on the following tabs receiver, motors and blackbox

![receiver_tab](https://user-images.githubusercontent.com/29702171/79064720-af44e080-7cab-11ea-9303-1275d9323b6a.jpg)

![motors_tab](https://user-images.githubusercontent.com/29702171/79064721-b53ac180-7cab-11ea-90e1-415551840e7a.jpg)

![blackbox_tab](https://user-images.githubusercontent.com/29702171/79064750-e915e700-7cab-11ea-9306-429fc7673c16.jpg)

**Comment by mikeller** [comment]
Uaaa, this CSS is an abomination wrapped into a nightmare. :sob:

**Comment by McGiverGim** [comment]
True, our css is a mesh... But a complete redo is frightening 😱

**Comment by mikeller** [comment]
@McGiverGim: If a complete redo, then it definitely should not be done with hand-crafted styling in the first place. But agreed, a complete redo will include a scary amount of work to get to the level of completeness we are at now.
