### ISSUE TITLE
Save button on Blackbox Tab is broken

### ISSUE THREAD

**Issue by TheAngularity** [betaflight/betaflight-configurator#199]
I can change quite normal but unfortunately not save on tick the button :(

**Comment by KiteAnton** [comment]
Which version of configurator and betaflight firmware do you experience this with?

**Comment by TheAngularity** [comment]
Configurator 1.7.2 from last commit and BF 3.0.0 also last commit

**Comment by KiteAnton** [comment]
Thanks,  I will try to check this later. Do you get any error/warnings in the inspector console?

**Comment by TheAngularity** [comment]
cant see any error or warning

**Comment by KiteAnton** [comment]
@TheAngularity I can't reproduce your problem. Save button works for me on latest configurator from github. I actually doesn't reboot the board as it states but data is saved.

**Comment by TheAngularity** [comment]
here is my way to reproduce the problem:
- go to blackbox tab ... change something and save ... it's save but not reboot
- go to cli ... then type exit to reboot
- back to blackbox tab ... and the old values befor changed are back

**Comment by KiteAnton** [comment]
Yes ok, I can reproduce the same. Will investigate this, maybe the missing reboot will fix the issue.

**Comment by KiteAnton** [comment]
Ok, found the issue and fixed it. @TheAngularity thanks for reporting this, I was not aware it didn't work.
