### ISSUE TITLE
reboot

### ISSUE THREAD

**Issue by borntocrash** [betaflight/betaflight-configurator#2004]
I use a Fc dalrc F722 dual, with the latest firmware 4.2 on configuration 10.6 everything works but with the configurator 10.7 under Mac, my fc connects well, I have access to all tabs but it is impossible to save and rebooter. And besides the guy heats up abnormally

**Comment by GuidoHS** [comment]
I also cannot save and reboot on the AIKON F7 DJI version. Tabs were only save is required will work and retain their settings but the 'save and reboot' button seems to not do anything at all. Using the 10.7 RC on MacOS.
