### ISSUE TITLE
FeatureRequest: custom text and formulas in the OSD 

### ISSUE THREAD

**Issue by somethingstarted** [betaflight/betaflight-configurator#2013]
I think it would be pretty cool if you could have one or two fields to have Custom STRINGS 

I also think that would be pretty cool if you could have two fields that you could do math on any thing that has a measurement, and be able to get information and store some information too. like for instance, what if you wanted to store your initial GPS location, but you also wanted to have your current GPS location. then maybe you could do some math to make it so that if you were at 0.000 x 0.000 That means that you’re really close to where you took off that means that you’re really close to where you took off (or right exactly where you took off depending on how accurate your GPS is) - another instance of custom formulas could be doing some equations with The battery and cell count and some other stuff to make an easy, way to determine something, anything? it would also be cool to be able to put strings of text within the math formulas. Kinda like STRING <P * I * d = F> {F}  or Maybe be able to do some GPS calculation where it estimates how many feet or meters you are from your takeoff location. i’ll be able to determine that you are north or south of your takeoff location, Do some sort of thing with the compass to know which way you should point Do some sort of thing with the compass to know which way you should point maybe have an updating arrow. Basically, if you have the ability to do custom formulas that can update on the OSD, you could do some seriously powerful shit But she wouldn’t be able to otherwise but she wouldn’t be able to otherwise. 

Hell maybe you could do some math to determine your height even if you don’t have a barometer or something. The possibilities are literally endless The possibilities are literally endless. 

If you were to enable the math formula, I would then add an option to expose the programming variables underneath anything that you could look at while editing in beta flight it could be  accessed  by the  OSD calculator. 

then if you wanted to take it an extra step, you could maybe do a thing where you simulate the flight control CPU usage to make sure that your formulas don’t overload the system. 

I think that the The ability to have custom strings displayed on the quadcopter would be a pretty neat feature. But I really think that having custom calculations in the OSD could be a serious game changer, or at least really helpful

**Comment by etracer65** [comment]
> Maybe be able to do some GPS calculation where it estimates how many feet or meters you are from your takeoff location.

Like maybe the already existing Home Distance OSD element?

> Do some sort of thing with the compass to know which way you should point Do some sort of thing with the compass to know which way you should point maybe have an updating arrow. 

For example the already existing Home Direction element?

> Hell maybe you could do some math to determine your height even if you don’t have a barometer or something.

Like how the altitude calculation will already use GPS data to determine altitude in the absence of a barometer?
