### ISSUE TITLE
The firmware updater not working with some fc

### ISSUE THREAD

**Issue by HatalyakMate** [betaflight/betaflight-configurator#2016]
I have to fc Matek F405-STD, and Furious FPV Piko f4, and the firmware updater not working. 
I use 10,7 betaflight configurator, and i want to update my matek fc for 4.1 RC1( but every firmware is not update my fc (all configurator version, and all target verion)) but this happen:
![image](https://user-images.githubusercontent.com/64532004/81474487-09cb5100-9206-11ea-9fb7-a39b9931c41c.png)
I click on the load firmware online, and after flash firmware, and i got this message. I tried No reboot sequence, Full chip erase, Manual baud rate settings, but everytime get this message.

**Comment by mikeller** [comment]
@HatalyakMate: What operating system are you using?

Also, can you try to flash using DFU mode using the sequence of steps as described in `Recovery / Lost communication` on the firmware flasher tab - please do report if the port drop-down shows 'DFU' after the 'Release BOOT button if your FC has one' step.

**Comment by HatalyakMate** [comment]
I use win10
I went through all the recovery/lost communication steps but it still doesn't work, and when i push the dfu boot button and plug in, the betaflight dont see my fc

**Comment by McGiverGim** [comment]
I had a similar problem and I "fixed" it trying different usb cables and different usb ports. Have you tried this?

**Comment by HatalyakMate** [comment]
Yeah, i try all usb port, and all usb cable that i find, but i have another fc and this is work perfect, the matek and furious fc has this problem

**Comment by mikeller** [comment]
@HatalyakMate: What model is the flight controller that is working? On the builds that do not work, do you have any RX or other components that are powered when you are connected to USB and try to flash?

**Comment by HatalyakMate** [comment]
Clracing f4 is work perfect, when i try, simple fc, no rx, no solder, no anything

**Comment by HatalyakMate** [comment]
Or mamba mk2 is work perfect

**Comment by mikeller** [comment]
This is super weird - it looks like some of your boards are recognised when in DFU mode, others aren't. Can you please test with one board that isn't recognised in DFU mode: Put it into DFU mode (push Boot button, connect USB, release Boot button). Then open device manager in Windows, and check if there are any errors detected, or otherwise search for the DFU device and provide a screenshot of this.

**Comment by MATEKSYS** [comment]
This issue should be related to DFU driver. the DFU driver worked with dfusedemo will not work with BF/INAV configurator.  and vice versa.
I used to use dfusedemo occasionally,  I have to uninstall DFU driver which works with configurator first, then restall DFU driver for dfusedemo.

**Comment by MATEKSYS** [comment]
DFU driver working with dfuse is "STM Device in DFU mode"
![20200510134202](https://user-images.githubusercontent.com/23047106/81491765-5b3a1580-92c4-11ea-91dc-7a00cb31f1dd.png)

After replacing drivers with ImpulseRC_Driver_Fixer or zadig , the device will change to "STM32 BOOTLOADER", this device will not be detected by dfusedemo
![20200510134745](https://user-images.githubusercontent.com/23047106/81491801-da2f4e00-92c4-11ea-884d-c7005189881b.png)

**Comment by mikeller** [comment]
Thanks @MATEKSYS. I am not a Windows user so I am not familiar with 'DfuSe Demo', and did not know that this does not use the official STM DFU driver. But this would be a reason for why this is not working. It's just surprising that it still seems to be working for some boards - could be that the DFU interface registers with a different ID for different MCU types.

**Comment by mikeller** [comment]
@HatalyakMate: Can you please install the correct drivers using the sequence of steps as described in 'Recovery / Lost communication' on the firmware flasher tab, and then report back if this fixes it for you?

**Comment by HatalyakMate** [comment]
Okey, i try the zadig but zadig cant see my fc, (normal and dfu mode) but the iflight driver fix is working, fix my driver, but on the betaflight nothinh changed

**Comment by HatalyakMate** [comment]
so, zadig is find my fc, fixed driver, but now, betaflight cant see, and i got a yellow triangle on device manager

**Comment by HatalyakMate** [comment]
and finaly, i run again the impulse rc driver fix, and now, when i connect my fc in dfu mode, the betaflight see, and the flashing is working
![image](https://user-images.githubusercontent.com/64532004/81500718-4ebdb900-92d4-11ea-92fc-c987f244aa08.png)

**Comment by HatalyakMate** [comment]
Thanks for help everybody ✌️
