### ISSUE TITLE
Betafligtht opens in wrong language

### ISSUE THREAD

**Issue by C4Terminator** [betaflight/betaflight-configurator#2019]
# If your issue looks like a hardware fault or a configuration problem please don't raise an issue here.

## If you believe there is an issue with the firmware itself please follow these steps:
1. Describe your problem;
2. Include ways to reproduce the problem;
3. Provide as much information as possible about your hardware and software, including:
- what hardware / software you are using;
- the version of all the software used;
- how things are connected / wired up.
4. Remove this Text :).

**Comment by C4Terminator** [comment]
Betaflight Configurator changed languages on me. It should be English. how do i fix this???

**Comment by etracer65** [comment]
There is a list of languages at the bottom of the page on the welcome tab. Click the one you want.

**Comment by C4Terminator** [comment]
Thanks 🙏

From the mobile office of
LEEKA Architecture and Planning
Neil Lee

________________________________

**Comment by Timlazisa** [comment]
Where at the bottom of the page??

**Comment by Timlazisa** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/65236573/158029774-004b44fb-315f-4b52-8b6e-0959fb1648f0.png)

**Comment by McGiverGim** [comment]
Just under the Facebook button...

**Comment by jonnytest1** [comment]
> There is a list of languages at the bottom of the page on the welcome tab. Click the one you want.

i would prefer moving that into a more visible spot maybe left of the version field in a dropdown 🤔

**Comment by haslinghuis** [comment]
![image](https://github.com/user-attachments/assets/3847a916-d477-432d-93ee-6470ffdd8b65)
