### ISSUE TITLE
Missing tooltip for MOTOR_PROTO

### ISSUE THREAD

**Issue by hydra** [betaflight/betaflight-configurator#2022]
![image](https://user-images.githubusercontent.com/57075/81681612-abe07880-9454-11ea-9e2a-c3174cc1cc2d.png)

version: 10.7.0-RC1

As an aside, there is `NO_ACC_CAL` and `MOTOR_PROTO`, but it feels like the latter should be called `NO_MOTOR_PROTO` to follow suit.  Probably best to review the name for the new disarming reason before adding the tooltip.

**Comment by Asizon** [comment]
Added in https://github.com/betaflight/betaflight-configurator/pull/1993

**Comment by hydra** [comment]
@Asizon great! Closing as fixed.
