### ISSUE TITLE
Color selection and garish color resulting in blurry text

### ISSUE THREAD

**Issue by hydra** [betaflight/betaflight-configurator#2023]
See screenshots:

![image](https://user-images.githubusercontent.com/57075/81682757-64a6b780-9455-11ea-9289-75167c31ec38.png)

![image](https://user-images.githubusercontent.com/57075/81682789-712b1000-9455-11ea-92b5-922909bb17e8.png)

These used to be black, but some CSS styling has either changed accidentally or purposefully, but regardless of the reason for the change it results in blurry and messy text.

Version: 10.7.0-RC1
OS: Windows 10

**Comment by mikeller** [comment]
Can you please provide screenshots of your change?

**Comment by Asizon** [comment]
Really this blue text is more intuitive, I like alotof. For me is working so fine, 1080p and 125% escale:

![bluetext](https://user-images.githubusercontent.com/43983086/81778541-5ad39180-94f3-11ea-8250-715ac365f1ef.jpg)

**Comment by McGiverGim** [comment]
I don't like the blue links neither. They seem like 90's. But I don't have time at this moment to propose a new solution. Maybe at some moment.

**Comment by hydra** [comment]
@mikeller here's what 10.6.0 looks like. (built from git tag `10.6.0`)

![image](https://user-images.githubusercontent.com/57075/81803679-55d50900-9518-11ea-9b52-e587d7f4a8bb.png)

![image](https://user-images.githubusercontent.com/57075/81803735-66857f00-9518-11ea-84fe-0627be769bf4.png)

You can remove the 'Missing Information' tag now.

**Comment by mikeller** [comment]
@hydra:

Can you point out how, in your proposal, a user should be able to distinguish between emphasised text

![image](https://user-images.githubusercontent.com/4742747/81816040-e1818080-957e-11ea-95ab-4fe215f7ebfe.png)

and a clickable link

![image](https://user-images.githubusercontent.com/4742747/81815968-c9a9fc80-957e-11ea-81e6-43581d20d43f.png)

?

The usability of this is utterly useless. Proposals that ruin the usablity for the sole purpose of looks make no sense whatsoever and should not be considered.

**Comment by hydra** [comment]
@mikeller The issue I have is that the colors/styling produces a garish result, and it appears there was an unintended change to the color of the text on the button to reset the Z axis, which is not a link, and shouldn't have a link style.

two fixes are needed:
* style the links so they are not garish.
* style the button so it's not using the link style and doesn't look like a link style.

With regards to how users can distinguish what is a link and what isn't, yes a visual clue is useful/needed; Suggest some other color that fits in with the Betaflight configurator color palette, not dark blue, which doesn't.  Perhaps an orange, or grey would work?

**Comment by McGiverGim** [comment]
I didn't like the old black neither 🤪 Maybe I'm too exigent. 
I think some kind of grey can look good, but this needs play with it to search a good tone and see if it works.

**Comment by mikeller** [comment]
@hydra: I frankly don't want to discuss matters of your taste here, and what you think is garish or not. Please stop wasting everybody's time.
