### ISSUE TITLE
Feature Request: PID and Rate Profiles in Diff and Dump

### ISSUE THREAD

**Issue by N4V1G4T0R** [betaflight/betaflight-configurator#2025]
When having more than one Profile, PID or Rate, only the current profile is displayed in diff or dump.  You have to switch the profile manually, either in die PID Tuning Tab, or in CLI with "rateprofile x" and diff/dump again.

It would be a lot less trouble if all the profiles are displayed in diff/dump, once changed from defaults.

**Comment by McGiverGim** [comment]
You only need to do a `diff all` to dump all profiles

**Comment by N4V1G4T0R** [comment]
My bad, I thought of it (diff) as default (diff all). Thanks for the fast reply.
