### ISSUE TITLE
I had this problem where i couldn't connect my drone at MacOS Catalina, my computer is a MacBook Pro and I can't find the dev/tty.usbmodem when i connected my drone to the computer with a Micro-USB cable.

### ISSUE THREAD

**Issue by T1m044325** [betaflight/betaflight-configurator#2027]
I had this problem where i couldn't connect my drone at MacOS Catalina, my computer is a MacBook Pro and I can't find the dev/tty.usbmodem when i connected my drone to the computer with a Micro-USB cable.

**Comment by T1m044325** [comment]
Anybody with solutions?

**Comment by T1m044325** [comment]
i fixed

**Comment by mikeller** [comment]
@T1m044325: What was the fix?
