### ISSUE TITLE
10.7-RC1 won't run on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by frelar8** [betaflight/betaflight-configurator#2028]
Running 10.7-RC1 on Ubuntu 18.04 LTS appears not to work. Installs ok, but opening configurator only activates two processes but nothing happens. 10.6 and 10.5.1 works ok.

**Comment by mikeller** [comment]
@frelar8: That's curious - configurator is working just fine on Ubuntu 19.10 here. Can you try completely removing and then re-installing configurator to see if this helps:

```
sudo dpkg -P betaflight-configurator
sudo rm -rf /opt/betaflight/betaflight-configurator

sudo dpkg -i ~/tmp/betaflight-configurator_10.7.0-RC1_amd64.deb
```

**Comment by frelar8** [comment]
@mikeller: Tried removing and re-installing.
`sudo dpkg -P betaflight-configurator` also removes `/opt/betaflight/betaflight-configurator`
Also tried removing _betaflight-configurator_ from _.config_. Same as before; activates two processes and then nothing happens. Re-installing 10.6 (after removing 10.7-RC1) works fine

**Comment by mikeller** [comment]
@frelar8: What window manager are you using?

**Comment by frelar8** [comment]
@mikeller: I use GNOME Shell 3.28.4

**Comment by haslinghuis** [comment]
Try
$ sudo mkdir /usr/share/desktop-directories/

Betaflight Configurator in UBUNTU 20.04 encounters a bug in XDG https://bugs.archlinux.org/task/33316

**Comment by frelar8** [comment]
@haslinghuis Thanks for the tip but I can't try it, I've upgraded to 20.04 a few days ago (it works now).
