### ISSUE TITLE
Receiver tab not reading input!

### ISSUE THREAD

**Issue by jgreene88** [betaflight/betaflight-configurator#2029]
My receiver tab is not reading any input. The rx is bound with the tx.

**Comment by mikeller** [comment]
# If your issue looks like a hardware fault or a configuration problem please don't raise an issue here.

## Please consider using other user support options such as asking the manufacturer of the hardware you are using, RCGroups: https://rcgroups.com/forums/showthread.php?t=2464844, or Slack (registration at https://slack.betaflight.com/) or other user support forums & groups (e.g. Facebook).
