### ISSUE TITLE
Problem with installing betaflight on windows 7 64 bit.

### ISSUE THREAD

**Issue by radudek332** [betaflight/betaflight-configurator#2030]
I tried installing The newest available version of betaflight configurator on my pc but it said that the program is not compatible with my system because it might be 32 bit (86x) and not 64 bit (64x). I'm not sure if it's my computer or the program or both. I'm looking for help with installing it on my pc. Thanks in advance.

**Comment by McGiverGim** [comment]
The oficial Configurator is 32 bit and is compatible with both, 32 and 64 bit system.

Can you provide more info about your system?

**Comment by radudek332** [comment]
It worked after i redownloaded the installer
