### ISSUE TITLE
10.7 RC1 won't detect FC if connected before starting the configurator

### ISSUE THREAD

**Issue by seriousrob** [betaflight/betaflight-configurator#2032]
BF Configurator 10.7 RC1 won't detect FC if configurator was opend after FC was connected to the PC.

Tested on DALRC F722 Dual and SpeedyBee F4 V2 with BF4.2 RC1, Windows 10 x64 Build 18362

Drivers are up to date and working properly.

Reproduce the issues:

Close the Betafkight configurator
Connect your FC to your PC and wait for it to boot up properly
Open the Configurator and try to select the COM port
Disconnect your FC
Reconnect your FC

Regards,
Robert

**Comment by McGiverGim** [comment]
What we have observed is that for some reason it takes more time than usual to detect the ports. How much time you let for the Configurator to detect the port?

**Comment by seriousrob** [comment]
Tried it again and left it open a bit longer. Can confirm what you've said. It detects the FC quite some time after start up. I was a little impatient probably. Thanks for the feedback.
