### ISSUE TITLE
Anti Gravity Gain Display

### ISSUE THREAD

**Issue by N4V1G4T0R** [betaflight/betaflight-configurator#2033]
When changing the Anti Gravity Gain in Configuratior 10.7 (RC) and BF 4.2 (RC2) below 3,5 the value will be reset to 3,5 after saving. 

For example to 3,0 is set, after saving it shows 3.5 again.

However, in the CLI the value is set correctly. 
anti_gravity_gain = 3000

The effect does not occur, when going up, f.e. to 4,0. This works fine. It's just, when reducing the value below the default.

**Comment by McGiverGim** [comment]
This was fixed here: https://github.com/betaflight/betaflight-configurator/pull/2005

Will be available in the official release 😊

**Comment by N4V1G4T0R** [comment]
👍
