### ISSUE TITLE
PID sliders disabling

### ISSUE THREAD

**Issue by illmillrig** [betaflight/betaflight-configurator#2049]
if you set the Master multiplier to 0.5, and the PD Balance slider to 1.5 and save, the sliders disable themselves.

**Comment by illmillrig** [comment]
it's not necessarily 0.5 and 1.5.  there are various combinations of slider values that when saved, cause the sliders to disable themselves.

**Comment by illmillrig** [comment]
Master Slider 0.5
PD Balance 1.2
P and D Gain 1.3

**Comment by illmillrig** [comment]
I think it would be better to manually have to disable the sliders via checkbox, in order to adjust individual RPY PID values, instead of guessing when i've changed those values and the sliders need to be disabled.

**Comment by Asizon** [comment]
Seems that you are using outdated Configurator version like 10.6.0, for 4.2 please use latest 10.7.0 build

**Comment by illmillrig** [comment]
![image](https://user-images.githubusercontent.com/12991367/83965617-b4687b00-a869-11ea-895b-8e11b8f777bf.png)

for some reason I recall needing to update to 10.7 in order to flash 4.2, but could be mistaken

**Comment by Asizon** [comment]
I got it! @illmillrig you need to provide more info about your setup, and diff. Anyway, I supose that your are making PID changes with Dmin feature disabled, im able to reproduce it in this way 👍 
![image](https://user-images.githubusercontent.com/43983086/83974342-f4bd0d00-a8ec-11ea-9359-7233fdb15f6e.png)

**Comment by Asizon** [comment]
From what I can see so far, its breaks in the new functionality for PD ratio calculation that is now aplied to D, but only on Dmin disabled part. Introduced in https://github.com/betaflight/betaflight-configurator/pull/1969

**Comment by Asizon** [comment]
To reproduce:
Betaflight 4.2 RC4
Configurator 10.7.0 RC2
1-go to pidtuning tab
2-disable dmin feature
3-put master slider on 0.5
4-put PD Balance slider on 1.5
5-save

**Comment by McGiverGim** [comment]
I have reproduced with the instructions of @Asizon, I reopen this again...

**Comment by McGiverGim** [comment]
I let this open, is good to have this bug as a remember, maybe someone gets to a good fix.

**Comment by haslinghuis** [comment]
Thanks for the testing procedure. It's still working now. Have to keep this in mind while we migrated to firmware sliders.

**Comment by haslinghuis** [comment]
Guess this can be closed now as there are a lot of PR's merged to fix the legacy sliders and introduce firmware sliders. Now the firmware sliders needs improvement :smirk: 
https://github.com/betaflight/betaflight-configurator/pull/2429
https://github.com/betaflight/betaflight-configurator/pull/2418
https://github.com/betaflight/betaflight-configurator/pull/2415

**Comment by ChristofferGylin** [comment]
I´m having the same issue, I don´t remember the values of the faders at the time, exept that the master was at 0.7, and the PD-ballance around 1.5. Dmin is turned off, and I´m on Betaflight 4.2 and running configurator 10.7.0

**Comment by haslinghuis** [comment]
@ChristofferGylin this has been fixed (so far we know) in the upcoming releases.
