### ISSUE TITLE
Build configurator for arm64 linux

### ISSUE THREAD

**Issue by ss8688** [betaflight/betaflight-configurator#2051]
I want to build it for Raspberry pi os (64bit),but I don t know how to build it for armv8 processor.

**Comment by mikeller** [comment]
@ss8688: Betaflight configurator does not support the armv8 platform. There is an armv7 target, run `yarn gulp release --armv7`: https://github.com/betaflight/betaflight-configurator/blob/0ee367b84191a86c72cb96d3cab2d579b369f3f5/gulpfile.js#L104

**Comment by smart2pet** [comment]
Please reopen this issue. I have the same problem.

**Comment by smart2pet** [comment]
Ok.

**Comment by godstargod** [comment]
> @smart2pet I wrote a _quick and dirty_ shell script available [here](https://raw.githubusercontent.com/romainvaltier/betaflight-configurator-arm64/master/install.sh) to automatically install and patch Betaflight-Configurator for my Pinebook-Pro (aarch64/arm64) and it is working properly.
> 
> `sudo ./install.sh`
> 
> You may have a try. No guarantee it will work for you as well.

thank you roman !! your work works off a pi400 with latest ubuntu 

now if i can only get to build edgetx native off of my pi ill be all set

cheers !

**Comment by vu2iia** [comment]
Thank you very much [romain](https://github.com/romainvaltier). I installed it on my pi-4 2024-03-15-raspios-bookworm-arm64 & BFC v10.10, had been struggling to compile it. 
mahesh-vu2iia

**Comment by moritzschaefer** [comment]
Nowadays Linux on Apple Silicon would very much appreciate if aarch64 would be supported

**Comment by moritzschaefer** [comment]
Thanks for the info. Will have a look
