### ISSUE TITLE
No Stick Inputs On Reciever Tab

### ISSUE THREAD

**Issue by Levikjohnson** [betaflight/betaflight-configurator#2057]
Hello, I have run into an issue after setting up a new build where the sticks and aux channels so not move in the reciever tab. I have spent probably 10 hours looking at everything on the internet. I have updated drivers, and firmware, changed every related setting in bf and changed my wiring multiple times. I am using a mambo nano f411 stack, a qx7 and an xm+. I am an experienced builder but this has really gotten me stumped. Any help wouldbe much aprec iated

**Comment by mikeller** [comment]
# If your issue looks like a hardware fault or a configuration problem please don't raise an issue here.

## Please consider using other user support options such as asking the manufacturer of the hardware you are using, RCGroups: https://rcgroups.com/forums/showthread.php?t=2464844, or Slack (registration at https://slack.betaflight.com/) or other user support forums & groups (e.g. Facebook).
