### ISSUE TITLE
Translation strings break UI

### ISSUE THREAD

**Issue by DusKing1** [betaflight/betaflight-configurator#2065]
Both zh_CN and zh_TW have this issue. Since we cannot shorten the translation, we hope we can find a solution in UI code.

I can't remember which version had the first problem, and I'm a little busy ATM. But I'm always willing to helping you guys find out.

![image](https://user-images.githubusercontent.com/31283897/84744317-a6db8f80-afe5-11ea-8a49-d5809f0c8f94.png)
![image](https://user-images.githubusercontent.com/31283897/84744343-ae029d80-afe5-11ea-9403-04bf1eeed574.png)

Edit: Similar problems occur on the Android APP.

![image](https://user-images.githubusercontent.com/31283897/84744804-4862e100-afe6-11ea-97d3-b5a6782a1df8.png)

**Comment by McGiverGim** [comment]
This worked at some version? I don't remember any change to this, but if you think it worked before I can go back in the code trying to find the culprit. Version 10.6 was working?

**Comment by DusKing1** [comment]
Also breaks on 10.6.0.

**Comment by McGiverGim** [comment]
I think it never worked. Maybe in 10.5.0 it was not translated, I don't remember.
So we need to try to find a way to let bigger texts. I think I looked at it before and I didn't find a suitable way :(
I will try to look at it.
