### ISSUE TITLE
Betaflight 10.7.0 preview android.apk/prob.

### ISSUE THREAD

**Issue by jaisenas** [betaflight/betaflight-configurator#2083]
# If your issue looks like a hardware fault or a configuration problem please don't raise an issue here.

## If you believe there is an issue with the firmware itself please follow these steps:
1. Describe your problem;
2. Include ways to reproduce the problem;
3. Provide as much information as possible about your hardware and software, including:
- what hardware / software you are using;
- the version of all the software used;
- how things are connected / wired up.
4. Remove this Text :). 
#
In the betaflight 10.7.0 preview android.apk
the vtx.js file should read as vtx: true not false.  It dose not display vtx setting at all.

**Comment by McGiverGim** [comment]
> In the betaflight 10.7.0 preview android.apk
the vtx.js file should read as vtx: true not false. It dose not display vtx setting at all.

It works in the standalone computer Configurator? It only fails in the Android version?

The VTX says true when it is connected and configured. Have you configured it in the ports tab?

**Comment by Asizon** [comment]
I think doesnt yet work file manager to load files like vtx table json

**Comment by jaisenas** [comment]
ive setup and configure my vtx and flightcontroller proper yet it wont
display vtx as an option in the app. Insted i just set it in the CLI [set
vtx_power = 3] or [set vtx_channel = 0] or what ev

**Comment by Asizon** [comment]
@jaisenas please provide a diff from your setup, seems that you are using a old version that not suported vtxtables
