### ISSUE TITLE
[FR] Android: Add a window with warning on app exit

### ISSUE THREAD

**Issue by Lord-Quake** [betaflight/betaflight-configurator#2100]
I believe it would be good idea to add a warning window concerning app exit.
When working on settings one can easily hit the back function on the phone by mistake with the app closing unexpectedly.

My recommendation:

Window Title "Warning"
Text "Are you sure you want to exit?" or something similar.
Options are "No"  "Yes"

**Comment by McGiverGim** [comment]
I close this, the change was implemented and merged.
