### ISSUE TITLE
[very minor] typo in div class in motors.html

### ISSUE THREAD

**Issue by alvaropp** [betaflight/betaflight-configurator#2105]
I guess it should say `"clear-both"` rather than `"cler-both"`. Not sure if there's any unintended effects but I reckon it's better fixed.

https://github.com/betaflight/betaflight-configurator/blob/master/src/tabs/motors.html

187 `<div class="cler-both"></div>
`

**Comment by Asizon** [comment]
Good catch @alvaropp !Fixed in https://github.com/betaflight/betaflight-configurator/pull/1946

**Comment by McGiverGim** [comment]
Merged and fixed, I close this.
