### ISSUE TITLE
Diff_Safe Feature

### ISSUE THREAD

**Issue by maybenikhil** [betaflight/betaflight-configurator#2106]
I'm not sure which git I should put this in, but in recent releases, it has not been advisable to diff settings (or at least diff all), which means the two options are to 1. diff all and then handpick what is considered "safe" or 2. completely reconfigure your setup. This makes upgrading inconvenient for many users who just want to get out there and fly, and makes it harder for some to justify an upgrade. A feature like "diff safe" would only diff the values considered safe, which would include the vtx table, rates (because although the rates have had a rework, betaflight rates = betaflight rates still), ports, most of the configuration tab (besides maybe looptimes), the failsafe tab, etc. This would make the transition between future BF versions much faster. 

A conversation about this on slack:
https://betaflightgroup.slack.com/archives/C221J1H54/p1593210603339100

**Comment by mikeller** [comment]
@maybenikhil: The problem with this is that what you are asking for would require an oracle: At the time that any given firmware it is released, it is not yet known what parameters will undergo a change in the development of the next version of firmware, so it is not possible to predict what parameters will be 'safe' to be applied to the next version.
I think a better way to deal with this will be an external tool (could be a web service) that allows one to paste a `diff` from a given firmware version, and select a target version, and then download a `diff` that's had unsafe values stripped, or even converted, to work with the target version.
