### ISSUE TITLE
Broken configuration tab

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/betaflight-configurator#2113]
since latest master is the configuration tab partial broken

here a screenshot ... i have marked what's wrong
also the switches from acc, baro and mag are shown as ON, although everything is deactivated in config

![configuration_tab_2](https://user-images.githubusercontent.com/29702171/86891370-03baf900-c0ff-11ea-812d-a2c5ce6998e7.jpg)

@McGiverGim pls can you check what's wrong with #2110

**Comment by McGiverGim** [comment]
Yes, this was a risky PR and the rebases make things worse... I will look into it. Thanks for the report!!
