### ISSUE TITLE
Filter Targets with text search in Firmware Flasher

### ISSUE THREAD

**Issue by rhys100** [betaflight/betaflight-configurator#2150]
My suggested feature here is to enable search in the betaflight targets as the list gets longer and longer so it's quicker and easier to find your betaflight target to flash. A suggested GUI interface example below, where you type and it filters the text you have written.

![Photoshop_Nm3DiRAj5J](https://user-images.githubusercontent.com/8174496/89697981-23de1200-d962-11ea-90ca-cd82fc43269f.png)

**Comment by rhys100** [comment]
I have put my money where my mouth is and kicked this off with a $15USD bounty reward https://www.bountysource.com/issues/92256568-filter-targets-with-text-search-in-firmware-flasher / You may back this as well if you think it's helpful.

**Comment by McGiverGim** [comment]
It's a good idea.

**Comment by pevecyan** [comment]
Hi, 
I added this option under pull request #2152 
If this will be accepted please consider giving that money directly to betaflight via donation :)

**Comment by McGiverGim** [comment]
@rhys100 this feature request has been developed by @pevecyan and merged.

You can test the nightly build if you want: https://github.com/betaflight/betaflight-configurator-nightlies/releases

**Comment by rhys100** [comment]
SO good.! 👍 
![image](https://user-images.githubusercontent.com/8174496/91147795-1e235300-e6fc-11ea-8fa4-f95bae4995e8.png)
