### ISSUE TITLE
BF not working on first build

### ISSUE THREAD

**Issue by zakrog** [betaflight/betaflight-configurator#2157]
I put together a tyro119 as my first build. Everything is together, plugged it into betaflight, and gyro was working (could see my quad moving in betaflight when I moved it IRL). I then saved the CLI dump in a text file, which also indicates that my board is a MATEKF405.

Accordingly, I held the boot button when I plugged it back in, entered DFU mode, loaded up the most recent version of the MATEKF405, and erase/flashed the FC.

Now, the gyro no longer works and the calibrate accelerometer tab is greyed out. Additionally, I can't set the drone up in Angle mode because it's simply not available on the mode tab. which suggests to me that the firmware is wrong. The FC is still receiving input from my transmitter, however.

I am throwing disable flags: NOGYRO RXLOSS BOXFAILSAFE CLI MSP GPS RESCUE_SW

I felt like I must have installed the wrong version, but I've tried 5 different MATEKF405 firmwares and the same issue is there each time. I then went into CLI and copy/pasted the original dump that I saved, but betaflight simply disconnects from the FC and states:

2020-08-19 @ 19:42:59 -- Unrecoverable failure of serial connection, disconnecting...

2020-08-19 @ 19:42:59 -- Failed to close serial port

I have installed the STM and the CP210x drivers on my comp, and run Zadig and the ImpulseRC driver fixer, but to no avail.\

This is my first time soldering, but I had plenty of practice and I feel like my joints are fine.

I would appreciate any tips on what to try next. Apologies if my entry is not specific enough, I am new to the hobby.

**Comment by McGiverGim** [comment]
Did you apply the default settings when connected the first time after flashing?
Github is for development problems, for user problems use Facebook group or official Betaflight slack chat.
