### ISSUE TITLE
Betaflight wont open on Windows 10

### ISSUE THREAD

**Issue by el-kwadro-fpv** [betaflight/betaflight-configurator#2161]
Hello,

i configured and flashed a F722 flight controller. After that i want to start up Betaflight.exe again but it wont open up anymore. Task manager shows that there is a Task open, but nothing happens anymore.

I uninstalled and reinstalled BF 10.7.0 severeal times. It doesnt help.

It worked allways flawless but from one moment to another its not working anymore.

**Comment by haslinghuis** [comment]
Try solution posted here: https://github.com/betaflight/betaflight-configurator/issues/2063

**Comment by el-kwadro-fpv** [comment]
> Try solution posted here: #2063

Thanks for that hint, but unfortunately it wont work out.

**Comment by mikeller** [comment]
@el-kwadro-fpv: What GPU / graphics card do you have in this PC, and what driver version for it is installed?

**Comment by el-kwadro-fpv** [comment]
> @el-kwadro-fpv: What GPU / graphics card do you have in this PC, and what driver version for it is installed?

@mikeller Nvidia Geforce GT 650M Version 376.54

**Comment by haslinghuis** [comment]
Maybe information below does apply to you? Are you using the drivers supplied by the OEM or did you update from Nvidia itself?

`"This is a reference driver that can be installed on supported NVIDIA notebook GPUs. However, please note that your notebook original equipment manufacturer (OEM) provides certified drivers for your specific notebook on their website. NVIDIA recommends that you check with your notebook OEM about recommended software updates for your notebook. OEMs may not provide technical support for issues that arise from the use of this driver."
`

**Comment by el-kwadro-fpv** [comment]
> Maybe information below does apply to you? Are you using the drivers supplied by the OEM or did you update from Nvidia itself?
> 
> `"This is a reference driver that can be installed on supported NVIDIA notebook GPUs. However, please note that your notebook original equipment manufacturer (OEM) provides certified drivers for your specific notebook on their website. NVIDIA recommends that you check with your notebook OEM about recommended software updates for your notebook. OEMs may not provide technical support for issues that arise from the use of this driver." `

until a couple hours the OEM drivers where installed. I made an update just right now to try out.

BF used to work until i flashed the FC to BF version 4.2.2. Now it wont start up anymore

**Comment by haslinghuis** [comment]
Please uninstall BFC 17.0 and manual remove `C:\Users\USERNAME\AppData\Local\betaflight-configurator` and install again to see if this helps.
Also is there a posibility to switch the GPU to use the Intel Graphics Adapter?

**Comment by el-kwadro-fpv** [comment]
> Please uninstall BFC 17.0 and manual remove `C:\Users\USERNAME\AppData\Local\betaflight-configurator` and install again to see if this helps.

Allready did this about 10 times. Switched to 10.6, 10.7 RC1 and RC2 and back to 10.7. No BF works anymore.

> Also is there a posibility to switch the GPU to use the Intel Graphics Adapter?

Yes it is. I allready deactivated the GPU but it's still not working for me.

**Comment by el-kwadro-fpv** [comment]
> Please uninstall BFC 17.0 and manual remove `C:\Users\USERNAME\AppData\Local\betaflight-configurator` and install again to see if this helps.

deleting the folder manually worked out! Thank you so much.
I feel pretty stupid, because i just deleted the remaining files in the installation folder.

Can't tell you how glad i am right now! THANKS.
