### ISSUE TITLE
Feature Request(presets based on quad class)

### ISSUE THREAD

**Issue by KAJE1977** [betaflight/betaflight-configurator#2167]
I really appreciate all the hard work you guys do. If I had the know how I would love to contribute myself. I been trying to learn as much as I can. I just wanted to put an idea out there about maybe having some presets based on quad class in the configurator for pids and filters and then have the sliders work based off those starting points of quad class. Could maybe simplify tuning a little bit more. I don't know how much work that would be. Thank you for all the amazing work and innovation you guys bring to the table on a daily basis

**Comment by McGiverGim** [comment]
This has been requested before: https://github.com/betaflight/betaflight-configurator/issues/1139 and https://github.com/betaflight/betaflight-configurator/issues/1811

Simply nobody has taken the time to work on it. :)
