### ISSUE TITLE
Flashing firmware pauses while configurator is out of focus

### ISSUE THREAD

**Issue by bluehallu** [betaflight/betaflight-configurator#2170]
When you start flashing firmware, the "Flashing" bar will stall and not move if you alt-tab into any other app. Bringing the configurator in focus seems to resume it without any issues.

Windows 10 / Configurator 10.7.0

**Comment by McGiverGim** [comment]
Yes it's a known issue but I don't know if it can be fixed in some way. I will mark this as a bug to not lost it, maybe sometime has some idea of time to look at it.

**Comment by McGiverGim** [comment]
More info about this: https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API
