### ISSUE TITLE
Motors Dont Stop Spinning on Disconnect

### ISSUE THREAD

**Issue by Minerest** [betaflight/betaflight-configurator#2174]
1. Describe your problem;
    When on the motors tab, you can choose to spin the motors using the GUI by manipulating the motor sliders. If the sliders are active and you disconnect from the Betaflight configurator, the motors continue to spin
2. Include ways to reproduce the problem;
    1. Navigate to the motors tab
    2. Check the box that reads "I understand the risks"
    3. Move the motor sliders
    4. Disconnect by hitting the red button on the top right of the screen. The motors continue to spin.
3. Provide as much information as possible about your hardware and software, including:
- what hardware / software you are using;
    HiFion F405 Stack
- the version of all the software used;
    Betaflight 4.1.0
    Betaflight Configurator 10.7.0

**Comment by haslinghuis** [comment]
Yes, this a feature, not a bug. This is to allow debugging motors in CLI with `dshot_telemetry_info` or using sensor tab. The safety precaution is to remove props before using this feature.
