### ISSUE TITLE
OSD problems

### ISSUE THREAD

**Issue by KAJE1977** [betaflight/betaflight-configurator#2214]
I had a recent issue with all 5 of my flight controllers. I am using the nightly builds of the configurator. I was using the latest nightly and had uploaded images to the osd no problem. It was only when i uploaded a different font i ran into a problem. I had thick black bars across my whole image in fpv feed and small random pixels of my video were showing through. Hard to explain. But i kept flashing previous nightly builds until i got to the version before 20201004.967. I think there was alot of osd refactoring in this version. Anyway i could upload an image completely fine but the font is what screwed it up on all of my flight controllers. Another wierd issue too was i tried flashing over to emuflight and the problem carried over until i went back to betaflight and went to the configurator version before the one i posted here and it fixed it. I dont understand at all why. Just an observation. If this is user error them i apologize in advance. Thank you.

**Comment by McGiverGim** [comment]
If I understood well, the OSD goes mad when you upload a new font. I will try to reproduce, but until Tuesday I'm out.
Someone more can confirm the issue?

**Comment by Asizon** [comment]
Tested @McGiverGim , definitelly it is a issue in osd code, using latest 10.8.0 build and old 4.3 build,it looks like that:

![image](https://user-images.githubusercontent.com/43983086/95680372-7e515400-0bd9-11eb-9d27-fccd757bfd9e.png)

**Comment by KAJE1977** [comment]
Yes exactly on everyone of my flight controllers and the issue carried over to a different firmware " emuflight ". The only fix was to go back to the release before the one i posted i believe.

**Comment by KAJE1977** [comment]
Fixed right away. Thank you so much
