### ISSUE TITLE
v10.07 "Save & Reboot" Serial Port Issue Crashing Ubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by fdmusn** [betaflight/betaflight-configurator#2216]
Hello,

Betaflight v 10.07
Ubuntu 18.04.5

Having problems with "Save and Reboot" crashing Ubuntu when serial port cannot be opened.

I can connect and flash fine
I can disconnect and reconnect fine
I can "save" on those pages that have "save" only

But as soon as I hit "save and reboot" ":
Every subsequent connection attempt fails
Ubuntu stops responding
Even software powerdown hangs up
Does the same with Cleanflight if that helps.

(added) reverting to prior linux kernel no help; same problem

After doing hard reset and power back up there's an Ubuntu issue report it asks to send ... appended below

Thoughts?

----------- UBUNTU CRASH REPORT ----------------
ProblemType: KernelOops
Annotation: Your system might become unstable now and might need to be restarted.
Date: Sun Oct 11 12:28:33 2020
Failure: oops
OopsText:
 watchdog: BUG: soft lockup - CPU#1 stuck for 23s! [kworker/1:1:2324]
 Modules linked in: ccm binfmt_misc nls_iso8859_1 snd_hda_codec_idt snd_hda_codec_generic snd_hda_codec_hdmi hp_wmi sparse_keymap wmi_bmof edac_mce_amd cdc_acm kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel pcbc aesni_intel aes_x86_64 crypto_simd glue_helper cryptd uvcvideo videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 videobuf2_core videodev media joydev input_leds serio_raw rtsx_pci_ms memstick k10temp snd_hda_intel snd_hda_codec radeon snd_hda_core snd_hwdep snd_pcm snd_seq_midi snd_seq_midi_event arc4 snd_rawmidi ath9k ath9k_common ath9k_hw snd_seq ath ttm drm_kms_helper mac80211 snd_seq_device snd_timer drm snd i2c_algo_bit fb_sys_fops soundcore cfg80211 syscopyarea sysfillrect sysimgblt shpchp wmi hp_wireless hp_accel lis3lv02d video input_polldev mac_hid sch_fq_codel
  parport_pc ppdev lp parport ip_tables x_tables autofs4 hid_logitech_hidpp hid_logitech_dj hid_generic usbhid hid rtsx_pci_sdmmc psmouse rtsx_pci r8169 mii ahci libahci i2c_piix4
 CPU: 1 PID: 2324 Comm: kworker/1:1 Tainted: G        W    L   4.15.0-118-generic #119-Ubuntu
 Hardware name: Hewlett-Packard HP Pavilion g4 Notebook PC/1847, BIOS F.26 02/21/2013
 Workqueue: usb_hub_wq hub_event
 RIP: 0010:try_to_grab_pending+0xf2/0x150
 RSP: 0018:ffff9bf1008dfaa0 EFLAGS: 00000286 ORIG_RAX: ffffffffffffff11
 RAX: 0000000000000000 RBX: ffff8d85d2a9e790 RCX: 0000000000000002
 RDX: 0000000000000001 RSI: 0000000000000002 RDI: 0000000000000286
 RBP: ffff9bf1008dfac0 R08: ffff8d85da401240 R09: ffff8d85deca1140
 R10: 0000000000000040 R11: 0000000000000000 R12: ffff9bf1008dfad0
 R13: ffff8d85deca1140 R14: ffff9bf1008dfaf0 R15: ffffffff86aa9800
 FS:  0000000000000000(0000) GS:ffff8d85dec80000(0000) knlGS:0000000000000000
 CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
 CR2: 00007f4199e49040 CR3: 000000000980a000 CR4: 00000000000406e0
 Call Trace:
 
Package: linux-image-4.15.0-118-generic 4.15.0-118.119
SourcePackage: linux
Tags: kernel-oops
Uname: Linux 4.15.0-118-generic x86_64

------------------------------------------------------------------

# If your issue looks like a hardware fault or a configuration problem please don't raise an issue here.

## If you believe there is an issue with the firmware itself please follow these steps:
1. Describe your problem;
2. Include ways to reproduce the problem;
3. Provide as much information as possible about your hardware and software, including:
- what hardware / software you are using;
- the version of all the software used;
- how things are connected / wired up.
4. Remove this Text :).

**Comment by haslinghuis** [comment]
There are memory leaks reported for linux-image-4.15.0-118-generic 4.15.0-118.119. Not sure if it has something to do with your problem. Try upgrading to Ubuntu 20.04
