### ISSUE TITLE
betaflight configurator 10.7 freezes.

### ISSUE THREAD

**Issue by ryansmall75** [betaflight/betaflight-configurator#2219]
Setup tab shows generic top bottom left right front back box. 
Calibrate accel. works properly. 
Clicking or trying anything else at all, freezes the configurator.
Betaflight configurator 10.6 works fine.
BFC 10.7
BF 4.2
MatekF411 fc.
windows pc.

**Comment by Asizon** [comment]
@ryansmall75 please try that:
https://github.com/betaflight/betaflight-configurator#graphics-issues

**Comment by ryansmall75** [comment]
Not a graphics issue, the program freezes as soon as i try to click any of the tabs...
FXAA was already off

**Comment by Asizon** [comment]
Yes, if you can see a box in setup tab, it is a graphic issue.

**Comment by ryansmall75** [comment]
Ah yes, you are correct. I thought BF worked with my other flight controllers yet. I cannot use 10.7 at all.

**Comment by Asizon** [comment]
This issue can be closed
