### ISSUE TITLE
Add a DFU Button

### ISSUE THREAD

**Issue by Tomcatt** [betaflight/betaflight-configurator#223]
Are you able to add a DFU Mode button on the Setup page?  That way you don't have to click on CLI then type it.

Yeah I know, lazy.
LOL

**Comment by mikeller** [comment]
This will have to be added to the MSP protocol on the flight controller side first.

**Comment by borisbstyle** [comment]
It does that automatically actually once you press flash

**Comment by gaelj** [comment]
Yes, what's the point ?
Also could you rename the issue to a more explicit title please ? Such as "add DFU button"

**Comment by Tomcatt** [comment]
I was looking for the option to make it a feature or a small enhancement; not a problem.

**Comment by borisbstyle** [comment]
Yes but can you explain why it is needee?

**Comment by Tomcatt** [comment]
Example
I'd like to go to DFU; so apply power configurator it sees the FC and connects.  First page I see is the setup page.  Oh look, there's "Reboot to DFU".  Why I didn't have to click on CLI to bring up a different page, click on the command box to activate the cursor and hit four keys on the keyboard to do to achieve DFU.

Or for some of us take the top plate off and short the BL pad with one hand and plug the other end of the USB to the computer.  (But that's reserved for if the flash goes bad)

GUI can be as good as CLI but this isn't the time or place for that age old argument.

**Comment by gaelj** [comment]
Ok but our question is, why would you want to go in DFU if it's not to
flash (in which case DFU automatically kicks in) ?

**Comment by Tomcatt** [comment]
Ah, I see where you two are coming from with that way of doing DFU.  I was going about it a different way.  No worries. My bad.

Could you guys close this ticket please?

**Comment by gaelj** [comment]
I can't, but you can close it if you opened it :)

**Comment by skaman82** [comment]
closed
