### ISSUE TITLE
Configurator not starting in debug mode

### ISSUE THREAD

**Issue by mikeller** [betaflight/betaflight-configurator#2257]
Reproduction:
- start configurator in debug mode with `yarn start`;

Expected behaviour:
- a configurator window opens

Actual behaviour:
- the following error message appears:
![image](https://user-images.githubusercontent.com/4742747/97087284-87383000-1685-11eb-9b75-f6f1ff831def.png)

**Comment by McGiverGim** [comment]
It says localisation used. Where we have chrome localisation? I tested it in my system before my pr. Let me do tomorrow more tests.

**Comment by McGiverGim** [comment]
Maybe you have the _locales folder remaining? The debug mode did not erase old files before building.

**Comment by haslinghuis** [comment]
After deleting the remaining _locales folders it works!

**Comment by mikeller** [comment]
@McGiverGim: Yes, you are correct, deleting `./debug/betaflight-configurator/linux64/_locales` fixed this.
