### ISSUE TITLE
[Feature request] geo-fence

### ISSUE THREAD

**Issue by Insorior** [betaflight/betaflight-configurator#2265]
Rescue options are great but I really feel like adding geo fence features would be minimal development and huge safety improvement.
Plus in multiple countries including France, it’s technically forbidden to fly a drone if you can’t :

_limit its operating zone BOTH vertically and horizontally 

Implementation ideas : 
For vertical : if the drone goes over vertical limit custom value in meters, it will stop ascending. It could be switched to level/horizon mode automatically and descend slowly until distance (or below distance minus margin, let’s say 190m if the limit is 200m) is below limit and pilot takes over.  

For horizontal : if the drone goes over horizontal set distance value, trigger failsafe/Géo rescue 

Again I’m pretty sure that relying on existing features this would be kinda easy to implement and allow lots of pilots to feel safer and complying with their local rules, which might spread to other countries.

Thanks for your time !

**Comment by mikeller** [comment]
@Insorior:

- the information you have on legislation in places like France is incomplete. Please read up on the **complete** requirements - implementing a small subset of the requirements in a piecemeal fashion, while being completely unable to comply with others (like having the firmware certified and locked down) will not  help anybody, as the resulting firmware will still be just as illegal to be used in these legislations as the current one is;
- if you see a way to add geofencing (in a way that actually works and does not just results in a crash when the boundary is reached) to Betafligth with minimal effort then feel free to open a pull request for this;
- in general, for anything to do with autonomous flight and GPS based navigation, [iNav](https://github.com/iNavFlight/inav) is a project that has this as a project goal - maybe you want to look into using this?
