### ISSUE TITLE
BETAFLIGHT EXECUTABLE IS INFECTED

### ISSUE THREAD

**Issue by ylectron** [betaflight/betaflight-configurator#2269]
Adware.Dotdo.Z.Lokq | Filseclab
-- | --

**Comment by McGiverGim** [comment]
It is not. We have several false positives with each version. Upload it to some web like https://www.virustotal.com/gui/ and you will se that the vast majority of antivirus approve it.

You can build it by yourself too if you are unsure.

**Comment by McGiverGim** [comment]
Here you have the list of 60 antivirus that have analyzed the executable: https://www.virustotal.com/gui/url/eb04e73e0dbb3441755f8df6e13a2f65bbaa297e8da4f3110de280acfc8c828a/detection

**Comment by mikeller** [comment]
Big part of this is that a lot of virus scanners (including Microsoft's) require an ~extortion fee~ registration of applications with them in order to not be tagged with all kinds of problems...

**Comment by skywinder** [comment]
I think you can  close it as invalid, since there even no any valid references in the description.

@ylectron please specify the source where did you download  executable file

**Comment by ylectron** [comment]
Definitely not closing it. Please download it by yourself from where you consider original source on github and make a test with the metascanonline engines ( https://metadefender.opswat.com/?lang=en). The previous version doesn't have any ADWARE, just the latest build for windows does.

**Comment by McGiverGim** [comment]
I did, and only 1/37 detected "something" that I'm sure is a false positive:
![image](https://user-images.githubusercontent.com/2673520/99233821-0a1b5900-27f4-11eb-9126-20b4a93fa758.png)

You can believe 1 or 36 engines, as you want. As I say, you can build it yourself from the source code if are unsure.

**Comment by mikeller** [comment]
False positive.

**Comment by mikeller** [comment]
@ylectron: Writing in ALL CAPS is considered rude and bad style, please refrain from it in the future.
