### ISSUE TITLE
SRLX2 drop down

### ISSUE THREAD

**Issue by Larryvoll** [betaflight/betaflight-configurator#2293]
I'm running BF 10.7.0, and I'm trying to set up a new receiver in config. There is supposed to be a drop down selection for SRLX2 receiver type, but it's not showing up? Any help would be great.

**Comment by mikeller** [comment]
Please provide the information you were asked to provide when opening this issue, like hardware used, firmware version,...

**Comment by Larryvoll** [comment]
Configuration Issue

**Comment by Larryvoll** [comment]
why did you close this
