### ISSUE TITLE
THREE.Loader.createMaterial: colorAmbient is no longer supported.

### ISSUE THREAD

**Issue by haslinghuis** [betaflight/betaflight-configurator#2294]
Just a reminder. Already removed deprecated `FaceMaterials` from WebGL but did not find a solution for this one. It's causing lag in loading on tabs where this message occurs:

`THREE.Loader.createMaterial: colorAmbient is no longer supported.`

**Comment by McGiverGim** [comment]
The only solution for this is to edit the directly the 3D file and update the definition there. I think I tried it some time ago but I left I don't remember why.
