### ISSUE TITLE
Rearrange configuration, motor and servo tab

### ISSUE THREAD

**Issue by haslinghuis** [betaflight/betaflight-configurator#2304]
`Feature Request:` as suggested by `@McGiverGim`:

- [x] Move `Mixer`, `ESC/Motor` and `3D`features to Motors TAB.
- [x] Move `Servo test bars` to Servos TAB.

`Follow-up reminder:`
- [ ] Fix #81 (already done, only need cleanup after this PR is done)
- [ ] Validate outputs with motor data after reboot and give a notice when there are to many outputs configured.
- [ ] Dynamic display of motor test bars depending on available resources.
- [ ] Redesign slider as suggested in this issue
- [ ] Design a Parameter Group based loading/saving/polling mechanism for MSP.

**Comment by haslinghuis** [comment]
- [x] Move ESC/Motor features from Configuration TAB to motors TAB. Configuration TAB is ready.
- [ ] MOTOR_STOP not showing
- [ ] ESC_SENSOR not showing
- [ ] 3D ESC/Motor Features not showing
- [ ] Remove mixer from Graph
- [ ] Move servo test to servos.js
- [ ] Maybe even move Dshot Beacon Configuration

Additional thoughts on Configuration TAB:
- [ ] Move System Configuration to sensor TAB
- [ ] Move board and sensor alignment / Accelerometer Trim to sensor TAB
- [ ] Move RSSI / Receiver / Arming to receiver TAB
- [ ] Move Receiver to receiver TAB
- [ ] Move Personalization / Camera to osd TAB
- [ ] Convert GPS to a feature and move GPS config to GPS TAB
- [ ] Move remaining Features into their respective TABs.

![Screenshot from 2020-12-23 08-26-31](https://user-images.githubusercontent.com/8344830/102971001-d7523800-44f8-11eb-9119-764177ee0d0e.png)

![Screenshot from 2020-12-23 08-35-21](https://user-images.githubusercontent.com/8344830/102971546-e1c10180-44f9-11eb-9c3c-be9f3988eced.png)


![Screenshot from 2020-12-23 08-29-11](https://user-images.githubusercontent.com/8344830/102971106-04064f80-44f9-11eb-8f3a-849313bd4afa.png)

![Screenshot from 2020-12-23 08-48-53](https://user-images.githubusercontent.com/8344830/102972684-bd662480-44fb-11eb-89bb-a5ddb199eaaf.png)

**Comment by haslinghuis** [comment]
Is this an old setting setting, because when using arming on an aux channel this should be automatic.

![Screenshot from 2020-12-25 04-22-25](https://user-images.githubusercontent.com/8344830/103117015-e22bda80-4668-11eb-8c5a-b4da74de17fe.png)

**Comment by haslinghuis** [comment]
Would be nice to have a grid layout where the user can swap panes

**Comment by haslinghuis** [comment]
There seems to be a bug I didn't notice before:

![Screenshot from 2020-12-26 16-07-07](https://user-images.githubusercontent.com/8344830/103153926-9c6c3080-4794-11eb-829c-7e6fd93d8b71.png)

**Comment by limonspb** [comment]
What's wrong here?

**Comment by haslinghuis** [comment]
![Screenshot from 2021-01-02 12-11-55](https://user-images.githubusercontent.com/8344830/103456174-fcfaf080-4cf3-11eb-863a-33bcbbdf92a8.png)

**Comment by haslinghuis** [comment]
![Screenshot from 2020-12-23 23-56-47](https://user-images.githubusercontent.com/8344830/104027450-b3187b80-51c7-11eb-9580-014147786820.png)

**Comment by haslinghuis** [comment]
![Screenshot from 2021-01-08 20-58-29](https://user-images.githubusercontent.com/8344830/104058664-672ffb80-51f4-11eb-9b02-78b2f079e63e.png)

**Comment by haslinghuis** [comment]
![Screenshot from 2021-01-09 16-40-59](https://user-images.githubusercontent.com/8344830/104095880-89c82000-5299-11eb-97dd-63f1ef073712.png)

**Comment by McGiverGim** [comment]
Great work here! Is taking some time but the result is very good!

**Comment by haslinghuis** [comment]
![Screenshot from 2021-01-09 17-53-54](https://user-images.githubusercontent.com/8344830/104103696-e03a5c00-52a3-11eb-80ca-baa396918e65.png)

**Comment by haslinghuis** [comment]
Last thing before done is to remove fc,js - it's part of another PR I will make ready asap - because this PR depends on it

**Comment by mikeller** [comment]
I am still not convinced that the square 'bars' and the tiny sliders are good UX.
I think if we arranged them side by side we'd actually make the slicers usable instead of 'pro forma' only.
Alternatively, if we don't think that users will want to use the sliders, we should remove them and replace them with numerical input fields, and use the space we gain to change the 'bars' to actually be bars and not squares.

**Comment by haslinghuis** [comment]
@mikeller: The minimum size would only take about 30% width at full HD. So we could save a lot of space.

If we also move the notice below the test we now have a column on the right for the configuration section.

![Screenshot from 2021-01-10 00-30-25](https://user-images.githubusercontent.com/8344830/104110832-d5032280-52db-11eb-9c73-7d205bad0161.png)

**Comment by mikeller** [comment]
I prefer something along the lines of this - having both the sliders and the bars side-by-side seems to be much more conducive to represent them in the optimal form of being tall and narrow:

![image (29)](https://user-images.githubusercontent.com/4742747/104111164-dff19d80-5343-11eb-9938-f1d08657b1d0.png)

**Comment by haslinghuis** [comment]
Wow @Asizon , this idea came from @limonspb any ideas?

**Comment by haslinghuis** [comment]
Besides webkit there also :smirk: many Vue sliders like https://github.com/xwpongithub/vue-range-slider

**Comment by haslinghuis** [comment]
![Screenshot from 2021-01-13 02-21-18](https://user-images.githubusercontent.com/8344830/104394061-231b5e80-5546-11eb-9e48-b242186353c6.png)
