### ISSUE TITLE
Show unstable release

### ISSUE THREAD

**Issue by TheAngularity** [betaflight/betaflight-configurator#234]
... is set as default ... would that be so?

**Comment by KiteAnton** [comment]
Latest configurator should keep in memory what you had selected previously. Default should be off.

**Comment by mikeller** [comment]
Yes, latest (unreleased) configurator 'remembers' the user's selection. 'Unstable releases' is off on initial startup.

**Comment by TheAngularity** [comment]
I'm switch it of ... loaded firmware and flashed ... then finish the configurator ... but next start it still appears switched on
