### ISSUE TITLE
Resource command is not working

### ISSUE THREAD

**Issue by limonspb** [betaflight/betaflight-configurator#2358]
![image](https://user-images.githubusercontent.com/2925027/103199512-9f5c4380-48b0-11eb-86f3-ff2bac9508ae.png)

CLI `resource......`  command not working on the current master branch.

Steps to reproduce:
1. Connect with FC, open CLI (4.2 or 4.3)
2. Type resource
3. Press Enter
4. Copy-paste any resource command from the output, press enter.

Desired behavior:
Resource command being sent, the resource being reassigned.

Actual behavior:
```
# null
###ERROR IN input: UNKNOWN COMMAND, TRY 'HELP'###
```
Looks like the issue appeared after this pull request is merged:
https://github.com/betaflight/betaflight-configurator/pull/2231
in particular file `CliAutoComplete.js`

**Comment by McGiverGim** [comment]
Thanks for reporting! I will look into it tomorrow.

**Comment by McGiverGim** [comment]
@limonspb I can't reproduce the problem. If I copy&paste the output of `resource` command in my case I don't have any error. It applies the resources without problem.

Maybe related to something more? Someone else can confirm the issue to see if we can find more common info?

**Comment by limonspb** [comment]
@McGiverGim after a little bit more testing:
The bug happens only when this little hint is visible and I push enter
If I hide this little hint first, then the command goes throug.

![image](https://user-images.githubusercontent.com/2925027/103326237-fd09a080-4a14-11eb-9e43-ca371592bdbe.png)
