### ISSUE TITLE
1.7.3 sets airmode_activate_throttle to 70 on any changes in PID Tuning tab

### ISSUE THREAD

**Issue by etracer65** [betaflight/betaflight-configurator#237]
Causes air mode to be active immediately on arming and leads to I-term windup and the quad wanting to take off on its own.

**Comment by borisbstyle** [comment]
Are you using RC8?

**Comment by etracer65** [comment]
No, RC7

**Comment by etracer65** [comment]
Just tested with RC8 and the same behavior.  Any changes on the PID Tuning tab cause airmode_activate_throttle to be set to 70.

**Comment by borisbstyle** [comment]
Try 1.7.4
https://chrome.google.com/webstore/detail/kdaghagfopacdngbohiknlhcocjccjao/publish-delayed?hl=nl

**Comment by etracer65** [comment]
Waiting for the new version to be active - still shows 1.7.3 in the chrome store.  The link you posted gives an error.

Er is een fout opgetreden:

Item niet gevonden. Dit item is mogelijk door de auteur verwijderd.

**Comment by etracer65** [comment]
I see the commit though and that looks like it will fix it.

**Comment by etracer65** [comment]
1.7.4 just showed up and it fixes the problem.
