### ISSUE TITLE
Sliders / Multipliers beyond 2.0x

### ISSUE THREAD

**Issue by harry1453** [betaflight/betaflight-configurator#2370]
I'm currently tuning my quad and I really like using the sliders, they really make it easier to tune.

However, my quad seems to want slightly lower than default I gain and much higher than default P/D gain. So my master multiplier is at 0.8x and my PD gain multiplier is at 2.0x. I would like to add more P and D gain, and I can't, as I have hit the limit. Obviously I could continue modifying individual values but sliders are much easier.

Please could you allow the user to (in expert mode only) manually input a multiplier (eg. type in 2.1x, 3x, etc to the left of each slider) to go beyond the limits of the slider?

**Comment by harry1453** [comment]
@mikeller I came up with a basic design:

![image](https://user-images.githubusercontent.com/37041552/106595942-3c636980-654c-11eb-9c10-a1c01a6a3ab8.png)

Would this be an acceptable contribution if I were to fully implement it?

**Comment by haslinghuis** [comment]
Sliders are undergoing change towards implementation using firmware sliders for upcoming release. The legacy sliders will be frozen. Now there are 7 sliders.

**Comment by harry1453** [comment]
@haslinghuis OK, so I presume that makes this issue irrelevant then? Or at least no longer relevant to this repo.

When you say sliders will be frozen, you mean code-frozen? or not movable? will we be able to move them if we continue to run BF4.2 and don't upgrade firmware?

**Comment by haslinghuis** [comment]
Legacy sliders would be frozen. Maybe your proposal could be beneficial for the firmware sliders too.

**Comment by harry1453** [comment]
Okay, thanks. Possibly but assuming that it is controllable via CLI a numeric value could be input that way. Min/max values will still be annoying though.

**Comment by haslinghuis** [comment]
Look at PR 8118 in firmware for details

**Comment by haslinghuis** [comment]
Start at PR 9119 in firmware for details

**Comment by spatzengr** [comment]
I think this is a good add, but I also wanted to ask:
If you had an i-Term slider, would you be moving the Master down to 0.8 (which is what is limiting your range).
![image](https://user-images.githubusercontent.com/25570978/106677703-3b036280-6587-11eb-871e-315b9e0b54ea.png)

Note this many sliders would ONLY be visible when you toggle to "Adv." in the header.  When set to Basic (the default), you would ONLY see:
![image](https://user-images.githubusercontent.com/25570978/106677841-7d2ca400-6587-11eb-9d4e-faa146ea6b64.png)
