### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by SPCORRIV** [betaflight/betaflight-configurator#2372]
VTX Power Mode

<img width="533" alt="Screen Shot 2021-01-02 at 5 48 10 PM" src="https://user-images.githubusercontent.com/73504378/103469874-a49a1200-4d38-11eb-956e-a4ee06f201c1.png">

Would like to be able change VTX power from transmitter. This could be done via an Aux switch. I set it up in CLI but it does not seem to work, Could this be added in Modes panel, or add this feature in adjustments drop down. Either one would work, I guess whichever would be easier.

Thank You

Scott

**Comment by mikeller** [comment]
This will need work in the firmware as well, since `vtxChannelActivationConditions` aren't currently available in MSP. In general, this is badly integrated into the rest of the firmware, and could probably do with some rework.

**Comment by SPCORRIV** [comment]
I was able to get it to work, just a round about way, hoping this can be added in the future.

**Comment by haslinghuis** [comment]
This is already implemented
