### ISSUE TITLE
OSD 16.9 Support

### ISSUE THREAD

**Issue by SPCORRIV** [betaflight/betaflight-configurator#2373]
The OSD panel only supports 4.3 as of now can 16.9 be added to help when laying out osd screens.

Thank You

**Comment by etracer65** [comment]
The preview panel in the OSD tab doesn't have an "aspect ratio". It's simply an arbitrary size to display the OSD fonts in 30 characters by 16 rows in PAL, and 13 rows in NTSC. The Configurator has no idea what "16:9" is in regards to your goggle display. Likewise it has no idea what your goggles might be cutting off on the top/bottom to poorly format the video to the display panel.
