### ISSUE TITLE
Move the RX configuration to the receiver tab

### ISSUE THREAD

**Issue by McGiverGim** [betaflight/betaflight-configurator#2379]
Only to let it here as feature request. 

Now that the motor configuration is being moved to the motor tab, I think it will be good and more intuitive to move the RX configuration to the receiver tab too.

**Comment by haslinghuis** [comment]
I guess this overrides https://github.com/betaflight/betaflight-configurator/issues/81
How can I assign to this task 😛

**Comment by mikeller** [comment]
Yeah, kind of duplicates it. :smile:

**Comment by McGiverGim** [comment]
Yes, you were right, closing this!
