### ISSUE TITLE
Google Chrome apps are no longer being supported

### ISSUE THREAD

**Issue by Austinthemighty** [betaflight/betaflight-configurator#238]
here is a link to the article that state that google is dropping support for google chrome apps: http://wccftech.com/google-planned-support-chrome-apps-mac-windows-linux/ 

In summary;
Google to phase out Chrome apps on desktops means that users will no longer be able to run Chrome apps on any platform except for Chrome OS. Google’s plans start later this year as Chrome apps will only be available to Chrome OS users. Current installed apps will not be affected by this and can still be updated. Moving forward at sometime in the year 2017, the Chrome Web Store will no longer display Chrome apps at any of the above mentioned operating systems. Finally, in 2018, you will not be able to load any of them on Macs, Windows and Linux.

one thing for sure is we need to start to move away from the google chrome app store, also maybe a dedicated app that you download, it may take some time to do this, that is why i was putting this here.

**Comment by mikeller** [comment]
Thanks for letting us know. There are already plans under way to do a reimplementation of the configurator based on a more modern framework. The sunsetting of Chrome apps, and the timeline that is planned for this, fit in nicely with those plans.

**Comment by Austinthemighty** [comment]
ok that is good the hear, also can we create an app that works on android and ipad that works via bluetooth

**Comment by gaelj** [comment]
GPL is not accepted on the Apple Store.

**Comment by Austinthemighty** [comment]
@gaelj you can still do it @borisbstyle just has to claim copyright to it

**Comment by Austinthemighty** [comment]
hey can @borisbstyle create a new repository for the code, i was looking into http://nwjs.io/ for clean flight and a lot of things have to change inorder for it to work
