### ISSUE TITLE
Betaflight-configurator app doesn't launch on Ubuntu 20.10

### ISSUE THREAD

**Issue by Emeric-dufour** [betaflight/betaflight-configurator#2381]
Hello,

I downloaded betaflight configurator release 10.7.0 on my ubuntu 20.10 OS but nothing happens when I launch the app after installation.
I used the file "betaflight-configurator_10.7.0_amd64.deb" for installation and there is no problem with installation.
Tried to change exec command to "sudo /opt..." in the betaflight-configurator.desktop file but still nothing happens after launch and sudo identification...

Is there a fix ?

**Comment by mikeller** [comment]
@Emeric-dufour:

Delete the `/opt/betaflight/betaflight-configurator/`, `~/.config/betaflight-configurator`, and `~/.cache/betaflight-configurator/` directories and try again.

**Comment by ClementYap** [comment]
I am also facing the same issue. How to resolve it?
