### ISSUE TITLE
Can´t install 10.8.0 configurator on Windows 7 64bits machine.

### ISSUE THREAD

**Issue by nangel0** [betaflight/betaflight-configurator#2384]
Had to re-install Windows. Also needed to update the configurator so went straight to 10.8.0 and I can't install the last version, nor the nightly.

If I try to install the previous version 10.7.0 it works ok like before, nothing changed on hardware.

![10 8 0](https://user-images.githubusercontent.com/46812102/104313683-49061c00-54d0-11eb-9561-9d7178544c90.png)
![10 7 0](https://user-images.githubusercontent.com/46812102/104313685-4a374900-54d0-11eb-93f9-b30addc0c9ce.png)
![vers](https://user-images.githubusercontent.com/46812102/104313687-4b687600-54d0-11eb-9e68-1774338a82ae.png)

Changing permits, install as admin, compatibility mode, etc, nothing changes the error.

**Comment by Asizon** [comment]
Hello! Windows 7 is no longer supported by Google and also by Betaflight Configurator.

**Comment by nangel0** [comment]
Face-palm... Not aware off that... Time to upgrade OS...

**Comment by Droneman72** [comment]
Nothing wrong with BF 10.7.2 anyway, and I am not about to replace my Win7 Ultimate in my main PC because Google and BF do not support it.  I just loaded it in a cheap Win10 notebook, which is also light and portable if needed at a flying site. Where there is a will there is a way!
