### ISSUE TITLE
last master overwrites wrong config data

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/betaflight-configurator#2393]
since #1821 a wrong config value is overwritten after setting the sliders. on fc run's latest bf 4.3 master.

@IvoFPV pls can you check this.

```
# get curve
dyn_lpf_gyro_curve_expo = 256
###ERROR IN get: CORRUPTED CONFIG: dyn_lpf_gyro_curve_expo = 256###
Allowed range: 0 - 10
Default value: 0
```

diff output:
```
...
# master
set dyn_notch_width_percent = 0
set dyn_notch_q = 250
set dyn_lpf_gyro_curve_expo = 256
###ERROR IN diff: CORRUPTED CONFIG: dyn_lpf_gyro_curve_expo = 256###
set acc_hardware = NONE
set mag_hardware = NONE
set baro_hardware = NONE
set rc_smoothing_auto_smoothness = 7
set serialrx_provider = FPORT
...
```

EDIT: In addition, the button `Enable Sliders` is displayed in the filter settings tab although all values are set to default.
Pressing on the button does nothing.

EDIT2:
- to reproduce using fc with default settings (i'm using Matek F722-Mini)
```
# diff

# version
# Betaflight / STM32F7X2 (S7X2) 4.3.0 Jan 17 2021 / 03:12:57 (34614231d) MSP API: 1.44
# config: manufacturer_id: MTKS, board_name: MATEKF722MINI, version: f173f9bc, date: 2019-10-02T14:43:13Z

# start the command batch
batch start

board_name MATEKF722MINI
manufacturer_id MTKS

profile 0

rateprofile 0

# end the command batch
batch end

# 
```
- go to PID Tuning Tab -> use simplified PID Mode RP or RPY -> Save -> go to CLI Tab -> show diff
```
# diff

# version
# Betaflight / STM32F7X2 (S7X2) 4.3.0 Jan 17 2021 / 03:12:57 (34614231d) MSP API: 1.44
# config: manufacturer_id: MTKS, board_name: MATEKF722MINI, version: f173f9bc, date: 2019-10-02T14:43:13Z

# start the command batch
batch start

board_name MATEKF722MINI
manufacturer_id MTKS

# master
set dyn_lpf_gyro_curve_expo = 256
###ERROR IN diff: CORRUPTED CONFIG: dyn_lpf_gyro_curve_expo = 256###
set simplified_gyro_filter = ON

profile 0

# profile 0
set p_pitch = 42
set i_pitch = 85
set d_pitch = 35
set f_pitch = 90
set d_min_roll = 26
set d_min_pitch = 26
set simplified_pids_mode = RP

rateprofile 0

# end the command batch
batch end

# 
```

**Comment by haslinghuis** [comment]
`dyn_lpf_curve_expo` and `dyn_lpf_gyro_expo`. Tried to exchange, setting defaults, but not enough to restore sliders. :confused:

**Comment by mikeller** [comment]
@TheIsotopes: Can you please add steps for how this can be reproduced?

**Comment by TheIsotopes** [comment]
@mikeller done ... see EDIT2 above

**Comment by Asizon** [comment]
Ok, so the problem seems that dyn_lpf_gyro_curve is part of simplified gyro filter but this feature is not yet added to MSP and Configurator so its breaking the value.

**Comment by IllusionFpv** [comment]
Maybe this can be reopened https://github.com/betaflight/betaflight/pull/10240

**Comment by TheIsotopes** [comment]
@IllusionFpv ok, tested now and the first bug is fixed. 👍 

@all now the problem is still missing that the slider does not appear in the filter settings.

**Comment by haslinghuis** [comment]
@TheIsotopes - found the problem. Please try again.

**Comment by haslinghuis** [comment]
Found another problem, We need to fix the tuning sliders for firmware below API 1.44. Now they are disabled by default but can be enabled but don't load after save - re-enter tab.

Didn't publish a fix yet but can load and save now with sliders enabled in legacy mode, but using the sliders is not working yet. Since sliders have many changes it's hard back-tracking. Running in circles at the moment.
