### ISSUE TITLE
Ghost OSD Link Quality

### ISSUE THREAD

**Issue by SPCORRIV** [betaflight/betaflight-configurator#2394]
Hey Guys

Opentx 2.3.10 IMRC 
Betaflight 4.2.6
Ghost Atto receiver
IFLIGHT_SUCCEX_E_F7 4.2.6

Ghost set for SRLX2 everything works but I get LQ 100 on radio but OSD LQ shows 9. Don't know if it's a bug or something I did wrong.

Scott

**Comment by mikeller** [comment]
@SPCORRIV: Betaflight 4.2.6 does not yet support the GHST protocol - you will have to wait for 4.3 to get full support for the Ghost hardware with the native protocol.

**Comment by SPCORRIV** [comment]
Hey Michael

   That you for the response.

Scott
