### ISSUE TITLE
[Feature] is it possible to add the blheli suit to the betaflight configurator

### ISSUE THREAD

**Issue by Austinthemighty** [betaflight/betaflight-configurator#240]
Is it possible to add the blheli suit to the betaflight configurator.

**Comment by mikeller** [comment]
There is an effort under way to implement a blheli configuration utility in JavaScript. It will not be implemented as part of the Betaflight configurator, as it is intended for users that run any of cleanflight / iNav / Betaflight, which all support the ESC passthrough protocol.
