### ISSUE TITLE
So I've been using Betaflight 10.7.0 for a few months now and has worked great. however this weekend I went open it and Betaflight was in a different language!?! like Russian or something. anyone know how to get it back to English? plz.

### ISSUE THREAD

**Issue by 2stixs** [betaflight/betaflight-configurator#2405]
# If your issue looks like a hardware fault or a configuration problem please don't raise an issue here.

## If you believe there is an issue with the firmware itself please follow these steps:
1. Describe your problem;
2. Include ways to reproduce the problem;
3. Provide as much information as possible about your hardware and software, including:
- what hardware / software you are using;
- the version of all the software used;
- how things are connected / wired up.
4. Remove this Text :).

**Comment by haslinghuis** [comment]
Open configurator and look ate the bottom of the screen where you can click your language.

![image](https://user-images.githubusercontent.com/8344830/107156860-0aee0200-6981-11eb-8743-3a6d0d8e73f7.png)

**Comment by kolyfan** [comment]
Spend some time to find this place from screenshot. Just small notice - this options for change language available only on Welcome screen, before you connect to flight controller.
