### ISSUE TITLE
Configurator does not load hex files

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/betaflight-configurator#2406]
since latest build the configurator does not load any hex files.

![Screenshot_console](https://user-images.githubusercontent.com/29702171/107195043-20027980-69f1-11eb-92ea-179b974c825c.png)

imo it comes from #2368 ... @chmelevskij pls can you fix this

**Comment by mikeller** [comment]
@TheIsotopes: Thanks for reporting.

@chmelevskij: Uh oh, I saw that one, checked it, and thought it must be unused as well. :-(

**Comment by chmelevskij** [comment]
Hmm, yeah, so workers use different execution context, hence the missing thing which was attached to global. I'm surprised it worked before though 🤔

**Comment by mikeller** [comment]
You removed one that was defined inside the worker. ;-)

**Comment by chmelevskij** [comment]
Ah, ok, my bad 😆  makes sense now.

**Comment by McGiverGim** [comment]
Maybe for this cases that we only want to log some elapsed time is better to use `console.log()` or `console.timeLog()`. They are just there for that.
