### ISSUE TITLE
Firmware sliders doesnt work

### ISSUE THREAD

**Issue by Asizon** [betaflight/betaflight-configurator#2412]
After https://github.com/betaflight/betaflight-configurator/pull/2409 firmware sliders doesnt work for 4.3.
To reproduce, go to pidtuning tab, check RPY and move sliders.
Using latest 4.3 and latest Configurator master build.
![image](https://user-images.githubusercontent.com/43983086/107871671-099e6700-6ea4-11eb-872e-e8dd15d7474d.png)

**Comment by klutvott123** [comment]
Can confirm. And if I move a slider and click "refresh" I get this:
![Skjermbilde](https://user-images.githubusercontent.com/41271048/107876944-7710be80-6ec9-11eb-9d1d-e9d002e9317c.PNG)

**Comment by haslinghuis** [comment]
Changes made only relate to API 1.43 or below, so not sure how this is able to affect 1.44 behavior at all. :confused:
