### ISSUE TITLE
Google Chrome apps are no longer being supported

### ISSUE THREAD

**Issue by bripkens** [betaflight/betaflight-configurator#242]
Copy from: https://github.com/cleanflight/cleanflight-configurator/issues/420

> here is a link to the article that state that google is dropping support for google chrome apps: http://wccftech.com/google-planned-support-chrome-apps-mac-windows-linux/

> In summary;
> Google to phase out Chrome apps on desktops means that users will no longer be able to run Chrome apps on any platform except for Chrome OS. Google’s plans start later this year as Chrome apps will only be available to Chrome OS users. Current installed apps will not be affected by this and can still be updated. Moving forward at sometime in the year 2017, the Chrome Web Store will no longer display Chrome apps at any of the above mentioned operating systems. Finally, in 2018, you will not be able to load any of them on Macs, Windows and Linux.

> one thing for sure is we need to start to move away from the google chrome app store, also maybe a dedicated app that you download, it may take some time to do this, that is why i was putting this here.

**Comment by KiteAnton** [comment]
Yes, thanks for information. It is already known for the dev team. Also just mentioned in #238
