### ISSUE TITLE
MacOs: dark mode has dark descriptions too

### ISSUE THREAD

**Issue by AndreaCCIE** [betaflight/betaflight-configurator#2420]
the latest Nightly builds (v20210217.1990, v20210216.1974 and v20210216.1971) have a dark colour description when in dark mode:

<img width="1410" alt="Screenshot 2021-02-17 at 16 28 57" src="https://user-images.githubusercontent.com/48698293/108235197-8304b680-713d-11eb-8d17-84d5ce30eeca.png">

**Comment by haslinghuis** [comment]
Thanks. @Asizon can you please take a look at how to solve the font color for the descriptions in dark mode?

**Comment by haslinghuis** [comment]
Fix is ready, also for servo tab:

![Screenshot from 2021-02-17 22-43-39](https://user-images.githubusercontent.com/8344830/108271785-a34e6880-7171-11eb-9c0b-a1d3306b70a5.png)

**Comment by haslinghuis** [comment]
@Asizon can't find why the line is broken in:

![Screenshot from 2021-02-17 23-00-16](https://user-images.githubusercontent.com/8344830/108273581-0214e180-7174-11eb-8404-9e8ec8a577c3.png)

**Comment by Asizon** [comment]
@haslinghuis for the broken line, maybe "border-colapse" can help.

**Comment by haslinghuis** [comment]
Thanks @Asizon - that solved it!
