### ISSUE TITLE
Motor Direction Dialogue: Warning Messages are Outdated

### ISSUE THREAD

**Issue by mikeller** [betaflight/betaflight-configurator#2422]
The messages refer to changing the settings in the Configuration tab, whereas the relevant settings have been moved into the same tab as the Motor direction dialogue:

![image](https://user-images.githubusercontent.com/4742747/108353826-753e5680-724d-11eb-8e3f-720c6098b661.png)

**Comment by haslinghuis** [comment]
I'm adding this LMM to #2421
