### ISSUE TITLE
BF Configurator wont launch?

### ISSUE THREAD

**Issue by huge-11** [betaflight/betaflight-configurator#2426]
Hello,
i installed version 10.7.0  but somehow i cant launch the configurator. When i do so just nothing happens ? 
I am on win 10 home
version 1909
build 18363.1379

tried to uninstall and reinstall but still same. 
i have no folder in ...AppData/Local/ called betaflight so i cant delete it like in #2410

any help would be apreciated

**Comment by haslinghuis** [comment]
Could you run compatibility troubleshooter?

![image](https://user-images.githubusercontent.com/8344830/108646499-61e1f400-74b6-11eb-8dcf-3d2bdb276795.png)

Also see https://github.com/betaflight/betaflight-configurator#graphics-issues

**Comment by huge-11** [comment]
So i uninstalled bf config with revo uninstaller, removed all the registrys and everything related to br config. Did some gpu config and updated my drivers. Now it's working thanks
