### ISSUE TITLE
BetaFlight Configurator 10.8.0 beta

### ISSUE THREAD

**Issue by sasplayers** [betaflight/betaflight-configurator#2458]
### Is your feature request related to a problem? Please describe.

Firstly The new look and configuration in the configurator is excellent, the issue I had was in the CLI. I had to change 
resource motor 6 none
resource led_strip 1 A08
---ERROR---Parse error
on my "matek F405 mini" flight controller

### Describe the solution you'd like

Other than the Parce error to be fixed I think its perfect

### Describe alternatives you've considered

I did fix it via the betaflight 10.7.0 version

![betaflight10-8-0](https://user-images.githubusercontent.com/22359070/113000482-c81dfe80-9167-11eb-9840-9557d6ac035f.png)

**Comment by haslinghuis** [comment]
@Asizon   @McGiverGim any idea?

**Comment by McGiverGim** [comment]
No, I can try Monday to see if I can find the bug.
