### ISSUE TITLE
dyn_notch_q in Betaflight 4.3/Betaflight Configurator 10.8.0

### ISSUE THREAD

**Issue by Autocrit** [betaflight/betaflight-configurator#2461]
Flight controller: iFlight Beast F7 IFLIGHT_F745_AIO (STM32F745)

Versions: 4.3.0 #2430 (29-03-2021 11:43) and 10.8.0 v20210331.2359

set dyn_notch_q = 250 gives an "INVALID NAME" error in the CLI or reverts to 0 on save in the GUI. I can get/set this value with 4.2.8

**Comment by McGiverGim** [comment]
If you are using latest master, this parameter does not exist anymore. More info here: https://github.com/betaflight/betaflight/pull/10554

**Comment by Autocrit** [comment]
Thank you for that... I need to do some reading.
