### ISSUE TITLE
Cannot remap motors in 10.8.0

### ISSUE THREAD

**Issue by SebastianKumor** [betaflight/betaflight-configurator#2467]
I am trying to remap motors in the configurator i built from latest master and get this error with this command `resource motor 1 a09`

<img width="385" alt="image" src="https://user-images.githubusercontent.com/8973431/113622636-90c6ba80-965d-11eb-9959-1a85912aba85.png">

I tried latest official release 10.7.0 and it works

In the console output the pin number is omitted once your write the command and press enter.

I am running  betaflight 4.2.8

**Comment by haslinghuis** [comment]
Duplicate of #2458 

Thanks for reporting, fix is ready and tested and implemented soon.

**Comment by SebastianKumor** [comment]
@haslinghuis cool, I will close it then. Thanks for quick reply
