### ISSUE TITLE
"Failed to load extension" Error message when running from yarn.

### ISSUE THREAD

**Issue by hydra** [betaflight/betaflight-configurator#2484]
Fresh checkout of master and launch results in error message:

"Failed to load extension from: . Manifest file is missing or unreadable"

Steps to reproduce: `yarn start`

OS: OSX BigSur fresh install.  Also happens on my OSX Catalina laptop.

See attached screenshot of fresh install and launch.

![Screenshot 2021-05-02 at 22 12 59](https://user-images.githubusercontent.com/57075/116826419-26d5fe00-ab94-11eb-8b8a-3485d805a43e.png)

The actual configurator binary does work, just the launch via yarn fails.

i.e. `open ./debug/betaflight-configurator/osx64/betaflight-configurator.app` works.

**Comment by haslinghuis** [comment]
https://betaflightgroup.slack.com/archives/CKTRF0342/p1616191182032800

**Comment by haslinghuis** [comment]
@chmelevskij have no clue about this. But if it's only on development and not on release it's not a big issue.

**Comment by hydra** [comment]
@haslinghuis it's a big issue if you're trying to develop on the configurator and it won't start!

**Comment by haslinghuis** [comment]
Yes I agree. But afaik after pressing OK configurator is loading. But we need to know the root cause of this message as I couldn't find one yet, but like to resolve this. We don't have a manifest file currently and this seems to be OSX specific. Just like Node 14 is working fine on Fedora 34 but not on other platforms.

**Comment by hydra** [comment]
After pressing OK it does not load up.  Yes, OSX specific.

**Comment by mikeller** [comment]
@hydra: Have you checked the launcher? For me it does load in OSX, but it loads minimised, so you have to click the launcher icon to get the main window to open after clicking away the error: 
![image](https://user-images.githubusercontent.com/4742747/125392838-fb288d00-e3fa-11eb-99fa-92e56a8a5978.png)

**Comment by chmelevskij** [comment]
Issue seems to be with [vue devtools](https://github.com/betaflight/betaflight-configurator/blob/5ed5d048317e8cfc322458b32dbe125872345425/package.json#L10)

Error message is pretty much chrome error. Tried removing it and it doesn't throw error anymore, but it doesn't open up the app as well 🤷‍♂️

**Comment by chmelevskij** [comment]
App not opening up seems to be some `Big Sur` issue.

```
{ Error: Command failed: open debug/betaflight-configurator/osx64/betaflight-configurator.app
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10827 "kLSNoExecutableErr: The executable is missing" UserInfo={_LSLine=3691, _LSFunction=_LSOpenStuffCallLocal}

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:466:23)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:466:23)
    at Pipe._handle.close (net.js:607:12)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'open debug/betaflight-configurator/osx64/betaflight-configurator.app' }
   ```
   
   Also, it seems to work even when doing `open debug/betaflight-configurator/osx64/betaflight-configurator.app` right after failure.

**Comment by haslinghuis** [comment]
Please try: https://disable-gatekeeper.github.io/

**Comment by hydra** [comment]
Just did a fresh install on another OSX machine (Macbook Pro 2015) and ran into the same issue today.

@haslinghuis 

> xattr -dr com.apple.quarantine

doesn't help here.

@chmelevskij I was encountering the problem when I had OSX Catalina installed.  My old laptop died so I no longer have a working Catalina install.

**Comment by haslinghuis** [comment]
Big Sur 11.5 is out now. Maybe try disable Gatekeeper system-wide and reboot to confirm this is not the issue.

**Comment by chmelevskij** [comment]
As I've mentioned, these are 2 separate issues.

`failed to load extension` happens because of vue devtools extension, removing the env variable which loads it gets rid of that error.

Disabling gatekeeper doesn't really make sense. Just using `open` works fine, but for some reason when it is run from gulp task it gets that error.  So it must be some sort of issue with `node` running `open` for us.

**Comment by mikeller** [comment]
@chmelevskij: Thank you for the detailed analysis. I think, all things considered, and seeing that everything effectively works, and all we have is an unwanted error message when running in debug mode, the right way out of this is to document the error message and focus on things that provide more value to the end user.
