### ISSUE TITLE
Erasing flash logs  not working properly while set blackbox_mode = ALWAYS

### ISSUE THREAD

**Issue by hyperion11** [betaflight/betaflight-configurator#2496]
1. set blackbox_mode = ALWAYS
2. Reboot FC
3. Click "Erase Flash"
4. Flash being erasing and recording simultaneously. After reboot log file may be 16Mb (Size of flash)
I think when "set blackbox_mode = ALWAYS" and user click "Erase flash" configurator must send command to stop logging and enable it after erasing flash.

**Comment by McGiverGim** [comment]
The Configurator only sends the information to the FC. I think this is more a bug in the firmware and the firmware needs to control that.
I don't know if the blackbox_mode is accesible in MSP to be used by the Configurator, but I think it will be more reliable if the firmware does the verification.
