### ISSUE TITLE
PID Slider: PD balance changed ?

### ISSUE THREAD

**Issue by muhkuh0815** [betaflight/betaflight-configurator#2499]
Why did the PD Balance Slider changed in the nightlies ?

before with 10.7.0 and some older 10.8 nightlies ('4 slider' version)   P was fixed and the PD balance slider adjusted D, now D stays the same and P changes ...

just got into brian white's 2-step basement tuning from the pidtoolbox youtube channel (https://urp.mak-it.at/basement-tuning/ ), worked pretty great until i changed to the newer nightlies where the pd balance slider is changed :( . 

edit: seems to have beed discussed as it changed with pull request #1821 https://github.com/betaflight/betaflight-configurator/pull/1821#issuecomment-761814673  
maybe there would be place for 2 sliders PD balance & DP balance and the users can choose which they use.

**Comment by haslinghuis** [comment]
We had some discussion already with @spatzengr. @IllusionFpv should know and suggested some changes, but it will take some time to get ready.

**Comment by spatzengr** [comment]
This is by design to get back to the correct behavior of 4.1 before it was messed up in 4.2.  D should be held and want your raise PD Balance slider, it should raise P and old D constant.

**Comment by haslinghuis** [comment]
Also see #2488
