### ISSUE TITLE
OSD SW Mode is mistakenly bound with feature OSD

### ISSUE THREAD

**Issue by skaman82** [betaflight/betaflight-configurator#251]
I can't select the OSD SW mode in the modes tab until I activate the OSD feature in the config tab. This activates also the OSD tab (makes sense for BFOSD targets). 

For users without BFOSD targets this is confusing. If a user uses mwosd the OSD tab makes no sense here. I suggest making the OSD SW mode always applicable like it was before.

**Comment by mikeller** [comment]
I don't think having the OSD SW depend on the feature OSD being enabled is wrong per se, with 'feature OSD' being used as 'all things related to OSD'. What is wrong however, is that the OSD tab is dependent on the OSD feature alone, it should only be shown if the feature is enabled, *and* the FC indicates that BFOSD is supported.

I will change that.
