### ISSUE TITLE
Unable to flash firmware from local file

### ISSUE THREAD

**Issue by MartinWa** [betaflight/betaflight-configurator#2510]
I downloaded Betaflight Configurator 10.5.1 and it worked. (10.6.0 and 10.7.0 did not)

Another person created this Reddit post on what seems to be the same problem:
https://www.reddit.com/r/fpv/comments/mkvzqw/cant_flash_local_firmware_file_in_betaflight/

**Comment by haslinghuis** [comment]
Not able to reproduce with 10.7.0 or 10.8.0 on Windows (needs drivers) or Linux (needs rules and add yourself to dialout and plugdev group and remove modemmanager). Look at our documentation for more information.
Ubuntu example:
```
    $ sudo usermod -a -G dialout $USER
    $ sudo usermod -a -G plugdev $USER
    $ sudo apt-get remove modemmanager
    $ (echo '# DFU (Internal bootloader for STM32 MCUs)'
     echo 'ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="df11", MODE="0664", GROUP="plugdev"') | sudo tee /etc/udev/rules.d/45-stdfu-permissions.rules > /dev/null
```
On Windows you will need other drivers, like Immersion RC driver fix or Zadeg.

**Comment by MartinWa** [comment]
@haslinghuis 
I am sorry but the original post had been chopped off by mistake. Also it did not contain enough information. So:

On Windows 10 using the betaflight-configurator-installer_10.7.0_win32.exe installer I have an issue with flashing firmware from local file. I can flash without problem firmware from the dropdown list (for instance the latest) but for older firmware that is not in the list (in my case Betaflight 3.5.7 that I wanted to test the original settings that came with my drone) there is no dropdown.

The button to flash does not do anything when I load firmware from local file. The problem exists in 10.6.0 but not in 10.5.1.

Perhaps this is intentional (that 10.6.0 no longer supports flashing 3.5.x) but then I was hoping for an alert for this fact instead of no action at all (or logs).

**Comment by haslinghuis** [comment]
Did not find anything which would block flashing an offline hex file.
Maybe you can try the maintenance 3.2 release from the dropboxes.
We stopped supporting releases before 4.0 a year ago, but did not make it impossible to use.

**Comment by McGiverGim** [comment]
Exactly, the flashing must work for all versions. Maybe you can record a video with what you do to see if we can reproduce it?

**Comment by BurnoutAg7** [comment]
I encountered the same issue, but found out that I didn't leave the FC board sector blank.

(Just a small tip for anyone who is kind of dumb one day like me.)
