### ISSUE TITLE
[Feature Request] Rest Voltage Approximator based on Load Voltage and Current

### ISSUE THREAD

**Issue by christopherheiser** [betaflight/betaflight-configurator#2517]
Pilots are looking to extend flight times by ensuring the entire pack capacity is safely consumed.  The two methods at present to optimize this are to track pack capacity consumption or to monitor the pack/cell voltage.

The first method requires careful calibration and the current sensing function can be nonlinear and unreliable.  The second method is more safe, but dynamic throttle application causes voltage to sag, and even at hover packs will read 0.2V to 0.6V below rest voltage.  It is not uncommon to land a drone and find the actual rest voltage well above minimum.

This feature request is to have an interpolated table of current values (rows) and load voltage vs rest voltage (columns).  The rest/load voltage pairs can be determined from simple bench testing, and likely a more generic formula could be created that captures different types of cell chemistries and C ratings.  The advantage is to be able to fly right up to the point where the rest voltage of the battery will be at the target value.

It is possible that this approach could benefit from a third axis (SOC) but since the only SOC range for which this info is relevant is in the last 10-20% of SOC the measurements for the table should be taken in this region only.

**Comment by haslinghuis** [comment]
See also: http://www.battgo.org/
This looks very interesting to me but probably should be presented to the firmware repo first as it would need coordination.
