### ISSUE TITLE
Invalid version warning

### ISSUE THREAD

**Issue by nablabla** [betaflight/betaflight-configurator#2519]
1. Plugin in a FC with ßF 4.3.0 promts the warning that my version is outdated. however i am running 10.7.0.
Am I missing something here?
2&3. board is ELRS board, OS is win10, don't know anything more that could be from importance
- how things are connected / wired up: USB

https://imgur.com/a/hs8Pps1

**Comment by haslinghuis** [comment]
This is to be expected as ßF 4.3.0 is not released yet and needs configurator 10.8.0 as 10.7.0 has no knowledge of changes made in 4.3.0

**Comment by haslinghuis** [comment]
You can test a nightly build on https://github.com/betaflight/betaflight-configurator-nightlies/releases at your own risk.
