### ISSUE TITLE
New firmware detection code doesn't work for new targets.

### ISSUE THREAD

**Issue by hydra** [betaflight/betaflight-configurator#2526]
1. Describe your problem;

Incorrect error message as follows:

![new-target-error](https://user-images.githubusercontent.com/57075/124123249-5f506600-da77-11eb-9520-43f20be4957b.PNG)

2. Include ways to reproduce the problem;

Flash an existing target for which there is a release
Create a new firmware target (no firmware published for it yet)
Observe that the 'Select your board' dropdown is BLANK.
Observe that the 'Firmware version' is NOT BLANK and should be.
Click 'Load firmware local'
Load up the .hex for the new firmware target.
Click Flash Firmware.
Observe error message shown as above

I noticed this when flashing the SPRacingH7RF local firmware image after flashing an SPRacingF7DUAL.

3. Provide as much information as possible about your hardware and software, including:
- what hardware / software you are using;
Windows x64

- the version of all the software used;
configurator built from latest `master`.
- how things are connected / wired up.
n/a

**Comment by hydra** [comment]
@haslinghuis this is related to #2485

**Comment by Asizon** [comment]
@hydra In this case, for development you need to add config file using cli, like before if the target config is not uploaded to github.

**Comment by Asizon** [comment]
Also please test with https://github.com/betaflight/betaflight-configurator/pull/2524

**Comment by hydra** [comment]
> 
> 
> @hydra In this case, for development you need to add config file using cli, like before if the target config is not uploaded to github.

The error message says I've *SELECTED* something that I have not, indicating that the implementation doesn't handle this case.

I don't understand the "like before" part of your reply.  I've never had to make any local changes before for every new target that I've ever made, and I've made A LOT!  I think it's unreasonable to force a target developer to work around errors in the configurator that are incorrect and shouldn't appear anyway.

**Comment by Asizon** [comment]
@hydra i hope https://github.com/betaflight/betaflight-configurator/pull/2524 fix your issue :)
