### ISSUE TITLE
"Verbindungsprobleme"?

### ISSUE THREAD

**Issue by Quattrodani** [betaflight/betaflight-configurator#2527]
habe probleme mit der verbindung, schalte meine drohne ein eachine novice 3 und in der brille (eachine) steht disarmed und die drohne lässt sich nicht steuern und piepst! hilfe :D

**Comment by DusKing1** [comment]
English please

**Comment by Quattrodani** [comment]
have problems with the connection, switch on my drone eachine novice 3 and in the glasses (eachine) it says disarmed and the drone cannot be controlled and beeps! help: D

**Comment by Quattrodani** [comment]
have problems with the connection, switch on my drone eachine novice 3 and in the glasses (eachine) it says disarmed and the drone cannot be controlled and beeps! help: D

**Comment by DusKing1** [comment]
@githug-action lack of infomation

**Comment by Asizon** [comment]
@Quattrodani please use our slack for user configuration problems:
https://slack.betaflight.com/

**Comment by Quattrodani** [comment]
> @github-actions Mangel an Informationen
thanks for nothing
