### ISSUE TITLE
can't connect quad through serial ports

### ISSUE THREAD

**Issue by channing1980** [betaflight/betaflight-configurator#2538]
So I just switched to a new MacBook Pro m1 and having connection problem with my quad. After installing CP210VCP driver, I didnt see a new serial port in the drop down menu of betaflight. Im sure I'm using good data cables. Ive tried unistalling and reinstalling. and restarting the computer. Does anyone have any ideas on how I can get my qaud to connect?

**Comment by haslinghuis** [comment]
Please try:

- power down Mac
- hold Control Option P and R while clicking Power button and hold until you hear the 2nd chime.

**Comment by haslinghuis** [comment]
Closing now as this seems a Mac problem - above steps should solve this.

**Comment by AlfredJKwack** [comment]
A few years later....
The steps to reset NVRAM don't apply to Mac computers with Apple silicon (M1), and aren't needed on those computers.
