### ISSUE TITLE
Columns don't match up (GUI cosmetics)

### ISSUE THREAD

**Issue by RipperDrone** [betaflight/betaflight-configurator#254]
On the BFC PID page, column titles and data fields do not match up at all:
![image](https://cloud.githubusercontent.com/assets/12601105/18035873/a25b7614-6d5e-11e6-9897-06caeec58e0a.png)

Is this difficult to implement?

**Comment by mikeller** [comment]
It needs some tweaking in the .css, which I am not particularly good at. I was hoping @skaman82 would give the PID tuning tab a makeover now that it has the new filter sub tab.

**Comment by RipperDrone** [comment]
Ok, maybe @skaman82 will do the trick sometime. In case: The craft name field could be a little wider to allow for more than 8 characters:

![image](https://cloud.githubusercontent.com/assets/12601105/18036681/1927b790-6d72-11e6-8e40-cbe32841d255.png)

**Comment by skaman82** [comment]
I take a look at this next week if I have time!

Von meinem iPhone gesendet

**Comment by mikeller** [comment]
@RipperDrone: Can you please create a separate issue for the name field size, so we can keep track of things?

**Comment by RipperDrone** [comment]
@mikeller Done.

**Comment by skaman82** [comment]
done

**Comment by RipperDrone** [comment]
Thank you!

**Comment by mikeller** [comment]
Dammit, you're too fast, @skaman82 ;-) There will be more changes to the table coming from #252. Sorry.

**Comment by RipperDrone** [comment]
Feedback: Name field and basic PIDs look wonderful, however STRENGTH & TRANSITION are still a little mis-scaled:
![image](https://cloud.githubusercontent.com/assets/12601105/18168651/0137a856-7057-11e6-94d7-3ea113058b45.png)
