### ISSUE TITLE
Installer doesn't prompt for elevated privileges

### ISSUE THREAD

**Issue by FlynnD273** [betaflight/betaflight-configurator#2546]
I am running Windows 10, just downloaded the 10.7.0 configurator, and it just gives me an error when I run it. No prompt or anything for admin password, just an "Can't open file for writing" error. I'd expect the installer to automatically prompt for the password instead of just throwing an exception. The installer does work if I right-click and run as administrator.

**Comment by haslinghuis** [comment]
With nightly build (using 64bit) we get:

![image](https://user-images.githubusercontent.com/8344830/127576782-7d3f0277-e894-4543-9378-24da8a06efed.png)

And then have to accept the UAC window. With 10.7 release we only get the UAC window. So all looks good here.
Maybe you have to remove previous versions or other settings on your machine have changed.
