### ISSUE TITLE
disable autoscroll in firmware flasher tab

### ISSUE THREAD

**Issue by mituritsyn** [betaflight/betaflight-configurator#2551]
There is annoing autoscroll to the "Release info" on this tab. On first entering this tab it will autoscroll, then one need to scroll up to select firmware:
- check "unstable releases" - you'll get auto scroll
- scroll up check "enable expert mode" - you'll get auto scroll
- scroll up change release to release candidate - and again...
I thing this is due to autodetect function but I'd prefer the header part stay constantly on top to see what am I doing on this tab.

**Comment by haslinghuis** [comment]
Let's wait for other opinions on this.

**Comment by haslinghuis** [comment]
Yes - not happy with the last commit after request to make it conditional either.

**Comment by haslinghuis** [comment]
@mituritsyn think we can close this.
