### ISSUE TITLE
Update or reset "Enable Expert mode" after "Firmware flasher" tab

### ISSUE THREAD

**Issue by mituritsyn** [betaflight/betaflight-configurator#2552]
steps to reproduce:
- Check "Enable Expert mode" on "Firmware flasher"
- Hit "Connect"

Expected behavior:
- "Enable Expert mode" reseted and Expert mode tabs are hidden or
- "Enable Expert mode" checked tabs visible

Actual behavior:
- Tabs are visible, "Enable Expert mode" unchecked
![image](https://user-images.githubusercontent.com/15355893/128216448-36dff506-2946-46fd-85df-b38a6ba93da1.png)

**Comment by haslinghuis** [comment]
Good find @mituritsyn
