### ISSUE TITLE
Can't set "Pit mode frequency" via VTX Table tab

### ISSUE THREAD

**Issue by mituritsyn** [betaflight/betaflight-configurator#2565]
"Pit mode frequency" could be changed only via cli. After changing it on VTX Table tab it is resetted in 0 on Save button press

**Comment by ikherty** [comment]
go away, bot)

**Comment by haslinghuis** [comment]
@mituritsyn does this issue still exist?

**Comment by mituritsyn** [comment]
> @mituritsyn does this issue still exist?

sorry for delay, missed notification. tested on release 10.9 and 4.4, still exist

**Comment by haslinghuis** [comment]
@mituritsyn please check

**Comment by mituritsyn** [comment]
> @mituritsyn please check

seems ok. thanks for fix
