### ISSUE TITLE
Move "Motors" tab above "PID Tuning"

### ISSUE THREAD

**Issue by mituritsyn** [betaflight/betaflight-configurator#2566]
As we moved some options to different tabs, could we move "Motors" tab above "PID Tuning"? The point is that we need activate Esc/Motor protocol and BDshot options on Motors tab to be able fully configure PID/Filters and Modes tabs. 
So now we have following order while tuning: setup>ports>conf->skip 4 tabs to the motors to set protocol ->PID or anything else while it could correspond to tabs order from top to bottom: setup>ports>conf->power>motors->pid> etc

**Comment by haslinghuis** [comment]
![Screenshot from 2021-08-16 20-07-10](https://user-images.githubusercontent.com/8344830/129609564-d23e49c2-8172-45f0-88ca-baf9dcce8ce3.png)

**Comment by haslinghuis** [comment]
![Screenshot from 2021-08-16 20-05-21](https://user-images.githubusercontent.com/8344830/129610519-fbec424a-53aa-40c2-975c-102f3dbaec10.png)

Other suggestions:

- Fail-Safe should go after Receiver.
- Servos perhaps after Motors

**Comment by ikherty** [comment]
This suggestion will be most useful for targets that do not have dshot pre enabled

**Comment by haslinghuis** [comment]
@ctzsnooze ?
