### ISSUE TITLE
[Feature Request] Alphabetize various dropdowns

### ISSUE THREAD

**Issue by swilkens** [betaflight/betaflight-configurator#2569]
Various dropdown lists could be better with alphabetized listing.

Specifically **Seriel reciever provider** and  **Blackbox debug mode** selection.

![ser_rec_pro](https://user-images.githubusercontent.com/13329383/129853954-5270cf6c-1c67-45ea-8c91-69e1b5dabada.png)

![gyr_bb_deb_mod](https://user-images.githubusercontent.com/13329383/129853962-44df4597-ef76-4fcd-8411-3a7b581779ab.png)

**Comment by Asizon** [comment]
Is already alphabetized, please try latest 10.8.0 dev builds

**Comment by swilkens** [comment]
Excellent, thanks!

**Comment by haslinghuis** [comment]
FYI - Mixerlist and escProtocol are sorted in https://github.com/betaflight/betaflight-configurator/pull/2563
