### ISSUE TITLE
GUI: Menu dead after resizing application window (e.g. horizontally)

### ISSUE THREAD

**Issue by RipperDrone** [betaflight/betaflight-configurator#260]
After extending the canvas of the app window horizontally, mouse selection / left-click does no longer select menu items - menu seems dead.

**Comment by mikeller** [comment]
What menu? What OS?

**Comment by RipperDrone** [comment]
All menu items of BFC itself. OS=Win10 x64. I reverted back to 1.7.7, then resizing windows lets the menu stay alive.

**Comment by mikeller** [comment]
There is not really any menus and menu items in the configurator, so I cannot quite follow you.

**Comment by RipperDrone** [comment]
sry, did not make myself clear enough. I am referring to the menu icons in the left side bar, e.g. Setup, Ports, Configuration, ...

Those are all dead in the latest build, after resizing the app window.

**Comment by mikeller** [comment]
Hmm, I cannot reproduce under Linux. Maybe someone with Windows can have a look?

**Comment by RipperDrone** [comment]
Seems fixed in 1.8
