### ISSUE TITLE
Bug on PID-Slider : calculation differ on same slider values (MacOS)

### ISSUE THREAD

**Issue by mrRobot62** [betaflight/betaflight-configurator#2608]
Used FW & Configurator : same as in #2605 
![image](https://user-images.githubusercontent.com/949032/133917034-257fb23f-2e6d-4649-b85c-975c1411d913.png)

Testszenario
1) go to PID enable slider, set all sliders to 1 and get this values
<img width="594" alt="image" src="https://user-images.githubusercontent.com/949032/133917063-bd5b226b-b9bb-4c9a-aa2f-2aaac4067b56.png">

2) set DGain slider to 2 - get this values
<img width="594" alt="image" src="https://user-images.githubusercontent.com/949032/133917075-0cb7c3fe-24e7-496a-9764-7aef5fa71c0c.png">

3) change back to 1 and get values as seen in (1)

4) change back to 2 and this values
<img width="594" alt="image" src="https://user-images.githubusercontent.com/949032/133917087-c9b52897-1718-436d-bc7c-bc17acf6e24f.png">

5) if I do this several times I get several calculations

6) this bug is **not always reproducible** sometimes it works as supposed, sometimes not. I did this check only on DGain slider

7) easiest way to reproduce: change slider several times from low to high.

**Comment by haslinghuis** [comment]
Seems you don't have the correct firmware. We still have to change some defaults in the firmware. PID values with slider position in middle should look like:
![Screenshot from 2021-09-19 14-13-39](https://user-images.githubusercontent.com/8344830/133927065-ca50db7f-b88b-402a-b1ae-20ff950e7136.png)

**Comment by mrRobot62** [comment]
???? - that‘s obfuscated :-O
For saftey reason, could you resend link to FW which I should use :-O 
mhm, maybe I rearranged values during my test - not sure - but could you see the described effekt on you test environment?

mhmmmmmm

**Comment by haslinghuis** [comment]
FW is here but the new defaults have to be added yet: https://dev.azure.com/Betaflight/Betaflight%20Nightlies/_build/results?buildId=3887&view=artifacts&pathAsName=false&type=publishedArtifacts

Also configurator has been updated. So you might need to grap the latest version again at: https://dev.azure.com/Betaflight/Betaflight%20Nightlies/_build/results?buildId=3917&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by mrRobot62** [comment]
Hi,
installed latest Betaflight FW as suggested (betaflight_4.3.0_STM32F405_55a67977f.hex)
installed lates Betaflight-Configurator as suggested

Bug?
- "Auto detect" deactivated if no board is selected. I assume it should be activated if NO board is detected and deactivated if a board is selected

Betaflight-Configurator (Build)
<img width="328" alt="image" src="https://user-images.githubusercontent.com/949032/133935400-53a87919-f873-44c1-a10f-c1ebe00ed5d7.png">

PID-Slider test (Default) (Expert-Mode OFF)
<img width="592" alt="image" src="https://user-images.githubusercontent.com/949032/133935416-4d4cecbe-6633-4f21-b5f3-a8b78df7dd65.png">

Set Damping to 2.0
<img width="592" alt="image" src="https://user-images.githubusercontent.com/949032/133935438-f61a6893-83d7-4f6f-8c76-bce781dd4736.png">

Play around moving Damping Slider
- no calculation error. Bug fixed

Flash FW again to avoid any misconfiguration in memory
Start PID Mask, **Expert-Mode ON**
<img width="592" alt="image" src="https://user-images.githubusercontent.com/949032/133936179-9f94ae60-77ce-4c03-a20e-40f406ec87ab.png">

Move Damping Slider to 2.0
After several movings the slider from left to right
<img width="592" alt="image" src="https://user-images.githubusercontent.com/949032/133936225-01c0638f-766b-4626-a6e7-50aaedcfb1d0.png">

<img width="592" alt="image" src="https://user-images.githubusercontent.com/949032/133936253-47be8391-f599-4844-ad6f-6db78d1ed071.png">

Bug not fixed

**Comment by mrRobot62** [comment]
# Update 1
## Moving Tracking (P&I) left/right several times
- same calculation problem as with Damping-Slider

## Moving Stick-Response
- ok - no problem same together with Master-Slider

## Dynamic-Damping (DMax)
- same problem as with Damping DGain Slider 
### Value set to 2.0
<img width="100" alt="image" src="https://user-images.githubusercontent.com/949032/133937198-971f61f6-9231-43dd-99ff-be2474016a0c.png">

<img width="100" alt="image" src="https://user-images.githubusercontent.com/949032/133937211-0d14792e-99ae-414b-be72-681c743ce2e5.png">

## Drift-Wobble
- same problem as Damping

## Pitch-Damping
- same problem as Damping

## Pitch-Tracking
- same problem as Damping

<img width="580" alt="image" src="https://user-images.githubusercontent.com/949032/133937288-423bd9b8-810a-4d52-b345-b5fd88b4ea81.png">

<img width="580" alt="image" src="https://user-images.githubusercontent.com/949032/133937303-dc612a9d-6be0-4a99-96c3-0c881c5391e9.png">

# Conclusion
While testing the sliders, I noticed that the error rate depends on the speed at which the user moves the slider.
The faster he moves, the higher the probability that the calculation is incorrect.
The slower the user moves, the higher the probability that the result is correct.

**Comment by haslinghuis** [comment]
@mrRobot62 thanks for testing, I can reproduce. Now added the mouseup next to the input element so it recalculates after releasing the mouse.
Please test again with new configurator (please wait for the build has done).

I like the issue to be in one place as they are related and otherwise duplicate.

**Comment by mrRobot62** [comment]
ok, will do further testings tomorrow, should I flash new firmware too?

**Comment by haslinghuis** [comment]
Thanks @mrRobot62 for testing. Closing now.

FYI: I've committed the needed defaults in firmware too.

**Comment by mrRobot62** [comment]
perfect :-) - good job @haslinghuis
