### ISSUE TITLE
Bug? - Auto-Detect deactivated if no board selected

### ISSUE THREAD

**Issue by mrRobot62** [betaflight/betaflight-configurator#2609]
Not a real bug but nearby ;-)
On update Firmware page the *Auto detect* Button is a great idea, but this button should enabled if NO board is selected and deactivated if user select a board or autodetect find a board. Currently user have to select something, than button is activated and user can use it.

That's little bit confusing.

In my opinion : **Low priority**

Latest BF-Configurator Build from yesterday : 
<img width="386" alt="image" src="https://user-images.githubusercontent.com/949032/134052523-302dfd91-98da-4acd-8ad4-7c7a7dc155e9.png">

<img width="351" alt="image" src="https://user-images.githubusercontent.com/949032/134051911-52c9eccf-9ef9-40a8-b00d-9e07c076685e.png">

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/949032/134052620-376f8fb4-83f7-4969-9fbc-5351b42cf888.png">

**Comment by haslinghuis** [comment]
This redefined function should fix it:
```
        function updateDetectBoardButton() {
            const isDfu = portPickerElement.val().includes('DFU');
            const isBusy = GUI.connect_lock;
            const isLoaded = self.releases ? Object.keys(self.releases).length > 1 : false;
            const isAvailable = PortHandler.port_available || false;
            const isButtonDisabled = isDfu || isBusy || !isLoaded || !isAvailable;

            detectBoardElement.toggleClass('disabled', isButtonDisabled);
        }
```

**Comment by mrRobot62** [comment]
Hi @haslinghuis made the chang on my local machine and tested it locally. Not sure what are the next steps :-O. I forked this repository. Should I checkin only - or should I do some more steps. First time for me in kind of a virtual development team on git.

**Comment by haslinghuis** [comment]
Above fix can be tested with the artifact from the PR mentioned above: https://dev.azure.com/Betaflight/Betaflight%20Nightlies/_build/results?buildId=3934&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by mrRobot62** [comment]
Oh jesus - I totally misunderstood you comment above :-O - haha - yeah know I installed bf-configurator sources and can play around it :-)

Seems this issue is fixed
