### ISSUE TITLE
GUI: cloumn alignment still confused?

### ISSUE THREAD

**Issue by RipperDrone** [betaflight/betaflight-configurator#261]
@skaman82 : Sry to bother, but with latest commits, still column border alignment seems confused on my Windows 10 system:

![image](https://cloud.githubusercontent.com/assets/12601105/18230576/e82e15fc-729f-11e6-8449-25414f2d143a.png)

In the VEL/ALT tab, everything matches just perfect - why is it different on the other tables?

**Comment by mikeller** [comment]
@RipperDrone: Please be patient. There are more changes to the PID tab in the pipeline, we'll clean up the layout once everything is in.

**Comment by RipperDrone** [comment]
no prob, just wanted to inform @skaman82 , since Albert seemed to be working on these alignments with his recent commits (he even referenced to these issues in his commit comments and the issues were put into closed state already - but not fixed yet).

**Comment by mikeller** [comment]
This seems to be fixed now, @RipperDrone?

**Comment by RipperDrone** [comment]
@mikeller it's better but not fixed. Depending how you size the window horizontally, there is a column mismatch in STRENGTH and TRANSITION still. All others are a perfect match.

**Comment by RipperDrone** [comment]
@skaman82 All perfect now - even on Windows 10. Thanks, mate!

**Comment by skaman82** [comment]
That wasnt me this time - but still great! ;)

Von meinem iPhone gesendet
