### ISSUE TITLE
Option "Permanently activate expert mode" works only if BF-Configurator is restarted

### ISSUE THREAD

**Issue by mrRobot62** [betaflight/betaflight-configurator#2610]
New function on "Option "Permanently activate expert mode" Tab did not work perfect.

# BF-Configurator Version
<img width="393" alt="image" src="https://user-images.githubusercontent.com/949032/134053743-379ebea9-4f03-4df5-9a2b-7b16b418425a.png">

<img width="324" alt="image" src="https://user-images.githubusercontent.com/949032/134053783-6dbae72c-0a87-4e54-ae4e-1de166892fbd.png">

# Problem
<img width="277" alt="image" src="https://user-images.githubusercontent.com/949032/134053694-e1b12b4a-92b8-47e5-b6fb-4abbed05a22f.png">
If switch is ON and user connect to FC "Enable expert mode"-Switch is ON - perfect.
If user switch manually to OFF "expert mode" and than disconnect from FC and reconnect to FC again ends with expert-Mode with OFF.

# Conclusion
Suggestion:  always read Option-states during connect and not only on start. This increase user experience

**Comment by mrRobot62** [comment]
mhm, but if expert-mode is set to on as base option, than my gut feeling is, users expectation is: Expert mode is ON as long I change it to off during a session and it’s ON again if disconnect/connect again. Because it’s a system wide configuration. Otherwise I do not understand why we need this option

As an other example: if user set in base options the flag "reopen last tab". if this switch is on, bf-conf store the latest tab and after restarting or re-connect, system jumps to users latest tab. Thats the expectation.

Same analogy should be done with "always expert mode on". If user set this flag at every time expert mode is on, even he/she restart the app or disconnect/connect.

**Comment by haslinghuis** [comment]
Have to check later as my drive has no space left. Please check the other issue.

**Comment by haslinghuis** [comment]
@mrRobot62 happy to assist you to make this happen if you like to contribute to the project.

**Comment by sobelek** [comment]
@haslinghuis 
Hey, if this issue is still open and up for grab I would like to give it a try

**Comment by haslinghuis** [comment]
@sobelek
Sure take a hit on it. Much appreciated.
