### ISSUE TITLE
For Discussion: Cosmetic Issues on 'Filter Settings' Tab

### ISSUE THREAD

**Issue by mikeller** [betaflight/betaflight-configurator#2620]
There are what I think a few minor UX / understandability issues on the 'Filter Settings' tab:
- when the 'D Term Filter Multiplier' slider are disabled and enabled the slider and the 'Enable Sliders' button are 'jumping around' - it's probably cleaner to have the enable button in the same place as the slider.
![image](https://user-images.githubusercontent.com/4742747/135839237-6be1e11b-2d3b-4e2b-98cb-83610ce9eddf.png)
![image](https://user-images.githubusercontent.com/4742747/135839296-43d49a9e-5ef2-4e81-b493-1b970ee7da2c.png)
- 'Enable D Term Filter Multiplier' or similar is probably a better label for this button - similar fore the button to enable the Gyro Filter Multiplier;
- it might be helpful to have a similar mechanism to explicitly disable each of these sliders to what we have on the PID Profile Settings tab:
![image](https://user-images.githubusercontent.com/4742747/135839679-49449374-83db-4e66-9a37-cfcadc8f284b.png)
- for clarity, we might want to annotate the Gyro Filter Multiplier slider with '(profile independent)'.

**Comment by haslinghuis** [comment]
Remove jumping of sliders and change enable button(s): 
Enable button for each slider `Enable Gyro Filter Multiplier` and `Enable D Term Filter Multiplier`. What if both are off?
Add a `Filter Slider Mode` could be BOTH, GYRO, DTERM and OFF.
Tooltip should mention `(profile independent)` for Gyro Filter Multiplier.
