### ISSUE TITLE
Installation taking forever with 10.7.1

### ISSUE THREAD

**Issue by pdxtigre** [betaflight/betaflight-configurator#2629]
Latest betaflight-configurator-installer_10.7.1_win32.exe taking forever to install.
It is searching the files in node_modules and hogging CPU at 18%.
Can anything be done to speed this process up?

![image](https://user-images.githubusercontent.com/40930840/136719278-14d0e60a-7892-4436-a498-77bd77b4a7b7.png)

**Comment by Nikotttin** [comment]
![wifi spikes](https://user-images.githubusercontent.com/92298269/136756991-ac1da4cd-9868-4ed8-8e22-c8be886b36eb.PNG)

seems like it is calling somewhere without response

**Comment by aka13-404** [comment]
I don't get it. how the listing is so slow and CPU intensive at the same time. I have it installed on an m2 ssd, and it is taking for ever.
I'd go with a zipped version, but sadly there is none, only the installer. 

Should be definately a warning in the release notes, killed my plans quickly tweaking some settings.

**Comment by grabejud** [comment]
![Screenshot 2021-10-17 203841](https://user-images.githubusercontent.com/92675950/137627561-eec28487-4cc9-4d79-920f-786a01cad13f.jpg)
too late to read this. got the bug. uninstallaed and installed. cleaned registry, deleted appdata files, and this thing is stuck

**Comment by ggmaniack** [comment]
@grabejud 
It will finish installing, it just takes ages.

**Comment by haslinghuis** [comment]
As suggested by @McGiverGim uninstall the current version before installing this one.

**Comment by haslinghuis** [comment]
Added a note in the release to uninstall previous version

**Comment by Asizon** [comment]
Why you dont report this issue in 10.7.0??it is the same behaviour.

**Comment by pdxtigre** [comment]
> Added a note in the release to uninstall previous version

Thanks a lot!  That's what is needed.  

> Why you dont report this issue in 10.7.0??it is the same behaviour.

Asking why is not helpful without understanding the background.  I am not a fan of installer in general, I prefer the zip package.  I do not install BF on a daily basis and only install when I need.  I happened to run into this specific version to start with and realized the problem, thus, I wanted to report so others can be aware of what is going on.  Not to mention, the latest available releases are listed here [betaflight-configurator/releases](https://github.com/betaflight/betaflight-configurator/releases), do I see a big disclaimer?  Nope.  Saving people time from running into the problem is much appreciated.

**Comment by ThisIsMyNameBecauseEverythingIsTaken** [comment]
> As suggested by @McGiverGim uninstall the current version before installing this one.

Incorrect.
Brand new windows install. BF configurator has never been installed on this computer. Still hangs on installation.

**Comment by mrcottonmouth** [comment]
Same issue 10.7.1 on Windows 11

**Comment by mwhidden** [comment]
> 
> 
> > As suggested by @McGiverGim uninstall the current version before installing this one.
> 
> Incorrect. Brand new windows install. BF configurator has never been installed on this computer. Still hangs on installation.

I second @ThisIsMyNameBecauseEverythingIsTaken : I tried installing on a new machine, no prior installation of Configurator, and it hung in exactly the spot described above.

**Comment by rickyyR** [comment]
Same problem on multiple windows machines, creating the uninstall taking forever at @fortawesome fonts even with completely clean install. 10.7.0 is installing fine but should not be used apparently...

**Comment by randstorm** [comment]
Tried to tweak some stuff quickly. Found out after uninstalling bf on two seperate computers and reinstalling bf 10.7.1 on both and hung up at the end on both. So letting it take it's course???? It's all I can do. This is very much time wasting at a very inconvenient time for me. Is it gonna finish? Anybody install 10.7.1 successfully?

**Comment by rickyyR** [comment]
> 
> 
> Tried to tweak some stuff quickly. Found out after uninstalling bf on two seperate computers and reinstalling bf 10.7.1 on both and hung up at the end on both. So letting it take it's course???? It's all I can do. This is very much time wasting at a very inconvenient time for me. Is it gonna finish? Anybody install 10.7.1 successfully?

Yes it willl work, just take some time. Tbh for me personaly it was going faster after installing 10.7.0 first, could have been luck tho.

**Comment by haslinghuis** [comment]
Okay, this is problem now. It's takes a very long time. However as this is fixed already in 10.8 we are working to get this released asap.

**Comment by wernerterreb** [comment]
I wonder how long....   mine has been sitting in the same state shown below for about two hours so far.   I will leave it to wait longer, but I am not very hopefull.

![image](https://user-images.githubusercontent.com/6859511/146712920-6c2015f6-32a8-4a2c-8220-9ef2266dd833.png)

**Comment by AngryPepper** [comment]
How long will it take to download BetaFlight

**Comment by wernerterreb** [comment]
Just for the record... it does eventually install.  Just takes very long.  And as @haslinghuis mentioned in an earlier comment... the issue will be fixed in a future release.  I think its just 10.7 that has this problem.

**Comment by Asizon** [comment]
@wernerterreb finally fixed on released 10.7.2
