### ISSUE TITLE
"Enable Sliders" in filters tab enables filters with default lowpass values of 2Hz and 5Hz

### ISSUE THREAD

**Issue by howels** [betaflight/betaflight-configurator#2644]
Using build v20211025.4320 the filters tab shows no sliders. When clicking "enable sliders" the sliders do not appear.

![image](https://user-images.githubusercontent.com/7933842/139163535-fcbc0a89-b3f8-41f1-b074-8c1716785a0e.png)

Running betaflight 4.3 (https://github.com/betaflight/betaflight/commit/a2bbd31c9c0d39d9e672e56e5c54e25a0c38e9f3).

Prior configurator nightly with fewer sliders was working as expected.

After clicking "enable sliders" I see some particularly crazy values for filter frequencies, gyro lowpass 1 now set to 2 and 5Hz. Looks like a decimal point is dropped or something?

![image](https://user-images.githubusercontent.com/7933842/139163920-ba7d4885-9177-42b9-ad5c-81942039fdf7.png)

**Comment by haslinghuis** [comment]
Should be fixed in https://github.com/betaflight/betaflight-configurator/pull/2638

**Comment by howels** [comment]
> Should be fixed in #2638 Disclaimer: you need the firmware in that PR to use it.

thanks for the update. I'll keep an eye on your PR.

**Comment by howels** [comment]
Safe to close
