### ISSUE TITLE
Betaflight not working correctly with windows or mac

### ISSUE THREAD

**Issue by Timlazisa** [betaflight/betaflight-configurator#2646]
Ok so I'm new to all this and was kinda like hoping this would be fun. I have built three drones finally got my transmitter the other day and all ready to rock and roll. But what's this betaflight seems to have been put together with chewing gum and string..... what flippin' gives guys??  So I tried my laptop (win 64) did the whole drivers thing, installed reinstalled, drunk a bunch of coffee, trawled the internet, came up with a big fat blank. Then Joshua Bardwell says a mac is easier, so off I goes and buys a cheap mac. But hey ho, so old same old. I've reinstalled the firm ware mamba 405 Fury etc, downloaded the Cp210x drivers, like three times and all that happens is its say, serial port successfully opened, followed about 3 secs later with serial port successfully closed. When I do get a connection to the FC, the hologram of the copter moves but precious little else. I have a Radiomaster with Tracer nano tx and rx both are bound. So any ideas folks before this lot gets binned in the skip and I go back to robbing banks for a living??!! helllppppp  # If your issue looks like a hardware fault or a configuration problem please don't raise an issue here.

## If you believe there is an issue with the firmware itself please follow these steps:
1. Describe your problem;
2. Include ways to reproduce the problem;
3. Provide as much information as possible about your hardware and software, including:
- what hardware / software you are using;
- the version of all the software used;
- how things are connected / wired up.
4. Remove this Text :).

**Comment by limonspb** [comment]
Is that still the issue?
It is kinda hard to understand what is the isuse exactly? It connects with the configurator and then disconnects after ~3 seconds?
And what exactly is happening with the "hologram", can't translate this: "but precious little else"

**Comment by KarateBrot** [comment]
No answer for 3 weeks, so I guess the problem is solved?
