### ISSUE TITLE
CLI tab not accessible when Expert Mode is Enabled

### ISSUE THREAD

**Issue by malinhiles** [betaflight/betaflight-configurator#2647]
When the expert mode toggle switch in the top right of the configurator is enabled, the extra "expert mode features/tabs" appear in the tab tree, pushing the CLI tab to the bottom of the configurator window, out of reach. I can't scroll through the tabs to access it either. Exiting expert mode removes the expert mode tabs, and makes the CLI tab accessible again. 

- Windows 10
- 10/29/21
- Configurator 10.7.1
- Betaflight 4.2.5

This is my first time posting an issue here; let me know if you need any more info. Thanks!

![Expert Mode Disabled](https://user-images.githubusercontent.com/93371446/139393657-f6df0244-b5f3-4b10-afae-8ac4030dc0c7.png)
![Expert Mode Enabled](https://user-images.githubusercontent.com/93371446/139393663-2258fc1e-d988-4e45-8ecc-a0c40c7197b1.png)
.

**Comment by grepboy** [comment]
For what it's worth, I have observed the same behavior on Linux.  If the Betaflight configurator window is maximized, the options that do not fit are not available below sensors (I have GPS enabled),  However, if you restore the window (un-maximize), then the scroll bar appears for the left side options allowing you to scroll down and get to CLI and the other options that are cut off.
It would seem this is a bug that the scroll bar for the left hand options is disabled/hidden when the window is maximized.

**Comment by haslinghuis** [comment]
Hmm, I see the scroll bar on the right side not reaching bottom?

**Comment by malinhiles** [comment]
> Does it become available when disabling led strip?
 - Yes, the CLI tab becomes available when I disable the LED strip function, but only because that removes an item from the left side of the tab tree, making space for the CLI tab. That does not fix the issue, I am using the LED strip function and can't disable it in this case.

> What is your screen resolution?
- 1920x1080

> Are you able to scroll menu down?
- No, I am not able to scroll the menu down to reveal the CLI tab. That is the issue.

> Hmm, I see the scroll bar on the right side not reaching bottom?
- The scroll bar on the right side of the window is not for the tab tree column on the left, it is for the GUI within each tab. That scroll function works fine, and is not related to the issue

**Comment by malinhiles** [comment]
>  It would seem this is a bug that the scroll bar for the left hand options is disabled/hidden when the window is maximized.

- Interesting find, I just checked and noticed the same behavior on my end as well. If the window is maximized, I am no longer able to scroll through the tab tree on the left of the window.

**Comment by haslinghuis** [comment]
@Asizon do you have a clue as I don't experience this behavior?

**Comment by Asizon** [comment]
It is already fixed in 10.8.0

**Comment by Asizon** [comment]
https://github.com/betaflight/betaflight-configurator/pull/2292
