### ISSUE TITLE
Crashed on MacOS

### ISSUE THREAD

**Issue by COOLFPVkevin** [betaflight/betaflight-configurator#2654]
I am using a 2021 MacBook Pro with M1 chip. I connected my fpvdrone with an adapter to the laptop. When I open the Betaflight and after I press the connect, after few seconds it will crashed. My software is macOS Monterey 12.0.1

**Comment by Six6siX** [comment]
Same random crashes on Mac Mini M1. It lost the normal graphics depicting the quad. See screenshot as an example.

![Screenshot 2021-11-14 at 13 38 26](https://user-images.githubusercontent.com/7066184/141683912-f90607b7-f678-4688-a1ce-4f1d64d32669.png)
![Screenshot 2021-11-14 at 13 38 14](https://user-images.githubusercontent.com/7066184/141683924-3c22daa2-04b1-4840-aa2b-d957366cc3ce.png)

**Comment by haslinghuis** [comment]
Please try a nightly build

**Comment by k4m454k** [comment]
same problem on m1

**Comment by haslinghuis** [comment]
Please try:

https://dev.azure.com/Betaflight/Betaflight%20Nightlies/_build/results?buildId=4996&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by haslinghuis** [comment]
And maybe also 

https://dev.azure.com/Betaflight/Betaflight%20Nightlies/_build/results?buildId=4730&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by Asizon** [comment]
@k4m454k did you try attached development builds??

**Comment by niceric3** [comment]
Running the following command resolved the issue for me: `codesign --remove-signature /Applications/Betaflight\ Configurator.app/Contents/Frameworks/nwjs\ Framework.framework/Helpers/nwjs\ Helper\ (Renderer).app`

**Comment by k4m454k** [comment]
> @k4m454k did you try attached development builds??

yep. works fine

**Comment by Asizon** [comment]
Already fixed
