### ISSUE TITLE
Cant use Firmewareupdate

### ISSUE THREAD

**Issue by Spookydo** [betaflight/betaflight-configurator#2662]
Hi,

I want click on update Firmeware and Betaflight is still loading forever.
https://user-images.githubusercontent.com/35696384/142759747-8a0c289c-7a25-454e-9610-ccdb65ed0697.mp4

at DevTools i find this.

![download](https://user-images.githubusercontent.com/35696384/142759721-32f02374-83a8-4972-b310-1202d93bdc7d.jpg)

**Comment by ctzsnooze** [comment]
The video shows that the flight controller is not in DFU mode.

Normally - or for many boards, at least, including most of mine - the board must be in DFU mode before clicking Update Firmware.

**Comment by limonspb** [comment]
Looking through the video... This is weird. Windows showing ports like Linux-Mac style?
What system is that?
![image](https://user-images.githubusercontent.com/2925027/142789863-eddc31cd-66d9-43a0-9279-25a9a4c22378.png)

**Comment by haslinghuis** [comment]
@Spookydo - you could test with a nightly build. Never saw an issue with manifest on windows.
