### ISSUE TITLE
cli-tab can no longer be used

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/betaflight-configurator#2669]
after testing the last master on windows 10 I noticed that the cli-tab can no longer be used. The input line is continuously filled with characters and does not stop. If I reset the content of #2660, everything works again without any problems.

@haslinghuis pls can you check this.

**Comment by haslinghuis** [comment]
@TheIsotopes Just tested master on Windows. That PR is only adding a 100ms timeout to allow MSP commands to complete when switching to CLI when coming from the PID Tuning tab. Also tested on Linux. How can I reproduce?

**Comment by TheIsotopes** [comment]
@haslinghuis For example, I use a Matek F7 mini with default settings.
I'm going to cli execute a `diff` then `exit`, after reconnect going back to cli and it fills the input line with characters.

here is a screenshot, not quite two lines are filled with characters.
![cli-tab](https://user-images.githubusercontent.com/29702171/143685669-c9929174-b523-41fe-9a31-426929494259.jpg)

**Comment by haslinghuis** [comment]
Interesting if you using remember last tab and being on the PID tuning tab it work's ok.
So we have to look at CLI here.

**Comment by TheIsotopes** [comment]
Here another screenshot with console output ... hope this help you.

![Zwischenablagebild](https://user-images.githubusercontent.com/29702171/143688056-62f7ce28-afbf-4fa3-bd50-08a7a6df95ec.jpg)

**Comment by haslinghuis** [comment]
@TheIsotopes yeah intermittent saw this issue while in development, especially with latest firmware. Just tested with Matek F722 Mini on 4.2.11 and 4.3.
This PR only addresses going to CLI if on the PID Tuning tab. So this issue is not with this PR but another issue we have to address. 

Maybe we should stop sending new MSP commands if they get in retry state after some amount and bail out.

**Comment by TheIsotopes** [comment]
so it is now more a problem with the firmware and less one with the configurator?

**Comment by haslinghuis** [comment]
@TheIsotopes: The MSPCodes shown are from update_live_status() in serial_backend.js which are not supposed to run in CLI tab anyway. So I'm thinking having a zero timeout is the issue of this temporary fix.

**Comment by haslinghuis** [comment]
@TheIsotopes Could you please test PR 2670 if this solves the issue for you.

**Comment by TheIsotopes** [comment]
Tested now https://github.com/betaflight/betaflight-configurator/pull/2670/commits/2ebc1550d3894a82d2ddf95e6f7a8c75134faeb8 ... all looks good, the issue was solved.

thx @haslinghuis 👍
