### ISSUE TITLE
Configurator Installation consistently freezes at this specific step, across multiple machines

### ISSUE THREAD

**Issue by malinhiles** [betaflight/betaflight-configurator#2675]
Betaflight Configurator setup wizard gets stuck consistently at this point in installation:
![Screenshot 2021-12-02 150950](https://user-images.githubusercontent.com/93371446/144517898-7647298d-32c0-417d-b6b7-fd6eef6d5605.png)

Reproducing the problem:
Perform a fresh install of the 10.7.1 configurator on a 64bit Windows 10 machine. I've had this same issue across 4 different machines this month

**Comment by Kubiskoi** [comment]
Freezes for me also at exactly same step.

**Comment by PeterE1968** [comment]
Yes same looking for me!

**Comment by bluelegion** [comment]
Could be related to the "fortawesome" typeo in the screenshot above?

**Comment by haslinghuis** [comment]
This problem is already fixed in 10.8.0.

**Comment by KimIV** [comment]
На Виндовс 7 тоже "зависает". Я решил подождать и установка продолжилась. Общее время установки около часа.

**Comment by truglodite** [comment]
I have seen the ole "this is fixed in 10.8.0"... problem being for the rest... releases top out at 10.7.1.

So "fixed in 10.8.0"... will be meaningless to those who don't have access to 10.8.

**Comment by haslinghuis** [comment]
:santa:

**Comment by ChadyG** [comment]
So the release for 1.0.7.1 should be disabled since it is not working?

**Comment by YutakaMatsushige** [comment]
I confirm the installation of 10.7.1 on my computer is freezing in the same way at this point. I did not understand the reason and installed version 10.8

**Comment by haslinghuis** [comment]
The 10.7.1 release was needed to work with 4.2.1x.

**Comment by Asizon** [comment]
Fixed on 10.7.2
