### ISSUE TITLE
Configurator: 10.8.0-debug-79e081f0

### ISSUE THREAD

**Issue by trnnwnnhe** [betaflight/betaflight-configurator#2688]
### Setup

- Configurator version:

```
PASTE THE OUTPUT OF 'diff' HERE
```

**Comment by haslinghuis** [comment]
Could you please try to enable this in options tab to disable the serial port filter:

![image](https://user-images.githubusercontent.com/8344830/146006148-64dfdc26-3d5f-4533-b69e-14467eb5130f.png)
