### ISSUE TITLE
Gps Assisted failsafe

### ISSUE THREAD

**Issue by Austinthemighty** [betaflight/betaflight-configurator#269]
There should be a way that when your receiver goes into failsafe the gps, says go up to an altitude of  50-100 feet and go home and land.

**Comment by KiteAnton** [comment]
You should check out iNav,  https://github.com/iNavFlight/inav,  it has better GPS support and features with that.

**Comment by Austinthemighty** [comment]
where i live my RX is somewhat shoddy, and i don't like walking out 40 to 50 meters to get my drone
