### ISSUE TITLE
Can't change pid/rate profiles on latest nightly configurator 

### ISSUE THREAD

**Issue by nangel0** [betaflight/betaflight-configurator#2690]
### Describe the bug
 Can't change PID/rate profiles on the drop-down menu, they appear grayed. 

### To Reproduce
 Installing latest 2 releases, found this today on v20211212.4870 and needed to roll back to release v20211202.4718 to be able to change profiles. FC and FW don't matter, it appears grayed out on at least 3 different quads. 

### Expected behavior
 be able to change profiles 

### Setup

- Configurator version: latest 

```
PASTE THE OUTPUT OF 'diff' HERE
```

**Comment by AndreaCCIE** [comment]
Same here

**Comment by haslinghuis** [comment]
Almost there with an update.

**Comment by Asizon** [comment]
Fixes in https://github.com/betaflight/betaflight-configurator/pull/2698
