### ISSUE TITLE
White square around text in OSD

### ISSUE THREAD

**Issue by LoakAudio** [betaflight/betaflight-configurator#2717]
### Describe the bug
 When moving an item in the OSD tab, a large withe square appear around the item making it difficult to position

### To Reproduce
Click an try to move an item in the OSD Tab of Betaflight configurator
### Expected behavior

The withe part should be transparent

![Betaflight OSD weird](https://user-images.githubusercontent.com/39970118/147410689-de390fc6-ff21-4b6a-b667-5b4ba4c4cbdb.png)

### Setup

- Configurator version:  Configurator: 10.8.0-debug-90f15faf / Debian 10 (Betaflight Configurator 10.8.0 Release Candidate 1)

```
PASTE THE OUTPUT OF 'diff' HERE
```
Maybe not needed ?

**Comment by Asizon** [comment]
@LoakAudio It is intended to improve to facilitate positioning, I do not understand why it is more difficult for you now.

**Comment by Asizon** [comment]
ouch, you are talking about the white square ? this is really weird!

**Comment by LoakAudio** [comment]
Sorry "white" yes

**Comment by Asizon** [comment]
can you try with this please?
https://artprodeau1.artifacts.visualstudio.com/A3a9037bc-5464-4b2e-9e8d-ed1a5aa29705/ce1d2eeb-ce65-4b95-a02a-7fee6c006c71/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL0JldGFmbGlnaHQvcHJvamVjdElkL2NlMWQyZWViLWNlNjUtNGI5NS1hMDJhLTdmZWU2YzAwNmM3MS9idWlsZElkLzUxNDAvYXJ0aWZhY3ROYW1lL2JldGFmbGlnaHQtY29uZmlndXJhdG9yLWxpbnV40/content?format=zip

**Comment by LoakAudio** [comment]
@Asizon, Perfect with this betaflight-configurator_10.8.0-debug-4f415d75 version.
Thanks !
Can I use it and upgrade later with RC2 ?

**Comment by Asizon** [comment]
thankyou for your report and test!

**Comment by LoakAudio** [comment]
@Asizon an other question, the the "TX Link Power" doesn't appear in the OSD (the value is 0), my link is ELRS. Will I have to open a bug report for Betaflight or for ELRS ?

**Comment by Asizon** [comment]
It should be report on firmware repo, please be sure there are not already opened issue.

**Comment by LoakAudio** [comment]
Super efficient, thank you again, and still let go of your keyboard to have a good holiday!

**Comment by Asizon** [comment]
Please keep it open, it will close automatically when fix is merged.
