### ISSUE TITLE
Failed to parse extension manifest Ubuntu 20.04.3 LTS 

### ISSUE THREAD

**Issue by wyeric1987** [betaflight/betaflight-configurator#2722]
### Describe the bug

When I tried to start the betaflight configurator, it freezes. Then when I tried in terminal, I got this error message.

I'm running 64 bit Ubuntu 20.04.3 LTS trying Betaflight Configurator 10.7.1

```
$ ./betaflight-configurator 
[58166:58166:1229/145154.373321:ERROR:component_loader.cc(169)] Failed to parse extension manifest.
```

**Comment by haslinghuis** [comment]
Please test with https://github.com/betaflight/betaflight-configurator/releases/tag/10.8.0-RC1 and carefully read release notes. Please update firmware accordingly (save a diff before doing so).
