### ISSUE TITLE
Increase number of VTX control lines from 10 to a more useable number

### ISSUE THREAD

**Issue by dabit20** [betaflight/betaflight-configurator#2738]
### Is your feature request related to a problem? Please describe.
Basically the same 'issue' as described earlier here: https://github.com/betaflight/betaflight/issues/10572
The number of 'vtx' lines allowed is limited to 10. Now, in the quoted issue above there is a good explanation why the limit is 10, but at the same time that limit of 10 seems like an arbitrary number to me. 

In my case, 10 lines is too limited. And given the very few people using this feature it probably is for many other folks too. 
I have repurposed a trim switch on my TX16S radio as channel selector using GV adjustments and logical switches, and the 6-position switch as power/pitmode/off selector. Being able to increase power beyond 25mW when searching for a crashed quad or killing power when crashing close to the pilot area is valuable, as is quickly selecting another channel when people join or leave the event. Sure, it can be done from the BF LUA script or ExpressLRS LUA script also, but buttons on the radio are so much faster.

Also, I can change the VTX settings on the radio before powering up the quad, and when powering on the quad it is very quick to take the new setting, minimizing the chance of disturbing other feeds. So all in all, VTX control on radio switches is a very useful and IMHO underutilised feature.

### Describe the solution you'd like
I would like to have the number of lines allowed increased to a number that actually matches a broader range of use cases. I understand that it is impossible to cover all possible use cases, but a little more makes the feature far more useable. 

I think that an increase from 10 to 15 would work. The reasoning behind that is that not many pilots are using more than 8 channels and 2 bands (e.g. Raceband and IMD6 or Fatshark). VTXes with more than 4 power levels are quite rare and even when offered more it hardly makes sense to be able to select more. When adding it up, this yields 14 lines. Add a single 'to be defined' line, and we are at 15. 

### Describe alternatives you've considered
Using the OSD or HDZero VTX menu is not really a substitution since you have to be transmitting video in order to use those, and I prefer to setup these things while not transmitting video as a courtesy to other pilots.

Using the BF LUA is a better solution, but the FC and RX needs power to be able to do so. Easy to do using an USB cable, but still...
I currently run a self-compiled HEX file with MAX_CHANNEL_ACTIVATION_CONDITION_COUNT increased to 15 in vtx_control.h. That does what I want, but it would be nice if I could use regular 'production' hexfiles.

**Comment by McGiverGim** [comment]
I close this. The limitation is in the firmware, not in the Configurator. I see you opened a firmware feature request. It was closed, but it must be discussed there, not here.

**Comment by IvanShvets42** [comment]
@dabit20 does it really enough to just change MAX_CHANNEL_ACTIVATION_CONDITION_COUNT in vtx_control.h? Suddenly didn't work for me...
