### ISSUE TITLE
reciever mode serial rx won't save unless port is defined

### ISSUE THREAD

**Issue by UncleMcNutz** [betaflight/betaflight-configurator#274]
reciver mode does not save if serial rx is selected and no serial rx is designated in ports, appears serial scenario does not get set before enableing serial rx port, unsure if intentional or not, possible that every time i've flashed a bored i set the ports first though i doubt it, until recently this did not happen.

**Comment by mikeller** [comment]
Yes, this is indeed a feature of the firmware, and not a bug of the configurator. Setting serial Rx as signal input, with no port configured for serial input would not result in a flyable configuration.

 Also, please note the tabs in the configurator are in such an order that the ports tab comes before the configuration tab, trying to steer the user towards doing it in the right order.
