### ISSUE TITLE
Selected preset is not loading correctly

### ISSUE THREAD

**Issue by elvisteck** [betaflight/betaflight-configurator#2763]
### Describe the bug
After selecting a preset, the window that opens to select the options does not load correctly

![image](https://user-images.githubusercontent.com/3124504/150046607-24f73830-b25f-4967-ae85-dedafb268997.png)

The wrong behavior happens when you select the official preset source, select the unofficial preset source and it worked perfectly, then go back to the official one and now it looks like this

![image](https://user-images.githubusercontent.com/3124504/150047908-9bbd2c3d-3446-4cb0-871e-696665628689.png)

### To Reproduce
Enter the presets tab and select the supaflyFPV Freestyle 5" tuning preset. 
2 days ago it worked fine for me

### Setup
SO: Windows
Configurador: 10.8.0 (c9b7ed8f)
```
Entering CLI Mode, type 'exit' to return, or 'help'

# 
# Building AutoComplete Cache ... Done!
# 
# diff

# version
# Betaflight / STM32F7X2 (S7X2) 4.3.0 Jan  9 2022 / 11:51:40 (ee8560af4) MSP API: 1.44
# config: manufacturer_id: IFRC, board_name: IFLIGHT_SUCCEX_E_F7, version: c2b8c0d3, date: 2021-06-18T03:42:42Z

# start the command batch
batch start

board_name IFLIGHT_SUCCEX_E_F7
manufacturer_id IFRC

# name: Nazgul

# serial
serial 0 1 115200 57600 0 115200

# beacon
beacon RX_SET

# map
map TAER1234

# aux
aux 0 0 0 1800 2100 0 0
aux 1 1 1 1325 1675 0 0
aux 2 2 1 1750 2100 0 0
aux 3 13 4 1750 2100 0 0
aux 4 35 2 1800 2100 0 0

# master
set gyro_lpf1_static_hz = 0
set dyn_notch_count = 2
set dyn_notch_q = 450
set dyn_notch_min_hz = 100
set gyro_lpf1_dyn_min_hz = 0
set acc_calibration = -11,16,-53,1
set mag_hardware = NONE
set baro_hardware = NONE
set rssi_channel = 12
set serialrx_provider = CRSF
set dshot_bidir = ON
set gyro_1_align_yaw = 1800
set name = Nazgul

profile 0

rateprofile 0

# end the command batch
batch end
```

**Comment by Asizon** [comment]
@elvisteck yes we have made some changes in presets, can yo try latest development build?

**Comment by elvisteck** [comment]
Hi @Asizon I tested the version v20220118.5652 (https://github.com/betaflight/betaflight-configurator-nightlies/releases/tag/v20220118.5652) and it's ok the window of official presets
![image](https://user-images.githubusercontent.com/3124504/150148284-a1278528-428f-40bb-9867-faefce9be889.png)

Note: I changed to the Backup source of presets and appears the follow message. I think this its ok because is the source of the community and might have some errors
![image](https://user-images.githubusercontent.com/3124504/150148880-7a31bb67-650a-4bea-8ea0-48d7e1478b55.png)

**Comment by limonspb** [comment]
> Hi @Asizon I tested the version v20220118.5652 (https://github.com/betaflight/betaflight-configurator-nightlies/releases/tag/v20220118.5652) and it's ok the window of official presets ![image](https://user-images.githubusercontent.com/3124504/150148284-a1278528-428f-40bb-9867-faefce9be889.png)
> 
> Note: I changed to the Backup source of presets and appears the follow message. I think this its ok because is the source of the community and might have some errors ![image](https://user-images.githubusercontent.com/3124504/150148880-7a31bb67-650a-4bea-8ea0-48d7e1478b55.png)

The backup branch has not been updated to the latest format yet. So undefined.undefined version is normal there in that window.

There official Betaflight source must work ok without this window on the nightly configurator.
