### ISSUE TITLE
Configurator 10.8  for Mac: Betaflight 4.3 Presets not working/loading

### ISSUE THREAD

**Issue by Snowy247365** [betaflight/betaflight-configurator#2768]
### Describe the bug

Hello, I have betaflight 10.8 configurator for mac (running macOS Monterey 12.1) and betaflight 4.3 loaded on my board. However, I cannot load any presets and apply them on the presets tab. There is no place for me to pick an option of a preset, view online works, but view CLI does not. When I select pick preset, nothing happens. After closing the window, option to Save and Reboot remains grayed out.

<img width="1467" alt="Screen Shot 2022-01-23 at 1 10 41 PM" src="https://user-images.githubusercontent.com/98279302/150692209-46f60e4e-35c6-441b-aad6-64861887876d.png">

### To Reproduce

Applies to every preset showing on the preset tab in betaflight configurator 10.8 for mac. 

### Expected behavior

When selecting a preset, it should allow me to select a preset option and then once "pick" at the bottom is selected, button to save and reboot should become green. 

### Configurator version

10.8

### Flight controller configuration

```
 
Entering CLI Mode, type 'exit' to return, or 'help'

# 
# Building AutoComplete Cache ... Done!
# 
# diff

# version
# Betaflight / STM32F405 (S405) 4.3.0 Jan  9 2022 / 11:40:24 (ee8560af4) MSP API: 1.44
# config: manufacturer_id: CLRA, board_name: CLRACINGF4, version: 14929e39, date: 2020-08-31T10:05:16Z

# start the command batch
batch start

board_name CLRACINGF4
manufacturer_id CLRA

# feature
feature -RX_PARALLEL_PWM
feature RX_SERIAL
feature TELEMETRY

# serial
serial 0 64 115200 57600 0 115200
serial 2 32 115200 57600 0 115200
serial 3 1 115200 57600 0 115200

# aux
aux 0 0 3 900 1300 0 0
aux 1 13 1 1700 2100 0 0
aux 2 35 2 900 1300 0 0

# master
set gyro_lpf1_static_hz = 337
set gyro_lpf2_static_hz = 675
set gyro_lpf1_dyn_min_hz = 337
set gyro_lpf1_dyn_max_hz = 675
set acc_calibration = -10,-13,-56,1
set serialrx_provider = CRSF
set vbat_scale = 159
set simplified_gyro_filter_multiplier = 135
set osd_link_quality_pos = 14370
set osd_mah_drawn_pos = 14387
set osd_warnings_pos = 14729
set osd_avg_cell_voltage_pos = 14380
set osd_flip_arrow_pos = 14787

profile 0

# profile 0
set dterm_lpf1_dyn_min_hz = 101
set dterm_lpf1_dyn_max_hz = 202
set dterm_lpf1_static_hz = 101
set dterm_lpf2_static_hz = 202
set simplified_dterm_filter_multiplier = 135

rateprofile 0

# end the command batch
batch end

```

### Add any other context about the problem that you think might be relevant here

MACOS Monterey

**Comment by Asizon** [comment]
@Snowy247365 please see https://github.com/betaflight/betaflight-configurator/issues/2763
