### ISSUE TITLE
Osd not showing on DJI only unknown elements 

### ISSUE THREAD

**Issue by Stekkereend** [betaflight/betaflight-configurator#2787]
### Describe the bug

Osd not showing up in the dji goggles after syncing with BF. 

### To Reproduce

I had bf osd in the dji goggles till I wanted to start rearranging the elements. On new connect to the FC all elements where gone again .
Using a chrome book with an old configurator since newer onces are no longer supported. 
In the osd tab there are lots of unknown elements all of a sudden. See picture attached

### Expected behavior

Osd showing as normal 

### Configurator version

10.4.1 

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```

### Add any other context about the problem that you think might be relevant here

![769FCD86-0803-4AFF-9BC8-58F6CADF8DF5](https://user-images.githubusercontent.com/98787719/151896044-98f8ef5c-d2f4-49d4-ae61-dbf9b7f5428c.jpeg)

**Comment by haslinghuis** [comment]
@Stekkereend je moet upgraden / you need to upgrade 😄 

https://github.com/betaflight/betaflight-configurator/releases/tag/10.8.0-RC3 (link available soon)

Flash latest RC3 firmware
