### ISSUE TITLE
Add mutually exclusive options to presets (radio buttons)

### ISSUE THREAD

**Issue by rochford77** [betaflight/betaflight-configurator#2794]
### Is your feature request related to a problem? Please describe

The new options groups in the Configurator are really amazing. That said, it's frustrating not being able to make an option group mutually exclusive/select only one.

### Describe the solution you'd like

 I would like to be able to add a $is_mutually_exclusive or $is_radio or $select_one tag/decorator to an option group, which would give that option group radio buttons rather than checkboxes. If I have an option group called "cell count" and has the options 3s, 4s, 6s, I don't want them to be able to select multiple, especially if the options each change the same parameter, as that would result in only the final option being implemented. I want the user to only be able to pick one option withing the group in this scenario. 

### Describe alternatives you've considered

I think the main idea is pretty clear and concise, I don't see many alternatives.

**Comment by KarateBrot** [comment]
That's a very nice idea. Considering the implementation we have multiple possibilities:
- Besides `OPTION_GROUP` we could add a mutually exclusive option group, like `OPTION_GROUP_MUTEX`.
- We could also add a `#$ MUTEX` flag that makes all option buttons in the flag's scope mutually exclusive

Just some initial brainstorming....
