### ISSUE TITLE
RC3 : "Preset source version mismatch" pop-up error when trying to load my repo

### ISSUE THREAD

**Issue by AndroidGX** [betaflight/betaflight-configurator#2799]
### Describe the bug

Hello,
I'm currently with latest available configurator (RC3) for BF 4.3, and since I updated from RC2 to RC3, I now have the following error when it tries to load my preset repo : 

![betaflight-configurator_xmU8CQY9K9](https://user-images.githubusercontent.com/5033546/152946580-944db099-19f5-425b-b030-1b9091cb0392.png)

I tried to reinstall RC3 just today but same issue.
Any idea how to fix that ?

Many thanks in advance for the help.

### To Reproduce

Try to load my own github repo while beeing in RC3.
Link of my repo : https://github.com/AndroidGX/firmware-presets/tree/Feisar-4.3

### Expected behavior

No warning pop-up, like in RC2.

### Configurator version

340087a4

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```

**Comment by McGiverGim** [comment]
I think you need to add the version to your repo, like in the Betaflight presets repo:

https://github.com/betaflight/firmware-presets/blob/005203122a15e05d80478bd35a0ea9214f152996/index.json#L1-L3

**Comment by haslinghuis** [comment]
This is for RC2 but should apply to RC3:

![image](https://user-images.githubusercontent.com/8344830/152981229-c2c49625-7627-4af4-a2eb-69333473fa96.png)

**Comment by AndroidGX** [comment]
> I think you need to add the version to your repo, like in the Betaflight presets repo:
> 
> https://github.com/betaflight/firmware-presets/blob/005203122a15e05d80478bd35a0ea9214f152996/index.json#L1-L3
> 
> Probably you are using an old version of the repo. The Betaflight repo has evolved since you forked it and added this values.

Many thanks, I deleted my fork and recreated a new one and it works perfectly this time 👍

**Comment by KarateBrot** [comment]
@AndroidGX You don't need to delete it. You can always pull the changes into your fork to update
