### ISSUE TITLE
Configurator minimizes itself when switching desktops on Mac

### ISSUE THREAD

**Issue by currivan** [betaflight/betaflight-configurator#2804]
### Describe the bug

When Configurator 10.8.0 RC3 is open on one virtual desktop on MacOS Mojave (but not maximized), switching to another virtual desktop causes the app to minimize itself to the dock. Restoring it in the second desktop causes a switch back to the first desktop, followed by the app minimizing itself again.

### To Reproduce

Open Betaflight Configuration on Mac with multiple virtual desktops and then change to another one.

### Expected behavior

Stay open on the desktop it was opened on like previous versions.

### Configurator version

10.8.0 RC3 (340087a4)

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```

**Comment by currivan** [comment]
Behavior is unchanged with that build.

**Comment by haslinghuis** [comment]
Please try updating OSX, as Mojave is no longer supported by Apple since 30-11-2021.

**Comment by currivan** [comment]
Tested on both High Sierra and Monterey on a second machine. Behavior is
the same.

**Comment by currivan** [comment]
Why is this tagged to be closed? It's still a problem and there hasn't been a release since it was reported.

**Comment by javamatte** [comment]
Confirmed. Still an issue on Configurator: 10.8.0-debug-04b4c74

macOs Monterey 12.3

If Betaflight Configurator is not full screen (no menu bar visible) then it will minimize itself when switching desktops. Switching back to the original desktop does not restore the window. No other application I've ever seen behaves this way on macOs.

**Comment by haslinghuis** [comment]
Please test RC5. Can't confirm without a Mac

**Comment by dtruchan** [comment]
It is still and issue with 10.8.0 (be4a9e1)

**Comment by haslinghuis** [comment]
@dtruchan please test https://github.com/betaflight/betaflight-configurator/actions/runs/2261547416

**Comment by dtruchan** [comment]
[error.mov.zip](https://github.com/betaflight/betaflight-configurator/files/8628261/error.mov.zip)

Same

**Comment by haslinghuis** [comment]
Please check latest build here https://github.com/betaflight/betaflight-configurator/pull/2930#issuecomment-1133472473

**Comment by dtruchan** [comment]
Same thing

**Comment by benlumley** [comment]
I think it's this workaround that causes it - visibilitychange gets fired when you change desktops too it seems... 

https://github.com/haslinghuis/betaflight-configurator/blob/af6d633279a841e2605643bfc1df6359d54c1e58/src/js/main.js#L186

**Comment by simoccc** [comment]
I can confirm this BUG in Catalina 10.15.7  and latest Maverick

**Comment by theMikeChow** [comment]
Issue started occurring since updating to 10.8.0 Stable release. Same problem with app window minimizing itself upon desktop switching

MacOS Monterey (12.1), Intel

**Comment by simoccc** [comment]
I had this issue for sure in version RC6 

Confirmed in Monterey 12.1 latest update ( Intel ) too

**Comment by haslinghuis** [comment]
Please test https://github.com/betaflight/betaflight-configurator/pull/2961#issuecomment-1167948422

**Comment by haslinghuis** [comment]
I tried before https://github.com/betaflight/betaflight-configurator/pull/2452
