### ISSUE TITLE
Screen blur

### ISSUE THREAD

**Issue by romanpadilla45** [betaflight/betaflight-configurator#2810]
### Describe the bug

The screen would get fuzzy at random times but very often, and will stay until I click something, then go back to fuzzy.

### To Reproduce

Just use the configurator normally

### Expected behavior

All text and pictures become very out of focus like a big drop is resolution

### Configurator version

10.8.0 RC3

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```

**Comment by haslinghuis** [comment]
Please try with latest nightly build: https://github.com/betaflight/betaflight-configurator-nightlies/releases/tag/v20220212.5956

**Comment by romanpadilla45** [comment]
Just updated, same thing happens.
Notice bottom left on cpu load it looks normal

**Comment by McGiverGim** [comment]
I think we need some screen capture or video to see exactly what are you talking for.
A log of the developers console can be useful too, maybe some error message appears there.
You can try too to start the app with the parameter `--disable-gpu` to see if it changes something.

**Comment by romanpadilla45** [comment]
https://drive.google.com/file/d/1Exo06MGaVuhDanJEhF7x_um03F2U6Lwy/view?usp=drivesdk

It also disconnects me and won't let me reconnect unless I restart the
program

**Comment by McGiverGim** [comment]
> You can try too to start the app with the parameter `--disable-gpu` to see if it changes something.

Have you tested with this?

**Comment by romanpadilla45** [comment]
Not yet, I'm not sure how to

**Comment by haslinghuis** [comment]
Right click on the app icon and choose properties. Append `--disable-gpu` to target add the end

**Comment by ahandyman59** [comment]
This issue still occurs. I even have gone through the Windows 10 methods of solving blurry screens. My computer is a high end system, so it's not the computer hardware.   
Here is an example:
![image](https://user-images.githubusercontent.com/41529774/174236880-8ea83538-3cdd-4fba-bea4-98726b5e2fae.png)

**Comment by ahandyman59** [comment]
Was having this issue, but the "--disable-gpu  startup command fixed it.
