### ISSUE TITLE
ELRS UID Byte Generator tool built into Receiver tab

### ISSUE THREAD

**Issue by RitterFPV** [betaflight/betaflight-configurator#2821]
### Is your feature request related to a problem? Please describe

Sort of...
Having a hell of a time getting the SPI receiver boards to bind properly.

Setting up Bind Phrase and just adding that CLI to each build eliminates the Bind Pulse Sync.

### Describe the solution you'd like

Instead of or in addition to the Bind button on receiver tab when using ELRS.
instead enter bind phrase and it auto inserts the UID in the CLI.

then that is added to a "User Preset..."

### Describe alternatives you've considered

The alternative is to point a link to the UID Byte Generator on https://www.expresslrs.org/2.0/hardware/spi-receivers/
then copy paste to cli...

### Other information

![image](https://user-images.githubusercontent.com/90079076/154527408-a19bcf15-d9b0-4a89-b3d2-6c64b5065ecb.png)
![image](https://user-images.githubusercontent.com/90079076/154527423-4133cf95-cd1f-4cc3-ad74-140e8fa6033c.png)

**Comment by KarateBrot** [comment]
See https://github.com/betaflight/betaflight-configurator/pull/2721 and https://github.com/betaflight/betaflight/pull/11192. You will get this feature in BF 4.4.

**Comment by haslinghuis** [comment]
Fixed in [#11192](https://github.com/betaflight/betaflight/pull/11192)
