### ISSUE TITLE
spektrum receiver bound, no response in receiver tab

### ISSUE THREAD

**Issue by omribrand7** [betaflight/betaflight-configurator#2822]
### Describe the bug

 all the bars are frozen and not responsive to my rc in receiver tab 

### To Reproduce

hello 
I bought a new iflight protek 25 pusher pnp version,
the problem is when i try to see the receiver tab all the bars are frozen and not responsive to my rc 
 i plugged in brand new spektrum spm4648 receiver and bind it from the cli tab in betaflight ( set spektum_sat_bind = 9 ) and the bind succeeded 
i enabled serial rx in uart2 (as written in the manual)
i set receiver mode to serial-based receiver and set the serial receiver provider to SPEKTRUM2048 in configuration tab
i also tired to type set serialrx_inverted = off in the cli 
i saw that the receiver need to get 3.3v and the port is 5v so i installed a 3.3V STEP-DOWN VOLTAGE REGULATOR 
after all this steps the problem didn't solved so i tried to connect frsky sbus receiver and it worked well, all the bars was responsive to the rc but when i connected again the spektrum receiver the problem didn't solved 

my full setup is 
iflight protek 25 pusher
spektrum dx8 rc
spektrum spm4648 receiver ( with 3.3V STEP-DOWN VOLTAGE REGULATOR )
I'm sure that the rc and receiver working well because i tested them on my 5 intch quad

### Expected behavior

![protek reciver tab](https://user-images.githubusercontent.com/99964055/154679187-ec0a7b81-6587-45ea-b0e4-7513834a5d1f.jpg)
![Untitled-1](https://user-images.githubusercontent.com/99964055/154679211-2598b183-bc8a-439d-91b2-3cb8e34cd53d.jpg)
![protek config tab](https://user-images.githubusercontent.com/99964055/154679466-e67d4015-d86f-4ac2-8798-f9f3f4c05065.jpg)

please help me to understand what I'm doing wrong and solve my problem

### Configurator version

10.7.2

### Flight controller configuration

# version
# Betaflight / STM32F411 (S411) 4.2.9 Jun 14 2021 / 23:20:52 (e097f4ab7) MSP API: 1.43
###ERROR: diff: NO CONFIG FOUND###
# start the command batch
batch start

board_name IFLIGHT_F411_PRO
manufacturer_id IFRC

# name: Protek25 Pusher

# resources
resource BEEPER 1 B02
resource MOTOR 1 B06
resource MOTOR 2 B07
resource MOTOR 3 A00
resource MOTOR 4 B10
resource PPM 1 A03
resource LED_STRIP 1 A08
resource SERIAL_TX 1 A09
resource SERIAL_TX 2 A02
resource SERIAL_RX 1 A10
resource SERIAL_RX 2 A03
resource I2C_SCL 1 B08
resource I2C_SDA 1 B09
resource LED 1 C13
resource LED 2 C14
resource SPI_SCK 1 A05
resource SPI_SCK 2 B13
resource SPI_SCK 3 B03
resource SPI_MISO 1 A06
resource SPI_MISO 2 B14
resource SPI_MISO 3 B04
resource SPI_MOSI 1 A07
resource SPI_MOSI 2 B15
resource SPI_MOSI 3 B05
resource ADC_BATT 1 B00
resource ADC_CURR 1 B01
resource FLASH_CS 1 A15
resource OSD_CS 1 B12
resource GYRO_EXTI 1 A01
resource GYRO_CS 1 A04
resource USB_DETECT 1 C15

# timer
timer A03 AF3
# pin A03: TIM9 CH2 (AF3)
timer A00 AF1
# pin A00: TIM2 CH1 (AF1)
timer B10 AF1
# pin B10: TIM2 CH3 (AF1)
timer B06 AF2
# pin B06: TIM4 CH1 (AF2)
timer B07 AF2
# pin B07: TIM4 CH2 (AF2)
timer A08 AF1
# pin A08: TIM1 CH1 (AF1)

# dma
dma ADC 1 0
# ADC 1: DMA2 Stream 0 Channel 0
dma pin A00 0
# pin A00: DMA1 Stream 5 Channel 3
dma pin B10 0
# pin B10: DMA1 Stream 1 Channel 3
dma pin B06 0
# pin B06: DMA1 Stream 0 Channel 2
dma pin B07 0
# pin B07: DMA1 Stream 3 Channel 2
dma pin A08 0
# pin A08: DMA2 Stream 6 Channel 0

# feature
feature -RX_PARALLEL_PWM
feature RX_SERIAL
feature TELEMETRY
feature LED_STRIP
feature OSD

# beacon
beacon RX_LOST
beacon RX_SET

# map
map TAER1234

# serial
serial 1 64 115200 57600 0 115200

# led
led 0 0,0::L:0
led 1 1,0::L:0
led 2 2,0::L:0
led 3 3,0::L:0

# aux
aux 0 0 0 1700 2100 0 0
aux 1 1 1 900 2100 0 0
aux 2 13 3 1700 2100 0 0
aux 3 35 1 1700 2100 0 0

# vtxtable
vtxtable bands 5
vtxtable channels 8
vtxtable band 1 BOSCAM_A A CUSTOM  5865 5845 5825 5805 5785 5765 5745 5725
vtxtable band 2 BOSCAM_B B CUSTOM  5733 5752 5771 5790 5809 5828 5847 5866
vtxtable band 3 BOSCAM_E E CUSTOM  5705 5685 5665    0 5885 5905    0    0
vtxtable band 4 FATSHARK F CUSTOM  5740 5760 5780 5800 5820 5840 5860 5880
vtxtable band 5 RACEBAND R CUSTOM  5658 5695 5732 5769 5806 5843 5880 5917
vtxtable powerlevels 4
vtxtable powervalues 25 200 400 600
vtxtable powerlabels 25 200 400 600

# master
set acc_calibration = 6,-4,27,1
set mag_hardware = NONE
set baro_bustype = I2C
set baro_i2c_device = 1
set baro_hardware = NONE
set serialrx_provider = SPEK2048
set blackbox_p_ratio = 16
set blackbox_device = SPIFLASH
set dshot_idle_value = 700
set dshot_burst = AUTO
set dshot_bitbang = OFF
set motor_pwm_protocol = DSHOT300
set align_board_roll = 180
set current_meter = ADC
set battery_meter = ADC
set ibata_scale = 100
set beeper_inversion = ON
set beeper_od = OFF
set yaw_motors_reversed = ON
set small_angle = 180
set osd_warn_batt_not_full = OFF
set osd_warn_core_temp = OFF
set osd_rssi_pos = 342
set osd_link_quality_pos = 310
set osd_rssi_dbm_pos = 299
set osd_tim_2_pos = 2453
set osd_flymode_pos = 2413
set osd_vtx_channel_pos = 2421
set osd_current_pos = 2400
set osd_mah_drawn_pos = 2432
set osd_craft_name_pos = 2471
set osd_warnings_pos = 14666
set osd_avg_cell_voltage_pos = 2369
set osd_disarmed_pos = 2336
set system_hse_mhz = 8
set debug_mode = GYRO_SCALED
set vtx_band = 5
set vtx_channel = 3
set vtx_power = 1
set vtx_freq = 5732
set max7456_spi_bus = 2
set flash_spi_bus = 3
set gyro_1_bustype = SPI
set gyro_1_spibus = 1
set gyro_1_sensor_align = CW180
set gyro_1_align_yaw = 1800
set name = Protek25 Pusher

profile 0

# profile 0
set dyn_lpf_dterm_min_hz = 77
set dyn_lpf_dterm_max_hz = 187
set dterm_lowpass2_hz = 165
set feedforward_transition = 40
set iterm_relax_cutoff = 10
set yaw_lowpass_hz = 100
set p_pitch = 51
set d_pitch = 32
set f_pitch = 105
set p_roll = 46
set d_roll = 29
set f_roll = 99
set p_yaw = 50
set f_yaw = 99
set d_min_roll = 0
set d_min_pitch = 0

rateprofile 0

# rateprofile 0
set rates_type = ACTUAL
set roll_rc_rate = 19
set pitch_rc_rate = 19
set yaw_rc_rate = 19
set roll_expo = 60
set pitch_expo = 60
set yaw_expo = 60
set roll_srate = 90
set pitch_srate = 90
set yaw_srate = 90
set tpa_rate = 60
set tpa_breakpoint = 1280

# end the command batch
batch end

**Comment by haslinghuis** [comment]
Please flash the right target:

```
###ERROR: diff: NO CONFIG FOUND###
```
