### ISSUE TITLE
ImpulseRC Driver Fixer link do not show in French language.

### ISSUE THREAD

**Issue by Ciolouse** [betaflight/betaflight-configurator#2839]
### Describe the bug

The link for the ImpulseRC Driver Fixer can be see in every languages except in French.

![Presse-papierspng](https://user-images.githubusercontent.com/22751878/155951099-8d7e62f5-d71b-4145-8653-4cd6a67bcab7.png)

### To Reproduce

Change the language to French.

### Expected behavior

Can you please add this to French language ?

### Configurator version

10.8.0-debug-989816a

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```

**Comment by McGiverGim** [comment]
The translations are managed in Crowdin https://crowdin.com/project/betaflight-configurator

You need to open the issue there.
