### ISSUE TITLE
Chrome applications are deprecated by google

### ISSUE THREAD

**Issue by jaimevisser** [betaflight/betaflight-configurator#284]
Betaflight configurator will need to move to either Electron or NW.js if it is to be kept in a usable state when chrome app support ends.

Electron is also used as the basis of Slack and Atom. Quite mature and packaging options for all major platforms.

NW.js is a bit older then Electron and is also widely in use. Packaging is a bit more difficult but the advantage is that it has support for all chrome api's which could make porting a lot easier.

**Comment by KiteAnton** [comment]
Yes thanks for the info.  It is already known in the dev team and there will be an independent configurator in the future, stay tuned. :)

**Comment by Austinthemighty** [comment]
should we re-open #238 so people see it
