### ISSUE TITLE
[10.8.0 RC3 Portable & 10.7.2 Installer] Profile error when loading app (NW.js)

### ISSUE THREAD

**Issue by swilkens** [betaflight/betaflight-configurator#2852]
### Describe the bug

When starting the 10.8. RC3 portable or 10.7.2 installed configurator, the following error pops up for a second.

![Untitled](https://user-images.githubusercontent.com/13329383/157720815-02ddef0f-26bb-4027-bb7f-78da436c7afa.png)

The popup disappears quickly.

I also have 10.7.2 installed, it has the same popup.

### To Reproduce

Start the configurator

### Expected behavior

No error popup

### Configurator version

10.7.2 & 10.8.0 (340087a4)

### Flight controller configuration

n.a.

### Add any other context about the problem that you think might be relevant here

Running windows 8.1

**Comment by Asizon** [comment]
Already fixed in development build.
