### ISSUE TITLE
Bug or feature : Gyro filter slider always deactivated

### ISSUE THREAD

**Issue by mrRobot62** [betaflight/betaflight-configurator#2863]
### Describe the bug

![image](https://user-images.githubusercontent.com/949032/159344226-ccc3da64-45a5-4032-a240-c2295d64f784.png)

Even I set unindependend or dependent switches to on. The gyro-slider is always deactivated.
Not sure if this is a feature based on some other function or a bug.

If not a bug, maybe user should be informed, why slider is deactivated.

Found in BF-Configurator (under Mac OS 10.15.7)
![image](https://user-images.githubusercontent.com/949032/159344530-2e3bb51a-93d9-41e7-b170-b116cef65afc.png)

### To Reproduce

everytime

### Expected behavior

Slider should usable

### Configurator version

see screen shot 10.8.0 RC3

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```

**Comment by mrRobot62** [comment]
Hi @haslinghuis - long time ago .... :-)
Yeap will check this, my thought was to test on RC3 to focus on current bugs or other thins and to avoid with nightlies to struggle maybe on other issues.

However, will install tomorrow Nightly FW and Nightly BF-Config

**Comment by mrRobot62** [comment]
[FuryF4OSD_diff_BF_Conf_10.8.0-RC3.txt](https://github.com/betaflight/betaflight-configurator/files/8319359/FuryF4OSD_diff_BF_Conf_10.8.0-RC3.txt)

**Comment by haslinghuis** [comment]
Using
```
set gyro_lpf1_static_hz = 0
set gyro_lpf2_static_hz = 0
set gyro_lpf1_dyn_min_hz = 0
set gyro_lpf1_dyn_max_hz = 0
```
we get 

![image](https://user-images.githubusercontent.com/8344830/159377259-410ea312-46ef-4413-a9d1-b64365aa0b59.png)

Just enabling any gyro filter will enable the slider.

**Comment by haslinghuis** [comment]
Notice ON / OFF state here.

**Comment by mrRobot62** [comment]
I tried all permutations with both ON/OFF switches - nothing helps. Currently I do not have enough time for debugging, will do it maybe later. I assume, there is an other hickup, which caused this issue

**Comment by mrRobot62** [comment]
OMG 😱- 
But on perspektive of an user, maybe it would be helpful to inform user, if using Gyro-Multiplier, gyro Lowpass should be activated - with all consequences behind.

However - thanks for helping
