### ISSUE TITLE
Setup Wizard

### ISSUE THREAD

**Issue by MOE-MK** [betaflight/betaflight-configurator#2864]
### Is your feature request related to a problem? Please describe

Betaflight is intimidating for a user that has never used it before, it can get overwhelming, and new users can get lost 

### Describe the solution you'd like

a clear and easy way to setup your quad.

Single button that says something like Setup Wizard, New Quad, Wizard....
The button will initiate a wizard that asks simple questions like.

- What kind of receiver are you using, and it gives simple multiple choices like Crossfire, Spectrum, DJI...
- Which Port/UART is the Receiver connected to: UART 2, UART 3, UART 4, and in the same window, you can see rx signal to confirm its working
- Board orientation will show a quad on screen and the user selects pre-set rotations to match or can enter degrees, until the on screen quad matches movement
- Motor Wizard for direction, and mapping will be part of this wizard
- Simple questions of Props out or props in with illustrations of props to explain
- For the modes, it can be like motors, Move the switch you would like to use for arming...

### Describe alternatives you've considered

I am sure you get the idea here, simplifying the setup process while ensuring that nothing crucial is forgotten

**Comment by haslinghuis** [comment]
Our documentation and presets should help a lot now.
