### ISSUE TITLE
Bi-Directional active is not consistent in User Interface

### ISSUE THREAD

**Issue by nyartboy** [betaflight/betaflight-configurator#2868]
### Describe the bug

When you use the newest configurator with either 4.3 or previous versions and turn on Bi-Directional DSHOT, after save and reboot the feature presents disabled in the UI however if you pull a CLI report it will show it as on

### To Reproduce

Turn on Bi-Directional DSHOT. Save and Reboot. Check CLI. Check interface tab

### Expected behavior

Should show On when its On in UI. 

### Configurator version

10.8.0 RC3

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```

**Comment by haslinghuis** [comment]
For 4.3 on configurator 10.8RC3 you need at least firmware 4.3RC3

**Comment by Asizon** [comment]
Fixed in https://github.com/betaflight/betaflight-configurator/pull/2817
