### ISSUE TITLE
Filter sliders showing disabled

### ISSUE THREAD

**Issue by nyartboy** [betaflight/betaflight-configurator#2869]
### Describe the bug

When you first load the UI on the PID Filters everything seem normal. After using the sliders and saving, the sliders go grey and Filter changes revert

### To Reproduce

Make any changes in the PID filters

### Expected behavior

If using the sliders on the PID Tuning tab, they should continue to display as configured prior to saving

### Configurator version

10.8.0 RC3

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```

**Comment by haslinghuis** [comment]
Please update firmware to 4.3 RC3 as it doesn't work with previous versions.
