### ISSUE TITLE
no blackbox log config possible . no log file

### ISSUE THREAD

**Issue by DM4DS** [betaflight/betaflight-configurator#2872]
### Describe the bug

i tryed to activate Blackbox log with 2khz (tryed also 4khz after 2khz not worked) - gyro_scaled after other problems to analyze and it does not work.

activate it, it enables the feature with 1khz and reboots.
then I try to change it, but after reboot it´s always back on 1khz

while the quad freaked out, I tryed to use blackbox to look why, but there is no file on the FC after short arm/disarm . longest arming was ~10 Seconds before I had to disarm with smoking ESC / motors (only in BF 4.3 with 32.83 variable PWM - works perfect with 4.2.11 and 32.8 standard)

after 5 tryies, still no file on the FC.

Flashed 4.2.11 and it works flawless and logs looking good + quad flys perfect. I also rerolled the ESC to 32.8 BLHeli32 standard. So I´m not sure about the FC or ESC are the problem for the freakout quad. On 4.2.11 it flys great on defaults Betaflight/BLHeli32

### To Reproduce

see above.

try to activate after defaults.
after reboot you are always back to 1khz, but no file is saved during arm/disarm

### Expected behavior

it should work like under 4.2.11 - activate it to whatever it is set, reboots and viola saving files

### Configurator version

# Betaflight / STM32F7X2 (S7X2) 4.3.0 Feb  1 2022 / 20:14:54 (3267f0417) MSP API: 1.44

### Flight controller configuration

```
  defaults nosave


# version
# Betaflight / STM32F7X2 (S7X2) 4.3.0 Feb  1 2022 / 20:14:54 (3267f0417) MSP API: 1.44
# config: manufacturer_id: EXUA, board_name: EXF722DUAL, version: c2b8c0d3, date: 2021-06-18T03:42:42Z

# start the command batch
batch start

# reset configuration to default settings
defaults nosave

board_name EXF722DUAL
manufacturer_id EXUA
mcu_id 001b00263238510d36353235
signature 

# name: 7

# feature
feature GPS
feature TELEMETRY

# serial
serial 0 1 115200 57600 0 115200
serial 1 0 115200 57600 0 115200
serial 2 64 115200 57600 0 115200
serial 4 2 115200 9600 0 115200

# aux
aux 0 0 0 1950 2100 0 0
aux 1 2 3 1300 1700 0 0
aux 2 46 3 1900 2100 0 0
aux 3 13 1 1300 1700 0 0
aux 4 35 1 1900 2100 0 0
aux 5 37 4 1300 2100 0 0

# master
set dyn_notch_count = 1
set dyn_notch_q = 500
set acc_calibration = -30,-11,-20,1
set serialrx_provider = CRSF
set dshot_bidir = ON
set failsafe_procedure = GPS-RESCUE
set align_board_yaw = 180
set small_angle = 180
set gps_provider = UBLOX
set gps_rescue_descent_dist = 50
set gps_rescue_sanity_checks = RESCUE_SANITY_FS_ONLY
set gps_rescue_min_sats = 5
set gps_rescue_min_dth = 50
set gps_rescue_allow_arming_without_fix = ON
set deadband = 10
set yaw_deadband = 10
set osd_current_pos = 2095
set osd_gps_speed_pos = 2060
set osd_gps_lon_pos = 2062
set osd_gps_lat_pos = 2065
set osd_gps_sats_pos = 2057
set osd_altitude_pos = 2052
set osd_avg_cell_voltage_pos = 2092
set gyro_2_align_yaw = 900
set name = 7

profile 0

profile 1

profile 2

# restore original profile selection
profile 0

rateprofile 0

rateprofile 1

rateprofile 2

rateprofile 3

rateprofile 4

rateprofile 5

# restore original rateprofile selection
rateprofile 0

# save configuration
```

### Add any other context about the problem that you think might be relevant here

While I´m now back on 4.2.11 (installed latest 4.2 configurator) I only have the diff all, sorry

maybe the Blackbox and the bidirectional DShot problem pointing into the same direction? That´s the other problem I posted few minutes ago.

**Comment by mrRobot62** [comment]
Do work with Windows or Mac?
In your configuration I do net see `debug_mode` is available.

To focus this issue a little bit more in detail.

Do following in CLI:
```
get blackbox
```
you get a couple of configuration around blackbox. I assume your F7 FC is logging into Flash, in this case you should see a commands like 
* `blackbox_device=SPIFLASH`
* all others `blackbox_xxxxx` should be OFF

Than configure 
```
set debug_mode = GYRO_SCALED
set blackbox_sample_rate=1/2
```
Than try again with a flight and BB-logging, do you get now data?

Please post your result - thanks
