### ISSUE TITLE
"Ready" Mode OSD for Racing

### ISSUE THREAD

**Issue by bberg115** [betaflight/betaflight-configurator#2874]
### Is your feature request related to a problem? Please describe

Racing typically requires an individual or race director to verify that everyone is ready by asking for a thumbs up. In big events, this may require a 2nd person (race line) to coordinate. Although it is not critical, this requires additional volunteer/time and is not efficicent.

### Describe the solution you'd like

Use OSD to notify director that everyone is ready via the video feeds. This could be done a couple of ways but I think using "pre-arm" mode may be the easiest. When a pilot is in "pre-arm" mode, the OSD would show "READY" and may eliminate the need for "thumbs up" requests all together.

### Describe alternatives you've considered

This could also be done with a standalone mode/switch that the pilots could trigger.

**Comment by bberg115** [comment]
Good point.

 I can see this being a separate mode / option in the configurator so that
the user can decide if they want it on the same switch or use a switch for
more than 1 mode.

**Comment by jonmahoney15** [comment]
So would this need to go away once flying or say something else like shred, burn, fly or rip?

**Comment by bberg115** [comment]
My thought is that it would turn off after throttling up or by changing the
switch state to cancel. In order to re-initiate on the same pack, you would
need to change the switch again before it would show up.

**Comment by jonmahoney15** [comment]
Would you want it to say anything when in a not ready state?

**Comment by bberg115** [comment]
My initial thought is no, but that may be a nice feature.

There's some situations where it could be tricky to implement if the mode
isn't enabled by a standalone switch.
