### ISSUE TITLE
Gyro and PID rate drop in cli tasks (Holybro Kakute H7)

### ISSUE THREAD

**Issue by wsnzone** [betaflight/betaflight-configurator#2883]
### Describe the bug

In cli tasks pidlooop and gyro doesn't get 8K (Gyro: 7981, pidllop: 7981). I've tryed do set 4K for pidloop, no luck. Gyro is still 7981Hz and pidloop is 3990

### To Reproduce

My config is Kakute H7 (bf4.3RC4), Matek GPS with magnetometer, viflyfinder buzzer.
Go to cli, type "tasks"

### Expected behavior

Consistant 8K gyro update rate

### Configurator version

10.8.0-debug-04b4c74

### Flight controller configuration

# 

# diff all

# version
# Betaflight / STM32H743 (SH74) 4.3.0 Feb  1 2022 / 20:15:46 (3267f0417) MSP API: 1.44
# config: manufacturer_id: HBRO, board_name: KAKUTEH7, version: e4b51680, date: 2021-10-04T00:52:01Z

# start the command batch
batch start

# reset configuration to default settings
defaults nosave

board_name KAKUTEH7
manufacturer_id HBRO
mcu_id 004500333330510130303736
signature 

# name: WSN (SATANA7)

# feature
feature -RX_PARALLEL_PWM
feature GPS

# serial
serial 3 2 115200 57600 0 115200

# beeper
beeper -ON_USB

# aux
aux 0 0 0 1525 2100 0 0
aux 1 1 1 1375 1425 0 0
aux 2 2 1 1175 1225 0 0
aux 3 13 0 1875 2100 0 0
aux 4 13 0 1125 1375 0 0
aux 5 26 0 1525 2100 0 0
aux 6 35 1 1775 1825 0 0

# master
set gyro_lpf1_static_hz = 0
set gyro_lpf2_static_hz = 900
set dyn_notch_count = 1
set dyn_notch_q = 420
set dyn_notch_max_hz = 500
set gyro_lpf1_dyn_min_hz = 0
set gyro_lpf1_dyn_max_hz = 900
set acc_calibration = -3,173,-79,1
set align_mag = CW270FLIP
set mag_align_pitch = 1800
set mag_align_yaw = 2700
set rc_smoothing_auto_factor = 75
set serialrx_provider = CRSF
set dshot_bidir = ON
set motor_pwm_protocol = DSHOT600
set vbat_display_lpf_period = 10
set yaw_motors_reversed = ON
set small_angle = 180
set gps_provider = UBLOX
set simplified_gyro_filter_multiplier = 180
set report_cell_voltage = ON
set osd_warn_link_quality = ON
set osd_vbat_pos = 14464
set osd_rssi_pos = 2400
set osd_link_quality_pos = 14561
set osd_tim_1_pos = 14424
set osd_tim_2_pos = 14392
set osd_flymode_pos = 14432
set osd_g_force_pos = 14744
set osd_throttle_pos = 14776
set osd_vtx_channel_pos = 49
set osd_crosshairs_pos = 12493
set osd_current_pos = 14764
set osd_mah_drawn_pos = 14528
set osd_craft_name_pos = 14400
set osd_gps_speed_pos = 14656
set osd_gps_lon_pos = 14785
set osd_gps_lat_pos = 14753
set osd_gps_sats_pos = 14368
set osd_home_dir_pos = 14597
set osd_home_dist_pos = 14592
set osd_altitude_pos = 14624
set osd_warnings_pos = 14794
set osd_avg_cell_voltage_pos = 14496
set osd_battery_usage_pos = 36
set osd_flip_arrow_pos = 14390
set debug_mode = GYRO_SCALED
set rpm_filter_q = 450
set rpm_filter_min_hz = 95
set rpm_filter_fade_range_hz = 40
set rpm_filter_lpf_hz = 300
set name = WSN (SATANA7)

profile 0

# profile 0
set dterm_lpf1_dyn_min_hz = 82
set dterm_lpf1_dyn_max_hz = 165
set dterm_lpf1_static_hz = 0
set dterm_lpf2_static_hz = 165
set iterm_relax_cutoff = 12
set pidsum_limit = 1000
set pidsum_limit_yaw = 1000
set yaw_lowpass_hz = 95
set p_pitch = 66
set i_pitch = 143
set d_pitch = 60
set f_pitch = 124
set p_roll = 67
set i_roll = 144
set d_roll = 56
set f_roll = 125
set d_min_roll = 56
set d_min_pitch = 60
set auto_profile_cell_count = 4
set feedforward_smooth_factor = 30
set feedforward_boost = 18
set feedforward_max_rate_limit = 95
set dyn_idle_min_rpm = 25
set simplified_pids_mode = RP
set simplified_master_multiplier = 150
set simplified_i_gain = 120
set simplified_d_gain = 125
set simplified_dmax_gain = 0
set simplified_feedforward_gain = 70
set simplified_pitch_d_gain = 95
set simplified_pitch_pi_gain = 95
set simplified_dterm_filter_multiplier = 110

profile 1

# profile 1
set iterm_relax_cutoff = 12
set pidsum_limit = 1000
set pidsum_limit_yaw = 1000
set yaw_lowpass_hz = 95
set p_pitch = 44
set i_pitch = 95
set d_pitch = 35
set f_pitch = 83
set p_roll = 42
set i_roll = 91
set d_roll = 31
set f_roll = 79
set p_yaw = 42
set i_yaw = 91
set f_yaw = 79
set d_min_roll = 31
set d_min_pitch = 35
set motor_output_limit = 85
set auto_profile_cell_count = 6
set feedforward_smooth_factor = 30
set feedforward_boost = 18
set feedforward_max_rate_limit = 95
set dyn_idle_min_rpm = 28
set simplified_master_multiplier = 95
set simplified_i_gain = 120
set simplified_d_gain = 110
set simplified_dmax_gain = 0
set simplified_feedforward_gain = 70

profile 2

# profile 2
set iterm_relax_cutoff = 12
set auto_profile_cell_count = -1
set feedforward_smooth_factor = 30
set feedforward_boost = 18
set feedforward_max_rate_limit = 95

# restore original profile selection
profile 0

rateprofile 0

# rateprofile 0
set roll_rc_rate = 8
set pitch_rc_rate = 8
set yaw_rc_rate = 8
set roll_expo = 80
set pitch_expo = 80
set yaw_expo = 80
set roll_srate = 85
set pitch_srate = 85
set yaw_srate = 85

rateprofile 1

rateprofile 2

rateprofile 3

rateprofile 4

rateprofile 5

# restore original rateprofile selection
rateprofile 0

# save configuration
save
# 

### Add any other context about the problem that you think might be relevant here

![photo_2022-04-07_11-35-07](https://user-images.githubusercontent.com/36262060/162220398-32f28b69-9e4f-4201-86cf-0f63f7a6898c.jpg)
![photo_2022-04-07_11-37-09](https://user-images.githubusercontent.com/36262060/162220401-fe0445d9-6e59-4966-b7c9-13468f7dc4e5.jpg)

**Comment by haslinghuis** [comment]
Just tried with `master` (RC4) I'd had to use tasks twice to get this output. On second connection it was showing as below:
```
# version
# Betaflight / STM32H743 (SH74) 4.3.0 Apr  5 2022 / 21:46:10 (2fd2e8eca) MSP API: 1.44
# config: manufacturer_id: HBRO, board_name: KAKUTEH7MINI, version: c24ea9c4, date: 2021-12-16T07:02:07Z
# board: manufacturer_id: HBRO, board_name: KAKUTEH7MINI

# tasks
Task list             rate/hz  max/us  avg/us maxload avgload  total/ms   late    run reqd/us
00 - (         SYSTEM)     10       1       0    0.0%    0.0%         0      0     70       0
01 - (         SYSTEM)    999       2       0    0.1%    0.0%         2      0   6830       1
02 - (           GYRO)   8013       4       0    3.2%    0.6%        34      0  54735       0
03 - (         FILTER)   8013       7       3    5.6%    2.5%       179      0  54735       0
04 - (            PID)   8013      11       6    8.8%    4.8%       353      0  54735       0
05 - (            ACC)   1000       4       1    0.4%    0.1%         6      0   6830       2
06 - (       ATTITUDE)    100       5       3    0.0%    0.0%         2      0    686       4
07 - (             RX)     10       8       4    0.0%    0.0%         1      2    210       8
08 - (         SERIAL)    100  729617       0 7296.1%    0.0%      1342      0    684      79
09 - (       DISPATCH)    999       2       0    0.1%    0.0%         1      0   6830       0
10 - (BATTERY_VOLTAGE)     50       3       0    0.0%    0.0%         0      0    343       1
11 - (BATTERY_CURRENT)     50       1       0    0.0%    0.0%         0      0    343       0
12 - ( BATTERY_ALERTS)      4       1       0    0.0%    0.0%         0      0     36       0
13 - (         BEEPER)    100       2       0    0.0%    0.0%         0      0    683       1
16 - (           BARO)     40      27      16    0.1%    0.0%        14      2    820      25
18 - (       ALTITUDE)     40       5       2    0.0%    0.0%         0      0    275       4
20 - (      TELEMETRY)    249       4       0    0.0%    0.0%         0      0   1707       0
23 - (            OSD)     12      23       8    0.0%    0.0%         8      7   1297      22
25 - (            CMS)     20       1       0    0.0%    0.0%         0      0    138       0
26 - (        VTXCTRL)      4       1       0    0.0%    0.0%         0      0     36       1
27 - (        CAMCTRL)      4       1       0    0.0%    0.0%         0      0     36       0
29 - (    ADCINTERNAL)      1       1       0    0.0%    0.0%         0      0      8       0
RX Check Function                   3       1                         1
Total (excluding SERIAL)                                 8.0%
```

**Comment by wsnzone** [comment]
> Just tried with `master` (RC4) I'd had to use tasks twice to get this output. On second connection it was showing as below:
> 
> ```
> # version
> # Betaflight / STM32H743 (SH74) 4.3.0 Apr  5 2022 / 21:46:10 (2fd2e8eca) MSP API: 1.44
> # config: manufacturer_id: HBRO, board_name: KAKUTEH7MINI, version: c24ea9c4, date: 2021-12-16T07:02:07Z
> # board: manufacturer_id: HBRO, board_name: KAKUTEH7MINI
> 
> # tasks
> Task list             rate/hz  max/us  avg/us maxload avgload  total/ms   late    run reqd/us
> 00 - (         SYSTEM)     10       1       0    0.0%    0.0%         0      0     70       0
> 01 - (         SYSTEM)    999       2       0    0.1%    0.0%         2      0   6830       1
> 02 - (           GYRO)   8013       4       0    3.2%    0.6%        34      0  54735       0
> 03 - (         FILTER)   8013       7       3    5.6%    2.5%       179      0  54735       0
> 04 - (            PID)   8013      11       6    8.8%    4.8%       353      0  54735       0
> 05 - (            ACC)   1000       4       1    0.4%    0.1%         6      0   6830       2
> 06 - (       ATTITUDE)    100       5       3    0.0%    0.0%         2      0    686       4
> 07 - (             RX)     10       8       4    0.0%    0.0%         1      2    210       8
> 08 - (         SERIAL)    100  729617       0 7296.1%    0.0%      1342      0    684      79
> 09 - (       DISPATCH)    999       2       0    0.1%    0.0%         1      0   6830       0
> 10 - (BATTERY_VOLTAGE)     50       3       0    0.0%    0.0%         0      0    343       1
> 11 - (BATTERY_CURRENT)     50       1       0    0.0%    0.0%         0      0    343       0
> 12 - ( BATTERY_ALERTS)      4       1       0    0.0%    0.0%         0      0     36       0
> 13 - (         BEEPER)    100       2       0    0.0%    0.0%         0      0    683       1
> 16 - (           BARO)     40      27      16    0.1%    0.0%        14      2    820      25
> 18 - (       ALTITUDE)     40       5       2    0.0%    0.0%         0      0    275       4
> 20 - (      TELEMETRY)    249       4       0    0.0%    0.0%         0      0   1707       0
> 23 - (            OSD)     12      23       8    0.0%    0.0%         8      7   1297      22
> 25 - (            CMS)     20       1       0    0.0%    0.0%         0      0    138       0
> 26 - (        VTXCTRL)      4       1       0    0.0%    0.0%         0      0     36       1
> 27 - (        CAMCTRL)      4       1       0    0.0%    0.0%         0      0     36       0
> 29 - (    ADCINTERNAL)      1       1       0    0.0%    0.0%         0      0      8       0
> RX Check Function                   3       1                         1
> Total (excluding SERIAL)                                 8.0%
> ```

Just after connection I've got 10K. But, retype "tasks" and enter a few times give another results

# 
# Building AutoComplete Cache ... Done!
# 
# tasks
Task list             rate/hz  max/us  avg/us maxload avgload  total/ms   late    run reqd/us
00 - (         SYSTEM)     10       2       0    0.0%    0.0%         0      0     72       1
01 - (         SYSTEM)    983    2259       0  222.0%    0.0%       120    242   6552      21
02 - (           GYRO)  10331       4       0    4.1%    0.8%        36      0  56514       0
03 - (         FILTER)  10331      10       5   10.3%    5.8%       315      0  56514       0
04 - (            PID)  10331      21      11   21.6%   11.9%       749      0  56514       0
05 - (            ACC)    998       4       0    0.3%    0.0%         5      0   6902       1
06 - (       ATTITUDE)    100       6       3    0.0%    0.0%         2      0    701       5
07 - (             RX)     10       9       6    0.0%    0.0%         1      2    216       7
08 - (         SERIAL)    100  770075       0 7700.7%    0.0%      1383      0    696      29
09 - (       DISPATCH)    998       3       0    0.2%    0.0%         1      0   6904       0
10 - (BATTERY_VOLTAGE)     50       3       0    0.0%    0.0%         0      0    353       1
11 - (BATTERY_CURRENT)     50       2       0    0.0%    0.0%         0      0    353       1
12 - ( BATTERY_ALERTS)      5       1       0    0.0%    0.0%         0      0     37       1
13 - (         BEEPER)    100       2       0    0.0%    0.0%         0      0    695       1
14 - (            GPS)    100      32       2    0.3%    0.0%         2      6    701      24
15 - (        COMPASS)     10      27      15    0.0%    0.0%         3      1    213      26
16 - (           BARO)     40      27      17    0.1%    0.0%        14      2    841      26
18 - (       ALTITUDE)     40       5       3    0.0%    0.0%         0      0    282       4
20 - (      TELEMETRY)    499       7       0    0.3%    0.0%         2      1   3437       0
23 - (            OSD)     12      38      10    0.0%    0.0%        11     21   1699      24
25 - (            CMS)     20       3       0    0.0%    0.0%         0      0    141       2
26 - (        VTXCTRL)      5       1       0    0.0%    0.0%         0      0     37       0
27 - (        CAMCTRL)      5       1       0    0.0%    0.0%         0      0     37       0
29 - (    ADCINTERNAL)      1       1       0    0.0%    0.0%         0      0      9       0
30 - (       PINIOBOX)     20       2       0    0.0%    0.0%         0      0    141       1
31 - (SPEED_NEGOTIATION)    100       9       0    0.0%    0.0%         0      1    693       4
RX Check Function                   4       1                         2
Total (excluding SERIAL)                                18.5%

# tasks
Task list             rate/hz  max/us  avg/us maxload avgload  total/ms   late    run reqd/us
00 - (         SYSTEM)     10       1       0    0.0%    0.0%         0      0     57       1
01 - (         SYSTEM)    998       4       0    0.3%    0.0%       124      0   5709       0
02 - (           GYRO)   7994       3       0    2.3%    0.5%        72      0  48076       0
03 - (         FILTER)   7994      10       5    7.9%    4.3%       583      0  48076       0
04 - (            PID)   7994      19      14   15.1%   11.2%      1404      0  48076       0
05 - (            ACC)    998       3       0    0.2%    0.0%        10      0   5723       0
06 - (       ATTITUDE)    100       6       3    0.0%    0.0%         4      0    573       3
07 - (             RX)     10       9       5    0.0%    0.0%         2      0    171       6
08 - (         SERIAL)    100   20611       0  206.1%    0.0%      1404      0    573      46
09 - (       DISPATCH)    998       1       0    0.0%    0.0%         2      0   5723       0
10 - (BATTERY_VOLTAGE)     50       2       0    0.0%    0.0%         0      0    287       0
11 - (BATTERY_CURRENT)     50       1       0    0.0%    0.0%         0      0    287       0
12 - ( BATTERY_ALERTS)      5       2       0    0.0%    0.0%         0      0     29       1
13 - (         BEEPER)    100       3       0    0.0%    0.0%         0      0    573       1
14 - (            GPS)    100      31       1    0.3%    0.0%         4      1    574      24
15 - (        COMPASS)     10      25      15    0.0%    0.0%         6      0    168      25
16 - (           BARO)     40      27      17    0.1%    0.0%        26      0    690      26
18 - (       ALTITUDE)     40       5       2    0.0%    0.0%         1      0    230       3
20 - (      TELEMETRY)    499       1       0    0.0%    0.0%         2      0   2861       0
23 - (            OSD)     12      24      10    0.0%    0.0%        19      6   1515      23
25 - (            CMS)     20       2       0    0.0%    0.0%         0      0    115       1
26 - (        VTXCTRL)      5       1       0    0.0%    0.0%         0      0     29       1
27 - (        CAMCTRL)      5       1       0    0.0%    0.0%         0      0     29       0
29 - (    ADCINTERNAL)      1       2       0    0.0%    0.0%         0      0      6       1
30 - (       PINIOBOX)     20       1       0    0.0%    0.0%         0      0    115       0
31 - (SPEED_NEGOTIATION)    100       1       0    0.0%    0.0%         0      0    572       0
RX Check Function                   4       1                         3
Total (excluding SERIAL)                                16.0%

# tasks
Task list             rate/hz  max/us  avg/us maxload avgload  total/ms   late    run reqd/us
00 - (         SYSTEM)     10       1       0    0.0%    0.0%         0      0     28       1
01 - (         SYSTEM)    998       2       0    0.1%    0.0%       126      0   2791       1
02 - (           GYRO)   7987       2       0    1.5%    0.7%        90      0  22323       0
03 - (         FILTER)   7987       8       5    6.3%    4.5%       707      0  22323       0
04 - (            PID)   7987      19      14   15.1%   11.4%      1722      0  22323       0
05 - (            ACC)    998       2       0    0.1%    0.0%        12      0   2791       0
06 - (       ATTITUDE)    100       5       3    0.0%    0.0%         5      0    280       3
07 - (             RX)     10       8       5    0.0%    0.0%         2      0     84       6
08 - (         SERIAL)    100   22608       0  226.0%    0.0%      1426      0    280      11
09 - (       DISPATCH)    998       1       0    0.0%    0.0%         2      0   2791       0
10 - (BATTERY_VOLTAGE)     50       1       0    0.0%    0.0%         0      0    140       0
11 - (BATTERY_CURRENT)     50       1       0    0.0%    0.0%         0      0    140       0
12 - ( BATTERY_ALERTS)      5       1       0    0.0%    0.0%         0      0     14       1
13 - (         BEEPER)    100       2       0    0.0%    0.0%         0      0    279       1
14 - (            GPS)    100      22       1    0.2%    0.0%         5      0    280      24
15 - (        COMPASS)     10      27      15    0.0%    0.0%         7      0     84      26
16 - (           BARO)     40      27      17    0.1%    0.0%        31      0    338      27
18 - (       ALTITUDE)     40       5       2    0.0%    0.0%         1      0    112       4
20 - (      TELEMETRY)    499       1       0    0.0%    0.0%         2      0   1396       0
23 - (            OSD)     12      23       4    0.0%    0.0%        24      3    771      23
25 - (            CMS)     20       2       0    0.0%    0.0%         0      0     56       1
26 - (        VTXCTRL)      5       1       0    0.0%    0.0%         0      0     14       1
27 - (        CAMCTRL)      5       1       0    0.0%    0.0%         0      0     14       0
29 - (    ADCINTERNAL)      1       1       0    0.0%    0.0%         0      0      2       1
30 - (       PINIOBOX)     20       1       0    0.0%    0.0%         0      0     56       1
31 - (SPEED_NEGOTIATION)    100       1       0    0.0%    0.0%         0      0    279       0
RX Check Function                   4       1                         4
Total (excluding SERIAL)                                16.6%

# tasks
Task list             rate/hz  max/us  avg/us maxload avgload  total/ms   late    run reqd/us
00 - (         SYSTEM)     10       1       0    0.0%    0.0%         0      0     23       0
01 - (         SYSTEM)    998       2       0    0.1%    0.0%       128      0   2201       1
02 - (           GYRO)   7987       2       0    1.5%    0.7%       103      0  17605       0
03 - (         FILTER)   7987       8       5    6.3%    4.3%       805      0  17605       0
04 - (            PID)   7987      19      14   15.1%   11.3%      1973      0  17605       0
05 - (            ACC)    998       3       0    0.2%    0.0%        14      0   2201       0
06 - (       ATTITUDE)    100       4       3    0.0%    0.0%         6      0    221       3
07 - (             RX)     10       8       6    0.0%    0.0%         3      0     69       6
08 - (         SERIAL)    100   19610       0  196.1%    0.0%      1446      0    221      89
09 - (       DISPATCH)    998       1       0    0.0%    0.0%         3      0   2201       1
10 - (BATTERY_VOLTAGE)     50       2       0    0.0%    0.0%         0      0    111       1
11 - (BATTERY_CURRENT)     50       1       0    0.0%    0.0%         0      0    111       1
12 - ( BATTERY_ALERTS)      5       1       0    0.0%    0.0%         0      0     11       1
13 - (         BEEPER)    100       1       0    0.0%    0.0%         0      0    221       1
14 - (            GPS)    100      25       2    0.2%    0.0%         5      0    221      24
15 - (        COMPASS)     10      25      15    0.0%    0.0%         8      0     66      25
16 - (           BARO)     40      26      17    0.1%    0.0%        36      0    264      26
18 - (       ALTITUDE)     40       4       3    0.0%    0.0%         1      0     88       4
20 - (      TELEMETRY)    499       1       0    0.0%    0.0%         3      0   1101       0
23 - (            OSD)     12      24       4    0.0%    0.0%        27      6    602      24
25 - (            CMS)     20       1       0    0.0%    0.0%         0      0     45       1
26 - (        VTXCTRL)      5       1       0    0.0%    0.0%         0      0     11       0
27 - (        CAMCTRL)      5       1       0    0.0%    0.0%         0      0     11       0
29 - (    ADCINTERNAL)      1       1       0    0.0%    0.0%         0      0      3       1
30 - (       PINIOBOX)     20       2       0    0.0%    0.0%         0      0     45       1
31 - (SPEED_NEGOTIATION)    100       1       0    0.0%    0.0%         0      0    221       0
RX Check Function                   3       1                         5
Total (excluding SERIAL)                                16.3%

# tasks
Task list             rate/hz  max/us  avg/us maxload avgload  total/ms   late    run reqd/us
00 - (         SYSTEM)     10       1       0    0.0%    0.0%         0      0     19       0
01 - (         SYSTEM)    998       2       0    0.1%    0.0%       129      0   1974       0
02 - (           GYRO)   7987       6       0    4.7%    0.5%       115      0  15789       0
03 - (         FILTER)   7987       9       5    7.1%    4.3%       893      0  15789       0
04 - (            PID)   7987      19      14   15.1%   11.3%      2198      0  15789       0
05 - (            ACC)    998       2       1    0.1%    0.0%        16      0   1974       0
06 - (       ATTITUDE)    100       4       3    0.0%    0.0%         6      0    198       4
07 - (             RX)     10       8       6    0.0%    0.0%         3      0     57       8
08 - (         SERIAL)    100   16613       0  166.1%    0.0%      1463      0    198      84
09 - (       DISPATCH)    998       1       0    0.0%    0.0%         3      0   1974       0
10 - (BATTERY_VOLTAGE)     50       1       0    0.0%    0.0%         0      0     99       1
11 - (BATTERY_CURRENT)     50       1       0    0.0%    0.0%         0      0     99       1
12 - ( BATTERY_ALERTS)      5       1       0    0.0%    0.0%         0      0     10       1
13 - (         BEEPER)    100       1       0    0.0%    0.0%         0      0    198       1
14 - (            GPS)    100      31       1    0.3%    0.0%         6      1    198      30
15 - (        COMPASS)     10      25      15    0.0%    0.0%         9      0     57      25
16 - (           BARO)     40      26      17    0.1%    0.0%        40      0    237      27
18 - (       ALTITUDE)     40       4       3    0.0%    0.0%         2      0     79       3
20 - (      TELEMETRY)    499       1       0    0.0%    0.0%         3      0    986       0
23 - (            OSD)     12      23       6    0.0%    0.0%        30      0    512      23
25 - (            CMS)     20       1       0    0.0%    0.0%         0      0     39       1
26 - (        VTXCTRL)      5       1       0    0.0%    0.0%         0      0     10       0
27 - (        CAMCTRL)      5       1       0    0.0%    0.0%         0      0     10       0
29 - (    ADCINTERNAL)      1       1       0    0.0%    0.0%         0      0      2       1
30 - (       PINIOBOX)     20       3       0    0.0%    0.0%         0      0     39       2
31 - (SPEED_NEGOTIATION)    100       1       0    0.0%    0.0%         0      0    197       0
RX Check Function                   3       1                         6
Total (excluding SERIAL)                                16.1%

**Comment by McGiverGim** [comment]
As far as I know the gyro is thrown with a interrupt, so the "exact" time depends on the internal clock on the gyro/fc. 7987 seems a reasonable value and not too much different from 8K.

**Comment by wsnzone** [comment]
> As far as I know the gyro is thrown with a interrupt, so the "exact" time depends on the internal clock on the gyro/fc. 7987 seems a reasonable value and not too much different from 8K.

I really don't know how it works. Just I've wached JB's video about processor utilization and checked mine.

**Comment by haslinghuis** [comment]
```
# status
Devices detected: SPI:1, I2C:1
Gyros detected: gyro 1 locked dma
GYRO=MPU6000, ACC=MPU6000, BARO=BMP280
OSD: MAX7456
System Uptime: 11210 seconds, Current Time: 2022-04-07T17:52:27.598+00:00
CPU:8%, cycle time: 125, GYRO rate: 8000, RX rate: 15, System rate: 9

# tasks
Task list             rate/hz  max/us  avg/us maxload avgload  total/ms   late    run reqd/us
00 - (         SYSTEM)     10       2       0    0.0%    0.0%        24      0 112428       0
01 - (         SYSTEM)   1000       3       0    0.3%    0.0%      4094      1 11238072       1
02 - (           GYRO)   8006       3       0    2.4%    0.7%     68887      0 90054698       0
03 - (         FILTER)   8006       6       3    4.8%    2.6%    306812      0 90054698       0
04 - (            PID)   8006      11       6    8.8%    5.1%    564174      0 90054698       0
05 - (            ACC)    999       4       0    0.3%    0.0%     10184      0 11237864       1
06 - (       ATTITUDE)    100       6       3    0.0%    0.0%      3703      0 1124275       4
07 - (             RX)     10       9       4    0.0%    0.0%      1672      0 337281       5
08 - (         SERIAL)    100    7521       0   75.2%    0.0%      1945      0 1124244      40
09 - (       DISPATCH)    997       3       0    0.2%    0.0%      2422      0 11238121       0
10 - (BATTERY_VOLTAGE)     50       3       0    0.0%    0.0%       406      0 562139       1
11 - (BATTERY_CURRENT)     50       3       0    0.0%    0.0%       201      0 562139       0
12 - ( BATTERY_ALERTS)      5       3       0    0.0%    0.0%        36      0  56231       0
13 - (         BEEPER)    100       3       0    0.0%    0.0%       515      0 1124244       1
16 - (           BARO)     40      28      17    0.1%    0.0%     23460      0 1349106      26
18 - (       ALTITUDE)     40       6       3    0.0%    0.0%      1261      0 449708       3
20 - (      TELEMETRY)    250       3       0    0.0%    0.0%       653      0 2810631       0
23 - (            OSD)     12      24       9    0.0%    0.0%     10904      0 1868422      23
25 - (            CMS)     20       3       0    0.0%    0.0%       114      0 224855       1
26 - (        VTXCTRL)      5       3       0    0.0%    0.0%        17      0  56231       0
27 - (        CAMCTRL)      5       3       0    0.0%    0.0%        15      0  56231       0
29 - (    ADCINTERNAL)      1       3       0    0.0%    0.0%         7      0  11247       1
RX Check Function                   4       1                      2087
Total (excluding SERIAL)                                 8.4%
```

**Comment by wsnzone** [comment]
> Looks normal. Can you check if your gyro is "locked"? (Type "status" in the CLI).

`Entering CLI Mode, type 'exit' to return, or 'help'

# 
# Building AutoComplete Cache ... Done!
# 
# status
MCU H743 (Rev.V) Clock=480MHz, Vref=3.29V, Core temp=37degC
Stack size: 2048, Stack address: 0x2001fff8
Configuration: CONFIGURED, size: 4184, max available: 131072
Devices detected: SPI:1, I2C:2
Gyros detected: gyro 1 locked dma
GYRO=MPU6000, ACC=MPU6000, BARO=BMP280, MAG=QMC5883
OSD: MAX7456
System Uptime: 32 seconds, Current Time: 2022-04-08T07:39:01.606+00:00
CPU:18%, cycle time: 119, GYRO rate: 8403, RX rate: 15, System rate: 9
Voltage: 0 * 0.01V (0S battery - NOT PRESENT)
I2C Errors: 7
SD card: Manufacturer 0x0, 30534656kB, 04/2021, v0.0, 'APPSD'
Filesystem: Ready
Arming disable flags: RXLOSS CLI MSP RPMFILTER`

**Comment by KarateBrot** [comment]
Everything looks fine.
