### ISSUE TITLE
Failsafe time values showed 10x smaller in RC5 than in 10.7.2

### ISSUE THREAD

**Issue by LoakAudio** [betaflight/betaflight-configurator#2898]
### Describe the bug

On Failsafe tab, the 2 times of the Stage 2 parameters ("Wait for stage 2" and the next under ... Sorry my BF is in french) show 10x smaller than the same quad in BF configurator 10.7.2.

Inversely, a value setted in RC5 will be 10x bigger in RC5.

### To Reproduce

- Config the Failsafe tab for a quad with BF 4.2.11 in the 10.7.2 configurator
- Watch the values in the RC5 configurator.

### Expected behavior

Expetcted to have the same values

### Configurator version

RC5 - fa662d2

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```

**Comment by haslinghuis** [comment]
The unit in UI has changed. Please verify the cli parameter on both firmware versions. They should be equal.

**Comment by LoakAudio** [comment]
Ok, as the UI still says [1 = 0.1 sec] I was confused

**Comment by haslinghuis** [comment]
I guess the translations are not up to date yet.

4.3: 
![image](https://user-images.githubusercontent.com/8344830/163734632-603cc1dd-bd0b-4d9e-a3c5-089d6c04500c.png)

4.2: 
![image](https://user-images.githubusercontent.com/8344830/163734694-03e85bf6-7103-4ecb-9a97-bee275ac27c5.png)

**Comment by haslinghuis** [comment]
Fixed in #2900
