### ISSUE TITLE
cant open on macos

### ISSUE THREAD

**Issue by inkingkkkk** [betaflight/betaflight-configurator#2902]
### Describe the bug

the dmg file dosent work on mac it sayes it is risricted to run how can i run it

### To Reproduce

try downloading on the latest version of mac

### Expected behavior

dosent let u open it and the link is ristricted

### Configurator version

mac version

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```

**Comment by haslinghuis** [comment]
Please try https://www.cnet.com/tech/computing/how-to-install-unidentified-app-on-a-macbook/
