### ISSUE TITLE
Problems with spi fr

### ISSUE THREAD

**Issue by ALFJAVIVI** [betaflight/betaflight-configurator#2906]
### Describe the bug

With RC4, RC5 and RC6 RC problems with Spi Fr.
Rxloxx in Rc4 and RC5 at distances of 10 to 15m and with RC6 the distance is about 25m for an hour with which the RC works best is in RC3.
The FC is a crazybeex FR versions v1 and v2

### Expected behavior

Reparar ese error de RC 

### Configurator version

10.8 Rc5

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```

**Comment by haslinghuis** [comment]
Continue here: https://github.com/betaflight/betaflight/issues/11560
