### ISSUE TITLE
Betaflight shuts down\overloads MCU and memory MBP 2021 OS Monterey 12.2

### ISSUE THREAD

**Issue by Keksisky** [betaflight/betaflight-configurator#2910]
### Describe the bug

Hello, short description:
-MBP 2021, M1 Pro 10/16, 16GB/1TB
-macOS Monterey 12.2

1.Betaflight often randomly shuts down. Or the window os BF blinks Gray (whole window fills  by solid Gray color for a moment)
2.Betaflight takes about 185% of CPU (nwjs Helper process). Also it takes about 54GB (no mistake, fifty four gigs) of memory. So under this load MBP start freezing in OS, overheats, runs coolers and so on.
3.Betaflight may immideately shut down itself right after it was launched. (I added the system report of this issue below)

P.S. Suddenly shutting down of Betaflight was with me for 1.5 years on MBP 13" 2015. But there was no overloads CPU and overheating of it. 

### To Reproduce

Just run Betaflight on MBP + Monterey 12.2

### Expected behavior

Stable work 🧐

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```
```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `resource show all`
```

### Flight controller

Any one, it doesn't matter

### Add any other context about the problem that you think might be relevant here

This is a "system report" which I've got after Betaflight shutter down right after it was launched. (3rd pt from my description) "nwjs" process:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               nwjs [24917]
Path:                  /Applications/Betaflight Configurator.app/Contents/MacOS/nwjs
Identifier:            com.nw-builder.betaflight-configurator
Version:               Version 10.7.2 (10.7.2)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-04-28 19:37:08.6222 +0300
OS Version:            macOS 12.2 (21D49)
Report Version:        12
Anonymous UUID:        6AB558B2-AE49-AADB-B118-4C0E0CB6DC2C

Sleep/Wake UUID:       CD9A291F-D5E0-4D37-A660-4268B506B080

Time Awake Since Boot: 230000 seconds
Time Since Wake:       2302 seconds

System Integrity Protection: enabled

Crashed Thread:        2  StackSamplingProfiler

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [24917]

VM Region Info: 0 is not in any region.  Bytes before following region: 4331753472
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      102315000-102381000    [  432K] r-x/rwx SM=COW  ...ts/MacOS/nwjs

Thread 0::  Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	    0x7ff81a907e66 objc_autorelease + 38
1   libdispatch.dylib             	    0x7ff81a8b4cc9 _dispatch_client_callout + 8
2   libdispatch.dylib             	    0x7ff81a8b5ec1 _dispatch_once_callout + 20
3   AppKit                        	    0x7ff81d9f99db NSColorMainBundleCustomAccentColor + 42
4   AppKit                        	    0x7ff81d45351f _UpdateSystemAppearancesWithAccentColor + 67
5   AppKit                        	    0x7ff81d452211 +[NSAppearance _darkAquaAppearance] + 369
6   AppKit                        	    0x7ff81d451e47 +[NSAppearance appearanceNamed:] + 21
7   AppKit                        	    0x7ff81d451aba _NSAppearanceCurrentSystemAppearance + 178
8   AppKit                        	    0x7ff81d451860 -[NSSystemAppearanceProxy init] + 81
9   AppKit                        	    0x7ff81d451806 __38+[NSSystemAppearanceProxy systemProxy]_block_invoke + 16
10  libdispatch.dylib             	    0x7ff81a8b4cc9 _dispatch_client_callout + 8
11  libdispatch.dylib             	    0x7ff81a8b5ec1 _dispatch_once_callout + 20
12  AppKit                        	    0x7ff81d4517f4 +[NSSystemAppearanceProxy systemProxy] + 42
13  AppKit                        	    0x7ff81d4517a0 -[NSApplication(NSApplicationAppearance_Internal) _registerForAppearanceNotifications] + 34
14  AppKit                        	    0x7ff81d44f37e -[NSApplication init] + 596
15  AppKit                        	    0x7ff81d44ef0d +[NSApplication sharedApplication] + 120
16  nwjs Framework                	       0x118b112a6 0x115569000 + 56263334
17  nwjs Framework                	       0x118b111a6 0x115569000 + 56263078
18  nwjs Framework                	       0x11556f219 0x115569000 + 25113
19  nwjs Framework                	       0x1188e8634 0x115569000 + 53999156
20  nwjs Framework                	       0x1188e8569 0x115569000 + 53998953
21  nwjs Framework                	       0x11bb886ac 0x115569000 + 107083436
22  nwjs Framework                	       0x1188e7768 0x115569000 + 53995368
23  nwjs Framework                	       0x11556c687 ChromeMain + 279
24  nwjs                          	       0x102316384 main + 372
25  dyld                          	       0x2025f94fe start + 462

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffc6f8e4 0x7ff7ffc6b000 + 18660
1   runtime                       	    0x7ff7ffc7c928 0x7ff7ffc6b000 + 71976
2   runtime                       	    0x7ff7ffc7e0a4 0x7ff7ffc6b000 + 77988

Thread 2 Crashed:: StackSamplingProfiler
0   libunwind.dylib               	    0x7ff825b8dca0 libunwind::CFI_Parser<libunwind::LocalAddressSpace>::decodeFDE(libunwind::LocalAddressSpace&, unsigned long, libunwind::CFI_Parser<libunwind::LocalAddressSpace>::FDE_Info*, libunwind::CFI_Parser<libunwind::LocalAddressSpace>::CIE_Info*) + 30
1   libunwind.dylib               	    0x7ff825b8fef2 libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step() + 114
2   libunwind.dylib               	    0x7ff825b8fef2 libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step() + 114
3   nwjs Framework                	       0x1190bcd99 0x115569000 + 62209433
4   nwjs Framework                	       0x11901459d 0x115569000 + 61519261
5   nwjs Framework                	       0x119014489 0x115569000 + 61518985
6   nwjs Framework                	       0x1190158a6 0x115569000 + 61524134
7   nwjs Framework                	       0x1190370cb 0x115569000 + 61661387
8   nwjs Framework                	       0x11904af2e 0x115569000 + 61742894
9   nwjs Framework                	       0x11904acc1 0x115569000 + 61742273
10  nwjs Framework                	       0x118febf17 0x115569000 + 61353751
11  nwjs Framework                	       0x11904b7b8 0x115569000 + 61745080
12  nwjs Framework                	       0x1190171a9 0x115569000 + 61530537
13  nwjs Framework                	       0x1190689ca 0x115569000 + 61864394
14  nwjs Framework                	       0x1190ad9b7 0x115569000 + 62146999
15  libsystem_pthread.dylib       	    0x7ff81aa6e4f4 _pthread_start + 125
16  libsystem_pthread.dylib       	    0x7ff81aa6a00f thread_start + 15

Thread 3:
0   runtime                       	    0x7ff7ffc8d814 0x7ff7ffc6b000 + 141332

Thread 4:
0   runtime                       	    0x7ff7ffc8d814 0x7ff7ffc6b000 + 141332

Thread 5:
0   ???                           	    0x7ff8aaffe940 ???
1   libsystem_kernel.dylib        	    0x7ff81aa31aba mach_msg_trap + 10
2   nwjs Framework                	       0x11a65199e 0x115569000 + 84838814
3   nwjs Framework                	       0x11a651ea9 0x115569000 + 84840105
4   nwjs Framework                	       0x11a648148 0x115569000 + 84799816
5   libsystem_pthread.dylib       	    0x7ff81aa6e4f4 _pthread_start + 125
6   libsystem_pthread.dylib       	    0x7ff81aa6a00f thread_start + 15

Thread 6:
0   runtime                       	    0x7ff7ffc8d814 0x7ff7ffc6b000 + 141332

Thread 2 crashed with X86 Thread State (64-bit):
  rax: 0x00007ff81a7ace18  rbx: 0x0000000000000010  rcx: 0x00007ff825b8fc06  rdx: 0x0000000309240058
  rdi: 0x0000000000000000  rsi: 0x0000000309240028  rbp: 0x000000030923edf0  rsp: 0x000000030923eda0
   r8: 0x0000000000000000   r9: 0x00007ff81a7d9ba0  r10: 0x00007ff81a7d9ba8  r11: 0x00007ff81a7d9b85
  r12: 0x0000000309240028  r13: 0x0000000000000000  r14: 0x0000000309240058  r15: 0x0000000000000000
  rip: 0x00007ff825b8dca0  rfl: 0x0000000000000202
 tmp0: 0x00007ff825b8fed5 tmp1: 0x00007ff825b8fed5 tmp2: 0x00007ff825b8fef2

Binary Images:
    0x7ff81a8f9000 -     0x7ff81a935fff libobjc.A.dylib (*) <900beeed-7528-3b89-86fd-01cad4027a9c> /usr/lib/libobjc.A.dylib
    0x7ff81a8b2000 -     0x7ff81a8f8fff libdispatch.dylib (*) <67d92c93-aa68-34c2-964b-23e8a8d32098> /usr/lib/system/libdispatch.dylib
    0x7ff81d44a000 -     0x7ff81e2dbfff com.apple.AppKit (6.9) <a737ebe6-3a9c-32f3-b975-5ce0ef6313e4> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x115569000 -        0x11f5acfff io.nwjs.nwjs.framework (80.0.3987.116) <4e534edc-9d2e-35de-ac45-1741bc7e4302> /Applications/Betaflight Configurator.app/Contents/Frameworks/nwjs Framework.framework/Versions/80.0.3987.116/nwjs Framework
       0x102315000 -        0x102380fff com.nw-builder.betaflight-configurator (Version 10.7.2) <757802d8-a86d-31ab-9ed6-3a951ca13cf6> /Applications/Betaflight Configurator.app/Contents/MacOS/nwjs
       0x2025f4000 -        0x20265ffff dyld (*) <7de33963-bbc5-3996-ba6e-f1d562c17c95> /usr/lib/dyld
    0x7ff7ffc6b000 -     0x7ff7ffc9afff runtime (*) <faca02c7-0a4c-3629-a746-55ddcfee9116> /usr/libexec/rosetta/runtime
    0x7ff825b88000 -     0x7ff825b92fff libunwind.dylib (*) <fe239a11-c2cf-3930-9f3f-b99bd0e54095> /usr/lib/system/libunwind.dylib
    0x7ff81aa68000 -     0x7ff81aa73fff libsystem_pthread.dylib (*) <ee564342-d8f2-396d-b642-40092cf34d82> /usr/lib/system/libsystem_pthread.dylib
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
    0x7ff81aa31000 -     0x7ff81aa67fff libsystem_kernel.dylib (*) <c1d58a50-5a4d-3bcb-a1fc-ec0902ce34d3> /usr/lib/system/libsystem_kernel.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.3G resident=0K(0%) swapped_out_or_unallocated=1.3G(100%)
Writable regions: Total=679.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=679.3M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
ColorSync                            4K        1 
Dispatch continuations            80.0M        1 
Kernel Alloc Once                    8K        1 
MALLOC                            79.1M       24 
MALLOC guard page                   96K        4 
MALLOC_MEDIUM (reserved)         352.0M        3         reserved VM address space (unallocated)
Mach message (reserved)              4K        1         reserved VM address space (unallocated)
Rosetta Arena                     4096K        2 
Rosetta Generic                    876K      216 
Rosetta IndirectBranch             128K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack               120K       12 
Rosetta Thread Context             120K       12 
STACK GUARD                         12K        3 
Stack                             18.0M        6 
Stack Guard                       56.0M        3 
VM_ALLOCATE                       7492K        6 
VM_ALLOCATE (reserved)               4K        1         reserved VM address space (unallocated)
__DATA                            39.5M      496 
__DATA_CONST                      29.3M      320 
__DATA_DIRTY                      1605K      209 
__FONT_DATA                          4K        1 
__LINKEDIT                       703.6M       14 
__OBJC_RO                         81.8M        1 
__OBJC_RW                         3136K        2 
__TEXT                           640.2M      514 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
mapped file                        5.0G      658 
shared memory                      800K       12 
unshared pmap                     6032K        4 
===========                     =======  ======= 
TOTAL                              7.2G     2532 
TOTAL, minus reserved VM space     6.8G     2532 

-----------
Full Report
-----------

{"app_name":"nwjs","timestamp":"2022-04-28 19:37:09.00 +0300","app_version":"Version 10.7.2","slice_uuid":"757802d8-a86d-31ab-9ed6-3a951ca13cf6","build_version":"10.7.2","platform":1,"bundleID":"com.nw-builder.betaflight-configurator","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.2 (21D49)","incident_id":"A0386043-4C1C-4778-B3D7-249FF2A3B202","name":"nwjs"}
{
  "uptime" : 230000,
  "procLaunch" : "2022-04-28 19:37:08.3640 +0300",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,1",
  "procStartAbsTime" : 5736866074607,
  "coalitionID" : 16890,
  "osVersion" : {
    "train" : "macOS 12.2",
    "build" : "21D49",
    "releaseType" : "User"
  },
  "captureTime" : "2022-04-28 19:37:08.6222 +0300",
  "incident" : "A0386043-4C1C-4778-B3D7-249FF2A3B202",
  "bug_type" : "309",
  "pid" : 24917,
  "procExitAbsTime" : 5736872143386,
  "translated" : true,
  "cpuType" : "X86-64",
  "procName" : "nwjs",
  "procPath" : "\/Applications\/Betaflight Configurator.app\/Contents\/MacOS\/nwjs",
  "bundleInfo" : {"CFBundleShortVersionString":"Version 10.7.2","CFBundleVersion":"10.7.2","CFBundleIdentifier":"com.nw-builder.betaflight-configurator"},
  "storeInfo" : {"deviceIdentifierForVendor":"8C925414-FDE1-5965-9A19-A84C425E5F77","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.nw-builder.betaflight-configurator",
  "crashReporterKey" : "6AB558B2-AE49-AADB-B118-4C0E0CB6DC2C",
  "wakeTime" : 2302,
  "sleepWakeUUID" : "CD9A291F-D5E0-4D37-A660-4268B506B080",
  "sip" : "enabled",
  "vmRegionInfo" : "0 is not in any region.  Bytes before following region: 4331753472\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      102315000-102381000    [  432K] r-x\/rwx SM=COW  ...ts\/MacOS\/nwjs",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000000","rawCodes":[1,0],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000000"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":24917},
  "vmregioninfo" : "0 is not in any region.  Bytes before following region: 4331753472\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      102315000-102381000    [  432K] r-x\/rwx SM=COW  ...ts\/MacOS\/nwjs",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 2,
  "threads" : [{"id":1802749,"queue":"com.apple.main-thread","frames":[{"imageOffset":61030,"symbol":"objc_autorelease","symbolLocation":38,"imageIndex":0},{"imageOffset":11465,"symbol":"_dispatch_client_callout","symbolLocation":8,"imageIndex":1},{"imageOffset":16065,"symbol":"_dispatch_once_callout","symbolLocation":20,"imageIndex":1},{"imageOffset":5962203,"symbol":"NSColorMainBundleCustomAccentColor","symbolLocation":42,"imageIndex":2},{"imageOffset":38175,"symbol":"_UpdateSystemAppearancesWithAccentColor","symbolLocation":67,"imageIndex":2},{"imageOffset":33297,"symbol":"+[NSAppearance _darkAquaAppearance]","symbolLocation":369,"imageIndex":2},{"imageOffset":32327,"symbol":"+[NSAppearance appearanceNamed:]","symbolLocation":21,"imageIndex":2},{"imageOffset":31418,"symbol":"_NSAppearanceCurrentSystemAppearance","symbolLocation":178,"imageIndex":2},{"imageOffset":30816,"symbol":"-[NSSystemAppearanceProxy init]","symbolLocation":81,"imageIndex":2},{"imageOffset":30726,"symbol":"__38+[NSSystemAppearanceProxy systemProxy]_block_invoke","symbolLocation":16,"imageIndex":2},{"imageOffset":11465,"symbol":"_dispatch_client_callout","symbolLocation":8,"imageIndex":1},{"imageOffset":16065,"symbol":"_dispatch_once_callout","symbolLocation":20,"imageIndex":1},{"imageOffset":30708,"symbol":"+[NSSystemAppearanceProxy systemProxy]","symbolLocation":42,"imageIndex":2},{"imageOffset":30624,"symbol":"-[NSApplication(NSApplicationAppearance_Internal) _registerForAppearanceNotifications]","symbolLocation":34,"imageIndex":2},{"imageOffset":21374,"symbol":"-[NSApplication init]","symbolLocation":596,"imageIndex":2},{"imageOffset":20237,"symbol":"+[NSApplication sharedApplication]","symbolLocation":120,"imageIndex":2},{"imageOffset":56263334,"imageIndex":3},{"imageOffset":56263078,"imageIndex":3},{"imageOffset":25113,"imageIndex":3},{"imageOffset":53999156,"imageIndex":3},{"imageOffset":53998953,"imageIndex":3},{"imageOffset":107083436,"imageIndex":3},{"imageOffset":53995368,"imageIndex":3},{"imageOffset":13959,"symbol":"ChromeMain","symbolLocation":279,"imageIndex":3},{"imageOffset":4996,"symbol":"main","symbolLocation":372,"imageIndex":4},{"imageOffset":21758,"symbol":"start","symbolLocation":462,"imageIndex":5}]},{"id":1802770,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18660,"imageIndex":6},{"imageOffset":71976,"imageIndex":6},{"imageOffset":77988,"imageIndex":6}]},{"triggered":true,"id":1802777,"name":"StackSamplingProfiler","threadState":{"r13":{"value":0},"rflags":{"value":514},"rax":{"value":140703572872728,"symbolLocation":0,"symbol":"xpc_null_create"},"rosetta":{"tmp2":{"value":140703761497842},"tmp1":{"value":140703761497813},"tmp0":{"value":140703761497813}},"r14":{"value":13038256216},"rsi":{"value":13038256168},"r8":{"value":0},"rdx":{"value":13038256216},"r10":{"value":140703573056424},"r9":{"value":140703573056416},"r15":{"value":0},"rbx":{"value":16},"r11":{"value":140703573056389},"rip":{"value":140703761489056},"rbp":{"value":13038251504},"rsp":{"value":13038251424},"r12":{"value":13038256168},"rcx":{"value":140703761497094,"symbolLocation":40,"symbol":"libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::getReg(int)"},"flavor":"x86_THREAD_STATE","rdi":{"value":0}},"frames":[{"imageOffset":23712,"symbol":"libunwind::CFI_Parser<libunwind::LocalAddressSpace>::decodeFDE(libunwind::LocalAddressSpace&, unsigned long, libunwind::CFI_Parser<libunwind::LocalAddressSpace>::FDE_Info*, libunwind::CFI_Parser<libunwind::LocalAddressSpace>::CIE_Info*)","symbolLocation":30,"imageIndex":7},{"imageOffset":32498,"symbol":"libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step()","symbolLocation":114,"imageIndex":7},{"imageOffset":32498,"symbol":"libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step()","symbolLocation":114,"imageIndex":7},{"imageOffset":62209433,"imageIndex":3},{"imageOffset":61519261,"imageIndex":3},{"imageOffset":61518985,"imageIndex":3},{"imageOffset":61524134,"imageIndex":3},{"imageOffset":61661387,"imageIndex":3},{"imageOffset":61742894,"imageIndex":3},{"imageOffset":61742273,"imageIndex":3},{"imageOffset":61353751,"imageIndex":3},{"imageOffset":61745080,"imageIndex":3},{"imageOffset":61530537,"imageIndex":3},{"imageOffset":61864394,"imageIndex":3},{"imageOffset":62146999,"imageIndex":3},{"imageOffset":25844,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":8},{"imageOffset":8207,"symbol":"thread_start","symbolLocation":15,"imageIndex":8}]},{"id":1802778,"frames":[{"imageOffset":141332,"imageIndex":6}]},{"id":1802779,"frames":[{"imageOffset":141332,"imageIndex":6}]},{"id":1802797,"frames":[{"imageOffset":140705997515072,"imageIndex":9},{"imageOffset":2746,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":10},{"imageOffset":84838814,"imageIndex":3},{"imageOffset":84840105,"imageIndex":3},{"imageOffset":84799816,"imageIndex":3},{"imageOffset":25844,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":8},{"imageOffset":8207,"symbol":"thread_start","symbolLocation":15,"imageIndex":8}]},{"id":1802806,"frames":[{"imageOffset":141332,"imageIndex":6}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703574233088,
    "size" : 249856,
    "uuid" : "900beeed-7528-3b89-86fd-01cad4027a9c",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703573942272,
    "size" : 290816,
    "uuid" : "67d92c93-aa68-34c2-964b-23e8a8d32098",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703619653632,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15278080,
    "uuid" : "a737ebe6-3a9c-32f3-b975-5ce0ef6313e4",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.30.116"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4652961792,
    "CFBundleShortVersionString" : "80.0.3987.116",
    "CFBundleIdentifier" : "io.nwjs.nwjs.framework",
    "size" : 168050688,
    "uuid" : "4e534edc-9d2e-35de-ac45-1741bc7e4302",
    "path" : "\/Applications\/Betaflight Configurator.app\/Contents\/Frameworks\/nwjs Framework.framework\/Versions\/80.0.3987.116\/nwjs Framework",
    "name" : "nwjs Framework",
    "CFBundleVersion" : "3987.116"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4331753472,
    "CFBundleShortVersionString" : "Version 10.7.2",
    "CFBundleIdentifier" : "com.nw-builder.betaflight-configurator",
    "size" : 442368,
    "uuid" : "757802d8-a86d-31ab-9ed6-3a951ca13cf6",
    "path" : "\/Applications\/Betaflight Configurator.app\/Contents\/MacOS\/nwjs",
    "name" : "nwjs",
    "CFBundleVersion" : "10.7.2"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8629731328,
    "size" : 442368,
    "uuid" : "7de33963-bbc5-3996-ba6e-f1d562c17c95",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703124860928,
    "size" : 196608,
    "uuid" : "faca02c7-0a4c-3629-a746-55ddcfee9116",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703761465344,
    "size" : 45056,
    "uuid" : "fe239a11-c2cf-3930-9f3f-b99bd0e54095",
    "path" : "\/usr\/lib\/system\/libunwind.dylib",
    "name" : "libunwind.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703575736320,
    "size" : 49152,
    "uuid" : "ee564342-d8f2-396d-b642-40092cf34d82",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703575511040,
    "size" : 225280,
    "uuid" : "c1d58a50-5a4d-3bcb-a1fc-ec0902ce34d3",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  }
],
  "sharedCache" : {
  "base" : 140703572492288,
  "size" : 15218196480,
  "uuid" : "13fe38d9-95ad-3d4f-889f-443cd57d94de"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.3G resident=0K(0%) swapped_out_or_unallocated=1.3G(100%)\nWritable regions: Total=679.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=679.3M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nColorSync                            4K        1 \nDispatch continuations            80.0M        1 \nKernel Alloc Once                    8K        1 \nMALLOC                            79.1M       24 \nMALLOC guard page                   96K        4 \nMALLOC_MEDIUM (reserved)         352.0M        3         reserved VM address space (unallocated)\nMach message (reserved)              4K        1         reserved VM address space (unallocated)\nRosetta Arena                     4096K        2 \nRosetta Generic                    876K      216 \nRosetta IndirectBranch             128K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack               120K       12 \nRosetta Thread Context             120K       12 \nSTACK GUARD                         12K        3 \nStack                             18.0M        6 \nStack Guard                       56.0M        3 \nVM_ALLOCATE                       7492K        6 \nVM_ALLOCATE (reserved)               4K        1         reserved VM address space (unallocated)\n__DATA                            39.5M      496 \n__DATA_CONST                      29.3M      320 \n__DATA_DIRTY                      1605K      209 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       703.6M       14 \n__OBJC_RO                         81.8M        1 \n__OBJC_RW                         3136K        2 \n__TEXT                           640.2M      514 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nmapped file                        5.0G      658 \nshared memory                      800K       12 \nunshared pmap                     6032K        4 \n===========                     =======  ======= \nTOTAL                              7.2G     2532 \nTOTAL, minus reserved VM space     6.8G     2532 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "name" : "StackSamplingProfiler"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "61fb0e87c773c43cde3bb80e"
      },
      "deploymentId" : 240000305
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "622657ce37186c771d5404ad"
      },
      "deploymentId" : 240000412
    },
    {
      "rolloutId" : "60356660bbe37970735c5624",
      "factorPackIds" : {

      },
      "deploymentId" : 240000027
    },
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000015
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000136
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000355
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,1, BootROM 7429.81.3, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5
AirPort: Wi-Fi, wl0: Dec 13 2021 17:12:34 version 20.10.853.31.8.7.109 FWID 01-804e92d8
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by haslinghuis** [comment]
@Keksisky please test with https://github.com/betaflight/betaflight-configurator/pull/2913#issuecomment-1115557255

**Comment by haslinghuis** [comment]
Please test with build here: https://github.com/betaflight/betaflight-configurator/actions/runs/2261547416
