### ISSUE TITLE
Emergency motor stop

### ISSUE THREAD

**Issue by JimB40** [betaflight/betaflight-configurator#2918]
### Is your feature request related to a problem? Please describe

No quick and safe way to stop motors once testing in Motor tab

### Describe the solution you'd like

![stopmotors](https://user-images.githubusercontent.com/46420768/167371080-2510f801-8e0d-4265-a010-d9c4fdcf50a3.png)

### Describe alternatives you've considered

As discussed in discord with @limonspb.
Big, easily clickable button plus shorcut to biggest keyboard key which is Space Bar
Palced in UI so it cannot be hidden while window is resized

**Comment by limonspb** [comment]
I think the button should be close to the motor sliders. For example check android version:
![Screenshot_2022-05-09-11-02-00-598_com betaflight betaflight_configurator_debug](https://user-images.githubusercontent.com/2925027/167455196-fea6f128-6726-4115-b5c6-bb51f6328941.jpg)

**Comment by haslinghuis** [comment]
@JimB40 please check #2921 - no need for UI changes here - added spacebar handler. Just needs documentation and mentioning  in youtube guides.

**Comment by haslinghuis** [comment]
@JimB40 check again. Added a simple button.
