### ISSUE TITLE
Google Play Store APK distribution

### ISSUE THREAD

**Issue by howels** [betaflight/betaflight-configurator#2919]
### Is your feature request related to a problem? Please describe

Has the team considered adding Betaflight Configurator into the Android Play Store?

Chromebooks cannot access the latest configurator since the web app was deprecated, but they can run Android apps. 

However, to load APKs outside the play store, a Chromebook must be wiped and set to "developer mode" which is less secure, and something that many users would not want to do. Adding the APK to the Play store enables everyone to access it, and it could allow easy installation and easy updates too.

### Describe the solution you'd like

Please register BetaFlight Configurator as an app on the Google Play store.

### Describe alternatives you've considered

Side-loading can be used, but typically requires changing security settings and on chromebooks this requires wiping the device completely before side-loading APKs is possible.

**Comment by haslinghuis** [comment]
See: https://github.com/betaflight/betaflight-configurator/pull/2577
