### ISSUE TITLE
feature request: Show known issues with H/W or S/W somewhere in UI

### ISSUE THREAD

**Issue by rodgerramjet** [betaflight/betaflight-configurator#293]
Was just thinking it would save everyone (you guys included) a with common problems & known issues somewhere in the UI.

This could be key bugs (or limitations) in a particular version of BF firmware (once connected to quad), or a hardware issue (e.g. gyros that are sensitive and need soft mounting, or receivers that have some known issues depending on the board/etc), or min_throttle suspiciously low, etc

Would be great if it integrated with github's issue system to pull out any bugs (open or fixed in later version) - but that might mean ensuring they are correctly classified in github if the aren't currently.

I guess this would be beneficial to CF and BF so not sure this is the best place for the suggestion?

**Comment by KiteAnton** [comment]
Are you referring to a wiki? https://github.com/betaflight/betaflight/wiki
