### ISSUE TITLE
The license in Betaflight Configurator appears as propietary

### ISSUE THREAD

**Issue by McGiverGim** [betaflight/betaflight-configurator#2935]
### Describe the bug

When looking at the package in Ubuntu, it is seen as propietary:

![image](https://user-images.githubusercontent.com/2673520/169962030-2812a428-c819-4720-9972-c2a7ad2b2b48.png)

### To Reproduce

Open the deb package with the software installer.

### Expected behavior

Appear GPL as license, not propietary.

### Configurator version

Not important

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```

**Comment by haslinghuis** [comment]
Do we need op copyrights file?
https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

**Comment by haslinghuis** [comment]
Do we need a copyrights file?
https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

**Comment by McGiverGim** [comment]
In theory is added, and I've seen others with the same problem in internet, but I've not found a workaround. I've opened the issue to see if someone with more knowledge in Linux finds something.

**Comment by haslinghuis** [comment]
Now we are moving to PWA this would no longer be necessary
