### ISSUE TITLE
Massive problems in the firmware flasher tab

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/betaflight-configurator#2938]
### Describe the bug

Since yesterday's merge, I've had massive problems with the Flasher tab. when I go to flashing this image appears (see screenshot). After switching through the tabs and restarting several times, it seems to work again. but only once, after a restart the flasher tab is defective again.

here the screenshot and console output:
![flasher_tab](https://user-images.githubusercontent.com/29702171/170856501-f0d09077-65e4-4260-9de4-85cc4c7425d2.png)
![console_output](https://user-images.githubusercontent.com/29702171/170856567-3190a640-0a4f-4624-9681-2098e6bb349e.png)

### To Reproduce

Using latest master on Windows 10 and going to Firmware flasher Tab.

### Expected behavior

working flashing tab :(

### Configurator version

10.8.0-debug-10645cb7

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```

**Comment by haslinghuis** [comment]
Thanks for reporting. Please test https://github.com/betaflight/betaflight-configurator/pull/2937.
Will look into this today.

**Comment by TheIsotopes** [comment]
> Please test https://github.com/betaflight/betaflight-configurator/pull/2937

Nope, unfortunately not.

The sledgehammer method of deleting the `C:\Users\xyz\AppData\Local\betaflight-configurator` folder is still the fastest and easiest way.

**Comment by haslinghuis** [comment]
@TheIsotopes. Updated a new version.

Quota has been exceeded. Have moved firmware flasher storage to session storage.

**Comment by TheIsotopes** [comment]
Yes, everything is working as it should now!!

Thx @haslinghuis 👍
