### ISSUE TITLE
feature request: PID and Filter calculation helpers

### ISSUE THREAD

**Issue by rodgerramjet** [betaflight/betaflight-configurator#294]
This might have been suggested before (or something similar)

I was thinking about a UI where you specified key parameters like FC, frame, battery, motors, etc and the page would recommend (or apply) PIDs/ filters for your setup.

Possibly using some kind of formula (e.g. we know a small frame with high KV motors will probably need lower pids). So you'd start with the betaflight defaults and based on your setup it would adjust the pids by a % with each variable potentially affecting the PIDs differently

Possibly centralizing them in a DB allowing user's to submit their PIDs and setups - and then learning from that.

Possibly automatically create a new profile e.g have current PIDs on profile 1 and create updated PIDs on profile 2 which you could switch to using stick commands & easily compare?

I think kiss has something similar but its pretty basic and just involves sharing them (which doesn't really make sense to me as you need the context of most of the gear)

I know nothing would be perfect - so this would just be for those who didn't want to tune the quad properly. It would also potentially allow more aggressive default PIDS in BF?

Maybe this needs to be its own website outside of configurator but obviously the configurator does have a lot of the info it needs.

**Comment by haslinghuis** [comment]
New presets are coming for configuration
