### ISSUE TITLE
10.8.0(5ec9465) Can't find my serial port, which is definitely exist.

### ISSUE THREAD

**Issue by lida2003** [betaflight/betaflight-configurator#2949]
### Describe the bug

10.8.0(5ec9465) Can't find my serial port, which is definitely exist and ok with previous 10.7.2(without pc reboot).

### To Reproduce

1) launch 10.8.0(5ec9465) 
2) plug fc serial port
3) I didn't see serial port in drop down list
4) windows manager show COM5 existed and OK

### Expected behavior

just same as 10.7.2 did, can  auto detect my fc serial port.

### Configurator version

10.8.0(5ec9465)

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```
I' think it not relevant to FC.

### Add any other context about the problem that you think might be relevant here

do I need reboot pc when upgrade the configurator?

**Comment by lida2003** [comment]
Reboot PC can't help. Fallback to 10.7.2, It's OK.

**Comment by haslinghuis** [comment]
Please show screenshot of (windows-R) devmgmt.msc in Windows - Ports (COM & LPT) when FC is attached

**Comment by lida2003** [comment]
![图片](https://user-images.githubusercontent.com/1296171/173718648-10ea9f5b-29cf-4b9e-bf0f-2157fb33fa60.png)
![图片](https://user-images.githubusercontent.com/1296171/173718930-9e00079b-519a-4301-b71c-ccfeea4ecb53.png)
![图片](https://user-images.githubusercontent.com/1296171/173719149-e79c77f8-d7fb-4669-86c2-0768f0cfa472.png)

**Comment by haslinghuis** [comment]
Two options to try:

Enable show all serial devices (option tab while disconnected):
![Screenshot from 2022-06-15 03-55-07](https://user-images.githubusercontent.com/8344830/173719809-679c319e-910a-40ae-80e1-8bc0a104071b.png)

Revert to english (welcome page while disconnected):
![Screenshot from 2022-06-15 03-58-04](https://user-images.githubusercontent.com/8344830/173720068-8ec373f4-7152-4eff-b04f-7e6b81d535cb.png)

**Comment by lida2003** [comment]
Configurator is using english as default.
![图片](https://user-images.githubusercontent.com/1296171/173721031-315320bc-a630-4609-bb43-902323925f73.png)

**Comment by haslinghuis** [comment]
Please try a nightly build so we can look at dev console using F12 when you plug in we should see something happening:
https://github.com/betaflight/betaflight-configurator/pull/2945#issuecomment-1148711357

**Comment by lida2003** [comment]
Seems work for me!  10.9.0-debug-c67360c
![图片](https://user-images.githubusercontent.com/1296171/173731917-2975657f-7fa3-48fa-a765-a4964cd03da2.png)
