### ISSUE TITLE
download links doesn't work

### ISSUE THREAD

**Issue by S-T-A** [betaflight/betaflight-configurator#2957]
### Describe the bug

when i go over the link to try and download it. it's grayed out and there is no link to download.

### To Reproduce

tried diffrent web browsers to no avail i'm on a mac OSX i even updated my lap top same thing is there something im missing
 

### Expected behavior

i thought it would download right away.:(

### Configurator version

beta flight  10.8.0

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```

**Comment by haslinghuis** [comment]
Can you describe the link (picture please) you are trying to access?

**Comment by S-T-A** [comment]
[](url
![Screen Shot 2022-06-23 at 8 37 13 PM](https://user-images.githubusercontent.com/19362591/175437429-fe149f6a-4fb5-4fa1-a1ee-6f217fa999e7.png)
)
i'm tring to downloasd the Mac osx version but non of them highlight as they normally would.

**Comment by haslinghuis** [comment]
Please scroll down and you find: https://github.com/betaflight/betaflight-configurator/releases/download/10.8.0/betaflight-configurator_10.8.0_macOS.dmg

**Comment by S-T-A** [comment]
Thank you sir you rock!!!!!
