### ISSUE TITLE
Fails to load remote config for any board.

### ISSUE THREAD

**Issue by Scout339** [betaflight/betaflight-configurator#2966]
### Describe the bug

`2022-06-29 @17:03:41 -- Failed to load remote config for https://raw.githubusercontent.com/betaflight/unified-targets/master/configs/default/FLWO-FLYWOOF7DUAL.config`

### To Reproduce

go to firmware flasher and select any board, it will say "Loading..." infinitely in the firmware selection dropdown.

### Expected behavior

supposed to load remote config for updating firmware...

### Configurator version

10.8.0

### Flight controller configuration

```
  # REPLACE THIS LINE BY THE OUTPUT OF YOUR `diff`
```

**Comment by haslinghuis** [comment]
Checking... Still working.
Please restart configurator and check you internet connection.

**Comment by Scout339** [comment]
Restarted PC, going to try it right now. Maybe ill try it on my phone as well to see if it gets the same issue

**Comment by Scout339** [comment]
I can't say why, but on the same network with a different system (my laptop) there are no issues.

**Comment by haslinghuis** [comment]
Curious what's going on but closing as incident. Please provide more info if you find out more.

**Comment by Madflying** [comment]
I am also facing the same problem what's the solution

**Comment by cm3913** [comment]
i am facing the same issue

**Comment by haslinghuis** [comment]
Just retry and it works. Saw this a few times now but is intermittent
