### ISSUE TITLE
backup file date formating

### ISSUE THREAD

**Issue by riquezjp** [betaflight/betaflight-configurator#297]
Date formatting convention used in backup file names could be improved.
OLD: cleanflight_backup_8.29.2016.17.9.txt 
(august 29th 2016, 17:09hrs)

Suggestion: cleanflight_backup_2016.08.29.17.09.txt 
(august 29th 2016, 17:09hrs)

I suggest the date should be formatted as big-endian to avoid confusion & be numerically hierarchical when sorting files on your computer.
Single digits without a leading 0 in the date & time are confusing.

**Comment by mikeller** [comment]
Yep, good point.

**Comment by sebastianha** [comment]
Can be closed as the pull request has been merges
