### ISSUE TITLE
M1 Macbook Pro wont connect

### ISSUE THREAD

**Issue by Airworks-Au** [betaflight/betaflight-configurator#2975]
### Describe the bug

Its been two years and multiple releases why is it still nto possible to connect my FPV using betaflight on a M1 mac?

### To Reproduce

Plug it in wont see the drone 

### Expected behavior

it should just connect

### Configurator version

latest

**Comment by Landsailor** [comment]
I'm running a MBP 2021, M1 Max on 12.4 and just installed 10.8.0 as my first installation. I just connected to a Meteor75 using an Amazon Basics USB-C to Micro USB cable. It works over here. Try a different cable, perhaps?

<img width="1196" alt="Screen Shot 2022-07-21 at 4 10 10 PM" src="https://user-images.githubusercontent.com/1393119/180330061-2fe2257e-9730-41f5-8c61-cc1a4fdbd637.png">
