### ISSUE TITLE
Android app not working.

### ISSUE THREAD

**Issue by Bugz84** [betaflight/betaflight-configurator#2978]
### Describe the bug

updated betaflight android app to the latest and it says im using an outdated version. It will not update. Tried many times.

### To Reproduce

updated betaflight android app to the latest and it says im using an outdated version. It will not update. Tried many times.

### Expected behavior

updated betaflight android app to the latest and it says im using an outdated version. It will not update. Tried many times.

### Configurator version

10.8.0

**Comment by TylerDD4** [comment]
I opened a case for the same reason a month ago...I was told it was fixed. But it definitely isn't and has the error still. I tried nightly builds and the error goes away but the layout is messed up and side menus are broken.

Good luck! I tried already and apparently it's fixed already.
