### ISSUE TITLE
Mixer QuadX1234 not selectable

### ISSUE THREAD

**Issue by dropax** [betaflight/betaflight-configurator#299]
The option "QuadX1234" is not in the dropdown list but still can be set in CLI with the mixer command. 
I vaguely recall it was in the GUI back then we used cleanflight configurator. Very handy when converting a CC3D quad from openpilot to betaflight. 

Is it betaflight configurator not showing or betaflight not telling via MSP? Had a quick glance at both but couldn't spot anything.

**Comment by mikeller** [comment]
It looks like it is a configurator problem. `QuadX1234` should be the last entry in `mixerList` in `js/model.js`, right below `Custom Tricopter`. But it could also be an oversight in the CLI code that this mixer type has never been removed from the CLI when support for it was removed from the firmware.

Can you please confirm if this still works as it should when configured from the CLI?

**Comment by dropax** [comment]
It is still in https://github.com/betaflight/betaflight/blob/master/src/main/flight/mixer.c
Can't confirm it working personally (my only CC3D in a quad doesn't boot atm, guess it's offended of being ignored for too long ;)) but others had success with my advice.

**Comment by mikeller** [comment]
Fair enough, I can readd it to the list. Just beat with me, I'm on holiday at the moment.
