### ISSUE TITLE
Omnibus F4SD connection problem with 10.8

### ISSUE THREAD

**Issue by kondzio-p** [betaflight/betaflight-configurator#3012]
### Describe the bug

On 10.7 I can normally connect with my Omnibus F4SD. 
I then try to hop on 10.8 and it just doesn't work. 
Same with 10.9-debug
![10 7](https://user-images.githubusercontent.com/88985391/187670760-5a8a7864-9af8-486f-a9d1-cdf48bbddd54.jpg)
![10 8](https://user-images.githubusercontent.com/88985391/187670984-33f9a574-69f3-4eac-bb40-cf08558a32b7.jpg)
![10 9](https://user-images.githubusercontent.com/88985391/187670999-153a05c6-cc04-493d-9615-7ad24eb6900d.jpg)

### To Reproduce

Plug in a Omnibus F4SD fc and run betaflight 10.8.

### Expected behavior

I expect to connect with my FC normally.

### Configurator version

10.8, 10.9-debug

**Comment by McGiverGim** [comment]
I only can say that I can connect with Betaflight Configurator 10.8.0 to my OmnibusF4SD without problem.

Do you see some port in the combo of Manual Selection or is empty?

**Comment by haslinghuis** [comment]
What does device manager ports and usb show?

**Comment by kondzio-p** [comment]
The combo of manual selection is empty, I downloaded all the drivers, ran the fc through the driver fixer. I literally can’t find a post or video from someone who has the same problem.

**Comment by Asizon** [comment]
@kondzio-p this is clearly drivers issue, try reverting to the previous driver or using zadig
