### ISSUE TITLE
bi directional dshot not sticking in linux 3.8.0 configurator

### ISSUE THREAD

**Issue by dmarch40** [betaflight/betaflight-configurator#3013]
### Describe the bug

Setting bi directional dshot option and pole count on motors page resets after save and reboot.
Using a windows OS version 3.8.0 (5ec9465) of the configurator I was able to set it and have it remain thru save/reboot.

Going back to Linux OS version 3.8.0 (340087a4) dshot appears off, but values and error numbers do appear when motors are started.

### To Reproduce

using matekf722se board running bfl 4.1.0  I see this issue when on motor tab. Set bidirectional dshot and pole count. Save and reboot
Return to motors tab and options will not be set.

### Expected behavior

options are not reset by save and reboot

### Configurator version

3.8.0 (340087a4)

### Flight controller configuration

```txt
Not available
```

**Comment by haslinghuis** [comment]
The versions used are intermediate. Please check with 10.8 release version or latest nightly build. In this case there should be no difference between OS version used.
