### ISSUE TITLE
Can't flash  411 AIO board using BFC 10.8.0

### ISSUE THREAD

**Issue by porlock** [betaflight/betaflight-configurator#3019]
### Describe the bug

Hey, I tried to flash BF 4.2.11 Tinyhawk FS II board with target MatekF411RX and Moblite 7 diamond AIO with target CRAZYBEEF4FR.  Both stuck on "erasing" part, nothing more happens.  On BF configurator 10.7.2 everything worked at first try.

### To Reproduce

Try flash BF 4.2.11 using BFC 10.8.0 on
- Tinyhawk FS II board with target MatekF411RX 
- Moblite 7 diamond AIO with target CRAZYBEEF4FR

### Expected behavior

boards flash successfully 

### Configurator version

10.8.0

**Comment by duanfpv** [comment]
how to download

**Comment by porlock** [comment]
why its closed
