### ISSUE TITLE
Betaflight Configurator 10.8.0 APK : "Obsolete" message

### ISSUE THREAD

**Issue by Canaill51** [betaflight/betaflight-configurator#3048]
### Describe the bug

When opening Betaflight Configurator Android app, it always reports that it is obsolete. Even if I clean its cache on my Android device, and reinstall the app, still reporting this message.
![BF10 8 0 GUI APK](https://user-images.githubusercontent.com/56505305/195798325-7beda799-6514-4d5e-a8c5-1bf8f99c0137.jpg)

### To Reproduce

1. Install the latest Android APK from https://github.com/betaflight/betaflight-configurator/releases/download/10.8.0/betaflight-configurator_10.8.0-debug-5ec9465_android.apk
2. Run BF10.8.0 GUI app.

### Expected behavior

BF Configurator should open without any out-of-date message reporting, because it is up to date.

### Configurator version

10.8.0-debug-5ec9465

**Comment by deadpool772** [comment]
Just ran into this trying to install betaflight on my phone for the first time ever. I'm new to the FPV hobby this year, hopefully there's a fix to this soon

**Comment by haslinghuis** [comment]
It will be fixed in next version.

**Comment by 123GoqkadMe** [comment]
- [ ] betaflight configurator nightly 
- [ ] download
