### ISSUE TITLE
Layout misaligned in android configurator nightlies

### ISSUE THREAD

**Issue by PSi86** [betaflight/betaflight-configurator#3049]
### Describe the bug

Hi Team,
In the 10.9 nightly builds the androids configurator layout is not aligned correctly.

On the right side of the screen the main frame of the app does not use the display to the edge. And the menu on the left side does not show any text - just the symbols.

![Screenshot_20221014-151112_Betaflight Configurator (Debug Build)](https://user-images.githubusercontent.com/5648573/195855337-24130184-db62-4daa-9000-acb1385469e3.jpg)

### To Reproduce

Install 10.9 android configurator nightly on an Android 12 device, open it and observe the layout. I am using a Samsung S21.

### Expected behavior

Main application frame should use the display to the right edge and the menu bar should show the labels.

### Configurator version

10.9.0-debug-b5c2216

**Comment by ASDosjani** [comment]
Can you check which is the first version where it starts happening?

**Comment by McGiverGim** [comment]
I think it's when we moved from css to less. I suppose some rule was converted in a wrong way.

**Comment by ASDosjani** [comment]
@McGiverGim you are right. I checked and it happens after #2929. v20220623.130

**Comment by PSi86** [comment]
Thank you for checking and finding the culprit. If you need me for testing, please ping me here.

**Comment by PSi86** [comment]
Wrong button..

**Comment by ASDosjani** [comment]
![Screenshot_2022-10-22-17-14-45-301_com betaflight betaflight_configurator_debug](https://user-images.githubusercontent.com/62965528/197347198-a8ba53f3-f7f2-4eff-918c-5f214724c7f4.jpg)
This gray line on the right is also related to #2929.
