### ISSUE TITLE
ELRS device dissapears after a second

### ISSUE THREAD

**Issue by ASDosjani** [betaflight/betaflight-configurator#3050]
### Describe the bug

After the configurator starts it discovers the elrs 3.0 device but it dissappears from the port list after a second. Based on my testings this bug happens after in the port_handler.js the `TCP_CHECK_INTERVAL` expires and the tcpCheck() method called in line 107.
![image](https://user-images.githubusercontent.com/62965528/196051452-d3ccdf08-6819-48d8-9ee6-22d03f10e9dd.png)

If I power my drone after the configurator loaded than it connects automatically but then it disconnect.
![image](https://user-images.githubusercontent.com/62965528/196051773-4620b6ad-b243-451c-be42-f0b787ec3e14.png)

I can connect to my drone manually via wifi.
@freasy can you check?
### To Reproduce

Plug the drone in and check the configurator.

### Expected behavior

Not dissappearing.

### Configurator version

10.9, master, Windows 11

**Comment by freasy** [comment]
Hello :)

yes i can take a look into that.

**Comment by ASDosjani** [comment]
Thanks

**Comment by freasy** [comment]
> @freasy this bug is still relevant.

I will look into this today

**Comment by ASDosjani** [comment]
> 

I found the bug and made a PR, check #3095

**Comment by ASDosjani** [comment]
@freasy do you have discord? I would glad if you could join to the Betaflight server.
I still have some problem on Android side.
