### ISSUE TITLE
GPS Position Hold / Air Brake

### ISSUE THREAD

**Issue by ray940** [betaflight/betaflight-configurator#3058]
### Is your feature request related to a problem? Please describe

GPS Position Hold. Thanks for everything you all do here. 

### Describe the solution you'd like

Position Hold when needed to stop fast or hold for safety reason etc.

### Describe alternatives you've considered

INAV

**Comment by haslinghuis** [comment]
This is worked on after next release.

[duplicate of #11306](https://github.com/betaflight/betaflight/issues/11306)
