### ISSUE TITLE
Increase scale for gyro readings in Motor and Sensor Tab

### ISSUE THREAD

**Issue by SupaflyFPV** [betaflight/betaflight-configurator#3072]
### Is your feature request related to a problem? Please describe

Currently there are a lot of gyro issues coming up due to QC issues. I've just encountered one with a BMI gyro with high baseline noise. 

In the motor tab there is a chart showing the active gyro outputs and the scale goes up to 10. This makes it a little easier to observe the noise floor. On the 'Sensors' tab the scale only goes up (or down) to 100 which means the noise floor can barely be seen.

I am asking if we could get further scaling on both to make it easier to observe the noise floor and look for issues without having to fly and take a black box log.

### Describe the solution you'd like

Scale on both readouts to perhaps 5 or even bigger....

### Describe alternatives you've considered

Logging is the only other alternative. However if we can get a proper scale then we can establish levels for normal and problematic noise levels without the need to fly/log when doing support.

**Comment by SupaflyFPV** [comment]
<img width="1728" alt="Screenshot 2022-11-06 at 16 50 46" src="https://user-images.githubusercontent.com/46397720/200185540-b56eb5f6-34a7-4b77-a0ec-51c7204302b9.png">

**Comment by haslinghuis** [comment]
Let me know which scales are usefull

**Comment by SupaflyFPV** [comment]
> Let me know which scales are usefull

could you add 5 and 2 and 1? I'm not sure how the scaling works...the image above is the biggest it can currently go set at 10...

**Comment by haslinghuis** [comment]
Please test 3073, added a lot more

**Comment by haslinghuis** [comment]
![image](https://user-images.githubusercontent.com/8344830/200198614-f129793e-9aa4-4661-af3e-ae00a213202f.png)

**Comment by SupaflyFPV** [comment]
awesome will test now

**Comment by SupaflyFPV** [comment]
thats brilliant thanks - really useful now

If I was greedy I'd ask if the constant peak values per axis can exist in the sensors tab like it does in the motors?

**Comment by SupaflyFPV** [comment]
for anyone interested you can straight away see the noisy BMI gyro I have here compared to a known working MPU6000
<img width="1504" alt="Screenshot 2022-11-06 at 23 00 03" src="https://user-images.githubusercontent.com/46397720/200200057-f96626eb-2efd-48bb-aeca-4f5a2f27c151.png">
<img width="1514" alt="Screenshot 2022-11-06 at 23 00 46" src="https://user-images.githubusercontent.com/46397720/200200063-8ee397f6-8371-429c-b500-bf90d31bfcd5.png">
