### ISSUE TITLE
`master` - OSD tab - HD grid scale/z-level issue

### ISSUE THREAD

**Issue by nerdCopter** [betaflight/betaflight-configurator#3100]
### Describe the bug

* when configurator window is rather narrow, and `HD` is selected, the OSD grid pattern is scaled wrongly and z-level is above the options.
* maybe in reference to https://github.com/betaflight/betaflight-configurator/pull/3071
* tested/found on master `8aced3b3`

### To Reproduce

* size the window about 1400 pixels wide.
* select HD
* try to select any other option in the same vertical level as the OSD-background-image.

### Expected behavior

* options should be selectable

### Configurator version

`8aced3b3`

![image](https://user-images.githubusercontent.com/56646290/204560522-cee47c94-54c3-49a2-909f-9ca0dc2e6d03.png)

**Comment by KarateBrot** [comment]
The grid is a "pre-baked" image afaik. Can we maybe just draw the gridlines dynamically "on the fly" using d3.js or something similar?

**Comment by McGiverGim** [comment]
It was changed to a dinamically one in the HD PR. What it seems to me is that the grid is ok, but the window is not. It does not have the correct proportion.

**Comment by haslinghuis** [comment]
Seems working with above fix. Might not be the right solution but it works now on smaller screens.
