### ISSUE TITLE
Cloud build tooltip doesn't match UI behaviour.

### ISSUE THREAD

**Issue by hydra** [betaflight/betaflight-configurator#3169]
### Describe the bug

![image](https://user-images.githubusercontent.com/57075/209667481-d1d5a1d6-3a77-4a23-b52f-494bd63ab740.png)

![image](https://user-images.githubusercontent.com/57075/209668038-5894ce49-f758-41f6-8531-3b844a00a1d5.png)

Contrary to the "This mode ignores all the parameters here (except for the commit when in export mode)." on the tooltip for the 'classic mode' toggle the entire build configuration panel is hidden.

### To Reproduce

* Visit firmware flasher page.
* Pick 'show release candidates'
* Enable 'expert mode'.
* Pick 'development'
* Pick any board.
* Observe that the 'commit' dropdown only appears when 'classic mode is disabled'.

### Expected behavior

The 'commit' dropdown should always be visible in expert mode like the tooltip says.

### Configurator version

10.9.0-debug-23b74d99

**Comment by blckmn** [comment]
This was raised at the time the panel moved to being entirely hidden.

The tooltip merely needs updating.
