### ISSUE TITLE
Unable to access build configuration settings unless 'show release candidates' is enabled.

### ISSUE THREAD

**Issue by hydra** [betaflight/betaflight-configurator#3170]
### Describe the bug

The UI, IMHO, doesn't make sense.

To access the full build configuration you have to both enable:
1) Show release candidates slider.
2) Pick 'development' from the list.

To access the cut-down build configuration you have to both enable:
1) Show release candidates slider.
2) Pick 'release and release candidate' from the list.

A custom build is not a 'Release Candidate', it's a 'Custom Build'.

Similarly the 'Release and Release Candidate' option needs to be selected to make a 'Custom Build' from a 'Release Build'.

### To Reproduce

See above.

### Expected behavior

'Build configuration' UI should always be shown.

### Configurator version

10.9.0-debug-23b74d99

**Comment by haslinghuis** [comment]
This is as intended. Cloud build has been introduced in firmware 4.4 without backwards compatibility.
