### ISSUE TITLE
Release notes / build information not shown in the UI.

### ISSUE THREAD

**Issue by hydra** [betaflight/betaflight-configurator#3173]
### Describe the bug

The build information panel no longer appears when selecting any firmware.

### To Reproduce

Select firmware, observe missing panel:

![image](https://user-images.githubusercontent.com/57075/209674937-e861c5b3-5ab7-4a8c-86e3-365170380e53.png)

### Expected behavior

Panel showing build information, filename, date, release notes, etc, should be shown.

### Configurator version

10.9.0-debug-dc2880fc

**Comment by blckmn** [comment]
This is an intentional omission.

**Comment by hydra** [comment]
Is there a PR somewhere that discussed the reasons for removing it?  I and probably others would like to know what happened to it and why.

**Comment by haslinghuis** [comment]
See https://github.com/betaflight/betaflight-configurator/pull/3083
