### ISSUE TITLE
Deb package compressed using Zstd, which is not supported yet by Debian

### ISSUE THREAD

**Issue by AlexandreBonneau** [betaflight/betaflight-configurator#3185]
### Describe the bug

The .deb packages released are compressed using Zstd, which is not yet supported by Debian.

Even if you have the `zstd` package installed, it will complain with `dpkg-deb: error: archive '/home/user/betaflight-configurator_10.9.0-RC2_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up`.

In order to be able to install the package, you have to extract it, then repack it with the `xz` compression tool:
```sh
ar x betaflight-configurator_10.9.0-RC2_amd64.deb
rm betaflight-configurator_10.9.0-RC2_amd64.deb
zstd -d < control.tar.zst | xz > control.tar.xz
zstd -d < data.tar.zst | xz > data.tar.xz
ar -m -c -a sdsd betaflight-configurator_10.9.0-RC2_amd64.deb debian-binary control.tar.xz data.tar.xz
rm -f control.tar.xz control.tar.zst data.tar.xz data.tar.zst debian-binary
```

Do note that the zst compression is not as effective as the xz one, since I can see the difference in sizes:
```
 564 control.tar.xz
 464 control.tar.zst
104M data.tar.xz
112M data.tar.zst
```

### To Reproduce

Try to install the package with `dpkg`.

### Expected behavior

It should install, instead of complaining that the archive is unusable.

### Configurator version

1.9.0-rc2

### Flight controller configuration

```txt
N/A
```

**Comment by haslinghuis** [comment]
Fixed in https://github.com/betaflight/betaflight-configurator/pull/3155
