### ISSUE TITLE
Compass View

### ISSUE THREAD

**Issue by druckgott** [betaflight/betaflight-configurator#3232]
### Is your feature request related to a problem? Please describe

It would be good to have a compass bar or something like this in the GPS Tab or maybe a extra Tab. Because otherwiese I can´t find out if my compass looks in the right direction bevor I activate it for example in GPS Rescue or in OSD.

### Describe the solution you'd like

Would be nice if it could be implemented so that there is are bar you can see if you rotate the copter that the direction shows for example to north if your copter looks to north.

### Describe alternatives you've considered

Switch on OSD have a look, but this takes long and it will be nice to directly handle it in the configuratior, like gps itself for test.

**Comment by McGiverGim** [comment]
You have it when you enter in the Configurator, connect, first page, to the right ;)
