### ISSUE TITLE
Table AutoComplete cannot Work Well in Betaflight-Configurator

### ISSUE THREAD

**Issue by CCNUI** [betaflight/betaflight-configurator#3238]
### Describe the bug

If I use table's AutoComplete to fill in the table. Then I can't save the cell which was filled by AutoComplete (AutoFill).
Like This:
<img width="307" alt="image" src="https://user-images.githubusercontent.com/88219502/212352144-9303f26c-a494-478a-9579-e8c0bd34c499.png">

### To Reproduce

1. Filling the VTX table's name by typing key"B" .
2. Clicking the Autofill's Suspended window.
<img width="307" alt="image" src="https://user-images.githubusercontent.com/88219502/212352144-9303f26c-a494-478a-9579-e8c0bd34c499.png">
3. Click "save" buttom
4. Reboot the board.
5. Found this set was lost and became a blank cell.

### Environment

Operating System: Windows 11 Education (22H2 22621.1105)

### Configurator version

10.9.0-RC4 (norevision)

### Flight controller configuration

```txt
# vtxtable
vtxtable bands 5
vtxtable channels 8
vtxtable band 1          A CUSTOM  5865 5845 5825 5805 5785 5765 5745 5725
vtxtable band 2          B CUSTOM  5733 5752 5771 5790 5809 5825 5847 5866
vtxtable band 3          E CUSTOM  5705 5685 5665 5665 5885 5905 5905 5905
vtxtable band 4          F CUSTOM  5740 5760 5780 5800 5820 5840 5860 5880
vtxtable band 5          R CUSTOM  5658 5695 5732 5769 5806 5843 5880 5917
vtxtable powerlevels 4
vtxtable powervalues 25 400 800 1600
vtxtable powerlabels 25 400 800 MAX
```

**Comment by haslinghuis** [comment]
Fixed in configurator 10.9
