### ISSUE TITLE
Rearrange boxes in the 'Configuration' tab

### ISSUE THREAD

**Issue by mikeller** [betaflight/betaflight-configurator#324]
After some tidying up in the Configuration tab. some of the boxes have been removed or shrunk, leaving empty spaces on the page. The remaining boxes should be rearranged to make it look tidy and compact.

I was hoping for @skaman82 to give me a hand with this. ;-)

**Comment by skaman82** [comment]
@mikeller I will have a look at this

**Comment by mikeller** [comment]
Wow, that was quick, thanks a lot @skaman82.
