### ISSUE TITLE
Please add Tooltip or wiki reference for "Other options" page

### ISSUE THREAD

**Issue by rally-dimi** [betaflight/betaflight-configurator#3261]
### Is your feature request related to a problem? Please describe

I'm new to FPV so I don't know every feature of my hardware - and it is hard to say what some of those "Other options" mean. 
I was searching for wiki for some, but found just code. 

<img width="1491" alt="image" src="https://user-images.githubusercontent.com/88184204/213383093-e8248665-5077-4d07-a166-87ab61b84243.png">

### Describe the solution you'd like

Please add tooltip to each selected option, so when you hover over it with mouse, it would put description. 
Or create a link near the selections that would redirect you to a wiki page with options.

### Describe alternatives you've considered

Just selecting minimal options without bothering.

### Other information

No other info.

**Comment by haslinghuis** [comment]
What do you see In the upper right corner of configurator in the flasher tab?

**Comment by rally-dimi** [comment]
Wow, it could be even tinier.  :smile: 
Thank you! @haslinghuis 
Maybe one note - can you add comment - `see description of features in **wiki**` ?
For example - in the same line as the `Other options` label ?

**Comment by rally-dimi** [comment]
Also those features on wiki could be a bit more descriptive - not sure what `PINIO` means. Or `Enable VTX` - like without it wouldn't be able to transmit video ?
