### ISSUE TITLE
"Failed to open serial port" in Linux

### ISSUE THREAD

**Issue by RahulGoyal-tech** [betaflight/betaflight-configurator#3282]
### Describe the bug

I have connected the flight controller to pc and it is being automatically detected by betaflight but whenever i try to connect, it shows failed to open serial port. Please suggest what should i do because my kernel is 5.x.x version so there is no installation available for cp210x

### To Reproduce

happening in my system

### Expected behavior

connect successfully to fc

### Configurator version

10.8.0

**Comment by haslinghuis** [comment]
Please check https://betaflight.com/docs/wiki/archive/Installing-Betaflight#platform-specific-linux

**Comment by RahulGoyal-tech** [comment]
Thank you so much. It worked perfectly 😊

**Comment by TheForsakenSpirit** [comment]
@haslinghuis can you update link or add solution description?

**Comment by haslinghuis** [comment]
Link has been updated.

**Comment by nerdCopter** [comment]
> @haslinghuis can you update link or add solution description?

@TheForsakenSpirit , this is fairly concise as well: https://hackmd.io/@nerdCopter/H1dtIuUSn

**Comment by passalini** [comment]
after pluging usb run `sudo chmod 0777 /dev/ttyACM0`

**Comment by adii-n** [comment]
`sudo chmod 777 /dev/tty/ACM0` works perfectly for me to make the com port recognizable. The only issue is that I have to run the command every time betaflight restarts; is there any way to make the change permanent?

**Comment by nerdCopter** [comment]
0777 is a workaround, the proper solution is udev rules and user groups.  see official docs or the link i posted above.

**Comment by kiranze** [comment]
> One more solution (without building) after pluguing usb run: `sudo chmod 0777 /dev/ttyACM0`

Thanks man, worked immediately

**Comment by Juribiyan** [comment]
For udev rules and usergroups follow the [instructions provided by the ExpressLRS Configurator].(https://github.com/ExpressLRS/ExpressLRS-Configurator?tab=readme-ov-file#linux). It worked for me.
