### ISSUE TITLE
Betaflight Configurator 10.9.0 APK: Same issue than https://github.com/betaflight/betaflight-configurator/issues/3048

### ISSUE THREAD

**Issue by Canaill51** [betaflight/betaflight-configurator#3285]
### Describe the bug

Exact same issue with latest 10.9.0 GUI APK, than one reported in https://github.com/betaflight/betaflight-configurator/issues/3048

### To Reproduce

Same than https://github.com/betaflight/betaflight-configurator/issues/3048

### Expected behavior

Same than https://github.com/betaflight/betaflight-configurator/issues/3048

### Configurator version

10.9.0 (697943b)

**Comment by haslinghuis** [comment]
@McGiverGim - we should document update process for next release.

@Canaill51 Please use `10.10`: https://github.com/betaflight/betaflight-configurator-nightlies/releases/tag/v20230128.362

**Comment by McGiverGim** [comment]
And use a real certificate... Except if we go to pwa.

**Comment by Canaill51** [comment]
@haslinghuis just removed 10.9.0 GUI from my Android smartphone and installed 10.10 from your above link:
No message no longer occurs.

Could 10.9.0 get this fix?

**Comment by Canaill51** [comment]
@haslinghuis, any update since this ?
As confirmed, 10.10 is not showing up this messages.
Which apk should we use on Android, to configure BF ?
Is it planned to fix 10.9 ?

**Comment by haslinghuis** [comment]
We are working on it: https://github.com/betaflight/betaflight-configurator/pull/3349
