### ISSUE TITLE
'Flash on connect' stops working after early disconnect

### ISSUE THREAD

**Issue by mikeller** [betaflight/betaflight-configurator#330]
When flashing a bricked board by using 'No reboot sequence' / 'Flash on connect' and the boot pins, if a reboot sequence that fails to jump into the boot loader is interrupted by the board being disconnected before its end, subsequent reboot sequences will fail with 'previous device still flashing, please replug to try again'. This can only be reset by restarting the configurator.

**Comment by borisbstyle** [comment]
not a high prio at all. It is advised everywhere to not disconnect your board during flash.

**Comment by mikeller** [comment]
It's not during flash. It is when the flash never starts, because the boot loader pads deep inside the craft are not properly bridged. This should not cause the configurator to hang.

**Comment by mikeller** [comment]
But if this is not a priority, we should remove this functionality, since it is clearly broken.
