### ISSUE TITLE
Strange defaults in Motor Test when DSHOT is used.

### ISSUE THREAD

**Issue by AndersHoglund** [betaflight/betaflight-configurator#331]
Referring to betaflight PR 1389, there are still a few problems in BFC motor test. 
If DSHOT150 is enabled and min_command is set to 990 the defaults in the motor tab is a bit off.
1. Motor Test enabled by default.
2. Throttle min values follow min_command for inactive motors.
3. Throttle min values follow min_command if slider is moved for active motors. Default OK.

Nb. Only tested with DSHOT150, no tests with DSHOT300 nor DSHOT600. 

![dshot_bfc_motor_test](https://cloud.githubusercontent.com/assets/15121917/19728421/95fdad84-9b93-11e6-8532-4c10ea683057.jpg)

**Comment by mikeller** [comment]
Will look into fixing these once the internal DShot data format has been finalised, and a decision made re adding an 'arm' command. (No point allowing 'disarmed' input from configurator if the ESCs have to be armed to get them to run.)

**Comment by brucesdad13** [comment]
This is happening for me also with brushed I went to motors tab. If a battery is plugged in immediately motors all go full throttle and I can't turn them off even unplugging the USB the motors remain and I have to pull the LiPO. Without LiPO the flight controller has a brownout and reboots.

**Comment by mikeller** [comment]
The original bug had been fixed in the meantime, but at the moment the motor tab is broken because it's missing some changes that have been made in cleanflight, but not yet ported to Betaflight.

**Comment by brucesdad13** [comment]
Ok thanks for clarifying :)
