### ISSUE TITLE
The System cannot find the file specified while upgrading to 10.9

### ISSUE THREAD

**Issue by lordhenrix** [betaflight/betaflight-configurator#3317]
### Describe the bug

clicking install gives Windows Error "The System cannot find the file specified" when betaflight initially tried to uninstall. I manually deleted betaflight 10.8 before trying to install 10.9 and cannot get 10.9 to install now. 

### To Reproduce

delete betaflight folder 

### Expected behavior

installation

### Configurator version

upgrading from 10.8 to 10.9

### Add any other context about the problem that you think might be relevant here

I may have deleted the wrong file. The file path followed is Cdrive-programfilesx86-betaflight- DELETED BETAFLIGHT CONFIGURATOR (blackbox was in the betaflight folder)

**Comment by haslinghuis** [comment]
This is not the correct way to delete applications from a system as we need to use the uninstall feature from `appwiz.cpl`

- Try uninstalling configurator from Add/Remove Programs.
- If still in the recycle bin you can simply restore the folder.
