### ISSUE TITLE
Feature request: pre pend craft name to black box log file.

### ISSUE THREAD

**Issue by atomiclama** [betaflight/betaflight-configurator#334]
It would be great if the craft name parameter could be read from the FC and used to distinguish between blackbox log files by prepending it to the blackbox log file name.

**Comment by mikeller** [comment]
Good idea.

**Comment by borisbstyle** [comment]
Could also print the logfile number to OSD so you can find it easier
afterwards!

**Comment by mikeller** [comment]
Yeah. We'd have to add that to MSP though.

**Comment by borisbstyle** [comment]
No msp needed on internal osd

**Comment by mikeller** [comment]
Should be done in the code that supports those two boards then, it can read file numbers directly from microSD. Maybe could even implement file management...
