### ISSUE TITLE
Build Configuration Profiles

### ISSUE THREAD

**Issue by kevinsumner** [betaflight/betaflight-configurator#3340]
### Is your feature request related to a problem? Please describe

As I'm flashing all my quads up to Betaflight 4.4, I find myself with one of a handful of build configurations that I reuse across a significant number of quads. They break down into two primary configurations, a bare-bones load out for F411-equipped tiny whoop AIOs, and dropping a couple options for F7- and H7-equipped freestyle quads. If I were flying long range, I'd add in Magnetometers on top of the default set.

### Describe the solution you'd like

I'd like to have the ability to save a specific selection of configuration options as a profile for reuse across multiple flashes. This saves me from forgetting a specific option and helps ensure all my FCs are running the feature set I expect.

### Describe alternatives you've considered

For now, I'm continuing to manually-select the items I need in each flash and have reduced the configuration deviations I've made from the defaults to lower the chance of human error.

**Comment by HThuren** [comment]
@haslinghuis I was wondering to fix this, but it seems to be done already ?

**Comment by haslinghuis** [comment]
Fixed in https://github.com/betaflight/betaflight-configurator/pull/3332

If build key is present in firmware build options are preset.
