### ISSUE TITLE
Clarification of Telemetry Protocols cloud build option

### ISSUE THREAD

**Issue by jawz101** [betaflight/betaflight-configurator#3342]
### Is your feature request related to a problem? Please describe

I have 3 quads.  All 3 have ExpressLRS.  2 have Smartaudio and 1 has IRC Tramp for telemetry.  Do I need to use any of the Telemetry Protocol selections to enable telemetry or are those baked into the default ROM?  If I do need to select a telemetry protocol, the names available match neither Smartaudio nor IRC Tramp.

### Describe the solution you'd like

A little more clarification of the Telemetry Protocol options if they are synonymous with Smartaudio or IRC Tramp.  Or if the choices are for legacy protocols, rename that section as Legacy Protocols so people know not to select them unless they have to.

### Describe alternatives you've considered

Confusion

**Comment by klutvott123** [comment]
smartaudio and tramp are vtx protocols so naturally can't be found in the telemetry dropdown. Telemetry will be included in the build automatically when using elrs so you don't have to select anything from the telemetry dropdown.
