### ISSUE TITLE
Gyro not detected on TMOTORF4 when using 10.9.0 configurator

### ISSUE THREAD

**Issue by hectormfl** [betaflight/betaflight-configurator#3345]
### Describe the bug

Hi,
During the migration to Betaflight 4.4 of my quads, detected an extrange issue on one of them.
The board is a TMOTORF4.
Using the latest configurator and installing the 4.4 version, when the process finishes and connects to the configurator, the Gyro is not detected.
Tried to reinstall the 4.3.2 version and works fine.

The thing is that if i use the 10.8.0 configurator, I can flash either 4.3.2  or 4.4 and gyro is detected fine. But I have doubts because its supposed that the version 4.4 should only be installed with de 10.9.0 configurator

On the pictures attached can be seen the gyro not detected on 4.4 flashed with 10.9.0  and gyro working after flashing 4.4 with 10.8.0 configurator
![2023-02-16 13_48_40-Betaflight Configurator](https://user-images.githubusercontent.com/96573593/219372677-d28b261d-7db9-4de6-9dd5-86f606039a79.png)
![2023-02-16 13_48_57-Betaflight Configurator](https://user-images.githubusercontent.com/96573593/219372687-e11be94b-8928-4121-882b-8bd29451f2c5.png)
![10 8 0](https://user-images.githubusercontent.com/96573593/219372690-546d52b7-d7c7-4bf2-96a5-4e418cc39cc9.png)
![10 8 0_2](https://user-images.githubusercontent.com/96573593/219372695-c08a9540-d016-45dc-bcf5-2ce8b6ff32f1.png)

### To Reproduce

installed 4.4 version with 10.9.0 configurator

### Expected behavior

Gyro not detected

### Configurator version

10.9.0

### Flight controller configuration

```txt
# version
# Betaflight / STM32F405 (S405) 4.4.0 Feb  9 2023 / 20:26:02 (4605309d8) MSP API: 1.45

# config: YES

# start the command batch
batch start

board_name TMOTORF4
manufacturer_id TMTR

# master
set osd_canvas_width = 30
set osd_canvas_height = 13

profile 0

rateprofile 0

# end the command batch
batch end
```

**Comment by haslinghuis** [comment]
Fixed in: https://github.com/betaflight/betaflight/pull/12371

You can test this PR in expert mode. Add `#12371` in the commit field before flashing.

**Comment by hectormfl** [comment]
Installed the version with the  #12371 commit, but same behaviour

**Comment by klutvott123** [comment]
that's strange. are we sure they aren't using other gyros than the mpu6000 on this board? Can you flash 4.3.2 and post the output of `status` in cli?

**Comment by klutvott123** [comment]
Looks like there's a regular and a HD version of this flight controller. Regular version uses ICM20602 while the HD version uses MPU6000.
Try adding ```GYRO_SPI_ICM20602``` and ```ACC_SPI_ICM20602``` to custom defines.
I think maybe the HD version should have had it's own config

**Comment by hectormfl** [comment]
> that's strange. are we sure they aren't using other gyros than the mpu6000 on this board? Can you flash 4.3.2 and post the output of `status` in cli?

MCU F40X Clock=168MHz (PLLP-HSE), Vref=3.31V, Core temp=26degC
Stack size: 2048, Stack address: 0x1000fff0
Configuration: CONFIGURED, size: 4100, max available: 16384
Devices detected: SPI:1, I2C:0
Gyros detected: gyro 1 locked dma
GYRO=ICM20602, ACC=ICM20602
OSD: MAX7456
System Uptime: 29 seconds, Current Time: 2023-02-17T08:05:06.276+00:00
CPU:33%, cycle time: 125, GYRO rate: 8000, RX rate: 15, System rate: 9
Voltage: 1 * 0.01V (0S battery - NOT PRESENT)
I2C Errors: 0
SD card: Not configured
Arming disable flags: RXLOSS CLI MSP MOTOR_PROTO

**Comment by hectormfl** [comment]
> `ACC_SPI_ICM20602`

Did it this way

![image](https://user-images.githubusercontent.com/96573593/219588550-3a82e2d2-1857-4823-8a4c-d2a85bf37344.png)

It seems it works! now it´s detected.

As you said, yes, should be two different targets... this is the F4 not the F4HD
Hope can try it soon.

Thanks!

**Comment by klutvott123** [comment]
Thanks! That confirms it. https://github.com/betaflight/unified-targets/pull/903 will fix it

**Comment by haslinghuis** [comment]
Fixed in https://github.com/betaflight/unified-targets/pull/903
