### ISSUE TITLE
Could not connect Chrome OS

### ISSUE THREAD

**Issue by Sybalau** [betaflight/betaflight-configurator#336]
I can no longer connected to betaflight with Chrome OS.

I tried 3 different FC which works fine under Windows 10.

When I press the "connect" button, everything is blocked and the mouse does not move. I am forced to remove the USB cable, so that it works again.

**Comment by mikeller** [comment]
Looks like there is a problem with the configurator under the latest ChromeOS release. Will look into it.

**Comment by danybd** [comment]
@mikeller does BF still support ChromeOS? I see this issue is over 4 years old. Is it still needed? I am looking for bugs, which eventually I can resolve 😄

**Comment by McGiverGim** [comment]
No, we have removed the support for Chrome OS. I close this.
