### ISSUE TITLE
Pressing SAVE in Configurator 10.9 "PID Tuning" will reset GYRO_HARDWARE_LPF to NORMAL setting

### ISSUE THREAD

**Issue by BrandonsBakedBeans** [betaflight/betaflight-configurator#3376]
### Describe the bug

I have been testing different hardware lpf settings for the BMI270. Pressing SAVE in any tab of the PID Tuning section of Betaflight 10.9 configurator will reset the GYRO_HARDWARE_LPF to NORMAL. Tested on Betaflight 4.4 firmware across several test builds. Does not affect users with configurator 10.8 and firmware 4.3.1.
Does not get triggered by adjustments via Betaflight Lua script or the CMS.

### To Reproduce

On 4.4 firmware, set GYRO_HARDWARE_LPF to any value that is not the default NORMAL setting. Save.
In the 10.9 configurator press SAVE button in the PID Tuning section.
In CLI, 'get gyro_hardware_lpf' returns value of NORMAL.

### Expected behavior

GYRO_HARDWARE_LPF remains set to the assigned value, persisting through pid tuning and filter changes via the configurator. 

### Configurator version

10.9.0 (697943b)

**Comment by nerdCopter** [comment]
for reference. https://github.com/betaflight/betaflight-configurator/blob/6ef0046a1da5d2d994291494bf1e855ccff84eaf/src/js/msp/MSPHelper.js#L1939
