### ISSUE TITLE
Receiver telemetry state changes with ports tab changes.

### ISSUE THREAD

**Issue by P-I-Engineer** [betaflight/betaflight-configurator#3380]
### Describe the bug

making changes then save/reboot ports tab turns off telemetry on receiver tab.

### To Reproduce

ports tab
set port to serial rx
set port to gps
save/reboot

rx tab
turn on telemetry
save/reboot

ports tab
turn off gps port
save/reboot

rx tab
telemetry will be off.

### Expected behavior

expect telemetry state to not change

### Configurator version

10.9

### Flight controller configuration

```txt
# 

# diff

# version
# Betaflight / STM32F411 (S411) 4.4.0 Mar 10 2023 / 22:37:15 (4605309d8) MSP API: 1.45

# config: YES

# start the command batch
batch start

board_name FPVCYCLEF401
manufacturer_id TURC

# feature
feature GPS

# serial
serial 0 64 115200 57600 0 115200
serial 1 2 115200 57600 0 115200

# master
set osd_canvas_width = 30
set osd_canvas_height = 13

profile 0

rateprofile 0

# end the command batch
batch end

#
```

### Add any other context about the problem that you think might be relevant here

i discovered this with my betafpv f405 board. i confirmed the issue with my fpvcycle board.

**Comment by haslinghuis** [comment]
Fixed in: https://github.com/betaflight/betaflight-configurator/pull/3298
