### ISSUE TITLE
Add ADVANCED_TUNING to tuning Tab // Iterm limits etc

### ISSUE THREAD

**Issue by borisbstyle** [betaflight/betaflight-configurator#34]
I think the pid tuning tab needs more hidden stuff in there. Like a checkbox for some extra advanced parameters. Maybe the filters should be in there too.

**Comment by skaman82** [comment]
@borisbstyle You can place hidden content easily in a popup with the integrated jBox. (see gui.js) here https://github.com/betaflight/betaflight-configurator/commit/f5e442f3e647bd4164cc12f27c94588c46a2fc65
![Uploading Bildschirmfoto 2016-06-21 um 17.29.45.png…]()

**Comment by borisbstyle** [comment]
That looks nice!
