### ISSUE TITLE
Ubuntu 22.04 : "Flash Firmware" not possible

### ISSUE THREAD

**Issue by fpvbam** [betaflight/betaflight-configurator#3411]
### Describe the bug

Firmware successfully loaded [Online] or cached.
Executing "Flash Firmware" prompts "Please load firmware file".

### To Reproduce

Select DFU, Update Firmware, Load Firmware [Online], Flash Firmware

### Expected behavior

Firmware flashing should be processed.

### Configurator version

10.9.0 (697943b)

**Comment by haslinghuis** [comment]
Check http://betaflight.com/docs/development/Building-in-Ubuntu#flashing-a-target-with-betaflight-configurator-on-ubuntu-2204

**Comment by fpvbam** [comment]
Thank you for the hint. This is a development machine, udev rules already added.

**Comment by haslinghuis** [comment]
No problems here on master

**Comment by haslinghuis** [comment]
Any output on dev console?

**Comment by fpvbam** [comment]
Right now I cannot try further.
The F722 of the iflight TwinG F7 does not offer DFU anymore.
Neither ST-Link with soldered SWDIO/SWCLK wires will work.
I will replace the FC soon.
