### ISSUE TITLE
When A Preset Branch does not exist, Add Button to make Default Repo Active (if there is an internet connection?)

### ISSUE THREAD

**Issue by rochford77** [betaflight/betaflight-configurator#3419]
### Is your feature request related to a problem? Please describe

I have a public repo that a handful of people use, I assume. I have not been good about frequently merging latest from /betaflight/firmware-presets, so anyone using it is likely missing out on a lot of good stuff for long periods of time. As I now have most of my presets in the official repo, I am considering deleting that branch to force people back into official (or another private repo of their choosing).

It would be a bad user experience if they are just greeted by a white screen one day, and dont know how to resolve it, so they have to ask on FB or whatever. So, I thought a button on that page that activates the official betaflight repo would be benificial. Even just for general use, someone types in the wrong info, they have a one click option to make default active again.

### Describe the solution you'd like

![active](https://user-images.githubusercontent.com/10854970/231004735-fe1ef3a6-cbf6-499d-8c70-db93fca89b0a.PNG)

### Describe alternatives you've considered

I considered that It could just go to the official automatically, no white screen at all, if the repo is not available, but then they might think it worked, you want to communicate that it failed, so this isnt the best approach. 

### Other information

This could be confusing if the reason it couldnt load the presets was due to a disconnected network, so, perhaps if we dont have a graceful way to verify an internet connection, its not worth doing

**Comment by haslinghuis** [comment]
Preset provide an option to use an alternative source.
