### ISSUE TITLE
Add a field in configurator receiver tab

### ISSUE THREAD

**Issue by Pancronos** [betaflight/betaflight-configurator#3420]
### Is your feature request related to a problem? Please describe

Lately ELRS team has introduced id model match, but in configurator using SPI rx, there is only the field for binding phrase.
Adding a field for model match will allow a more user friendly approach, other then setting it in cli (method not well known).

### Describe the solution you'd like

Would like to see a field, in the receiver tab for SPI receivers, where you can set model id, same as per the exsisting binding phrase.

### Describe alternatives you've considered

The only alternative is to know that can be added via cli with "set expresslrs_model_id = x " but user new to fpv will go crazy before they find out how to do it.

### Other information

N/A

**Comment by Prajwal-Koirala** [comment]
**Subject:**  Feature Request: Add Model ID Field for SPI Receivers in Configurator

**Dear ELRS Team,**

I'm writing to formally request a valuable addition to the ExpressLRS Configurator: a dedicated Model ID field within the Receiver tab for SPI receivers.

**Motivation:**

- The recent introduction of model ID matching significantly enhances model pairing security and reliability.
- The current method of setting the model ID via CLI command ("set expresslrs_model_id = x") presents a considerable barrier for users unfamiliar with CLI operations. This is especially true for those new to FPV or less technically inclined.

**Proposed Solution:**

- Implement a new field for entering the desired model ID directly within the Receiver tab, alongside the existing Binding Phrase field.
- This UI-based approach would provide a more intuitive and user-friendly experience, aligning with the overall ease of use that ExpressLRS is known for.

**Benefits:**

- **Enhanced Accessibility:** Extends model ID matching functionality to a wider range of users, regardless of technical expertise.
- **Improved User Experience:** Streamlines configuration and contributes to a more seamless overall experience.
- **Maintained Security:** Ensures the continued benefits of model ID matching for enhanced model pairing integrity.

**Alternatives Considered:**

- While CLI-based configuration is a viable option, it's not ideal for user-friendliness and broader adoption.

**Conclusion:**

I strongly believe the addition of a Model ID field within the Receiver tab would significantly benefit both experienced and novice ExpressLRS users. It would not only make model ID matching more accessible but also contribute to a more intuitive and streamlined user experience.

I kindly request that you consider this feature request and its potential to further enhance the already excellent ExpressLRS ecosystem.

Thank you for your time and consideration.

**Sincerely,**
Prajwal
