### ISSUE TITLE
Firmware Flasher page 'USB Flashing' help link not working

### ISSUE THREAD

**Issue by junwoo091400** [betaflight/betaflight-configurator#3436]
### Describe the bug

Current 'USB Flashing' link in the configurator's Firmware flasher page points to https://github.com/betaflight/betaflight/wiki/Installing-Betaflight, which doesn't exist anymore.

It should rather point to: https://betaflight.com/docs/wiki/boards/BETAFLIGHTF3#driver-related-problems

### To Reproduce

![image](https://user-images.githubusercontent.com/23277211/236103411-f8f83c0e-d3b7-42c4-a8ff-1beabf2fc62c.png)

In the configurator, click the 'USB Flashing' text above

### Expected behavior

Should direct users to the appropriate page where the driver installation steps are introduced: It should rather point to: https://betaflight.com/docs/wiki/boards/BETAFLIGHTF3#driver-related-problems

### Configurator version

10.9.0

### Add any other context about the problem that you think might be relevant here

I couldn't really find the central source of truth for where to download the appropriate drivers, so if there's a better link, that would be better!

**Comment by junwoo091400** [comment]
Note, referencing https://www.reddit.com/r/Multicopter/comments/w9qo32/unable_to_flash_firmwareget_stuck_at_initiating/, this could be worth adding to the helpful programs for driver related fixes as well: https://impulserc.com/pages/downloads

**Comment by haslinghuis** [comment]
The link is fixed in the nightly builds of configurator. Now each tab has it's own wiki page:
https://betaflight.com/docs/wiki/configurator/firmware-flasher-tab

https://betaflight.com/docs/wiki/archive/Installing-Betaflight
