### ISSUE TITLE
Multiple Active Preset Sources

### ISSUE THREAD

**Issue by hughsaunders** [betaflight/betaflight-configurator#3437]
### Is your feature request related to a problem? Please describe

Only one preset source can be active at a time, so I cannot apply official presets and personal presets without switching preset sources.

### Describe the solution you'd like

I would like to store only my presets in my presets repo, then use the rest of the presets from the official repo. Currently I have to switch preset sources to do this. This request is for having multiple sources be active at once. So add all your sources, then pick presets from any of them. 

### Describe alternatives you've considered

I could fork the official repo and add my presets to that, but then I have to keep rebasing it to pull in new/updated official presets.

### Other information

KAACK

**Comment by limonspb** [comment]
> @limonspb ?

totally possible, and on my todo list :)
