### ISSUE TITLE
TCP connection does not work in betaflight configurator nightly

### ISSUE THREAD

**Issue by hnvr324** [betaflight/betaflight-configurator#3450]
### Describe the bug

I cannot connect to my board over TCP address on the nightly configurator, it will recognize it correctly then serial connection closed.

### To Reproduce

try to connect over tcp to nightly configurator

### Expected behavior

board found, serial connection closed after 10 seconds.

### Configurator version

10.10

**Comment by haslinghuis** [comment]
Mdns can be enabled in options tab as this is an experimental feature.
