### ISSUE TITLE
Loading Local Firmware - Incorrect Custom Defaults

### ISSUE THREAD

**Issue by skyfpv** [betaflight/betaflight-configurator#3453]
### Describe the bug

The configurator sometimes applies incorrect custom defaults when loading local firmware. The GUI appears to store which custom defaults to use upon the user pressing the Flash Firmware button. It should, instead, store which custom defaults to use once the user attempts to connect for the first time. Otherwise, the incorrect custom defaults are very likely to be loaded by users flashing local HEXs.

### To Reproduce

1. plug in a flight controller while holding boot button
2. navigate to "Firmware Flasher" tab
3. Make sure the dropdowns say "Choose a Board" and "Choose a Firmware version"
4. Click "Load Firmware [Local]"
5. Select an appropriate HEX for the connected FC
6. Click "Flash Firmware"
7. Note that the dropdown correctly identifies the FC and firmware
8. Click "Connect"
9. Click "Apply Custom Defaults"
10. Click "Connect"
11. Note that the FC is not configured with the correct custom defaults despite correctly identifying the FC and firmware post-flash

### Expected behavior

The configurator should wait until after the user has flashed before selecting which custom defaults to use
OR
The user interface should make clear to the user which board's custom defaults are being applied when the click "Apply Custom Defaults"
OR
The user interface should prevent the user from flashing local firmware without first selecting a board

### Configurator version

10.9.0 (697943b)

### Add any other context about the problem that you think might be relevant here

We discovered this bug after many users reported the issue while flashing Street League HEXs. It can be reproduced by building HEXs from the main Betaflight fork though and is ultimately just a user experience problem. I've also spoken to a couple Betaflight contributors who have run into this whilst developing locally also.

**Comment by haslinghuis** [comment]
Should be solved: https://github.com/betaflight/betaflight-configurator-nightlies/releases

Firmware 4.5.0 no longer uses custom defaults.
