### ISSUE TITLE
cloud build feature selection component is buggy

### ISSUE THREAD

**Issue by GTorreil** [betaflight/betaflight-configurator#3457]
### Describe the bug

I have consistently reproduced buggy behavior from the "tag list" component that handles feature selection for cloud builds. 

A video of the problem is availabile here : https://youtu.be/Zmzu7pTbqzc

### To Reproduce

As shown in the video, remove some features and add one (in my case , servo). 
the feature does not appear but it is selected, some text remains and there's void space in the input. 

### Expected behavior

An example of expected behavior can be found here :

https://vuetifyjs.com/en/components/autocompletes/#usage

Select : 
- [x] clearable
- [x] chips
- [x] multiple

### Configurator version

10.9.0

### Flight controller configuration

```txt
N/A
```

**Comment by haslinghuis** [comment]
Often when I need to add something into Custom Defines mouse was left above - and I'm starting to type into Other Options.
Removing the ability to type in Other Options is probably the solution to this.

**Comment by VitroidFPV** [comment]
I'm not sure what to fix, maybe besides the extra margin on the left. Would it be preferential to try to make the text box behave exactly as the example, or make it purely a select box?

**Comment by haslinghuis** [comment]
Agree - would opt for pure select box.

**Comment by GTorreil** [comment]
Hello, sorry for the late reply. 

UX bugs are very hard to describe, so I hoped my video would help. But I can say for sure that following my STRs lead to behavior that is unexpected and misleading (selected features do not appear, weird text behavior)

With that said, it is not a major roadblock so the best solution might be the most simple, here are some ideas I can think of :
- Exchange the "tag-style inputs" for a set of checkboxes
- Use a list of checkboxes that can be filtered with a filter string 

Cheers,
