### ISSUE TITLE
On 10.9.0 (697943b), with permanently enable expert mode, Custome defines does not show in Firmware Flasher initially

### ISSUE THREAD

**Issue by void-spark** [betaflight/betaflight-configurator#3460]
### Describe the bug

Open Betaflight configuration
Go to Options
Verify Permanently enable export mode is on.
Go to Firmware Flasher
Select board (MATEKF4111RX)
Select firmware version (4.4.1)
**No advanced options show (No Custom Defines / Select commit)**

Also:
If you switch back to Options, and then back to Firmware Flasher, the options do show!
Even without Permanently enable export mode selected

### To Reproduce

See description

### Expected behavior

With Permanently enable export mode on, the advanced options show.

### Configurator version

10.9.0 (697943b)

### Flight controller configuration

```txt
Not relevant
```

**Comment by haslinghuis** [comment]
Fixed in #3301

Try: https://github.com/betaflight/betaflight-configurator-nightlies/releases/tag/v20230512.453
