### ISSUE TITLE
Unable to compile, missing nw-install

### ISSUE THREAD

**Issue by lobo500** [betaflight/betaflight-configurator#3469]
### Describe the bug

Compilation fails with the following error

'
root@debian ~/betaflight-configurator-10.9.0 # yarn install
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/nw-install/-/nw-install-0.3.4.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/root/betaflight-configurator-10.9.0/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
'

I cant seem to find nw-install-0.3.4.tgz anywhere to supply it manually either. 
Attached transcript of what i was doing and yarn-error.log, tried to compile on fresh virtual Debian install.
[yarn-error.log](https://github.com/betaflight/betaflight-configurator/files/11652516/yarn-error.log)
[cliTranscript.txt](https://github.com/betaflight/betaflight-configurator/files/11652519/cliTranscript.txt)

### To Reproduce

Follow the App build via NW.js (windows/linux/macos) or Cordova (android) instuctions.

### Expected behavior

Compilation succeds.

### Configurator version

10.9.0

**Comment by McGiverGim** [comment]
Yes, it's a know error, an external dependency is missing.
It was fixed here https://github.com/betaflight/betaflight-configurator/pull/3462
