### ISSUE TITLE
Jerky data vizualization on beta configurator.

### ISSUE THREAD

**Issue by limhyon** [betaflight/betaflight-configurator#349]
Hi,
The 3D visualization on the first page of configurator looks jerky also accelerometer graph on motor page.
However, cleanflight configurator is not.
Have you found issue like this?

**Comment by mikeller** [comment]
This is often caused by problems with the installation of the WebGL framework that is used to display the animations.

In most cases, uninstallation / reinstallation of the Chrome browser and the Betaflight configurator will fix this.
