### ISSUE TITLE
Unable to flash 2.8.1

### ISSUE THREAD

**Issue by bbbenji** [betaflight/betaflight-configurator#35]
Posting for posterity.

Using BFC 1.2 I was unable to flash my SPRacingF3 board from 2.7.1 to 2.8.1. Using the same `Manual baud rate` and `Full chip erase` options in CFC, it went without a problem. Issue occurred if I downloaded the fw via BFC. I did not attempt to flash the file downloaded directly from BF repo via BFC, only via CFC. Issue may lay here. I probably wont be testing this problem anymore.

**Comment by borisbstyle** [comment]
I actually successfully flashed mine on that way

**Comment by bbbenji** [comment]
I will try to do some testing this weekend and post more info. If anyone else can confirm this working i might as well close it.

**Comment by KiteAnton** [comment]
I just tried flashing 2.8.1 downloaded online via the configurator to a SPRacingF3 board and it worked. The SPRacingF3 board has always been a bit problematic to flash, you need to set manual baud rate and try to unplug/plug in the board some times before it works. That is however not an issue with either betaflight configurator (it is the same in cleanflight configurator) nor betaflight FW.
