### ISSUE TITLE
configurator does not show any icons

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/betaflight-configurator#3518]
### Describe the bug

see on screenshot. icon in taskbar and in left upper corner don't show.

![Screenshot 2023-07-19 153610](https://github.com/betaflight/betaflight-configurator/assets/29702171/b38692a6-30e3-4b89-aa3d-5fca28aaef74)

### To Reproduce

use latest configurator

### Expected behavior

display of the icon

### Configurator version

10.10

**Comment by haslinghuis** [comment]
Any NW.js version above 0.72 seems to handle icon differently.

**Comment by haslinghuis** [comment]
@chmelevskij @McGiverGim any idea here (besides revert the change)
