### ISSUE TITLE
Betaflight Configurator - confusing explaination for DShot/Dynamic Idle setting

### ISSUE THREAD

**Issue by jawz101** [betaflight/betaflight-configurator#3571]
### Describe the bug

![Untitled](https://github.com/betaflight/betaflight-configurator/assets/14151703/f6e26d86-606b-4aba-a1a7-0e330ddc74c3)

### To Reproduce

Under PID Tuning tab, found when hovering over the Dynamic Idle help button

### Expected behavior

A consistent use of either the term DShot Idle or Dynamic Idle if they mean the same thing.

And if the current version of the configurator is for firmware 4.4.x then, according to the pop-up, this setting is no longer relevant- implies that it no longer does anything- then the setting should be removed from the ui altogether.

If the terms DShot Idle and Dynamic Idle are indeed two distinct settings, direct the user to the other setting because I have no idea where it is.

### Configurator version

10.9.0

**Comment by McGiverGim** [comment]
No, it's not. Dshot idle and dynamic idle are the two different ways to set up the speed of the motors when idle. They are not the same.

**Comment by nerdCopter** [comment]
@jawz101 , DShot Idle is this: 
![image](https://github.com/betaflight/betaflight-configurator/assets/56646290/9cedd86a-aa0d-45e3-932a-91fb4c084b67)

**Comment by jawz101** [comment]
That looks like it's called motor idle

**Comment by nerdCopter** [comment]
> That looks like it's called motor idle

it's called "motor" idle, because when you use multishot, it's still an idle. when you use dshot then it's digital (dshot)

**Comment by jawz101** [comment]
So Dynamic Idle is different than DShot Idle - which is a motor idle.  Motor idle can be either Dshot Idle or Multishot Idle.

How about replacing DShot Idle with the term 'Motor Idle' within the Dynamic Idle pop-up so the user can knows to which setting the pop-up description is referring?

**Comment by haslinghuis** [comment]
Static or fixed idle ? @ctzsnooze

**Comment by nerdCopter** [comment]
`Static motor idle` fine by me, but no one ever confused in the past :shrug:

**Comment by haslinghuis** [comment]
![image](https://github.com/betaflight/betaflight-configurator/assets/8344830/49b025aa-a3c1-4d31-aaf7-1d37065f42c7)

Motor idle (%, static) should be hidden when Bidirectional Dshot is enabled.

**Comment by jawz101** [comment]
This is all confusing.  Why can't choices which do not function be hidden if they are not being used?
