### ISSUE TITLE
Firmware list unavailable in betaflight-configurator_10.9.0_win64-portable

### ISSUE THREAD

**Issue by swilkens** [betaflight/betaflight-configurator#3596]
### Describe the bug

When using betaflight-configurator_10.9.0_win64-portable (release), the firmware flasher appears stuck on "loading".

![image](https://github.com/betaflight/betaflight-configurator/assets/13329383/0525d503-4651-4f16-a9c5-065caf6cd923)

Current betaflight-configurator_10.10.0-RC1_win64-portable is working fine.

![image](https://github.com/betaflight/betaflight-configurator/assets/13329383/b3147c7b-f874-4f33-9c4a-8be3d44d3b69)

### To Reproduce

Download betaflight-configurator_10.9.0_win64-portable, unpack and start. Enter the firmware flasher.

### Expected behavior

Show a list of boards and firmware versions.

### Configurator version

10.9.0

### Flight controller configuration

```txt
n/a
```

**Comment by nerdCopter** [comment]
not having the same issue here. maybe internet issue?
https://build.betaflight.com/api/targets online for me.

**Comment by nerdCopter** [comment]
very odd. maybe some system npm_module taking orecedence :shrug: . i did test the portable; however, mine is linux.

**Comment by swilkens** [comment]
Ran a folder compare between portable and installed windows versions, quite some differences found.

![image](https://github.com/betaflight/betaflight-configurator/assets/13329383/e0ed971a-9f4f-42cf-8108-1555d6871320)

For now I'll just used the installed version.

**Comment by nerdCopter** [comment]
concur.

Recommend not using any "shortcuts" as those may be pointing to another installation.  Use only the .exe when using portable versions. Otherwise, maybe delete everything, find all remnants to purge, then try again.

closing this ticket.

**Comment by swilkens** [comment]
@nerdCopter I did some more checking.

Windows 10 PC - Portable not OK, installed version OK
Windows 11 Laptop - Portable OK, installed version OK

I can't explain it. maybe there's some issue I can't find on my PC. but I think I agree that the problem is somehow with me.
