### ISSUE TITLE
OSD Video format forces NTSC mode when CLI opened

### ISSUE THREAD

**Issue by gaoDean** [betaflight/betaflight-configurator#3628]
### Describe the bug

This is just a minor inconvenience issue.

Before CLI tab opened:
<img width="1920" alt="Screenshot 2023-11-09 at 9 06 00 pm" src="https://github.com/betaflight/betaflight-configurator/assets/97860672/b2babe0b-eea1-4e1e-922a-79247c38da4b">

After CLI tab opened:
<img width="1920" alt="Screenshot 2023-11-09 at 9 06 16 pm" src="https://github.com/betaflight/betaflight-configurator/assets/97860672/324cef49-9e36-463e-a830-667c84e1fdc9">

In the OSD tab, if "Auto" is selected under Video Format on the right, and the camera uses PAL mode, the screen height will increase by 2 or 3 blocks as the OSD will auto detect "PAL", which will allow you to place OSD items there. When you save, they will still stay there. 

If you then select "NTSC" under Video Format you will see that the height of the OSD screen will decrease by 2 or 3 blocks, a.k.a the bottom of the screen will go up by like 3 "blocks".

The bug here is that if your OSD auto detects PAL in the OSD tab, you will be able to place items at the bottom of the screen in the extra space. As soon as you open the CLI though, all items placed in the 2-3 extra blocks at the bottom of the screen that PAL provides is moved up above the 2-3 block threshold to fit just within the NTSC frame, and when you go back to the OSD tab, it will auto detect PAL mode, but there will just be empty space in the extra 3 blocks because the items in that space will have been moved up to the NTSC boundary. 

I think when the CLI tab is clicked, it just temporarily defaults the video format to NTSC, which will move the OSD items up to the NTSC boundary. Then when you go back to the OSD tab it will automatically select PAL, which will create the empty space. 

This is just speculation, but perhaps when the CLI tab is opened, it doesn't power up the camera, so it can't auto detect the video mode and just defaults to NTSC. If this is the case, it must run a function to "save" the NTSC format and move the OSD items, which is probably where the problem is.

If you select PAL under Video Format to force it to use PAL, this issue goes away.

PAL: 720 x 576 @ 25fps (extra height)
NTSC: 720 x 480 @ 30fps (less height)

### To Reproduce

1. Use a PAL camera (I don't know how the OSD detects PAL mode but you just need it to auto detect PAL mode)
2. Select Auto mode under OSD tab, Video Format. You want to have it auto detect PAL mode, and you will know it is in PAL mode because when you select NTSC format under Video Format, you will see that the screen height will decrease by a few blocks.
3. Place an OSD item in that extra space (more than one also works, they all collapse on top of each other at the boundary when the video format is reset)
4. Save OSD settings.
5. Click on the CLI tab, wait for it to load, then click back to the OSD tab. 
6. You should see that it has moved the item at the bottom of the screen to just above the boundary of if you used the NTSC video format.

### Expected behavior

When clicking on the CLI tab and then clicking back, I would expect that any item placed at the bottom of the screen would stay there, not be moved up to the edge of the NTSC boundary.

### Configurator version

10.9.0

### Flight controller configuration

```txt
# 

# diff

# version
# Betaflight / STM32F7X2 (S7X2) 4.4.2 Jun  8 2023 / 00:33:18 (23d066d08) MSP API: 1.45

# config: YES

# start the command batch
batch start

board_name IFLIGHT_SUCCEX_E_F7
manufacturer_id IFRC

# name: Nazgul5 V2

# feature
feature -SOFTSERIAL
feature -TELEMETRY

# serial
serial 0 8192 115200 57600 0 115200

# aux
aux 0 0 2 1300 1700 1 0
aux 1 1 1 1300 1700 0 0
aux 2 13 3 1300 1700 1 0
aux 3 35 3 1800 2100 0 0
aux 4 36 4 1800 2100 0 0

# adjrange
adjrange 0 0 5 1800 2100 12 0 0 0

# vtxtable
vtxtable bands 5
vtxtable channels 8
vtxtable band 1 BOSCAM_A A CUSTOM  5865 5845 5825 5805 5785 5765 5745 5725
vtxtable band 2 BOSCAM_B B CUSTOM  5733 5752 5771 5790 5809 5828 5847 5866
vtxtable band 3 BOSCAM_E E CUSTOM  5705 5685 5665 5665 5885 5905 5925 5925
vtxtable band 4 FATSHARK F CUSTOM  5740 5760 5780 5800 5820 5840 5860 5880
vtxtable band 5 RACEBAND R CUSTOM  5658 5695 5732 5769 5806 5843 5880 5917
vtxtable powerlevels 4
vtxtable powervalues 25 100 400 600
vtxtable powerlabels 25 100 400 600

# vtx
vtx 0 6 0 0 1 900 1200
vtx 1 6 0 0 2 1200 1500
vtx 2 6 0 0 3 1500 1800
vtx 3 6 0 0 4 1800 2100

# rxfail
rxfail 3 h
rxfail 15 s 1000

# master
set gyro_lpf1_static_hz = 0
set gyro_lpf2_static_hz = 0
set dyn_notch_count = 2
set dyn_notch_q = 500
set dyn_notch_min_hz = 80
set dyn_notch_max_hz = 650
set gyro_lpf1_dyn_min_hz = 0
set acc_calibration = -39,-33,278,1
set baro_hardware = NONE
set rssi_channel = 16
set rc_smoothing_auto_factor = 60
set serialrx_provider = SBUS
set dshot_bidir = ON
set failsafe_delay = 5
set bat_capacity = 1300
set vbat_max_cell_voltage = 440
set beeper_dshot_beacon_tone = 3
set yaw_motors_reversed = ON
set small_angle = 180
set osd_warn_bitmask = 8189
set osd_rssi_alarm = 40
set osd_cap_alarm = 274
set osd_alt_alarm = 0
set osd_tim2 = 1537
set osd_vbat_pos = 386
set osd_rssi_pos = 2490
set osd_link_quality_pos = 385
set osd_rssi_dbm_pos = 408
set osd_tim_2_pos = 2519
set osd_flymode_pos = 226
set osd_throttle_pos = 386
set osd_vtx_channel_pos = 18468
set osd_crosshairs_pos = 4333
set osd_ah_sbar_pos = 4334
set osd_ah_pos = 206
set osd_current_pos = 392
set osd_mah_drawn_pos = 400
set osd_motor_diag_pos = 8503
set osd_craft_name_pos = 33
set osd_home_dir_pos = 45
set osd_compass_bar_pos = 42
set osd_pid_roll_pos = 65
set osd_pid_pitch_pos = 33
set osd_pid_yaw_pos = 97
set osd_pidrate_profile_pos = 2137
set osd_warnings_pos = 14729
set osd_avg_cell_voltage_pos = 2497
set osd_pit_ang_pos = 4235
set osd_battery_usage_pos = 40
set osd_disarmed_pos = 2283
set osd_esc_tmp_pos = 8439
set osd_esc_rpm_pos = 8311
set osd_esc_rpm_freq_pos = 119
set osd_log_status_pos = 8258
set osd_rate_profile_name_pos = 130
set osd_pid_profile_name_pos = 98
set osd_profile_name_pos = 66
set osd_canvas_width = 30
set osd_canvas_height = 13
set debug_mode = GYRO_SCALED
set vtx_band = 5
set vtx_channel = 8
set vtx_power = 3
set vtx_low_power_disarm = UNTIL_FIRST_ARM
set vtx_freq = 5917
set gyro_1_align_yaw = 1800
set rpm_filter_fade_range_hz = 100
set craft_name = Nazgul5 V2

profile 0

# profile 0
set dterm_lpf1_dyn_min_hz = 70
set dterm_lpf1_dyn_max_hz = 110
set dterm_lpf1_type = BIQUAD
set dterm_lpf1_static_hz = 0
set dterm_lpf2_static_hz = 0
set vbat_sag_compensation = 100
set anti_gravity_gain = 50
set pidsum_limit = 1000
set pidsum_limit_yaw = 1000
set p_pitch = 51
set i_pitch = 0
set f_pitch = 0
set p_roll = 49
set i_roll = 0
set f_roll = 0
set p_yaw = 49
set i_yaw = 0
set f_yaw = 0
set d_max_advance = 0
set feedforward_averaging = 3_POINT
set feedforward_jitter_factor = 10
set feedforward_boost = 19
set dyn_idle_min_rpm = 30
set simplified_i_gain = 0
set simplified_pi_gain = 110
set simplified_feedforward_gain = 0
set simplified_dterm_filter = OFF

rateprofile 0

# rateprofile 0
set thr_mid = 40
set thr_expo = 50
set rates_type = BETAFLIGHT
set roll_rc_rate = 150
set pitch_rc_rate = 150
set yaw_rc_rate = 120
set roll_expo = 30
set pitch_expo = 30
set yaw_expo = 30
set roll_srate = 64
set pitch_srate = 64
set yaw_srate = 64
set throttle_limit_type = CLIP
set throttle_limit_percent = 80

# end the command batch
batch end

#
```

### Add any other context about the problem that you think might be relevant here

I'm flying the analog 4s iflight nazgul5 v2, which comes with a racecam r1 camera (AKA caddx ratel), and the succex force vtx. The FC is the SucceX-E F7, flashed with betaflight 4.4.2

**Comment by haslinghuis** [comment]
Needs investigation.

**Comment by haslinghuis** [comment]
```
// No valid input signal, fallback to default (XXX NTSC for now)
```

https://github.com/betaflight/betaflight/blob/d3488d1345cfa8f760d0d4821dd9b1f0531d3482/src/main/drivers/max7456.c#L298-L310

Okay in AUTO mode the MAX7456 chip detects the camera signal to verify video system setting and then it defaults to NTSC.
While in configurator AUTO defaults to PAL.

**Comment by haslinghuis** [comment]
```
// No valid input signal, fallback to default (XXX NTSC for now)
```

https://github.com/betaflight/betaflight/blob/d3488d1345cfa8f760d0d4821dd9b1f0531d3482/src/main/drivers/max7456.c#L298-L310

Okay in AUTO mode the MAX7456 chip detects the camera signal to verify video system setting and when that fails it defaults to NTSC while in configurator AUTO defaults to PAL.
