### ISSUE TITLE
Cant find the file specified

### ISSUE THREAD

**Issue by kingphan1234** [betaflight/betaflight-configurator#3631]
### Describe the bug

so i uninstalled the old betaflight configurator by deleting it with the trash bin and downloaded the newer version then it said this
![Capture](https://github.com/betaflight/betaflight-configurator/assets/150593997/0a945011-6d0f-448a-bf49-dd93910406c9)
what should I do?

### To Reproduce

uninstalled and download it again

### Expected behavior

the new betaflight configurator can be set

### Configurator version

10.9.0

**Comment by McGiverGim** [comment]
You must delete it manually. Delete the folder on disk and the register entries. I don't remember now the path in the registry.
After that you can install it again.
