### ISSUE TITLE
connect to fc failed

### ISSUE THREAD

**Issue by TheAngularity** [betaflight/betaflight-configurator#364]
@mikeller 
after merging #363 i can not more connect to fc

**Comment by mikeller** [comment]
Doesn't look like #364 is the culprit.

Question: What OS are you having the problems on? I noticed that after a chromium update yesterday on ubuntu, the configurator often stops connecting until a reboot. Chrome on Windows still works fine (but maybe just because the update is still pending).

**Comment by TheAngularity** [comment]
i think it is ... using latest chrome on windows 10 ... here a screenshot:

![zwischenablagebild](https://cloud.githubusercontent.com/assets/20139767/21467375/8c50dd48-c9eb-11e6-8076-1f56411b8e3d.jpg)

**Comment by TheAngularity** [comment]
#366 fixed this for now ... closed
