### ISSUE TITLE
Not Working on Mac

### ISSUE THREAD

**Issue by rmv221** [betaflight/betaflight-configurator#3643]
### Describe the bug

Downloaded the latest Betaflight Configulator. Installed it, but will not work. Can only see header at the top of the page. Yet earlier version ie 10.7.2 will work

### To Reproduce

Run application on Mac High Sierra 10.13.6

Download betaflight-configurator_10.9.0_macOS.dmg
open
drag to apps folder
open BF

### Expected behavior

To be able to use lastest version

### Configurator version

10.9.0

**Comment by nerdCopter** [comment]
try [10.10-rc1](https://github.com/betaflight/betaflight-configurator/releases/tag/10.10.0-RC1)
