### ISSUE TITLE
Save Button on LED Tab not working

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/betaflight-configurator#3691]
### Describe the bug

Save button on LED Tab not working

screenshot console output:
![image](https://github.com/betaflight/betaflight-configurator/assets/29702171/add3bf38-7cfc-4ed7-bc6e-7e9c10a03d06)

### To Reproduce

- go to led tab
- configure led's
- press save button
- go on another tab
- go back to led tab
- config was not saved

### Expected behavior

working save button

### Configurator version

last nightly

**Comment by haslinghuis** [comment]
@TheIsotopes thanks for testing - much appreciated.

**Comment by TheIsotopes** [comment]
@haslinghuis your welcome ;-)

#3692 tested and working
