### ISSUE TITLE
Error in link referring to website

### ISSUE THREAD

**Issue by ortas88** [betaflight/betaflight-configurator#3723]
### Describe the bug

Error in link referring to website. This is the page that allows you to configure VTX Tables
https://betaflight.com/docs/wiki/archive/VTX-tables

### To Reproduce

Video transmiter click Go to this Page

### Expected behavior

change website link https://betaflight.com/docs/wiki/guides/current/VTX-Tables

### Configurator version

10.10.0

**Comment by haslinghuis** [comment]
:confused:  duplicate of #3724
