### ISSUE TITLE
Feature Request: Auto identify board for flasher

### ISSUE THREAD

**Issue by pfriedel** [betaflight/betaflight-configurator#373]
So the board (usually) knows what it is if you ask it with 'version', is there any reason the firmware flashing interface needs to have the end user choose which of fifty three different targets they're using?  This worked back in the baseflight days when we had like eight targets, it's getting a little difficult to keep track of these days.

It seems like the configurator could connect and interrogate the board and select the appropriate firmware from the list.  Add a way to manually select the board type if the user knows better or the board is so challenged it doesn't know what it is and all bases are covered.

i.e. something like this:

Choose a board
(Automatically detect board)
AFROMINI
AIORACERF3
...
ZCOREF3

Clicking on "Load Firmware [Online]" when (Automatically detect board) is selected would update the release info pane with "Target: NAZE32 (Automatically detected)" to provide some degree of cover for misidentified firmwares.

**Comment by mikeller** [comment]
@pfriedel: There is an effort under way to add exactly this. Thanks for showing interest in it.
