### ISSUE TITLE
10.10.0 Release Candidate 2 is marked  as latest stable release

### ISSUE THREAD

**Issue by suschizu** [betaflight/betaflight-configurator#3742]
### Describe the bug

not sure if this is intentional - but a release candidate shouldn't be displayed as latest (stable) release 

### To Reproduce

go to: https://github.com/betaflight/betaflight-configurator/releases

### Expected behavior

should be marked as pre-release (like Betaflight Configurator 10.10.0 Release Candidate 1)

### Configurator version

10.10.0 RC 2

**Comment by nerdCopter** [comment]
thank you , fixed.
