### ISSUE TITLE
MAG declination does not save correctly

### ISSUE THREAD

**Issue by trenth00** [betaflight/betaflight-configurator#3761]
### Describe the bug

This is a bug with the 10.10 RC2 configurator. Under GPS, If I try to use a decimal in the Magnetometer declination, the interface accepts it, but never stores it. Instead it rounds it up/down (e.g I try to store 11.8 but it only stores 12.0). If I enter the declination in the Cli , then it stores it properly. If I then go back into the configurator it will show the correct decimal figure, but once again revert to a rounded up/down figure if I try to save again in the UI

### To Reproduce

Under GPS, enter a declination with a decimal value (e.g.) 11.8. Once saved the declination is rounded up to 12.0

### Expected behavior

The resolution of the declination should be a single decimal digit. I.e. a value of 11.8 should be stored and reported in the CLI as 118

### Configurator version

10.10 RC2

**Comment by nerdCopter** [comment]
seemingly by design. see here math.round, albeit the input allows for decimal.  i don't personally know GPS, maybe @ctzsnooze can report.
```
src/js/msp/MSPHelper.js:1842:            buffer.push16(Math.round(FC.COMPASS_CONFIG.mag_declination) * 10);
```
```
src/tabs/gps.html:63:                                    <label> <input type="number" name="mag_declination" step="0.1" min="0" max="359.9" />
```
