### ISSUE TITLE
GPS/Mag Declination Spinbox appearance

### ISSUE THREAD

**Issue by roofg** [betaflight/betaflight-configurator#3782]
### Describe the bug

While folloing guide for configuration of magnetometer (https://betaflight.com/docs/wiki/guides/current/Magnetometer) I set parameter via CLI:
"set mag_declination=25"
"save"

In the GPS tab under GPS Configuration/Magnetometer Declination the spinbox is not themed as similar visual elements.
![image](https://github.com/betaflight/betaflight-configurator/assets/15089495/6860f0d0-913a-426a-a0f5-9c649a745edc)

### To Reproduce

Via CLI set parameters:
"set mag_declination=25"
"save"

Visit GPS tab.

### Expected behavior

Spinbox should be aligned with appearance e.g: Power&Battery tab
![image](https://github.com/betaflight/betaflight-configurator/assets/15089495/95d719b8-696d-486b-a9cb-70f95d039335)

### Configurator version

10.10.0-RC2(norevision)

**Comment by haslinghuis** [comment]
Fixed in https://github.com/betaflight/betaflight-configurator/pull/3737
