### ISSUE TITLE
Radio protocol lost in 10.10.0 RC2

### ISSUE THREAD

**Issue by kmaxium** [betaflight/betaflight-configurator#3784]
### Describe the bug

<img width="917" alt="微信图片_20240205124923" src="https://github.com/betaflight/betaflight-configurator/assets/122260808/09247da3-cb35-4817-a677-d8490266be63">
<img width="926" alt="微信图片_20240205124935" src="https://github.com/betaflight/betaflight-configurator/assets/122260808/751e743a-0d40-4260-8d11-3c66eb186a45">

### To Reproduce

don't know how, just report the issue.

### Expected behavior

Please fix it in the future release.

### Configurator version

10.10.2 rc2

**Comment by nerdCopter** [comment]
One protocol only in the drop-down is by design.

if you want to **_add_** protocols, then do so in the custom defines field.

example: 
![image](https://github.com/betaflight/betaflight-configurator/assets/56646290/33e339e8-0958-4065-85f6-38d0553ce2f4)

https://hackmd.io/@nerdCopter/H11rvS8Lh

**Comment by kmaxium** [comment]
Got it, many thx
