### ISSUE TITLE
Disable update modal for release candidates

### ISSUE THREAD

**Issue by sundowndev** [betaflight/betaflight-configurator#3791]
### Is your feature request related to a problem? Please describe

Release candidates are not like any other release and should be considered instable. Most users don't know what a release candidate is and will simply update the configurator if it tells them to do so. However it can lead to configuration issues and even lead to fly issues. It's dangerous to use it in the wild, especially when the user has no idea of the consequences.

### Describe the solution you'd like

Do not trigger a modal for release candidates. Instead, trigger it when the version is anterior to the latest stable version.

### Describe alternatives you've considered

N/A

### Other information

N/A

**Comment by haslinghuis** [comment]
Did you check

![image](https://github.com/betaflight/betaflight-configurator/assets/8344830/14a0735f-53a3-4cf7-8494-5479391360a0)

**Comment by haslinghuis** [comment]
Be aware sometimes RC release are needed for later RC firmware releases.

**Comment by sundowndev** [comment]
@haslinghuis my bad, it does the job. Is it enabled by default?

**Comment by sundowndev** [comment]
Thanks for the info. Closing.
