### ISSUE TITLE
[logos] 

### ISSUE THREAD

**Issue by nerdCopter** [betaflight/betaflight-configurator#3797]
### Describe the bug

not very important, but the sponsor logos on Android overflow in the UI
![image](https://github.com/betaflight/betaflight-configurator/assets/56646290/c69a7d78-f0b6-4d34-943e-54b600cd6ab7)

### To Reproduce

`75546e5c`

### Expected behavior

no overflow in layout

### Configurator version

75546e5c

**Comment by haslinghuis** [comment]
@KarateBrot @VitroidFPV
