### ISSUE TITLE
reodered dshot and pid loop 

### ISSUE THREAD

**Issue by TheAngularity** [betaflight/betaflight-configurator#380]
@mikeller 
pls can you check latest #379 ... when i choose dshot600 i can not select a pid loop of 8k or higher only 4k is posible ... but when i choose dshot150 i can select up to 16k

**Comment by wind0r** [comment]
the problem is that https://github.com/betaflight/betaflight/pull/2059 did get merged before https://github.com/betaflight/betaflight/pull/2058 was merged

@mikeller is allready working on it. see https://github.com/betaflight/betaflight/pull/2068

**Comment by TheAngularity** [comment]
working now ... bf api is bumped to 1.26 ... closed
