### ISSUE TITLE
Video transmitter page crashes after loading vtx table from json file if FC.VTX_CONFIG.vtx_power value is greater than TABS.vtx.VTXTABLE_POWERLEVEL_LIST

### ISSUE THREAD

**Issue by chizar** [betaflight/betaflight-configurator#3814]
### Describe the bug

if json file has vtx table that has no current FC.VTX_CONFIG.vtx_power index - UI is crashed due to out of boundary error

### To Reproduce

Video Transmitter page.

1. Add for example 5 power levels.
2. select the latest for Power in "Selected Mode" section (basically set 5 to the FC.VTX_CONFIG.vtx_power)
3. Save
4. Go to Video Transmitter page
5. "Load from file" - upload json file with vtx table, which contains less than 5 power levels
see crashed ui:
<img width="1211" alt="image" src="https://github.com/betaflight/betaflight-configurator/assets/12751826/4a76b09f-3cbe-46d0-bab8-3476b4874761">

### Expected behavior

no error, 
best scenario is set max FC.VTX_CONFIG.vtx_power

### Configurator version

10.9.0

**Comment by haslinghuis** [comment]
1. please provide the json file for testing
2. try configurator 10.10 (nightly build)

**Comment by chizar** [comment]
10.10.0 has the issue, as you can see from the attached screenshot (I've made it from the 10.10.0)
json file:
[Readytosky LST 58G VTX.json](https://github.com/betaflight/betaflight-configurator/files/14386675/Readytosky.LST.58G.VTX.json)

**Comment by nerdCopter** [comment]
using same .json with Feb 22 softwares.
![image](https://github.com/betaflight/betaflight-configurator/assets/56646290/571b5ac0-f7cc-4049-a30e-92fe83328eaf)

**Comment by chizar** [comment]
> using same .json with Feb 22 softwares. 

You just missed first step in the step "To Reproduce" section from my original post.
You have to add 5 powers, select the latest in the "Selected Mode", and after that upload the file.

**Comment by haslinghuis** [comment]
What does F12 dev console show?

**Comment by chizar** [comment]
Sorry, unable to run it via "yarn dev" in browser mode :(
I launch it as "npm start". 
It runs as an application on my mac.

**Comment by chizar** [comment]
yep
got it:

<img width="1104" alt="image" src="https://github.com/betaflight/betaflight-configurator/assets/12751826/b09a74f8-bd13-499e-becb-00bcf60a34b9">

**Comment by haslinghuis** [comment]
Will be back at the office in a few days - do not have hardware to test here.

**Comment by haslinghuis** [comment]
We need to look at the result in cli after step 3 and after step 5 (with fix applied).
