### ISSUE TITLE
Flash local firmware not working since 10.9

### ISSUE THREAD

**Issue by Berlinologe86** [betaflight/betaflight-configurator#3833]
### Describe the bug

I had a problem copter on the table on Saturday and wanted to install the firmware from the manufacturer. Betafpv Pavo pico/pavo 20. (bf4.4.1) I couldn't do this on either Windows or Mac. Cloud building worked on both systems. The configurator never switched to the bootloader and flashed local hex files. Not even with the bootloader activated. The last attempt was to try out 10.8.0. It worked wonderfully with that. Kind regards, Sören

### To Reproduce

Try local firmware upload with 10.9 and 10.8

### Expected behavior

A Little fix ?

### Configurator version

10.8/10.9/10.10

**Comment by nerdCopter** [comment]
Although this document mainly for Windows, please investigate all notes: https://hackmd.io/@nerdCopter/rJv5TUrQ2

Third party dependencies may be involved here (NWjs upon which the UI is based.)

**Comment by Berlinologe86** [comment]
I think you didn't understand me correctly. On Windows and Mac, the local firmware upload only works without problems from version 10.8. This doesn't work with the newer versions 10.9 and 10.10. A system error can therefore be ruled out. Since it works as usual with 10.8. So I don't have a driver problem. The configurator has a problem.

**Comment by josser** [comment]
Same for me for Meteor65 Pro but not working even on 10.8 
1. Opened Configurator. (10.8, 10.9, 10.10-RC3) (Mac, Windows 11)
2. Selected target BETAFPVF411
3. Selected local file. Configurator saying: "Loaded Local Firmware"
4. Clicked "Flash Firmware" and nothing happened. 
![SCR-20240321-bksk](https://github.com/betaflight/betaflight-configurator/assets/103639/4653a6a2-7254-4aff-bd56-c8bebed0e07d)
5. Online flashing works fine, but I want to flash OEM firmware because it has some extra fixes related to OSD. With original Betaflight meteor65 pro has some blinking on 4.3+

**Comment by nerdCopter** [comment]
There may be a bug in some unknown state of workflow.
I suggest running Configurator fresh, and immediately Load-Local without doing anything else first. do not even select any items in drrop-down fields.
![image](https://github.com/betaflight/betaflight-configurator/assets/56646290/cf69e751-44c8-47ba-9047-80cda4914e43)
![image](https://github.com/betaflight/betaflight-configurator/assets/56646290/2ba2ed76-b7c5-4e6c-bb43-61c607caedb9)

**Comment by haslinghuis** [comment]
Have tested local flashing succeeded.

**Comment by josser** [comment]
Could it be somehow related to the "custom" nature of the .hex file? 
It was built by BetaFPV and I bet they made some changes to it.

**Comment by nerdCopter** [comment]
Tested PYRODRONEF7 with 10.9 and two different local .hex -- erased/flashed successfully on Linux.
Tested same with 10.10.-RC3, successfully on Linux. 

**_May be a timing issue, or something specific to local computers._** :man_shrugging: :confused: 

<hr>

Further notes:
10.10-RC3 auto-reconnected after the v4.5 reboot as well; However there was no reboot with the v4.4.3.

4.5 + 10.10-RC3:
```
2024-03-21 @08:28:42 -- Erased 512 kB of flash successfully
2024-03-21 @08:29:03 -- USB device successfully closed
2024-03-21 @08:29:05 -- Query board information to preselect right firmware
2024-03-21 @08:29:05 -- MultiWii API version: 1.46.0
2024-03-21 @08:29:05 -- Configurator has successfully detected and verified the board: PYRODRONEF7
```
auto-reconnected and shows limited buttons:
![image](https://github.com/betaflight/betaflight-configurator/assets/56646290/77dc7557-0026-4fdc-b3b4-b037822e215e)

**Comment by nerdCopter** [comment]
> Could it be somehow related to the "custom" nature of the .hex file? It was built by BetaFPV and I bet they made some changes to it.

Interesting!Yes, if HEX fails parsing/checks, it may not enable Flashing.

**Comment by josser** [comment]
https://github.com/betaflight/betaflight-configurator/assets/103639/8f1001ee-1f68-4960-bfab-758927b42d93

Video demo

**Comment by nerdCopter** [comment]
please post a link to the BetaFPV hex.

**Comment by josser** [comment]
https://support.betafpv.com/hc/en-us/article_attachments/13093661336729

**Comment by nerdCopter** [comment]
Hex problem, IMHO. 

![image](https://github.com/betaflight/betaflight-configurator/assets/56646290/99a4be20-8c24-4142-a637-bce60dd52e68)

**Comment by josser** [comment]
Hm, that's correct, BetaFPV provides CLI-dump but tells 
"CLI for quadcopter (Do not need to be flashed separately):"
Is there any way to bypass this check?

**Comment by Berlinologe86** [comment]
https://support.betafpv.com/hc/en-us/articles/21133140518937-CLI-and-Firmware-for-Pavo-Pico-F405-2-3S-20A-V1-0-FC

**Comment by nerdCopter** [comment]
i don't know for fact, but i think that the hex points to an incorrect memory address. nothing to do with the .txt file even though i did experiment with it on the second try.

**Comment by Berlinologe86** [comment]
https://support.betafpv.com/hc/en-us/articles/23244448530201-CLI-and-Firmware-for-Pavo-20-F405-2-3S-20A-V1-0-FC

**Comment by nerdCopter** [comment]
> [support.betafpv.com/hc/en-us/articles/23244448530201-CLI-and-Firmware-for-Pavo-20-F405-2-3S-20A-V1-0-FC](https://support.betafpv.com/hc/en-us/articles/23244448530201-CLI-and-Firmware-for-Pavo-20-F405-2-3S-20A-V1-0-FC)

same result. thank you both. someone else with further knowledge will need to take-over. or maybe BetaFPV need to be informed.?
![image](https://github.com/betaflight/betaflight-configurator/assets/56646290/6338738d-0e43-4c05-884d-1b3845cc99d4)

**Comment by josser** [comment]
I've contacted BetaFPV support and they told me the following: 

>  We need to use BF 10.8.0 to flash the custom firmware, and if we encounter a stuck situation, we can solve it by restarting BF, as shown in the video.
> https://drive.google.com/file/d/1iirpJmA30ne1AWNkYhNOM5qIPuDGoaXC/view?usp=drive_link

I've tried this and everything is worked! 

I think it's solution for all betafpv bnf quads.

Now I'm not sure is it a bug or it's expected behaviour ) 
But this issue is helpful for those who will face same issues.

**Comment by haslinghuis** [comment]
![image](https://github.com/betaflight/betaflight-configurator/assets/8344830/786e884d-30d5-4699-a106-4028fd2c9e61)

**Comment by haslinghuis** [comment]
For reference: this was the `diff` the board came with. ACC + GYRO were not recognized. After flashing 4.5RC3 it works.

[BTFL_cli_PAVO_PICO_20240322_171322_BETAFPVF405.zip](https://github.com/betaflight/betaflight-configurator/files/14725602/BTFL_cli_PAVO_PICO_20240322_171322_BETAFPVF405.zip)
