### ISSUE TITLE
BF GUI RC3 Android App - Presets not loading

### ISSUE THREAD

**Issue by Canaill51** [betaflight/betaflight-configurator#3839]
### Describe the bug

From BF GUI RC3 on Android app, Presets are not being loaded

See the video as attached.
https://youtu.be/3gEgdT-oNEc

### To Reproduce

Install BF GUI RC3 on an Android Smartphone
Connect to FC flashed on BF 4.5
Go Presets Tab and select one (ex: HD, ELRS, etc...).

### Expected behavior

Presets selected should be downloaded to apply then to FC.

### Configurator version

betaflight-configurator_10.10.0-RC2-debug-norevision

**Comment by haslinghuis** [comment]
Connected with FC the preset tiles show up here.

Going back to nightly builds to find the culprit - now on 29 january - still gives the `Error loading presets from the internet` error message.

**Comment by ASDosjani** [comment]
I tested the nightly android build. On windows it's fine.

**Comment by haslinghuis** [comment]
Debugging android shows the following the download has been blocked by CORS policy:

![image](https://github.com/betaflight/betaflight-configurator/assets/8344830/fce7b8a8-995a-4554-b150-024d0d1bb626)

**Comment by ASDosjani** [comment]
We fixed this issue a while back😂

**Comment by ASDosjani** [comment]
I added cleartext support in this PR:
https://github.com/betaflight/betaflight-configurator/pull/3095/files#diff-2431b1e97cd2951b5d8333ad7094652ff5f7131b63509116e2531122a2d8a94a

**Comment by Canaill51** [comment]
Do you guys, need anything else from me?

**Comment by limonspb** [comment]
> Do you guys, need anything else from me?

Could you please test if backup preset source works? (Deactivate the main, and activate backup)

**Comment by haslinghuis** [comment]
Maybe @atomgomba might know a solution

**Comment by ASDosjani** [comment]
Backup works for me

**Comment by Canaill51** [comment]
> > Do you guys, need anything else from me?
> 
> Could you please test if backup preset source works? (Deactivate the main, and activate backup)

Yes, it's working. Just tried / tested:
https://youtu.be/K0TkzgZqJzo?si=8_VeiS3FeUup0qEn

However, "Backup" is still available up to 4.4 firmware.

**Comment by Canaill51** [comment]
@HThuren , not sure why you assigned this issue to me :)

**Comment by Canaill51** [comment]
Hi guys,
What are the next steps for this? Will it be fixed when Released?

**Comment by haslinghuis** [comment]
@Canaill51 Seems to work now for me now. There was an issue with CORS policy...

**Comment by SupaflyFPV** [comment]
Tested using this config on old android phone

https://github.com/betaflight/betaflight-configurator/releases

Works as expected for me.

@Canaill51 can you confirm?

**Comment by Canaill51** [comment]
@haslinghuis, @SupaflyFPV , just tried and tested: Works now!

Thanks all for your help (as always!). Really appreciate
