### ISSUE TITLE
Asset missing from RC3 release page

### ISSUE THREAD

**Issue by placidblob** [betaflight/betaflight-configurator#3841]
### Describe the bug

The asset `betaflight-configurator_10.10.0-RC3_linux64-portable.zip` is not in the downloads page.

### To Reproduce

- go to https://github.com/betaflight/betaflight-configurator/releases/tag/10.10.0-RC3
- there is no download link for `Linux (others)`

### Expected behavior

There should be a download link for the file `betaflight-configurator_10.10.0-RC3_linux64-portable.zip`

### Configurator version

10.0.0-RC3

**Comment by haslinghuis** [comment]
- Will be fixed for next release in #3840
- In the mean time you could grab a portable from [nighlies](https://github.com/betaflight/betaflight-configurator-nightlies/releases)
