### ISSUE TITLE
Change TPA rate and Breakpoint to Percentages for ease of understanding

### ISSUE THREAD

**Issue by ChrisRosser** [betaflight/betaflight-configurator#3844]
### Is your feature request related to a problem? Please describe

For newer pilots TPA rate and breakpoint are somewhat obscure. It's not always clear to them that throttle goes from 1000 to 2000 as this isn't really the case any more with Dshot. 

TPA rate is clearer but might make even more sense as a percentage attenuation. 

### Describe the solution you'd like

Presenting TPA rate and TPA breakpoint as percentages (and perhaps converting to 1000-2000 behind the scenes) and adding a tooltip explaining TPA would resolve this problem.

<img width="321" alt="image" src="https://github.com/betaflight/betaflight-configurator/assets/41840611/1bdce652-e517-4fc3-906a-0dc56fe233fa">

1350 would become 35%.
0.65 would become 65%.

### Describe alternatives you've considered

I don't see the need to change anything in BF I think this could just be a configurator tweak.

**Comment by nerdCopter** [comment]
@ChrisRosser , my opinion is only a personal one. If the PR i made is not acceptable, then you can certainly open debate for other devs' attention. thank you.

**Comment by haslinghuis** [comment]
Is it okay now @ChrisRosser  ?

**Comment by ChrisRosser** [comment]
Hi Mark,

TPA rate is now very clear thank you!

I still take issue with using us for throttle.

1. Motor output limit on the same page is a percentage.

2. No-one uses PWM for throttle anymore.

Thanks,

Chris

**Comment by haslinghuis** [comment]
@ChrisRosser did a take 3 - see above - but it does not correlate with blackbox. See comment in PR.
