### ISSUE TITLE
Yaw RC Rate forced to zero, MaxVel = NaN

### ISSUE THREAD

**Issue by riquezjp** [betaflight/betaflight-configurator#385]
Using bf2.9.0 & Config: 1.8.7 
Yaw PID RC Rate is broken.
It is set to 0.00 & cannot be changed. PID graph doesnt show due to this error.
Max Vel cannot be calculated.
![screen shot 2017-01-11 at 11 37 46 pm](https://cloud.githubusercontent.com/assets/10734045/21853570/057c7268-d85b-11e6-9f73-c4b88fee5e27.png)

**Comment by borisbstyle** [comment]
Please upgrade to 3.0 or 3.1 version. 

Older versions than 3.0 will not be maintained in the configurator. Especially the yaw rc rate was a workaround to get it working.

**Comment by riquezjp** [comment]
Ok. I understand you have to focus on the new versions. I have downloaded 1.8.5
I dont wish to update any further on this quad as its taken 6 months to get it just right, I cant keep up :-0 :-D

**Comment by mikeller** [comment]
Ok. You can still use the CLI to set your values. Or upgrade to 2.9.1, which only fixes some bugs present in 2.9.0.

**Comment by borisbstyle** [comment]
You can indeed also use cli. The configurator only doesnt display it correctly
