### ISSUE TITLE
Make Throttle Preview in Rates Tab Respect Throttle Limit/Scale Settings

### ISSUE THREAD

**Issue by ChrisRosser** [betaflight/betaflight-configurator#3852]
### Is your feature request related to a problem? Please describe

It would be cool if the throttle preview curve respected your throttle limit clip/scale settings. No need to change any functionality, this is purely a cosmetic enhancement to improve understanding of the settings.

### Describe the solution you'd like

scaling the max of the curve if throttle limit is set to scale:
<img width="335" alt="image" src="https://github.com/betaflight/betaflight-configurator/assets/41840611/24e6eb6c-4725-4897-a7bd-604aacb05905">

showing a flat section at the top of the curve if throttle limit is set to clip
<img width="341" alt="image" src="https://github.com/betaflight/betaflight-configurator/assets/41840611/2c944bb7-a4c2-4143-a09d-106d0321cff3">

### Describe alternatives you've considered

No alternatives relevant.

**Comment by McGiverGim** [comment]
Hi! I'm looking into this. I don't use myself this, so I'm not too sure how must it look exactly.
The mode SCALE seems clear that it reduces in the vertical to the % configured.
The mode CLIP I'm not sure what it does. It removes the right part of the curve starting in the % configured replacing it for a horizontal line?

**Comment by ChrisRosser** [comment]
Hi!

Yes you're right that scale, proportionally reduces the Y value across the range.

Clip limits the maximum Y value on the graph. if(Y > Clip): Y= Clip

**Comment by McGiverGim** [comment]
But in the clip option the "expo" and other values, are calculated like if the graph was all the canvas and then it "erases" the righ part?  Or it reduces the graph to the proportional part?
I think is the first option, but I'm not sure.

**Comment by ChrisRosser** [comment]
Throttle limit is applied after the expo calculation. Calculate the throttle expo curve as normal then set all values where Y > Clip to Y = Clip

**Comment by McGiverGim** [comment]
Ok, understood!
