### ISSUE TITLE
In column of Power & Battery, there is no fields to fill Voltage & Current when i click the "calibrate" button. 

### ISSUE THREAD

**Issue by Signal99** [betaflight/betaflight-configurator#3856]
### Describe the bug

In column of Power & Battery, there is no fields to fill Voltage & Current when i click the "calibrate" button. 
![截图_选择区域_20240323231038](https://github.com/betaflight/betaflight-configurator/assets/87796693/f93e8356-f214-4bd3-95ba-f404e273bcfb)

### To Reproduce

Every time i click the button of "Calibrate", it happens.

### Expected behavior

Calibrate Voltage & Current.

### Configurator version

10.9

**Comment by haslinghuis** [comment]
![image](https://github.com/betaflight/betaflight-configurator/assets/8344830/cb48a778-8863-4ea5-9392-69aba0747096)

After applying power to the ESC and rebooting FC:
![image](https://github.com/betaflight/betaflight-configurator/assets/8344830/e1005e44-90bd-4d4b-9b7c-71230ba3c180)

**Comment by Signal99** [comment]
Thanks for ur reply. finally, i got the answer. 
actually, i powered the ESC. But i didnt calibrated the Voltage manually, so the ESC got a wrong voltage, it seems like hav no battery.  
thanks.
