### ISSUE TITLE
[feature request] 2 Profiles for "Power & Battery" Tab

### ISSUE THREAD

**Issue by bim4n** [betaflight/betaflight-configurator#3891]
### Is your feature request related to a problem? Please describe

When I fly my Long Range copter, the "Power & Battery" Tab is configured for LiPo. But sometimes I use Li-Ion battery and then the config doesn't match for that. A connected buzzer then starts to beep loudly.That would be unnecessary.

### Describe the solution you'd like

For Long Range copter it could be very nice I have **2 Profiles**. 
One Profile for **LiPo**'s and another for **Li-Ion** batteries.

### Describe alternatives you've considered

Manuell config this Tab, but it's not nice ...

**Comment by chrispijo** [comment]
I would also like this feature

**Comment by bim4n** [comment]
Yes, that would be a very useful Feature !
And I am sure that many pilots would have liked it ...

**Comment by YarosMallorca** [comment]
We should look into this, would be nice!
