### ISSUE TITLE
Add selection for delta method in PID tab

### ISSUE THREAD

**Issue by borisbstyle** [betaflight/betaflight-configurator#39]
I think a little dropbox above pids would be nice to be able to select between delta on measurement and delta on error.

**Comment by nathantsoi** [comment]
almost done w/ this...

![screen shot 2016-06-24 at 1 45 18 am](https://cloud.githubusercontent.com/assets/399770/16332893/5304631c-39ad-11e6-8c0f-df0df299ba84.png)

**Comment by borisbstyle** [comment]
Awesome nathan!

Can you also add the filter selection. Maybe as a tab
Op 24 jun. 2016 10:45 schreef "Nathan" <notifications@github.com>:
