### ISSUE TITLE
Angle mode not going yellow but horizon is?

### ISSUE THREAD

**Issue by Afronutella** [betaflight/betaflight-configurator#3918]
### Describe the bug

i just upgraded my build to 4.5 from 4.1, i did a clean build but the angle mode will not go yellow for some reason. so i tried rolling back the release to 4.4.3 but that still did nothing. am i missing something? (acc is on and calibrated, everything eles is on default). 

![Capture](https://github.com/betaflight/betaflight-configurator/assets/168411590/ce0f41e1-4942-477d-9e12-ba58cdfb0653)
![Capture2](https://github.com/betaflight/betaflight-configurator/assets/168411590/c8ddaaa9-b795-4c9b-8266-8508b6d5fc20)
![Capture3](https://github.com/betaflight/betaflight-configurator/assets/168411590/c22ea055-718c-417f-8f08-20d9abcf689e)
![Capture4](https://github.com/betaflight/betaflight-configurator/assets/168411590/e1612a84-0cfb-40df-b289-a474c31b297f)

### To Reproduce

just flash and go to modes 

### Expected behavior

for angle to go yellow when pressed

### Configurator version

4.5 and 4.4.3

### Flight controller configuration

```txt
# version
# Betaflight / STM32F405 (S405) 4.5.0 Apr 28 2024 / 02:32:10 (c155f5830) MSP API: 1.46
# config rev: 3068e6e

# start the command batch
batch start

board_name OMNIBUSF4SD
manufacturer_id AIRB

# feature
feature INFLIGHT_ACC_CAL
feature SOFTSERIAL
feature TELEMETRY
feature LED_STRIP
feature OSD

# serial
serial 5 64 115200 57600 0 115200

# aux
aux 0 0 1 1825 2100 0 0
aux 1 1 2 1800 2100 0 0
aux 2 2 2 1400 1650 0 0
aux 3 13 4 1700 2100 0 0
aux 4 35 3 1800 2100 0 0

# master
set acc_calibration = 13,-23,55,1

profile 0

rateprofile 0

# end the command batch
batch end
```

**Comment by nerdCopter** [comment]
mine works when i click `save`.
![image](https://github.com/betaflight/betaflight-configurator/assets/56646290/4babc33a-0237-4cdd-a560-c6dca79d184d)
![image](https://github.com/betaflight/betaflight-configurator/assets/56646290/84aae730-4a4f-422f-a2b0-bfada230d526)

i would have asked if accel is enabled, but i see it is.  is it calibrated as well?  
doubtful, but maybe is your arming angle not sufficient?
![image](https://github.com/betaflight/betaflight-configurator/assets/56646290/36fc3056-8cc7-41d1-b344-e4c4d85e0010)

**Comment by Afronutella** [comment]
Its enabled and calibrated. Not sure why its not working tho. Arming angle is 25 and ive tried flipping the drone while the button is on. But if that was the problem then horizon should also not activate. 

Think next im gonna roll it back at 4.2/4.3 and see if its the FC thats the issue. 

Also i checked the dump and its registering in AUX. So im stumped ngl.

**Comment by Afronutella** [comment]
Yea i cant figure out why this is happening. If anyone has any ideas or thoughts it would be greatly appreciated. 

Also on the modes section angle is a lighter shade of grey for some reason as if its not been used. But it obviously has

**Comment by haslinghuis** [comment]
:confused: Works here as expected

**Comment by Afronutella** [comment]
Damn ill just have to use horizon as angle if i ever need and just change the strength and trans. Ty tho

**Comment by NaorFPV** [comment]
i have the same issue, airmode also will not light yellow.. with BF4.5 release

**Comment by SteveCEvans** [comment]
Using the MSP radio emulator so you can see the AUX 1 position on screen, see below. It's working as it should.

![image](https://github.com/betaflight/betaflight-configurator/assets/11480839/16d0cd49-bd09-4e7d-8ec3-21008b142672)

![image](https://github.com/betaflight/betaflight-configurator/assets/11480839/8c6b448f-a7b5-4469-9b65-6bb954f735ef)

![image](https://github.com/betaflight/betaflight-configurator/assets/11480839/9ddebab3-3d3d-4d1f-9756-8d4b4d1b2cd9)

Am I missing something?

**Comment by NaorFPV** [comment]
![airmode](https://github.com/betaflight/betaflight-configurator/assets/169043025/63b686a2-3610-40be-b225-24dec7d102f3)
![angel](https://github.com/betaflight/betaflight-configurator/assets/169043025/0be7a61d-07bb-43b3-a667-6a8dc893341a)

**Comment by haslinghuis** [comment]
@NaorFPV try light mode and it works.

Found the issue started in be0103f

@McGiverGim please have a look at it.

**Comment by Afronutella** [comment]
yup perfect it works on light mode only. ty guys 
![light mode](https://github.com/betaflight/betaflight-configurator/assets/168411590/f8d3a72b-6c0a-4735-8d7f-1a29d08a70cd)

**Comment by Afronutella** [comment]
and works with the fix on dark 
![dark mode](https://github.com/betaflight/betaflight-configurator/assets/168411590/57c70742-7235-42bd-a595-191e7a922334)
