### ISSUE TITLE
two new osd fonts...

### ISSUE THREAD

**Issue by DeepnineRC** [betaflight/betaflight-configurator#392]
I made two different font for the internal osd.

The first is a extralage font, i looks like the EZOsd font. I found it some years ago, i don't know where the file came from. I modified it to fit betaflight osd.

The second one is from me. I tried a "betaflight" font but is very small. I don't think its good for flying.

![btfl_extralarge](https://cloud.githubusercontent.com/assets/16404343/21986870/809eb43e-dc01-11e6-84c9-9394816654a8.png)
[btfl_extraLarge.zip](https://github.com/betaflight/betaflight-configurator/files/708661/btfl_extraLarge.zip)

![btfl_btfont](https://cloud.githubusercontent.com/assets/16404343/21986871/80a16c6a-dc01-11e6-9586-980448cd6db2.png)
[btfl_btFont.zip](https://github.com/betaflight/betaflight-configurator/files/708662/btfl_btFont.zip)

Feel free to do what ever you like with the fonts. Maybe someone would like to add them to the configurator.

**Comment by mikeller** [comment]
I like the first one, it's got a very good readability.

**Comment by DeepnineRC** [comment]
Thats the one i'm using for mwosd for years. :-)

Can someone add them to the configurator? I can't get the git stuff working.

**Comment by DanNixon** [comment]
Added them in #410.

Love the extra large font, much easier to read when wearing goggles for me.

**Comment by toddco** [comment]
Thanks, so much for the large font, better than stock. So much easier on my eyes.
