### ISSUE TITLE
BlackBox Tab: Remove "Save File to file" button

### ISSUE THREAD

**Issue by Canaill51** [betaflight/betaflight-configurator#3943]
### Is your feature request related to a problem? Please describe

Hi team,
Regarding to this button "Save File to file" in Blackbox tab, is there a specific reason that it still does exist?

Actually, reading at its comment, seems like it is not recommended to use it. The way to go is "Activate Mass Storage Device Mode" button.

Maybe removing this button would be a good idea?

Thanks to this, users would not have to choice which button to use, as there is one button only available.

### Describe the solution you'd like

Remove "Save File to file" button from Blackbox Tab.

### Describe alternatives you've considered

Use the existing and recommended "Activate Mass Storage Device Mode" button.

**Comment by Canaill51** [comment]
![Blackbox Menu](https://github.com/betaflight/betaflight-configurator/assets/56505305/6b91ecb2-04c6-478c-9bf4-753353c72b28)

**Comment by haslinghuis** [comment]
I am still using that feature during development on linux as I'm lazy to use the Mass Storage Mode.

**Comment by haslinghuis** [comment]
Maybe could make it expert only option first. Or perhaps experimental option.
