### ISSUE TITLE
nwjs >=0.85.0 is unusable

### ISSUE THREAD

**Issue by qubitnano** [betaflight/betaflight-configurator#3947]
### Describe the bug

When running with nwjs >=0.85.0 the app doesn't render properly

### To Reproduce

Build betaflight-configurator 10.10.0 with nwjs 0.85.0, 0.86.0 or 0.87.0 on linux

### Expected behavior

App renders

### Configurator version

10.10.0

**Comment by haslinghuis** [comment]
- We still are using NWjs 0.72
- Did not implement #3695
- We are abandoning NWjs soon
