### ISSUE TITLE
OSD timer selection results in different timer in OSD

### ISSUE THREAD

**Issue by ApexStudioFPV** [betaflight/betaflight-configurator#3981]
### Describe the bug

In the OSD tab, selecting a certain type of timer for Timer 1 and Timer 2 result in a different type of timer actually displaying in the OSD. 
Selecting "On time" in BF config. gives me the "Last armed time" timer in my OSD.
Selecting "Last armed time" in BF config. gives me the "On time" timer in my OSD.
Selecting "On/armed time" in BF config. gives me the "Total armed time" timer in my OSD.
Selecting "Total armed time" in BF config. gives me the "On/armed time" timer in my OSD.

### To Reproduce

Enable OSD element Timer 1 on OSD profile 1
Select Total armed time in Timer 1 drop down selection
Save and disconnect.
Power on quad and goggles to find the On/armed time timer is actually displaying in the OSD

### Expected behavior

Expected Total armed time timer to be displayed in OSD

### Configurator version

10.10.0

### Add any other context about the problem that you think might be relevant here

I first noticed this on my Emax Babyhawk II HD flight controller. The problem also is present on my JBF7 v2 flight controller. Both FCs are running Betaflight 4.4

**Comment by haslinghuis** [comment]
Fixed in #3894
