### ISSUE TITLE
"Reorder motors" wizard uses to small idleThrottleValue

### ISSUE THREAD

**Issue by shukari** [betaflight/betaflight-configurator#3989]
### Describe the bug

No motor is spinning in the "Reorder motors" wizard because it uses 1060 as idleThrottleValue but my motors start to spin at 1070. I have a Mobula8 Walksnail edition and i dont know why my motors start so late.
[Code line](https://github.com/betaflight/betaflight-configurator/blob/a6e3761c26cdd9515476a70e4153c35e87018cfc/src/js/tabs/motors.js#L1235)

It was apparently changed here, but now its to low https://github.com/betaflight/betaflight-configurator/pull/2770

### To Reproduce

1. open "Reorder motors" wizard
2. accept warning
3. you should select the spinning motor
4. no motor is spinning

### Expected behavior

a motor should spin

### Configurator version

10.10.0

### Add any other context about the problem that you think might be relevant here

It would be nice if there would be a cli setting to change that value or it should use the idle setting

**Comment by haslinghuis** [comment]
@atomgomba @limonspb should we revive #2766

**Comment by atomgomba** [comment]
> @atomgomba @limonspb should we revive #2766

Though not sure how much the base branch has diverged in the meantime, but I would gladly help implementing a UI widget for this again

**Comment by haslinghuis** [comment]
A ... lot :rofl:  - but reorder motors is somewhat isolated from refactoring.

**Comment by limonspb** [comment]
that be neat to have... Maybe just in the general settings? Since it's very unusual thing to twek

**Comment by YarosMallorca** [comment]
Why not use the static idle value for this?

**Comment by haslinghuis** [comment]
Or dynamic value

**Comment by jazzroutine** [comment]
And for me interface after hitting "reorder motors" or "motor directions" is just blank window. Only in browser. 
In dedicated Windows app or on Android phone everything is fine. 
![Screenshot 2024-09-03 152129](https://github.com/user-attachments/assets/e70e7aee-859e-4077-811b-4bf7bfea2325)
