### ISSUE TITLE
Todo: Change firmware source to enable flashing BF directly from configurator

### ISSUE THREAD

**Issue by skaman82** [betaflight/betaflight-configurator#4]

**Comment by borisbstyle** [comment]
Yes this is needed too! Thanks for helping man!

**Comment by skaman82** [comment]
This could be helpful: https://github.com/iNavFlight/inav-configurator/pull/5/commits/fc60f02b81bd7a288229ca4a06bf4794388aaaac

**Comment by borisbstyle** [comment]
Where does the configurator get its files from. Github links?

**Comment by skaman82** [comment]
@borisbstyle yes it seem so. see the change in inav configurator to get this done: iNavFlight/inav-configurator@fc60f02
