### ISSUE TITLE
[Idea] Firmware Flasher, change firmware selector

### ISSUE THREAD

**Issue by bilson** [betaflight/betaflight-configurator#40]
In firmware flasher tab, firmware selector is very long and with version 3.0, each new version adds ~30 new targets. I think is a good idea change to two select box, one with firmware version, and second with target list.

**Comment by borisbstyle** [comment]
good idea indeed

**Comment by skaman82** [comment]
I think ist would be more helpful the other way around. First select target then select all the versions

**Comment by blckmn** [comment]
I think @skaman82 is right. Target, then version.

It would be good to get v3.0.0 in there now as unstable for testing ? thoughts @borisbstyle @martinbudden

**Comment by mikeller** [comment]
@blckmn: Sounds like a good idea. Maybe have a checkbox 'Show pre-release versions', and present the user a 'be aware that these versions may fail and cause damage, do bench test first' dialog?
