### ISSUE TITLE
using BLE to connect to Betaflight Configurator, got serial corruption/CRC errors

### ISSUE THREAD

**Issue by bluemoon-i** [betaflight/betaflight-configurator#4027]
### Is your feature request related to a problem? Please describe

I am using BLE to connect to Betaflight Configurator, but it freezes intermittently. The error is serial corruption/CRC errors

### Describe the solution you'd like

1

### Describe alternatives you've considered

1

**Comment by nerdCopter** [comment]
https://github.com/betaflight/betaflight-configurator/pull/4024#issuecomment-2167176894
