### ISSUE TITLE
 Does not work with version 4.6

### ISSUE THREAD

**Issue by Samodelkin-YouTube** [betaflight/betaflight-configurator#4032]
### Describe the bug

Compiled firmware 4.6 for my own DIY FC. After that, the configurator does not want to start
![3456789](https://github.com/betaflight/betaflight-configurator/assets/45720006/5e393373-efe2-4ce7-bbdd-51eaf9e95b20)

### To Reproduce

\\\\\

### Expected behavior

Launching the configurator and setting up the flight controller

### Configurator version

10.10.0

**Comment by haslinghuis** [comment]
*For 4.6 we need https://app.betaflight.com. We had much support issues where people were using an older configurator with newer firmware. This way we also gain early feedback from users using firmware 4.6*

**Comment by Samodelkin-YouTube** [comment]
> _For 4.6 we need https://app.betaflight.com. We had much support issues where people were using an older configurator with newer firmware. This way we also gain early feedback from users using firmware 4.6_
Does it only work with 4.6?  Is it possible to work with old versions?
Also I couldn't find version 11 of the configurator.

**Comment by haslinghuis** [comment]
11.0 supports firmware 4.3 - 4.6

**Comment by Samodelkin-YouTube** [comment]
OK. Thanks

**Comment by YarosMallorca** [comment]
@haslinghuis Where is the github repo for the 11.0 Betaflight Configurator?
Can't find the source code for it.

**Comment by haslinghuis** [comment]
@YarosMallorca you already have it forked :upside_down_face:

**Comment by haslinghuis** [comment]
Try chrome or chromium.

For Ubuntu it needs an non sand boxed installation - not the snap version.

**Comment by YarosMallorca** [comment]
Currently not supported on browsers that aren't Chrome, Edge and Opera.

Check this compatibility list: https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API#browser_compatibility

**Comment by Yamboss** [comment]
still can't find a betaflight configurator for 4.6 and the web don't work on my mac... i really want to test the alt mode on the new 4.6 i was waiting for it.

**Comment by YarosMallorca** [comment]
@Yamboss Make sure you use Chrome, the Betaflight PWA version (online) works, can confirm on my MacBook Air M3.
