### ISSUE TITLE
Easy language change after installation

### ISSUE THREAD

**Issue by szafranski** [betaflight/betaflight-configurator#4110]
### Is your feature request related to a problem? Please describe

I cannot change the language of the BF configurator. 

### Describe the solution you'd like

Drop-down menu in the settings tab

### Describe alternatives you've considered

Change during reinstallation

### Other information

Sorry if that's something that seems stupid but I tried to find the solution and even re-installation with clearing the installation path is not seeming to work. Thanks

**Comment by haslinghuis** [comment]
Language can be changed at the bottom of the Welcome tab.

**Comment by j4k0xb** [comment]
The Welcome tab is mainly for displaying information, and I didn't expect a setting there (having to scroll down to see it made it even harder to find).
imo it makes more sense to put it in the options tab
