### ISSUE TITLE
PWA - modes: add 2nd range not working properly. 

### ISSUE THREAD

**Issue by nerdCopter** [betaflight/betaflight-configurator#4139]
### Describe the bug

in the PWA modes tab, adding a secondary range is not adding the UI for the secondary range.

### To Reproduce

PWA: modes: add range + add range.

### Expected behavior

add secondary, tertiary, etc ranges,

### Configurator version

PWA master 11.0

- https://discord.com/channels/868013470023548938/1274425606716788758

**Comment by nerdCopter** [comment]
![image](https://github.com/user-attachments/assets/5fdf6c21-f07b-421a-a695-2bc6e93f2783)

**Comment by haslinghuis** [comment]
@VitroidFPV please have a look
