### ISSUE TITLE
[Feature request] Modes auto recognize correct AUX channel based on movement

### ISSUE THREAD

**Issue by MathijsG** [betaflight/betaflight-configurator#414]
A minor 'issue' I always encounter with this configurator is that you need to switch between the 'receiver' tab and the 'modes' tab all the time, just to see which AUX channel is mapped to which axis or switch.

Wouldn't it be possible to (maybe optionally?) possible to switch to the current AUX that has a change of value? Or maybe see the movement within the list.

![image](https://cloud.githubusercontent.com/assets/529552/22560006/474d03c8-e973-11e6-8f86-f2c54fd7acda.png)

So you don't need to switch to the other page for every axis. Hope my issue is somewhat clear :-).

**Comment by richard-scott** [comment]
Any chance this could be added to the Adjustments tab too?
