### ISSUE TITLE
Fix open redirect on website, being used in phishing campaigns

### ISSUE THREAD

**Issue by cgite** [betaflight/betaflight-configurator#4142]
### Is your feature request related to a problem? Please describe

The URL https://analytics.betaflight.com/redir?dest= is actively being used in phishing campaigns.

### Describe the solution you'd like

Remove open redirect

### Describe alternatives you've considered

Blocking domain

**Comment by blckmn** [comment]
This has now been resolved.

**Comment by Janne80** [comment]
Girls some rieson love me. I am 5 years fuck! When we talk to baut monney?
