### ISSUE TITLE
Ubuntu 24.04 LTS missing dependency 

### ISSUE THREAD

**Issue by hremling** [betaflight/betaflight-configurator#4145]
### Describe the bug

The installation of betaflight configurator on Ubuntu 24.04  LTS fails due to a missing dependency. A packet called libgconf-2-4 has no install candidates in the official noble nombat repositories. I researched the issue and found some forum posts, saying that libgconf-2-4  is deprecated from 23.10 onwards. 

A workaround might be to add the 22.04 LTS repositories to the sources.list file and install the missing packet manually. 

However it should be reviewed, if the dependency is really necessary or if another package could be used instead. 

### To Reproduce

Ubuntu 24.04.1 LTS Clean Install

Download betaflight-configurator_10.10.0_amd64.deb file

dpkg -i betaflight-configurator_10.10.0_amd64.deb

### Expected behavior

All dependencies are installed automatically from the default Ubuntu 24.04 repository without errors 

### Configurator version

10.10.0

**Comment by nerdCopter** [comment]
duplicate
https://github.com/betaflight/betaflight-configurator/issues/3969
https://github.com/betaflight/betaflight-configurator/issues/3869
https://github.com/betaflight/betaflight-configurator/issues/2950

**Comment by shahmirthesquid** [comment]
Hello, you can fix this issue by manually installing the following packages:

gconf2-common_3.2.6-5_all.deb
libgconf-2-4_3.2.6-5_amd64.deb 

Google these package names, download them, and install. I downloaded them from debian pkgs org. Then you will be able to install betaflight with no problem. This was working for me on Linux Mint 22 and 23.

After installing betaflight I did the USB permissions command like it says in the betaflight wiki for linux, and everything was connecting perfectly.

**Comment by nerdCopter** [comment]
i feel like using the portable (.zip) is a functional "fix" as well.  however, the included `.desktop` file should be edited to point to the correct location of the executable (not `/opt/...`).

**Comment by hremling** [comment]
I think both of those options shouldn't be called a "fix" because they require manual intervention from the user. In addition, those workarounds could stop working at any time because they rely on the deprecated libgconf-2-4 package. Even if that's not happening anytime soon, it poses a security risk at least.
My issue was just intended to give a heads up to the developers since the Ubuntu 24.04.1 LTS was being rolled out to the users. As one of the most widely used Linux distributions, this might have lead to many more users having to face the same issue.

**Comment by nerdCopter** [comment]
understood. Binary installables are no longer in the Betaflight workflow in favor of https://app.betaflight.com

**Comment by shahmirthesquid** [comment]
Could we please add some kind of disclaimer somewhere on how to do the linux fix. I was able to figure it out by scouring enough forums, but it would be a lot better if betaflight itself linked to safe mirrors of libgconf and other dependencies. I think its reasonable for users to have to download some extra .deb files and install those first. That happens on windows all the time. But making the users scour the internet themselves and possibly download an unsafe version of libgconf seems like a bad idea.

**Comment by haslinghuis** [comment]
For ubuntu 22.04:

- What is the output of `sudo apt list gconf2` ?
- What is the output of `sudo apt list lib-gconf-2-4` ?
- Found some in http://archive.ubuntu.com/ubuntu/pool/universe/g/gconf/

**Comment by YifeiNie** [comment]
For Ubuntu 24.0, I downloaded the [betaflight-configurator_10.10.0_linux64-portable.zip](https://github.com/betaflight/betaflight-configurator/releases/download/10.10.0/betaflight-configurator_10.10.0_linux64-portable.zip)，and extracted successfully, after tha, I clicked the option ‘Executable as program, finally double clicked betaflight-configurator,  but nothing happened.... Can any masters give me a solution?

**Comment by nerdCopter** [comment]
the `.desktop` file should be edited to point to `./` not `/opt/....`
![image](https://github.com/user-attachments/assets/4e0fe8a7-a5cc-439d-a858-1c263d32b5b4)
![image](https://github.com/user-attachments/assets/aa0afa31-9bbb-4f0f-8ea9-3648e3cf9f8b)

Alternatively you could also execute it via commandline , go into the extracted folder and run  `./betaflight-configurator`

**Comment by YifeiNie** [comment]
> the `.desktop` file should be edited to point to `./` not `/opt/....` ![image](https://private-user-images.githubusercontent.com/56646290/374197017-4e0fe8a7-a5cc-439d-a858-1c263d32b5b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNjAwOTQsIm5iZiI6MTcyODM1OTc5NCwicGF0aCI6Ii81NjY0NjI5MC8zNzQxOTcwMTctNGUwZmU4YTctYTVjYy00MzlkLWE4NTgtMWMyNjNkMzJiNWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAzNTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYzk2NTRlMTNmY2FiNWRlY2QxZTU4MzM1MmQwYzVlN2U5ZDUwMmMzYWUwZmVkNmVjYWRhOGRmMzJlNTRkYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jKGTs24FZs0t_sjrcW1DVVwwgWds0lpMOlDO0ZTobdk) ![image](https://private-user-images.githubusercontent.com/56646290/374197914-aa0afa31-9bbb-4f0f-8ea9-3648e3cf9f8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNjAwOTQsIm5iZiI6MTcyODM1OTc5NCwicGF0aCI6Ii81NjY0NjI5MC8zNzQxOTc5MTQtYWEwYWZhMzEtOWJiYi00ZjBmLThlYTktMzY0OGUzY2Y5ZjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAzNTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNDg2MDZhM2Y0MGUwMjJjYzk3OWU0NTMwZDM5OWNkZDJkZDk4ZGZhOGYyNmQ1OGJhNTM3YzYxOTM3MzQzNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qcUOE9BpKzIRvDd15Xqyt1MAHy9D-NlhM47mX6aIbb4)
> 
> Alternatively you could also execute it via commandline , go into the extracted folder and run `./betaflight-configurator`
tks for reply，however I finally found that the configrator cannot support arm64 based ubuntu which is installed on my RK3588 development board 
![MQ( PX%F ( %K9D57 W276U](https://github.com/user-attachments/assets/626700f6-151e-4259-b046-5d1e0349e225)
So it may not work

**Comment by YonatanSimson** [comment]
This is what worked for me:
Download the following packages
wget http://ftp.it.debian.org/debian/pool/main/g/gconf/gconf2_3.2.6-8_amd64.deb
wget http://ftp.it.debian.org/debian/pool/main/g/gconf/libgconf-2-4_3.2.6-8_amd64.deb
wget http://ftp.it.debian.org/debian/pool/main/g/gconf/gconf2-common_3.2.6-8_all.deb
wget http://ftp.it.debian.org/debian/pool/main/g/gconf/gconf-service_3.2.6-8_amd64.deb
wget http://ftp.it.debian.org/debian/pool/main/o/openldap/libldap-2.5-0_2.5.13%2bdfsg-5_amd64.deb

Then install the packages in the following order

sudo dpkg -i gconf2-common_3.2.6-8_all.deb // Install gconf2-common first
sudo dpkg -i libgconf-2-4_3.2.6-8_amd64.deb // Then libgconf
sudo dpkg -i libldap-2.5-0_2.5.13+dfsg-5_amd64.deb // Then libldap
sudo dpkg -i gconf-service_3.2.6-8_amd64.deb // Then the gconf service
sudo dpkg -i gconf2_3.2.6-8_amd64.deb // Finally gconf.

The order is important. The I had a problem connecting to the serial port despite my FC being recognized.

sudo usermod -a -G plugdev <username>

With all of this you should be good to go. Could not get the app to work on my browser on unix laptop.

Ubuntu 24.04
