### ISSUE TITLE
Motor direction and ordering not usable on the web application! 

### ISSUE THREAD

**Issue by timmyfpv** [betaflight/betaflight-configurator#4163]
### Describe the bug

When i try to change the motor direction from the web application i just get met with a blank page! I cannot do anything! 
<img width="1679" alt="Skärmavbild 2024-09-09 kl  14 32 02" src="https://github.com/user-attachments/assets/4203a191-65ff-4811-8eac-8ce72f6382d1">

### To Reproduce

Try to change the motor direction from web application

### Expected behavior

A menu to fix the motor direction just like in the normal configurator

### Support ID

```txt
Didn't get any with virtual connection
```

### Flight controller

Any. Virtual, Rush, mamba MK2, mamba MK4.

### Other components

None

### How are the different components wired up (including port information)

USB

### Add any other context about the problem that you think might be relevant here

I used a macbook pro m1 but i get the same result from my windows 10 machine if i remember correctly

**Comment by haslinghuis** [comment]
This has been fixed here: https://github.com/betaflight/betaflight-configurator/pull/4158

Just tested again using app.betaflight.com
