### ISSUE TITLE
Add gui option for osd_stick_overlay_radio_mode

### ISSUE THREAD

**Issue by RobertoD91** [betaflight/betaflight-configurator#4164]
### Is your feature request related to a problem? Please describe

It would be helpful to have a option in the OSD section for selecting `osd_stick_overlay_radio_mode`

### Describe the solution you'd like

A simple drop-down menu in OSD tab

### Describe alternatives you've considered

A reminder in the help section `osdDescElementStickOverlayLeft`and `osdDescElementStickOverlayLeft`

**Comment by haslinghuis** [comment]
Alternative: parameter `overlayRadioMode` is already in MSP.
Just can't decide where we should place it as it's only used for stick overlay element[s].
A variant would create a selection on the element.
