### ISSUE TITLE
Slow or delayed connection during weak internet connection

### ISSUE THREAD

**Issue by flyasky** [betaflight/betaflight-configurator#4165]
### Describe the bug

Connect to a very slow or weak internet connection and try to connect to the drone via the com-port (I tried on Windows). It freezes often and does not go to the dashboard. But the port successfully opened.
If I disable the internet completely - it becomes much faster.

### To Reproduce

Connect to a very slow or weak internet connection and try to connect to the drone via the com-port

### Expected behavior

Fast response.

### Configurator version

10.10.0

### Flight controller configuration

```txt
N/A
```

**Comment by haslinghuis** [comment]
You can disable some traffic

![image](https://github.com/user-attachments/assets/95a7150a-a106-465a-b8cb-129fbf28e023)

**Comment by flyasky** [comment]
> You can disable some traffic
> 

Will do that, but that traffic has to be non-blocking by design.

**Comment by flyasky** [comment]
Opting out data collection didn't help. Tested today again. It even fails of I connect to the WiFi without Internet connection (elrs rx/tx OR disabled because of missed payment)

**Comment by haslinghuis** [comment]
@flyasky please check #4168

**Comment by flyasky** [comment]
@haslinghuis wow, so fast solution=) right now it's hard to emulate, but I'll verify soon on my location. For now, I checked out your branch, compiled - it seems to be working at first sight.
