### ISSUE TITLE
Add "Reset to Custom Defaults" in the Setup tab

### ISSUE THREAD

**Issue by YarosMallorca** [betaflight/betaflight-configurator#4192]
### Is your feature request related to a problem? Please describe

The "Reset Settings" resets the FC to Betaflight defaults. not target defaults, as I understand.

### Describe the solution you'd like

It would be great to have another button to reset it to the custom (target) defaults.

### Describe alternatives you've considered

A workaround is to reflash the flight controller, which will reset automatically to target defaults.

**Comment by haslinghuis** [comment]
it defaults on betaflight + target defaults.

**Comment by YarosMallorca** [comment]
Got it, thanks for the clarification.

I got confused by this in the docs:
<img width="850" alt="Screenshot 2024-09-30 at 00 17 51" src="https://github.com/user-attachments/assets/3b80b922-28f6-45b6-9a2e-bc8e6a23bcbc">

Made me think this resets to BF defaults.
