### ISSUE TITLE
Add ability to enable / disable Senors

### ISSUE THREAD

**Issue by borisbstyle** [betaflight/betaflight-configurator#42]
User should be able to turn on or off sensors in GUI

**Comment by KiteAnton** [comment]
I had an idea that you could perhaps just press the sensors in the top bar to toggle them on/off? Or would that be to "hidden" since people are not used to that functionality?

**Comment by skaman82** [comment]
I think this would be better placed in the config tab.

**Comment by borisbstyle** [comment]
@KiteAnton 
I was actually thinking the same, but it wont be intiutive.

I did some MSP preparations. Can you perhaps add this into config tab @KiteAnton ?
https://github.com/betaflight/betaflight-configurator/commit/3b496324faca2de4921acb136132efd572d214eb

I want to continue with some more compatibility stuff to be added and try to finish it to bring out the updated configurator. It would be nice if the sensors also could be disabled / enabled.

**Comment by KiteAnton** [comment]
Ok maybe it can be both. I will try to get some time during the weekend to add this.
