### ISSUE TITLE
Sik radio msp support

### ISSUE THREAD

**Issue by InfinyUAV03** [betaflight/betaflight-configurator#4209]
### Describe the bug

If i turn on the msp and set baud rate in ports tab, after that when i try to connect wireless through my sk radio, it is not working. but this same feature is working in inav, not working in betaflihgt

### To Reproduce

please resolve the issue of msp connection through sikradio for wireless connection

### Expected behavior

should connect wirelessly. msp should work

### Configurator version

10.10.0

**Comment by haslinghuis** [comment]
Can you check with 4.3.x firmware and does it need:

![image](https://github.com/user-attachments/assets/6af7bca2-8124-4e28-8f34-9c08ab14474c)
