### ISSUE TITLE
New Font

### ISSUE THREAD

**Issue by mixMugz** [betaflight/betaflight-configurator#421]
Hi. I made new font for BF. You can use if you like.

![mugzless](https://cloud.githubusercontent.com/assets/17923916/22628760/03e157d6-ebeb-11e6-9a41-7a6e202a7486.png)

Link for download: https://cl.ly/1z1J1u02113G

**Comment by DanNixon** [comment]
As this font appears to be identical to the one added in #419 I'd suggest this should just replace that one (digital.mcm`) as the battery icon does look nicer in this one.

(@basdelfos)

**Comment by mixMugz** [comment]
Oh. Wow! in #419 is also my font what i make for minimOSD ;)

**Comment by mixMugz** [comment]
Anyway you can rename it to anything you like and use

**Comment by DanNixon** [comment]
Cool, I'll be able to get that done some time tomorrow.

**Comment by mixMugz** [comment]
Okay! If you need to change something - let me know.

**Comment by basdelfos** [comment]
What's the difference besides the battery level icons?
I like the battery icons from the default Betaflight font more, I left them
out on purpose. But that's just suggestive. It's possible to just upload
the font you like in the BFC.

@mixMugz I thought you wouldn't mind sharing this font as you requested it
on RCG a while ago.
Op ma 6 feb. 2017 om 18:54 schreef mixMugz <notifications@github.com>

**Comment by mixMugz** [comment]
@basdelfos Of course i don't mind sharing ;)

I didn't notice your post. If i did i wouldn't have written.

There aren't many differences.
1. Battery icon
2. 'v' and 'a' symbol for Voltage and Current
3. Correct center cross

**Comment by mixMugz** [comment]
And battery icon is better. Because it is more informative.

**Comment by DanNixon** [comment]
Yeah, having the individual segments would make it easier to read at a glance IMO.
Although those icons aren't even used in the Betaflight OSD (at the  moment) so for now it makes little difference.

**Comment by basdelfos** [comment]
@mixMugz I will replace it with your font, it's your font anyway :)

**Comment by DanNixon** [comment]
@basdelfos If you PR it then you also need to add it to the font UI, otherwise no one will ever know it's there.

See #410.

**Comment by basdelfos** [comment]
Good point, didn't notice that.

**Comment by mixMugz** [comment]
And you can use original digital.mcm filename (or betaflight-digital). mugzless - temporary name.
