### ISSUE TITLE
Unable to use the new version of configurator in my android phone

### ISSUE THREAD

**Issue by Linjieqiang** [betaflight/betaflight-configurator#4216]
### Describe the bug

![3f1773c43feed741ff6f40099bd72f4](https://github.com/user-attachments/assets/6ba64e0a-1f69-498a-9382-fbfdea963d93)

### To Reproduce

- Web Serial APl support is disabled.

### Expected behavior

- How to solve?

### Configurator version

v11.0

**Comment by nerdCopter** [comment]
Andoid Chrome does not support WebSerial; no way to change this.

**Comment by YarosMallorca** [comment]
@Linjieqiang Try installing the APK from [here](https://github.com/betaflight/betaflight-configurator/releases/download/10.10.0/betaflight-configurator_10.10.0-debug-c97deaf_android.apk)

**Comment by haslinghuis** [comment]
Cordova has been replaced with Capacitor but needs more development.

More info: https://github.com/betaflight/betaflight-configurator/pull/3955#issuecomment-2197259001

**Comment by haslinghuis** [comment]
@Linjieqiang check https://github.com/betaflight/betaflight-configurator/pull/4227

Long term solution planned is using capacitor without ETA.
