### ISSUE TITLE
[style/color] BBL download pregress bar blue

### ISSUE THREAD

**Issue by nerdCopter** [betaflight/betaflight-configurator#4219]
style issue, assigning to @YarosMallorca 
![2024-10-19_17-06](https://github.com/user-attachments/assets/e61ec3da-623e-4770-82b4-24a53adddf06)

**Comment by YarosMallorca** [comment]
Will fix this soon! 🙂

**Comment by YarosMallorca** [comment]
@nerdCopter I fixed it in #4220, please check it!
