### ISSUE TITLE
Windows Arm Support

### ISSUE THREAD

**Issue by wom** [betaflight/betaflight-configurator#4242]
### Is your feature request related to a problem? Please describe

![image](https://github.com/user-attachments/assets/227c7295-82d8-43d8-a954-6ad8b968e2ad)
Running on Arm, Windows installer is blocked.  Portable installer appears to work fine via Prism emulator.

### Describe the solution you'd like

Unblocking install on Arm is probably enough, though an actual arm build would be appreciated.

### Describe alternatives you've considered

Portable installer appears to work fine via emulation.

### Other information

Machine I'm playing with:

```
Device name	wompro
Processor	Snapdragon(R) X 12-core X1E80100 @ 3.40 GHz   3.42 GHz
Installed RAM	16.0 GB (15.6 GB usable)
Device ID	6CC891C5-7CF9-438C-9A68-179D0A0245C1
Product ID	00356-06300-76523-AAOEM
System type	64-bit operating system, ARM-based processor
Pen and touch	Pen and touch support with 10 touch points

```

**Comment by haslinghuis** [comment]
Try app.betaflight.com

**Comment by Kristoffz** [comment]
Hi, have this Issue been resolved?
