### ISSUE TITLE
Rockchip RK3588S new-gen 8-core 64-bit Ubuntu 20.04 How to compile and use https://app.betaflight.com ​ Can't connect.

### ISSUE THREAD

**Issue by jiaozhuliu** [betaflight/betaflight-configurator#4247]
### Describe the bug

Rockchip RK3588S new-gen 8-core 64-bit Ubuntu 20.04 How to compile and use https://app.betaflight.com
​ Can't connect.
![IMG_20241112_012013](https://github.com/user-attachments/assets/b6aecfd8-7187-4e6c-9810-14bb6ef06d25)

### To Reproduce

Rockchip RK3588S new-gen 8-core 64-bit Ubuntu 20.04 How to compile and use https://app.betaflight.com
​ Can't connect.

### Expected behavior

Rockchip RK3588S new-gen 8-core 64-bit Ubuntu 20.04 How to compile and use https://app.betaflight.com
​ Can't connect.

### Configurator version

Rockchip RK3588S new-gen 8-core 64-bit Ubuntu 20.04 How to compile and use https://app.betaflight.com ​ Can't connect.

**Comment by haslinghuis** [comment]
No need to compile online configurator. Chromium based browser will provide an offline option.

For connection issues see https://betaflight.com/docs/development/building/Building-in-Ubuntu#flashing-a-target-with-betaflight-configurator

**Comment by haslinghuis** [comment]
Default chromium installation uses snap builds which are sand boxed for added security.

Remove that one and try instead:

```
sudo add-apt-repository ppa:xtradeb/apps -y
sudo apt update
sudo apt install chromium
```

**Comment by jiaozhuliu** [comment]
ttyACM0  No data
cat@lubancat:~$ sudo cat /dev/ttyACM0







^Z
[1]+  Stopped                 sudo cat /dev/ttyACM0
cat@lubancat:~$ sudo cat /dev/ttyS0
[  199.679957] of_dma_request_slave_channel: dma-names property of node '/serial@fd890000' missing or empty
▒XQ68▒▒▒8'▒\x▒▒9▒▒F▒▒▒▒!J▒▒▒▒▒5▒h;J▒A▒▒BxL▒▒)▒r CD▒▒    !B▒Q▒'w▒N!▒▒!▒);C

**Comment by haslinghuis** [comment]
There is no issue with betaflight configurator.

Checkout https://betaflight.com/docs/development/building/Building-in-Ubuntu#flashing-a-target-with-betaflight-configurator
