### ISSUE TITLE
Large Blackbox doesn't get recognized in the app bar

### ISSUE THREAD

**Issue by YarosMallorca** [betaflight/betaflight-configurator#4262]
### Describe the bug

On flight controllers with large flash, or that use external SD cards for logging, the blackbox status says "no dataflash chip found" although in the Blackbox tab it is recognized correctly. This is on my Speedybee F7 V3 FC:

<img src="https://github.com/user-attachments/assets/63ad95a2-9611-4306-9af6-45f152f9374b" width="300px">

<img src="https://github.com/user-attachments/assets/3c46f861-574a-4459-9fc8-f688476c9809" width="700px">

On other flight controllers with smaller more traditional flash, it shows correctly.

### To Reproduce

Connect to a Flight Controller that uses an SD Card or other larger flash type to store Blackbox logs.

### Expected behavior

It correctly shows the space on the flash as with all other flight controllers.

### Configurator version

Configurator: 11.0.0 (e95e3a4c)

**Comment by nerdCopter** [comment]
4GB partition max
https://www.speedybee.com/speedybee-f405-v3-bls-50a-30x30-fc-esc-stack/#Parameters
![image](https://github.com/user-attachments/assets/50a85569-0785-4364-b986-89ab0f1b39a8)

**Comment by haslinghuis** [comment]
Think we like to see flash or sdcard showing up in

![image](https://github.com/user-attachments/assets/1fca9177-0cde-47fd-bd13-17783419a2b5)

**Comment by haslinghuis** [comment]
![image](https://github.com/user-attachments/assets/8ec96a32-32fd-4714-803d-6ee1c8a191c4)
