### ISSUE TITLE
Cleanflight-version specific code must be migrated

### ISSUE THREAD

**Issue by gaelj** [betaflight/betaflight-configurator#43]
`msp.js` and other files contain conditional code related to api version.
This code is still adapted to Cleanflight, whose MSP version is not synced with Betaflight's.
This will yield unexpected behaviour, especially when BF's API version is increased.

**Comment by borisbstyle** [comment]
not at all actually. All betaflight specific commands are only applied to
betaflight firmware. All old betaflight firmware will also be supported
from next release.

MSP does a check for firmware version and type
Op 25 jun. 2016 14:12 schreef "Gaël James" <notifications@github.com>:

**Comment by gaelj** [comment]
@borisbstyle what about these blocks for example?
Line 450:
```
if (semver.lt(CONFIG.apiVersion, "1.18.0"))
    MISC.mag_declination = data.getInt16(offset, 1) / 10; // -1800-1800
else
    MISC.mag_declination = data.getInt16(offset, 1) / 100; // -18000-18000    
```

Line 468:
```
if (semver.lt(CONFIG.apiVersion, "1.17.0")) {
    offset += 2;
    _3D.deadband3d_throttle = data.getUint16(offset, 1);
}
```
If unchanged, they will alter the configurator's behaviour with future releases of BF MSP.
Don't you agree ?

**Comment by borisbstyle** [comment]
Thats all fine. That cant hurt anything.

Betaflight supports all those apis.

There is:
MSP version
Firmware identifier
Firmware version.

Betaflight and Cleanflight share same MSP versions. That helps supporting
OSDs and mobile apps like ezgui.
Only Betaflight has some additional commands only supported by betaflight
configurator.

And everything is backwards compatible.
Op 25 jun. 2016 19:15 schreef "Gaël James" <notifications@github.com>:

**Comment by gaelj** [comment]
In thise case in my LED strip PR, which currently uses MSP version 17, needs to be updated to jump to MSP version 20, which is the CF MSP version where all current new LED functions are present.
But this means the bahaviour in lines 450 and 458 (those are just examples) will change.
What do you think ?

**Comment by borisbstyle** [comment]
@gaelj 
You need to inspect differences between MSP 17 to 20. It may be there is much more than just leds

**Comment by gaelj** [comment]
Got it.

**Comment by gaelj** [comment]
#### MSP changes from 17 to 20
Current CF version is 19 ; I have a pending LEDstrip improvement PR which will bump it to 20.

##### CF MSP 1.17
- move `deadband3d_throttle` from `MSP_3D` to `MSP_RC_DEADBAND`

##### CF MSP 1.18
- `MSP_MISC`: `mag_declination` / 100 instead of / 10 (https://github.com/cleanflight/cleanflight-configurator/pull/369).
- `MSP_PID`: remove float conversion of PID values
- function: MAVlink telemetry https://github.com/cleanflight/cleanflight/pull/806
- function: LEDstrip: GPS, Blink, RSSI

##### CF MSP 1.19
- `MSP_LED_STRIP_MODECOLOR`
- function: LEDstrip: battery

##### CF MSP 1.20
- `MSP LED_STRIP_CONFIG` now uses new 32 bit format for each LED definition
- function: LEDstrip: Larson scanner, blink on landing, RSSI is now a function instead of an overlay, Blink is an overlay instead of a function

#### Actions
1. I issue 4 distinct BF PRs to merge CF changes in MSP verisons 17 and 18 (including MAVlink telemetry, I hope I'm not getting myself into trouble here -> if too complex, maybe we leave it aside ?)
2. bump MSP to 20 in this LED strip PR and the related configurator PR
3. finally, maybe we wait until the MSP 20 changes are merged into CF before merging them here, just to be safe, and polite (I don't want anyone to feel I am forcing changes to one fork by pushing them to another)

How does that sound to you @borisbstyle ?

**Comment by gaelj** [comment]
>    move deadband3d_throttle from MSP_3D to MSP_RC_DEADBAND

The main change here was to put this setting in profile instead of main config. Do you want this ? Or would you just want the MSP frames to be compatible ?

**Comment by skaman82** [comment]
@gaelj @borisbstyle regarding 3: I don't think it would be bad at all to merge this new LED function here first. It is summer and people are flying NOW. So every day counts to get it out here for users to benefit from it. Since the main goal of CF 1.14 is the OSD support, it can take a while till it will be ready and I am almost sure that Dominic will merge his OSD code first and all other PRs have to be updated/rebased till they could be included as well.

**Comment by borisbstyle** [comment]
We dont want it to break something else.

This change changes MSP version and that impact of that needs to be checked.
Op 26 jun. 2016 16:50 schreef "Albert Kravcov" <notifications@github.com>:

**Comment by skaman82** [comment]
Yes sure. My comment was just related to Gäels question about waiting for it o be merged in CF.

Von meinem iPhone gesendet

**Comment by gaelj** [comment]
If I only modify the MSP frame format and not the underlying changes, We could have something compatible quite quickly.

**Comment by borisbstyle** [comment]
but what if those users use cleanflight configurator?
Op 26 jun. 2016 18:01 schreef "Gaël James" <notifications@github.com>:

**Comment by skaman82** [comment]
From now on we schould assume that users would use the bf configurator for betaflight otherwise the development of new stuff would still depend from CF configurator. If i am not mistaken this is the whole point of the bf configurator to change that?

Von meinem iPhone gesendet

**Comment by gaelj** [comment]
> but what if those users use cleanflight configurator?

What I meant is, I move deadband3d_throttle from MSP_3D to MSP_RC_DEADBAND. So CF configurator will indeed work. The difference being, (unless I missing anything) BF will still see at as a global parameter. The CF commit is this one https://github.com/cleanflight/cleanflight/pull/1976/commits/b6830dea314b7603590f28d11bc79c1ae43041ad.

> From now on we schould assume that users would use the bf configurator for betaflight otherwise the development of new stuff would still depend from CF configurator

Not entirely true regarding MSP protocol, as it is shared with other devices and frame format should indeed be kept coherent between forks. Handling different MSP versions is one thing, adding the granularity of which Flight control's MSP it was issued by would be a nightmare. What BF developers are allowed to do, is add their own additional MSP messages, and this is what the specific configurator is for.

**Comment by skaman82** [comment]
Ok, got it. Thanks.

Von meinem iPhone gesendet

**Comment by gaelj** [comment]
Just discovered 

> MSP_MISC: mag_declination not scaled by 10 

 got left behind after a code cleanup.
MAVlink telemetry is just a serial port in the configurator, I think it can be skipped for now.
MSP PID is already in BF too.
I put back MSP 20 instead of 17 in the LED code so we should be ready.
