### ISSUE TITLE
getting "failed to open serial port"

### ISSUE THREAD

**Issue by Supersix4** [betaflight/betaflight-configurator#442]
I suspect I have not setup zadig correctly. trying to connect to a new beebrain. never used this kind of program before... I downloaded and installed all drivers but when I get to Zadig I really don't want to click on wrong items.

**Comment by mikeller** [comment]
Read https://github.com/betaflight/betaflight/wiki/Installing-Betaflight#dfu-flashing-under-windows---usb-dfu .
