### ISSUE TITLE
Accelerometer graph doesn't work since 1.9.2 in motors tab

### ISSUE THREAD

**Issue by jurkust** [betaflight/betaflight-configurator#448]
Accelerometer graph doesn't work in motors tab.

**Comment by jurkust** [comment]
It looks like this dispite if accelerometer is on or off:
![Motors tab](https://photos-5.dropbox.com/t/2/AACP1w7xmUpCfT020OtmwitH86Q07gSaVpuF-wJZEByqxQ/12/51402303/jpeg/32x32/3/1487894400/0/2/motors.JPG/EI_WxycY_rOnASACKAI/PNCf5E9xEmxM3e9f8-MfYLyfmBn3AuGjgyjKGyH92ak?dl=0&size=1600x1200&size_mode=3)

Another question is why accelerometer is used instead of gyroscope in motors tab? Most (if not all) acro pilots do not use accelerometer at all and just gyroscope is used in pid loop. So, shouldn't be gyroscope used to measure vibrations when testing motors?

**Comment by mikeller** [comment]
Sorry, my bad, I was a bit too eager in cleaning up dead code.

But it's a good point that you are making about gyroscope data being a better graph to display on the motors tab. Will change this in a future PR.
