### ISSUE TITLE
Suspicious permissions requirements in new version of betaflight-configurator.

### ISSUE THREAD

**Issue by janekbaraniewski** [betaflight/betaflight-configurator#449]
Today when I've opened the BF-configurator this showed up:

<img width="466" alt="screen shot 2017-02-23 at 19 44 38" src="https://cloud.githubusercontent.com/assets/9478651/23274093/bc08e5c6-fa01-11e6-97e3-fd51beeef139.png">

Everything sounds reasonable apart from the first point. I honestly don't believe that in order for application to work it needs permission to exchange data using the network with any other device whatsoever. The only devices it should exchange data with are accessed via USB. Mind explaining this one?

**Comment by mikeller** [comment]
Sure. This is required for the functionality to communicate with a flight controller over WiFi and an ESP8266 running esp-link, as discussed in #425. But well spotted, we should probably have placed a note about this somewhere.

**Comment by janekbaraniewski** [comment]
All clear! Thanks for the quick response.
