### ISSUE TITLE
 No Motor line not showing in Motor tab

### ISSUE THREAD

**Issue by carloscampos775** [betaflight/betaflight-configurator#453]
No Motor line not showing in Motor tab

**Comment by mikeller** [comment]
Fixed in #451.

**Comment by carloscampos775** [comment]
How do I use this fix?

**Comment by mikeller** [comment]
You'll have to clone the configurator repository. Then in Chrome, got More tools / Extensions / Load unpacked extension and point it at the top level directory of the repository.

**Comment by carloscampos775** [comment]
Where is the repository located. I've tried downloading the 1.9.2 zip file
and using chrome.

On Feb 26, 2017 9:07 PM, "Michael Keller" <notifications@github.com> wrote:

You'll have to clone the configurator repository. Then in Chrome, got More
tools / Extensions / Load unpacked extension and point it at the top level
directory of the repository.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/betaflight/betaflight-configurator/issues/453#issuecomment-282610868>,
or mute the thread

**Comment by mikeller** [comment]
1.9.2 won't work, you'll have to use latest. If you want to download as a zip file, go to Code / Clone or Download / Download ZIP.

**Comment by carloscampos775** [comment]
Got it to work. Thanks for your help
