### ISSUE TITLE
Backup feature not working

### ISSUE THREAD

**Issue by SupahDave** [betaflight/betaflight-configurator#461]
I noticed that BetaFlight was updated to 1.9.3 recently and now my BACKUP button doesn't do anything when I press it. The RESTORE button works fine but I am now unable to backup my configurations other than manually doing a CLI dump backup. Any ideas as to what would cause this? 

I've tested this with my Eachine QX95 and also my Diatone Tyrant S and I can't get the feature to work. Please advise.

**Comment by mikeller** [comment]
Hmm, that's odd. There is a bug in restore in 1.9.3 (fixed in #460), but backup should work. Can you open the developer console (right click, 'Inspect'), and check if you get an error message there when you click 'Backup'?

**Comment by SupahDave** [comment]
I don't understand. Where am I supposed to right click?

**Comment by SupahDave** [comment]
If you were telling me to right click in the CLI window, it doesn't do anything. I've tried right clicking everywhere in the interface and nothing happens

**Comment by mikeller** [comment]
That is odd. When you go into the Chrome menu / More tools, does it show you a keyboard shortcut for the 'Developer tools'? Try that one when in the configurator.

**Comment by SupahDave** [comment]
Okay, I can get into that menu. This is what it shows when I open it 
with the configurator open... Right clicking in the developer tools 
window does nothing.


------ Original Message ------

**Comment by SupahDave** [comment]
[
![untitled](https://cloud.githubusercontent.com/assets/25854784/23687324/e87ce3a4-037b-11e7-9e52-03f1a985575a.png)
](url)

**Comment by mikeller** [comment]
That's the one. now click on 'console' at the top, and then click on the 'Backup' button in the configurator, and see if you get an error message.

**Comment by SupahDave** [comment]
I tried that and nothing shows up in the console window at all when I press backup in the configurator... What does that mean? I've already uninstalled and reinstalled the configurator in case something was corrupt. What should I try next?

**Comment by SupahDave** [comment]
![image](https://cloud.githubusercontent.com/assets/25854784/23694874/49c4b6cc-03aa-11e7-9ce9-d159bc0cec9f.png)

**Comment by mikeller** [comment]
Ah. This is the console for the web page you're currently browsing. You need to open it in / for the configurator window. Can't help you how to do this, if your right - click menu does not show up.

**Comment by SupahDave** [comment]
So I should be able to right click in the Betaflight window? From CLI?

**Comment by mikeller** [comment]
From anywhere in the configurator really.

**Comment by SupahDave** [comment]
I just setup Betaflight on my laptop and tried right clicking in the window and it doesn't do anything on the laptop either. This eliminates any possibility of it being my PC that is causing the issue. Could this be an incompatibility with Windows 10?

**Comment by mikeller** [comment]
Shouldn't be, works fine for me:

![image](https://cloud.githubusercontent.com/assets/4742747/23704749/3c56072c-046b-11e7-9a6a-44edbb84d8ff.png)

You don't use your mouse left handed by any chance, and have the mouse buttons swapped?

**Comment by SupahDave** [comment]
Nope

**Comment by SupahDave** [comment]
Does Betaflight depend on any plugins in Chrome that may be getting blocked?

**Comment by bilson** [comment]
@SupahDave 

- Clone the repo to any local directory or download it as zip
- Start Chromium or Google Chrome and go to tools -> extension
- Check the "Developer mode" checkbox
- Click on load unpacked extension and point it to the Betaflight Configurator directory (for example D:/betaflight-configurator)

**Comment by mikeller** [comment]
@SupahDave: Sorry, my bad. If you installed the configurator from the web store, the process to get a console is different:
- start configurator;
- enter `chrome://extensions/` into chrome's url bar;
- on the page that opens, find configurator, click on `main.html` under 'Inspect views'.

**Comment by SupahDave** [comment]
Can you give me a screenshot of what you mean? I know how to find the Chrome Extensions page easily but I do not know where to find the "main.html" under "inspect views"

**Comment by SupahDave** [comment]
![image](https://cloud.githubusercontent.com/assets/25854784/23734838/a9256b5c-044f-11e7-9424-09f413be278a.png)

**Comment by SupahDave** [comment]
Nevermind. I found it. I had to enable Developer mode in the extensions page

**Comment by SupahDave** [comment]
This is what I get when I press the backup button in the configurator

**Comment by SupahDave** [comment]
![image](https://cloud.githubusercontent.com/assets/25854784/23734901/226bbf66-0450-11e7-987e-42f37bc1da8a.png)

**Comment by SupahDave** [comment]
![image](https://cloud.githubusercontent.com/assets/25854784/23734978/c3e03796-0450-11e7-8b0f-bac0c3e53245.png)

**Comment by SupahDave** [comment]
![image](https://cloud.githubusercontent.com/assets/25854784/23734988/d267513c-0450-11e7-8d25-49f7a0154244.png)

**Comment by SupahDave** [comment]
![image](https://cloud.githubusercontent.com/assets/25854784/23735000/e90695a6-0450-11e7-9fe6-a34126735cba.png)

**Comment by SupahDave** [comment]
I upped screenshots of what the console shows when I click on each of the links

**Comment by mikeller** [comment]
From looking at your screenshots, the 'error' seems to be 'User cancelled', i.e. Chrome thinks that you hit 'Cancel' in the dialog that asked you to specify where you want to save your backup file. If this happens without you actually hitting cancel, then I suspect something is wrong with your Chrome installation.

I'd try uninstalling and reinstalling Chrome.

**Comment by SupahDave** [comment]
I uninstalled Chrome from my laptop and reinstalled it without signing in to Google so that it wouldn't sync anything from my PC's browser. I then installed Betaflight from and tried it again and I get the same error that I already posted pics of (those pics were from my PC). 

So both my PC and laptop are experiencing the same issue even with a fresh install of Chrome/Betaflight on my laptop... 

Any other suggestions?

**Comment by tyler78** [comment]
I have the same problem with "backup".  There's also post over in the betaflight by woody37 that also sounds like the same problem.... So not isolated to just SupahDave....  happy to do some troubleshooting if there are additional recommendations.

**Comment by SupahDave** [comment]
Thanks for the validation Tyler. Nothing has changed on either of my computers other than the Betaflight version being updated automatically from the Chrome app store. I wish there was a way to downgrade it to a version from January because I know that was working then...

**Comment by mikeller** [comment]
Ok. I think I can see what goes wrong. Looks like Chrome auto-closes the file selection dialog if the suggested file name contains characters that cannot be part of a filename, which is the case with the currently released version under windows. Unfortunately it does so and logs this with the utterly unhelpful message 'User cancelled'.

I will get a new version released.

**Comment by SupahDave** [comment]
Excellent! Glad you were able to figure this out since it was apparently happening to several people.

**Comment by SupahDave** [comment]
Great job diagnosing and fixing the issue. Backup is working again with the version of betaflight that is on the Chrome web store now. Thanks!!!

**Comment by ChristianProgrammerTaylor** [comment]
excuse noob observation but I believe this is happening ( albiet not a browser version ) in the new 10.1  not chrome  configurator
