### ISSUE TITLE
Motors tab gyro graph

### ISSUE THREAD

**Issue by killerm1** [betaflight/betaflight-configurator#468]
Hi,
 I use the motors tab acc graph to balance motors and since it has been changed to a gyro graph all I see is erratic behavior on the graph. I have tried it with 3 different FC's and they all do the same thing. Is it normal for  the gyro to jump all over the place when sitting level on the desk? Is it possible to change it back to the acc graph or maybe have a selector to choose which graph you want to see?
thanks

**Comment by mikeller** [comment]
Have you tried reducing the sensitivity in the 'Scale:' drop down in the right?

**Comment by killerm1** [comment]
from what I can see that doesnt reduce sensitivity just changes the scale of the graph. also I have noticed the reset button doesnt work.

**Comment by mikeller** [comment]
The reset button was fixed in #464.

**Comment by HerrTim** [comment]
Do I have to update the file manually or how does it work?
I'm having the same issues than killerm1. Is it possible to change back to the Accelerator?

**Comment by mikeller** [comment]
You don't have to do anything, iIt will be included in the next update of the Betaflight configurator.

**Comment by HerrTim** [comment]
Thank you. Do you know why the Accelerator graph has been replaced?

**Comment by mikeller** [comment]
Because it was pointed out that Betaflight defaults to having the accelerometer graph disabled, making the accelerometer graph useless out of the box (#448).

I am neither here nor there, I will probably make it user selectable when I get around to it.

**Comment by csbuzkp** [comment]
Could you tell me when there will be an update fixed reset button?

**Comment by mikeller** [comment]
@csbuzkp: It's fixed in current master (#464), which will be released together with the firmware 3.2 release.

**Comment by OtterNas3** [comment]
Is this still going to happen for a newer(ish) version of the BF Configurator?

**Comment by mikeller** [comment]
@OtterNas3: Definitely. It's just waiting for somebody to implement it...

**Comment by KoDaKrom** [comment]
Somebody could explain to me if it's normal that the gyroscope realtime values are not stable and fluctuate even the quadcopter is on a table without any mouvements ???

In these conditions, if you go to sensors tab, you ca see that accelerometer value are stable. Gyro values "moves" (sorry for my english...) equaly to the motors tab.

I would use the motors tab to verify the balancing of my motors, but actually it's not very usable with the gyro values/graph.
Reset button works on 3.2.1 release but it's no sense to use it. xyz value change all the time!

@OtterNas3: I'have the same request as you, having an option to choose Acc or Gyro would be great.

**Comment by OtterNas3** [comment]
@KoDaKrom 
Download the new Betaflight configurator from the Github here:
