### ISSUE TITLE
Grammar in PID Tuning -> Filter Settings -> Tuning Tips

### ISSUE THREAD

**Issue by LaughingLogic** [betaflight/betaflight-configurator#476]
Re:  Grammar in PID Tuning -> Filter Settings -> Tuning Tips box.

In the second sentence of the "Tuning tips" where it says "**..., but you _do to_ get more noise into the motors**"

 ![grammer-beta-flight](https://cloud.githubusercontent.com/assets/102772/24608356/83bf7b7c-18b9-11e7-85ed-b2b1d0ee30b8.png)

Not sure what it's meant to say. You have to read it slowly to know it doesn't sound right.

**Comment by skaman82** [comment]
Fixed in https://github.com/betaflight/betaflight-configurator/pull/518
