### ISSUE TITLE
Flashing STM32F4 via UART fail.

### ISSUE THREAD

**Issue by AndersHoglund** [betaflight/betaflight-configurator#477]
Flashing F4 based FCs via UART1 fails, tested on my Revo Acro and BFC 3.1.1. Both "No response...." or "wrong response..:" have been seen in the log. FCs using F1 and F3 works OK. 

Using the "STM Flash loader" via UART works just fine on F4, even the old problem with "Full Chip erase" #200 works (assuming STM vocabulary "Global Erase" means the same).

So, for maintenance and update of F4 based FCs I would recommend everyone to download and install "STM Flash Loader Demo", unfortunatly a native Windows app only. http://www.st.com/en/development-tools/flasher-stm32.html

Users of FCs with broken USB connectors can this way keep their old crippled FCs alive, by building a custom binary with `USE_MSP_UART` defined and flash that binary using the STM Flasher. Both flashing and configuration can be done via UART1.

**Comment by erakli** [comment]
Found this issue closed but information in it is a truly treasure.

I agree with @AndersHoglund that information about flashing firmware through UART on F4 controllers could not be performed through BetaFlight Configurator (BFC) at the moment (even with latest version – 10.5.1) and **STM Flasher** have to be used. 

Recently I broke micro USB port on my FC (clone of OMNIBUS F4 Pro) and it was real pain to flash modified firmware to activate MSP on UART1. Soldering USB port without hot gun wasn't an option for me.

At first glance, the problem looks like a simple one. Oscar Liang in his [article](https://oscarliang.com/connect-fc-broken-usb/) describes everything very well, except I couldn't load firmware through BFC. 

Some people are talking about using FTDI adapter for F3 controllers and special STM programming board (for example, Project Blue Falcon [suggests this](https://www.youtube.com/watch?v=5VmhoyL6Z7Q); [this video](https://www.youtube.com/watch?v=2jjRIvqTbiA) does the same) for any board with VCP (all current FCs, starting from F4). The latter case is what I met and it seems to be an overkill to buy another board just to use FC without USB port. I wanted to use FTDI adapter I had.

Others [reported](https://www.reddit.com/r/Multicopter/comments/60xbjc/well_shit/dfa8ph2?utm_source=share&utm_medium=web2x) that they successfully flashed modified firmware through UART3 on OMNIBUS F4 without any problem. I tried both UART1 and UART3 through BFC and only got messages like "No response from bootloader" or "wrong response..:" as described above.

[This](https://www.youtube.com/watch?v=9wwQZPGugoc) video was a reminder for me of an alternative way of flashing firmware. I’m using Linux (Ubuntu 16.04) and [STM Flasher](https://www.st.com/en/development-tools/flasher-stm32.html) app doesn’t work for me at all. I found that [`stm32flash`](https://github.com/ARMinARM/stm32flash) works extremely well for the same purpose if you’re on Linux side.

Steps that worked for me:

0. `sudo apt install stm32flash`
1. connect FTDI-adapter to UART1
2. hold boot button on FC
3. connect FTDI to PC
4. release boot
5. run `stm32flash -w <path-to-downloaded-firmware>/betaflight_3.5.7_OMNIBUSF4SD-6-e8d4fa3c4.hex  /dev/ttyUSB0`
6. reconnect FTDI
7. you’re awesome

At this point I think that one of this actions should be performed in BFC.

1. BFC need to have troubleshooting section on connecting through FTDI adapter, that describes steps above. There should be mentioned that BFC already has modified firmwares with activated MSP on UART1 in unstable releases under **Maintenance (USB rescue)** section. 
  
   To use these firmwares with `stm32flash` one need to load firmware (online) and click "Binary" link in *Release info* section to acquire actual `*.hex` file. It was confusing for me that there's no explicit clue where to download specific version while on GitHub I can find only stable releases.

2. Fix BFC to do same things, that `stm32flash`/STM Flasher do.

Hope this helps somebody.
