### ISSUE TITLE
Implementation of Configurator RC Curve not the same as the FC RC Curve.

### ISSUE THREAD

**Issue by nateimig18** [betaflight/betaflight-configurator#480]
Looks like the RC Curve inside the configurator code does not match the same implementation in the FC code. Specifically the `rcInput` in the configurator is cubicly remapped where as the `rcCommandfAbs` is not.

![image](https://cloud.githubusercontent.com/assets/3208983/24811240/d3ba9980-1b8a-11e7-96ee-bb42c492edc9.png)

![image](https://cloud.githubusercontent.com/assets/3208983/24811229/bf73df86-1b8a-11e7-97da-bd02602e1ab9.png)

**Comment by borisbstyle** [comment]
Yeah.....it seems one uses 3 power exponential and configurator 2.

I think its my mistake on the configurator side.
But feel free to experiment with different curves

**Comment by borisbstyle** [comment]
Actually just checked and it looks all same to me

**Comment by nateimig18** [comment]
So I was looking at the current master source for both FC and Configurator: 
https://github.com/betaflight/betaflight/blob/master/src/main/fc/fc_rc.c#L174
https://github.com/betaflight/betaflight-configurator/blob/master/js/RateCurve.js#L83

**Betaflight FC Implementation**
There are two variables initially used here `rcCommandf` & `rcCommandfAbs`
![bf_fc_rateimplementation](https://cloud.githubusercontent.com/assets/3208983/24985296/ed7155d0-1fb8-11e7-84f0-aca31fb75d14.jpg)

**Betaflight Configurator Implementation**
Here though there initially is only one variable `inputValue` and then later the cubic remapping is stored back into `inputValue` before a second variable `rcInput` is declared and initialized with `inputValue/maxRC`.   
![bf_config_rate_implementation](https://cloud.githubusercontent.com/assets/3208983/24985283/e68136aa-1fb8-11e7-9ee1-381ba2df0d36.jpg)
