### ISSUE TITLE
CLI can't handle special characters

### ISSUE THREAD

**Issue by Arakon** [betaflight/betaflight-configurator#481]
Example: I name my craft "Mücke" (german for "gnat").
It shows right in the dump, in configurator too. But if I type "name Mücke", the name gets changed to "Mcke".

**Comment by mikeller** [comment]
Yes. The Betaflight firmware only handles 8 bit ASCII characters. The craft name is the only place where this is a potential shortcoming, and it's not worth the additional flash space requirements to make it handle unicode there.

Can I suggest you call your craft 'Muecke'?
