### ISSUE TITLE
Rest button does not work in Motors tab

### ISSUE THREAD

**Issue by haybeseret** [betaflight/betaflight-configurator#482]
Hi,
Chrome: 57.0.2987.133, Configurator: 3.1.1
OS:Windows

It seem that the reset button does not reset the gyro 'max' in the motors tab.
tested with BFF3,XRACERSPI,AIRBOTF4.
I recall this functionality worked in previous configurators , I don't know for sure which version.
Thanks !

**Comment by haybeseret** [comment]
BTW - when cloning the repo and adding to chrome it does work..

**Comment by mikeller** [comment]
Fixed in #464.
