### ISSUE TITLE
Adjustments 

### ISSUE THREAD

**Issue by micworg** [betaflight/betaflight-configurator#49]
Hi, the adjustments in the Betaflight Configurator are still the ones from Cleanflight. Some of them are not available in Betaflight (yet?).    

(BTW: What do you think about this: http://www.rcgroups.com/forums/showthread.php?t=2681167 ? I have done this for Betaflight too. Maybe this can become part of Betaflight)

**Comment by KiteAnton** [comment]
Seems to be some people requesting telemetry feedback for actual adjustment values so if you can put the solution together in a PR towards betaflight then it can be reviewed/discussed there.

**Comment by KiteAnton** [comment]
@micworg can you continue the discussion on the betaflight page instead, see this [#409](https://github.com/betaflight/betaflight/issues/409), it is a similar discussion.
