### ISSUE TITLE
Omnibus F4 wont flash with full chip erase

### ISSUE THREAD

**Issue by UltiFix** [betaflight/betaflight-configurator#493]
Just came back from kiss to give BF another chance. Enabled full chip erase to make sure I started clean and fresh. Just says flashing forever with this option ticked...

Why I went to kiss lol

**Comment by nathantsoi** [comment]
what happens if you just click flash again?

**Comment by mikeller** [comment]
@UltiFix: Full chip erase for F4 is broken at the moment. Disable 'Full chip erase' for flashing, then do a 'Reset Settings' to reset to defaults.
