### ISSUE TITLE
looks like all the osd elements are enabled by default

### ISSUE THREAD

**Issue by nathantsoi** [betaflight/betaflight-configurator#495]
![screen shot 2017-05-06 at 8 12 52 pm](https://cloud.githubusercontent.com/assets/399770/25777651/77204844-3298-11e7-804b-2e87a55bf9c8.png)

**Comment by mikeller** [comment]
Don't think that's a configurator problem, seems that they are all initialised to be set to visible: https://github.com/betaflight/betaflight/blob/master/src/main/io/osd.c#L583-L614
