### ISSUE TITLE
Confusing RSSI channel listing

### ISSUE THREAD

**Issue by MathijsG** [betaflight/betaflight-configurator#511]
While having trouble setting up RSSI and finally got it working later, I discovered that the RSSI dropdown channel list just uses the regular channel numbers, which are different from the AUX numbers. This was the first time I saw the raw channels listed. So when you are mapping functions and flight modes and stuff to AUX channels all the time, it could be quite confusing to pick the right channel out of a raw channel list, because you need to add the 4 control channels to the AUX number to get the raw channel (in my case anyway)

And because I'm not the only one I want to suggest some clarification. Here a screenshot of how it looks currently:
![image](https://cloud.githubusercontent.com/assets/529552/26579846/f003102a-4535-11e7-81a3-6a583c11217d.png)

Maybe we can make the RSSI channel list dropdown somewhat more clear, maybe also output their current function, the same as in the left list. Now people easily mistake AUX 5 with channel 5, while you need to add the 4 control channels and pick channel 9 if you wanted to choose AUX 5. Or maybe add the raw channel number in the regular list on the left. I always wondered why my channel 5 on my receiver wasn't AUX 5 in my flight controller. But now I understand it all, but I'm opting for a consistent notation of channels.

See for my initial issue: https://github.com/betaflight/betaflight/issues/3181

**Comment by mikeller** [comment]
You are right, this is not entirely clear.

My suggestion would be to use the channel names in the drop down.

**Comment by MathijsG** [comment]
Are there more places in the configurator where you need to fill in raw channel numbers? Or is the AUX notation the main form of presenting the channels? I'm with you on the solution.

**Comment by piepluquad** [comment]
from receiver.js, maybe this could be sufficient ? :  
```
for (var i = 1; i < RC.active_channels + 1; i++) {
            rssi_channel_e.append('<option value="' + i + '">' + i + '</option>');
```
becomes : 
```
 for (var i = 5; i < RC.active_channels + 1; i++) {
            rssi_channel_e.append('<option value="' + i + '"> AUX' + i-4 + '</option>');
```
so that : 
 * get rid of channels 1->4 that are reserved for Roll Pitch Yaw & Throttle
 * displays start from "AUX 1" (with inner value unchanged of 5)

**Comment by mikeller** [comment]
@piepluquad: Yep, that looks good. Do you want to submit a PR for this?

**Comment by piepluquad** [comment]
looking at receiver.js, aux names are found with chrome.i18n.getMessage(), so better should be : 

```
 for (var i = 5; i < RC.active_channels + 1; i++) {
            rssi_channel_e.append('<option value="' + i + '"> ' + chrome.i18n.getMessage("controlAxisAux" + (i-4)) + '</option>');
```

**Comment by piepluquad** [comment]
You know mike, i didn't even tested it... is there a way to test modifications to betaflight-configurator after having done a change in my repo ?

**Comment by mikeller** [comment]
Yes there is, follow https://github.com/betaflight/betaflight-configurator#alternative-way to make Chrome use the version in your local repository.

**Comment by piepluquad** [comment]
thanks

**Comment by piepluquad** [comment]
ok, i tested this one, and seems ok on channel list for rssi
