### ISSUE TITLE
Display bug in OSD tab: cannot scroll down to see all checkboxes

### ISSUE THREAD

**Issue by matoy** [betaflight/betaflight-configurator#514]
Hi,

OSD configurable directly from betaflight is a very nice feature.
There are many checkboxes to enable or disable each item to the OSD but the scroll down elevator don't allow to go to the very bottom.

I can see the save button but it's banner hides some checkboxes too.

Thank you for your hard work.
Regards,

**Comment by mikeller** [comment]
This was fixed in #499. It will be released as part of the next configurator release, around the time of the release of betaflight 3.2.

**Comment by matoy** [comment]
Thanks! Sorry for duplicate issue.
