### ISSUE TITLE
GUI is open on taskbar but won't show window

### ISSUE THREAD

**Issue by RobvanKlaveren** [betaflight/betaflight-configurator#522]
I have been using BF configurator for over a year now with no problems. This weekend it somehow stopped working. When I open it from the start menu (Windows 10) it shows only in the taskbar. When I right or left click I can not get it to open on the screen. It looks to be working but just can't get it to open in a window.
I have tried uninstalling, restarting the PC then reinstalling but still no joy. Any ideas would be appreciated.
Rob

**Comment by mikeller** [comment]
Have you tried uninstalling / reinstalling Chrome?

**Comment by richard-scott** [comment]
Have you tried loading it from the "Apps" section within Chrome?
