### ISSUE TITLE
Motors keep spinning after leaving motor tab

### ISSUE THREAD

**Issue by Dutch-Drone-Dude** [betaflight/betaflight-configurator#536]
I noticed that the motors keep spinning if you set the master slider at any given setpoint and you leave the motors tab. They even keep spinning if you disconnect from the board.

**Comment by mikeller** [comment]
Yes. That is by design. You might want to go to the 'sensors' tab and look at some debug output while your motors are spinning, for example.

**Comment by Dutch-Drone-Dude** [comment]
Okay I can imagine that, but even if you hit the disconnect button the motors keep spinning, isn't that a bit tricky?

**Comment by mikeller** [comment]
Why? Your props are off. You might want to test something that requires disconnecting your craft from your PC.

**Comment by Dutch-Drone-Dude** [comment]
Okay no problem, I thought it was an extra safety.

**Comment by mikeller** [comment]
The safety is in removing the props. If a user does not do that despite explicitly confirming that they've done it, any assumption about them doing reasonable things is void anyway.
