### ISSUE TITLE
Naze32 dead after bf 3.2.0 hex flash

### ISSUE THREAD

**Issue by killaGFPV** [betaflight/betaflight-configurator#539]
i flashed a new naze32 rev6 board with bf 3.2.0 and it worked for two connections and then nothing.

**Comment by mikeller** [comment]
Read and follow the instructions on the firmware flashing tab in the configurator.

**Comment by killaGFPV** [comment]
no need. its cmpletely dead. lol. i knew its end of life with no support,
but someone gotta burn one down :)
