### ISSUE TITLE
PID tab is no longer working

### ISSUE THREAD

**Issue by lhora** [betaflight/betaflight-configurator#54]
Hi there,
 
I'm running betaflight 2.8.1, I'm able to access every tab in the betaflight chrome extension but as soon as I hit the PID tab the configurator just freezes ( I am able to disconnect and reconnect). My osd is disconnected. And am running the latest version of chrome too.

**Comment by borisbstyle** [comment]
upgrade to 2.9, but latest version of chrone app should work
Op 28 jun. 2016 07:25 schreef "lhora" <notifications@github.com>:

**Comment by lhora** [comment]
Hi Boris, figured out the issue before your reply. Sorry for wasting your time and thank-you for taking the time to reply.
