### ISSUE TITLE
Regression: OSD tab blank for Betaflight 3.2/Omnibus F3 target

### ISSUE THREAD

**Issue by jrussellsmyth** [betaflight/betaflight-configurator#542]
This problem is introduced by the merge of https://github.com/betaflight/betaflight-configurator/pull/534

OSD tab is blank for Betaflight 3.2 on Omnibus F3 target (possibly others)

Console log showing console error message and thrown exception.
[osd-tab-blank.log.txt](https://github.com/betaflight/betaflight-configurator/files/1133381/osd-tab-blank.log.txt)

**Comment by mikeller** [comment]
Works all fine for me with an OMNIBUS F3, latest Betaflight, and latest configurator from GitHub. Do you get an error in the console?

**Comment by jrussellsmyth** [comment]
Error is attached to the issue.

**Comment by mikeller** [comment]
Ok. Looks like your firmware is older than your configurator. Can you update to latest firmware from GitHub and check again.

**Comment by jrussellsmyth** [comment]
Updated to todays build, all is good. My apologies for the wild goose chase.
