### ISSUE TITLE
Font issue BF OSD (Betaflight font)

### ISSUE THREAD

**Issue by Arakon** [betaflight/betaflight-configurator#551]
The "E" letter has a black pixel in the top left of it. Shows up both in the configurator and on-screen.
This is using the latest 3.1.2 configurator.

![28239599-0f643e2c-6970-11e7-9293-23ee473b1066](https://user-images.githubusercontent.com/12016360/28245840-af2670ca-6a0f-11e7-81fb-ede48222d744.png)
![2017-07-16 10_18_32-betaflight - configurator](https://user-images.githubusercontent.com/12016360/28245863-26ceef94-6a10-11e7-9a1e-4895a5ca1b43.png)

**Comment by basdelfos** [comment]
Fix is added to PR: https://github.com/betaflight/betaflight-configurator/pull/553

**Comment by basdelfos** [comment]
If you can't wait, download the font here and upload it to your FC ;)
https://drive.google.com/file/d/0B-6fyO8R3B_YSVFVbE1IT1ZTTms/view?usp=sharing
