### ISSUE TITLE
Servo tab not saving channel assignments

### ISSUE THREAD

**Issue by jflyper** [betaflight/betaflight-configurator#555]
As reported in betaflight/betaflight#3540.

Only channel assignments are not saved; others are okay.

EDIT
Reproduces with BFC 3.1.3 + BF 3.1.7 and BFC 3.1.3 + BF 3.2.

**Comment by AdinAck** [comment]
Yeah I have bf 3.1.7, had 3.1.1 and configurator 3.2 and i can't change anything!

**Comment by AdinAck** [comment]
I just tried bf 3.1.2 no change
