### ISSUE TITLE
Request: Enable/Disable all button for OSD screen

### ISSUE THREAD

**Issue by Arakon** [betaflight/betaflight-configurator#560]
Either that, or leave most of the uncommon options disabled by default.
Right now, when flashing a fresh firmware, almost everything is enabled and takes ages to disable one by one.

**Comment by tigert** [comment]
I don't think it is possible to have a default setting that works for everybody, since each person has their own favorite setup.

But you really should use the "diff" command on CLI to save your configuration between firmware upgrades, that makes it easy to get your config back after a new version.

**Comment by Arakon** [comment]
I do that, but when you do a clean setup, it's annoying.
Also, for some reason the "Horizon sidebar" setting doesn't seem to save in the diff command.. it's always enabled when I paste my commands, even though it's always disabled.

**Comment by spuder** [comment]
A button to disable everything would be helpful. 

<img width="450" alt="screenshot 2017-08-08 21 18 42" src="https://user-images.githubusercontent.com/242382/29132809-a0e5c19a-7cee-11e7-8cf0-5656b2af5b01.png">
