### ISSUE TITLE
Feature suggestion: Reciever tab quad preview should respect deadband settings

### ISSUE THREAD

**Issue by swilkens** [betaflight/betaflight-configurator#565]
The quad preview graphic in the receiver tab doesn't seem to respect the RC deadband settings in that same tab.

My transmitter has a slight jitter on the yaw channel, which i take care of by setting a deadband of 2. However, the quad graphic in the transmitter tab will continue to rotate (be it very slowly) as if the deadband is not applied.

My sugegstion is to let the graphic check if the receiver input is within the deadband before actually rotating, to better reflect the real world situation.

**Comment by timman2er** [comment]
Should be closed.

**Comment by swilkens** [comment]
Good catch :)
