### ISSUE TITLE
Beeper config not working

### ISSUE THREAD

**Issue by Arakon** [betaflight/betaflight-configurator#569]
The buttons are there, but they don't do anything. Always reset to everything active in the configurator after save and reboot, while not actually modifying any of the beeper settings (checked in CLI). PR #563 

Using BF 3.2.0 402de03bd402ff6d6e5260dff404e934118cfeb3 (not the very latest as that breaks CLI saving).

**Comment by basdelfos** [comment]
The changes in BF has to be merged yet and therefor it doesn't do anything at this point. Before official RC1 release this will be implemented and working.

**Comment by adfayed** [comment]
Hello, I am here running:
```
Configurator: 10.7.0
Firmware: BTFL 4.2.2
Target: IFRC/IFLIGHT_F722_TWING(STM32F7X2)
```
and I am still getting the same issue. Even after executing save in CLI mode it will **not** save beeper config. On reboot, everything resets to active.
