### ISSUE TITLE
Feature req: make "expert mode" toggle in configurator sticky

### ISSUE THREAD

**Issue by tigert** [betaflight/betaflight-configurator#570]
It would probably be good to have the expert mode toggle remember its state after you close and reopen the configurator.

**Comment by wind0r** [comment]
this option allready exists. just click the option symbol near expert mode. top right corner

**Comment by Arakon** [comment]
It's reset next time you start the configurator, though.

**Comment by wind0r** [comment]
Huh?
"Permanently enable Expert Mode" will not reset!

**Comment by tigert** [comment]
Oh, duh, that was pretty hidden :-) Is there a reason the sticky setting it is split into a separate config option and not just save its state between configuration "sessions"?

**Comment by wind0r** [comment]
Because there is the stick feature for experts and for normal users it should not be sticky. They need to know those settings are for "experts"
