### ISSUE TITLE
Desync motors

### ISSUE THREAD

**Issue by gotdirt** [betaflight/betaflight-configurator#575]
I just flew my quad after changing a notch filter and didn't notice the update to 3.1.2 config. I been running 4K/4K loops on my sp FC and now it desyncs and drops from the sky. No prob running these loops in 3.1.1 ever! Had to drop my PID loop down to 2k to work. Can I go back to 3.1.1? Also my motors tab is reversed as well and will not change on save and reboot. Also tried calibrating motors and no tone with master slider all way up when plugging in battery?

**Comment by basdelfos** [comment]
New version of BFC is released in the chrome store to address the issues you reported about the reversed motors preview and motor tab not working. Please try the new version.

The issue you have with motor desync is probably not related to the configurator. If you still have the issue, please report it in het Betaflight repo.
