### ISSUE TITLE
3.1.3 Non-power of 2 denominator selection is not displayed correctly

### ISSUE THREAD

**Issue by jflyper** [betaflight/betaflight-configurator#578]
3.2 + 3.1.3

When logging rate is set to the value corresponding to non-power of 2 denominator, it will not be displayed correctly when coming back to the page.

Set this up
![betaflight_-_configurator](https://user-images.githubusercontent.com/14850998/28754372-cdf835fe-757e-11e7-845e-f75cba1169f9.jpg)

And after save & reboot, it shows
![betaflight_-_configurator](https://user-images.githubusercontent.com/14850998/28754381-ec858e54-757e-11e7-9a1c-55f8018d4a7d.jpg)

**Comment by basdelfos** [comment]
I have debugged this, it is probably a firmware bug. The configurator send the correct data when saving. After rebooting the BlackboxRateNum is reported 0 by the firmware. This is only when setting logging rate to 33%, 20%, 17%, 14%. All other values seem to work OK.
