### ISSUE TITLE
3.1.2 "reversed motor direction" is always checked when it's not

### ISSUE THREAD

**Issue by timothyswt** [betaflight/betaflight-configurator#580]
I have a F4 V5 PRO that when its connected to betaflight, on the configuration tab it shows that the mototor direction is reversed:
<img width="555" alt="screen shot 2017-07-30 at 9 16 09 am" src="https://user-images.githubusercontent.com/1736223/28755109-0d91a866-7508-11e7-90c0-ce826dbb900c.png">

except that it is not:
<img width="257" alt="screen shot 2017-07-30 at 9 16 40 am" src="https://user-images.githubusercontent.com/1736223/28755111-1347cc40-7508-11e7-8ac8-6f7574c9ed64.png">

and every time I try to set it, it still shows reversed.

EDIT: this happened on both the 3.1.5 and 3.1.7 firmware version. I don't believe this is a firmware issue but rather a display bug since the motors are not actually reversed.

**Comment by pechovic** [comment]
Duplicate. https://github.com/betaflight/betaflight-configurator/issues/573

Should be closed.

**Comment by timothyswt** [comment]
Sorry I didn't see that one. I did a search but I just have done a poor job searching. Thanks!
