### ISSUE TITLE
Motors tab, "I understand..." switch is sometimes on

### ISSUE THREAD

**Issue by aowi7280** [betaflight/betaflight-configurator#585]
When I go to the Motors tab, sometimes the "I understand..." switch is already on. It should default to off.

**Comment by Arakon** [comment]
Are you using the 3.1.3 configurator? Cause in 3.1.3, it's fine.

**Comment by aowi7280** [comment]
versions must have just changed .

**Comment by basdelfos** [comment]
That was a known issue in the 3.1.2 configurator with BF 3.1.x. It's solved in configurator 3.1.3.
Please close this issue when this solved it.
