### ISSUE TITLE
Disable all OSD elements at once

### ISSUE THREAD

**Issue by spuder** [betaflight/betaflight-configurator#601]
The OSD currently has 37 elements that can be configured. If a user wants to only use a handful of elements, they need to do a lot of clicking to disable all of them. 

As a user, I want to press a button to clear all active elements, so I can select just the 4 or 5 elements I actually use. 

I envision something like this

<img width="450" alt="screenshot 2017-08-08 21 18 42" src="https://user-images.githubusercontent.com/242382/29103833-3018fb9a-7c7f-11e7-8730-64c113635ffa.png">

<img width="984" alt="screenshot 2017-08-08 21 10 57" src="https://user-images.githubusercontent.com/242382/29103710-8289e002-7c7e-11e7-97ec-d1fad9c648c6.png">

**Comment by piepluquad** [comment]
kinda duplicate of #560 ?

**Comment by spuder** [comment]
Yes, that is a duplicate.
