### ISSUE TITLE
Feature discussion: make the receiver configuration easier

### ISSUE THREAD

**Issue by tigert** [betaflight/betaflight-configurator#602]
#600 suggests a feature to calibrate the stick ranges, and that got me into thinking how the receiver page could be improved a bit.

  * The Receiver options (port and protocol) from the main configuration page could be moved to the receiver tab to combine things into one place? 

  * Then one could have a button to do automatic detection of receiver port and protocol (I guess this would require changes to betaflight code as well - would it require more flash space / code than what would be sensible?) - in any case this could happen in a popup dialog so the main UI could stay as it is.

  * Additionally you could then, once you found the receiver, proceed to the stick calibration as in #600 

  * Taking this even further, one could perhaps configure an arming switch by asking the user to flip it and detecting movement - but taking this path would be a bit bigger pandora's box as we're touching stuff outside the receiver page (modes) - and thus would mean some thought would need to be given to the whole configurator layout / grouping of things. 

However, doing this just for the receiver would contain everything inside the receiver page.

If this idea is deemed useful, I can assist with the user interface layout design if needed. My code-fu is weak but will have a look at how things are working under the hood. :-/

**Comment by haslinghuis** [comment]
Made an attempt in https://github.com/betaflight/betaflight-configurator/pull/2386
