### ISSUE TITLE
3.2.1 Blink on landing bug

### ISSUE THREAD

**Issue by damul** [betaflight/betaflight-configurator#605]
Blink on landing does not change anything. 

![image](https://user-images.githubusercontent.com/19986813/29203082-024deb5e-7ea9-11e7-9790-3870520f3072.png)

**Comment by mikeller** [comment]
If you can still see 'Blink on landing' your configurator needs to be updated. 'Blink on landing' has been replaced with 'VTX' for 3.2 (see https://github.com/betaflight/betaflight/pull/3250 for details on how 'VTX' works).

**Comment by damul** [comment]
It is automatically updated. Configurator is 3.2.1 released version.

**Comment by mikeller** [comment]
Ok. What is your firmware version?

**Comment by TheIsotopes** [comment]
fixed in #608

**Comment by damul** [comment]
I am using 3.1.5. should I upgrade it to 3.1.7?

**Comment by mikeller** [comment]
Ok, that should work then. You can try 3.1.7.
