### ISSUE TITLE
REQUEST - add post flight BB log number to serial interface

### ISSUE THREAD

**Issue by ShortnStubby** [betaflight/betaflight-configurator#612]
https://github.com/betaflight/betaflight/pull/3342

Please add post flight blackbox log number to serial interface selection for those using openlog device, also allow Log number to be query over serial interface so 3rd party osd such as mwosd can query flight log number.

Thank you.

**Comment by jflyper** [comment]
@ShortnStubby 
Adding log number to serial bblog device and external OSD both can not be done, because there is no way to know the "last log number".
