### ISSUE TITLE
Set Small Angle 

### ISSUE THREAD

**Issue by spuder** [betaflight/betaflight-configurator#617]
Since 3.2.x, `small_angle` is the only setting I have to set from the command line. 

In the past, many people would disable the accelerometer entirely, reducing the need for small_angle. 
Now that 3.2.x has crash detection (which I believe requires the accelerometer), more people will want to set `small_angle` to something like 180. 

Add support to set `small_angle` via betaflight configurator gui

## Implementation details

- [x] If accelerometer is disabled, grey out small_angle
- [x] If accelerometer is enabled, activate small_angle
- [x] Limit between 0 and 180
- [x] Include Tip explaining what Small Angle does
- [x] Hide if using api before 3.3.x (1.37.0)
- [x] Add get/set `small_angle` to betaflight fimware (https://github.com/betaflight/betaflight/pull/3868)

## Discussion items

- [x] In which section should this be located ( I think Configuration -> System Configuration tab)
- [x] What order should this option be located (directly after `Accelerometer`, or after `Magnetometer`)
- [x] What to name the option (Should it be called `small_angle` or something more intuitive like `ARM Angle`) `'Maximum ARM Angle [degrees]"'`
- [x] Which API version will this apply on? `1.37.0`

---
Option 1: Located at bottom
<img width="525" alt="screenshot 2017-08-15 20 57 52" src="https://user-images.githubusercontent.com/242382/29345610-21ef5f68-81fd-11e7-984a-3f42a7d9bb47.png">
Option 2: Located after accelerometer
<img width="524" alt="screenshot 2017-08-15 20 59 54" src="https://user-images.githubusercontent.com/242382/29345612-23b73c12-81fd-11e7-8b6e-d1bdc46cda3b.png">

**Comment by mikeller** [comment]
Good suggestion!

As a name I would probably go for something like 'maximum arm angle'.

Also, please be aware that, since 3.2.0 is already in the RC phase and this will require a change in the firmware (to get / set the parameter value), this will be a change to go into 3.3.

**Comment by spuder** [comment]
I actually think putting this under the ESC/Motor features makes more logical sense. 

<img width="522" alt="screenshot 2017-08-15 23 43 49" src="https://user-images.githubusercontent.com/242382/29348858-a96151d4-8213-11e7-809d-f081573b291d.png">

**Comment by martinbudden** [comment]
Why do you think it should be in the ESC/Motor features?

**Comment by spuder** [comment]
The thinking behind the ECS/Motor features is that 2 of the options relate to arming. 

Perhaps it would be better to have a dedicated ARMing section
![screenshot 2017-08-16 10 47 26](https://user-images.githubusercontent.com/242382/29374915-5e93425e-8270-11e7-9b4a-3e9965d3eaa5.png)

**Comment by tigert** [comment]
I am pondering it should explain *what* the angle is in relation to (horizontal plane or whatever) - and then I realze I try to understand what is the function of small_angle? Why is there a defined max tilt angle that inhibits arming? For angle mode takeoff to avoid prop strikes?

**Comment by spuder** [comment]
@tigert small_angle goes back to the days of multiwii https://github.com/multiwii/baseflight/wiki/CLI-Variables

For quad copters, I can't think of any reason you would want small_angle. Perhaps it was for safety when working on an aircraft? Perhaps to prevent prop strikes. 

I suggested removing small_angle entirely, or at least defaulting to 180 to the devs in the slack channel, but was met with some resistance. Making it easier to set is better than nothing

**Comment by valerioangelici** [comment]
@spuder I think it could be a safety feature for beginners to have small_angle low at the beginning, as it prevents the copter from arming if you have it on your hand if you inadvertently flip the arming switch.
I agree that it should be configurable with the gui and not only from cli.

**Comment by tigert** [comment]
@valerioangelici exactly, this is what I realized too - also the pretty common case of installing the flight controller flipped but failing to configure the board orientation accordingly - either because you are a new builder, or by mistake.

**Comment by spuder** [comment]
Here is what I have working. 

![betaflight-smallangle](https://user-images.githubusercontent.com/242382/31478943-2e5a7c96-aed1-11e7-870b-3458d0c1f785.gif)
