### ISSUE TITLE
PID Tab: show all PIDs function

### ISSUE THREAD

**Issue by skaman82** [betaflight/betaflight-configurator#62]
This table should be hidden as well until the "Show all PIDs" button is clicked. It would be also great if the state would be remembered. At the moment the PIDs are gone again on refresh.

<img width="727" alt="bildschirmfoto 2016-06-30 um 12 01 37" src="https://cloud.githubusercontent.com/assets/11768024/16484656/a896d960-3eba-11e6-9ce2-2f4516d85a6c.png">

**Comment by skaman82** [comment]
@mikeller could you please take a look at this as well?

**Comment by mikeller** [comment]
Done, #64. Let me know if you are good with the UI.

**Comment by skaman82** [comment]
@mikeller the second part of this issue is still open

**Comment by mikeller** [comment]
Is what you mean that if you click 'show all PIDs' and then refresh, only the active PIDs are showing again? If so, it's quite simple and I can do that when i get to do the rest of the work in the PID tab.

**Comment by skaman82** [comment]
yes, I mean exactly that. It is a pain in the butt if you testing inflight adjustments

**Comment by skaman82** [comment]
@mikeller thanks!
