### ISSUE TITLE
blackbox download error

### ISSUE THREAD

**Issue by nikfpv** [betaflight/betaflight-configurator#622]
Hi, when I try to download the blackbox log file, a message "save completed" pop up but the size of file is zero. with configurator v3.1.3 works good

I have bf 3.2.0 RC2 on target airbot f4, bf configurator version 3.2.1

**Comment by cyriq** [comment]
I got exactly the same problem, same version on configurator, Using bf 3.2.0 rc3, Emax Magnum stack (omnibus target).

**Comment by nikfpv** [comment]
With 3.2.0 rc3 seem to work :)

Il 24 ago 2017 20:01, "JonnyPhenomenon" <notifications@github.com> ha
scritto:

**Comment by JonnyPhenomenon** [comment]
awesome. Mark it as closed :)
