### ISSUE TITLE
Add sticks overlay to OSD 

### ISSUE THREAD

**Issue by JonnyPhenomenon** [betaflight/betaflight-configurator#630]
Feature request, to add the sticks to the OSD, kind of like the blackbox explorer can do, but in the FPV feed. 

Sure, the pilot really would have no need for this, as they would be watching where they were going, but this feature would be good for "passengers" monitoring your flight, especially in training scenarios, where an instructor would be able to watch the control inputs and coach the pilot, or while demonstrating a flight while showing the movements of the sticks... 

For example: (apologies for the crudeness of my sketch)

![sticks overlay](https://user-images.githubusercontent.com/16902792/29577705-76e808f2-873a-11e7-8c08-24d0a06c0bb7.jpg)

**Comment by mikeller** [comment]
I assume you want this to happen in the live OSD generated by the quad, and not in the 'preview' shown in the configurator? If so, can you please close this, and re-open an issue in https://github.com/betaflight/betaflight/issues ? It sounds like a good idea, and we'll keep track of it in there.

**Comment by JonnyPhenomenon** [comment]
Thanks Mike, I have opened the issue at https://github.com/betaflight/betaflight/issues/3988 and am closing this now.
