### ISSUE TITLE
Feature:ADD Android Support

### ISSUE THREAD

**Issue by Stavr0s91i** [betaflight/betaflight-configurator#636]
Isnt it time someone ported this over to android or ios? It should be that hard using Apache Cordova is someone has some experience with it

**Comment by tigert** [comment]
This is an open source project created by people like you mostly on their spare time. Maybe you can give it a try?

**Comment by Woody9999** [comment]
With release of the new Spektrum transmitter that is capable of running Android apps, the ability to run the configurator app would be very beneficial, with a potentially huge user base.

I'm just a user, and have no experience to be able to  program such a project.

**Comment by cmengler** [comment]
I've made progress with Apache Cordova using the latest Configurator v10.3.0 source and USB OTG for connectivity -- there is also the possibility for iOS using WiFi serial modules later on.

Just wanted to open up further discussions on some approaches regarding the UI layout.

My thoughts is to start with making the Configurators layouts be responsive for smaller screen sizes, use something lightweight like Pure CSS grid layout system.

**Comment by McGiverGim** [comment]
I don't know if you have seen the speedybee app https://appadvice.com/app/speedybee-app/1150315028

I'm pretty sure they are breaking the GPL, but what they have done is what you are trying to do. Maybe you can take ideas from there.

**Comment by mikeller** [comment]
> SpeedyBee is an Appllication for Flight controller parameters settings

They are also breaking the rules of English orthography...

**Comment by haslinghuis** [comment]
We have Android releases based on Cordova now. But support is brittle as no one seems interesting in supporting this.
