### ISSUE TITLE
Feature idea: "Channel Bug" logo for OSD

### ISSUE THREAD

**Issue by tigert** [betaflight/betaflight-configurator#646]
Wrote this down after some discussion on slack today.

We have currently some free space in the OSD chip character memory that is used to display the Betaflight logo on startup. It seems to be 24 characters in 3 rows. What if we used part of this as "channel bug" feature? Basically a small bitmap you could put on your OSD to personalize your DVR footage, for example, a bit like TV channels have in their broadcast.

You can currently hack this using the "aircraft name" setting by naming your craft for example "XYZ" and then make a customized font where you draw your logo over the XYZ characters. And hope that nothing else in the OSD uses those letters :-)

Ideally you could select a PNG image with the configurator with some maximum size (48x54 for example, so it uses 4x3 character grid) and upload it as custom characters to the OSD chip. 

You could then place your "pilot art" as a data field on the OSD wherever you wanted.

**Comment by mikeller** [comment]
I like the idea. I think before we address this, we should get the font optimisations that are proposed in betaflight/betaflight#3461 and #541 implemented (including a 'header character' containing metadata about the font). This will give us enough space in the first bank to implement the custom logo for all OSD chips.

**Comment by tigert** [comment]
A bit of inspiration and a default bug (pun intended :))

![image](https://user-images.githubusercontent.com/2587818/29957239-0e021252-8ef5-11e7-9f39-66983b9e130b.png)

![image](https://user-images.githubusercontent.com/2587818/29957254-2a324d20-8ef5-11e7-9cbd-cc1faaa179bc.png)

It might be a bit large, but chopping to 2x2 characters might be a bit too small as well, so I guess the designs would need to be placed towards the topright corner in case you want a slightly smaller logo (unless we want to implement exact positioning in the OSD settings, I guess that would be possible too, if you map it to the underlying character grid and then endode it into a font on the fly when you upload it?

**Comment by tigert** [comment]
A bit smaller version - though we start to lose clarity fast if we shrink it further.

![image](https://user-images.githubusercontent.com/2587818/29958000-37a3a658-8ef9-11e7-961c-e4c3a708a358.png)

**Comment by wind0r** [comment]
This PR: https://github.com/betaflight/betaflight/pull/3461 also will allow way more free spaces for logos and stuff :)

**Comment by tigert** [comment]
In case you want to replace the current logo in the fonts with a bit more pixel-aligned version that has the contrast outline too, so it looks better over the video.

![image](https://user-images.githubusercontent.com/2587818/29961742-347d17b0-8f09-11e7-8314-0bdd1f70adbf.png)

**Comment by tigert** [comment]
Sorry @jimmac I just had to ;-)

![image](https://user-images.githubusercontent.com/2587818/29963903-12d4eedc-8f11-11e7-9822-8d7f1a99b430.png)

**Comment by mikeller** [comment]
@tigert: We need transitions based on <ground speed> / <altitude> according to this scale: https://i.imgur.com/9w0SPNn.jpg

**Comment by tigert** [comment]
First I was like, waiting for the race to start..
![image](https://user-images.githubusercontent.com/2587818/30013877-d48a2f28-9151-11e7-841d-2fe3e3a8645c.png)

Noooo!
![image](https://user-images.githubusercontent.com/2587818/30013887-e54f2cbe-9151-11e7-87b8-c6779efa3b88.png)

Would be fun and awesome, but I doubt the readability would be useful.

However, animating your avatar from series of images based on a variable (like bank angle or throttle or aux channel ;-) ) would be pretty awesome.
