### ISSUE TITLE
"Camera control" Modes displaying old/wrong text first time

### ISSUE THREAD

**Issue by Arakon** [betaflight/betaflight-configurator#649]
Runcam Split configured on UART2.
Connecting to current 3.2.0 (as of today) using the latest (as of today) configurator and clicking on modes results in this screen:
![2017-09-02 23_37_51-betaflight - configurator](https://user-images.githubusercontent.com/12016360/29998955-1c028082-9038-11e7-99fa-eb2f99cd22a3.png)
If I then click on another tab (i.e. receiver or configuration) and back on the modes tab, the names change to the correct ones:
![2017-09-02 23_38_16-betaflight - configurator](https://user-images.githubusercontent.com/12016360/29998960-3ea933c4-9038-11e7-9e29-ef5b3aec0ed6.png)
As soon as I disconnect and reconnect, it returns to showing the wrong names again until I change tabs.

**Comment by tigert** [comment]
Dumb question, but you clicked "Reload" in your git-cloned configurator in the Extensions config on Chrome after you did a git pull?

**Comment by Arakon** [comment]
Yup. No difference. Issue was confirmed in the runcam split thread on RCG by someone else too.

**Comment by basdelfos** [comment]
The box names for the runcam split commands are translated in code.
https://github.com/betaflight/betaflight-configurator/blob/13e505ec61d99fe227d91c77a579264bbddc2089/tabs/auxiliary.js#L39-L50

Somehow there is a condition when the runcam split box names are only translated when runcam split is selected as peripheral in the ports tab. This is wrong, the text should always be translated even when runcam split is not selected as peripheral.

https://github.com/betaflight/betaflight-configurator/blob/13e505ec61d99fe227d91c77a579264bbddc2089/tabs/auxiliary.js#L58-L60

I will submit a pr to fix this and also move the hardcoded translation to the localized resource file.
