### ISSUE TITLE
OSD screen layout for buttons is broken

### ISSUE THREAD

**Issue by Arakon** [betaflight/betaflight-configurator#652]
Configurator 3.2.2 (current master) is missing the save and refresh (?) buttons in the bottom right.
![2017-09-03 21_27_59-](https://user-images.githubusercontent.com/12016360/30005984-e73bc19e-90ee-11e7-8158-5e0cabc6cdcd.png)

**Comment by AndersHoglund** [comment]
My copy of BFC 3.2.2 (current master HEAD = 7104a95edcef23a1240d78206dc696339127c489) works just fine.  Checked on two Win10 machines, one small low-res Laptop screen and one large hi-res stationary. Both in windowed and fullscreen modes.

**Comment by Arakon** [comment]
I just re-downloaded the current master and overwrote the folder again and it still happens. Switch to official 3.2.1 release and the buttons are there (Font Manager and Save, not Refresh as I stated above).
