### ISSUE TITLE
32khz gyro sampling causes incorrect blackbox log rate options

### ISSUE THREAD

**Issue by etracer65** [betaflight/betaflight-configurator#661]
If 32khz gyro sampling is enabled, then the blackbox logging rates are incorrect for on-board flash.  Consider the following configuration:

![screen shot 2017-09-10 at 7 07 29 pm](https://user-images.githubusercontent.com/17088539/30253850-78a9d28a-965b-11e7-9a7d-9353c7c5806e.png)

Then the only options in the blackbox tab are:

![screen shot 2017-09-10 at 7 09 21 pm](https://user-images.githubusercontent.com/17088539/30253857-98999fc6-965b-11e7-94ad-3f63130a3a78.png)

If a rate is selected in the cli for a faster speed like 8khz (`blackbox_p_denom = 256`) then the blackbox tab shows an empty selection for the rate:

![screen shot 2017-09-10 at 7 10 40 pm](https://user-images.githubusercontent.com/17088539/30253865-e32b5106-965b-11e7-9840-caa308e337a6.png)

The rate options in the blackbox tab appear to behave normally when 32khz sampling is not selected.

**Comment by mikeller** [comment]
Thanks, @basdelfos.

**Comment by basdelfos** [comment]
I can reproduce this issue also without 32khz enabled (as I don't own a 32khz capable fc). I tried it on an OMNIBUSF4 by settings `set blackbox_p_denom = 256` in the cli. The blackbox tab shows the same empty dropdown box.

**Comment by martinbudden** [comment]
Yes, `blackbox_p_denom` should be checked in `validateAndFixConfig`.

**Comment by mikeller** [comment]
> The fw shouldn't allow to set the blackbox_p_denom setting to a higher rate than the active pidloop speed, or am I wrong?

To my understanding, this is an intrinsic property of `blackbox_p_denom` being a denominator, and being based off the PID loop. (i.e. `blackbox_p_denom` of `1` means a P frame gets logged for every PID loop iteration, `2` means every second PID loop iteration, and so forth)

**Comment by martinbudden** [comment]
@mikeller , the way the denominator works has changed in 3.2.

Blackbox has two main types of frames, I-frames which store the absolute data, and P-frames which store deltas (so P-frames are smaller). In 3.2 blackbox was changed so that there are 32 I-frames per second, regardless of PID loop speed. The blackbox logging rate is then determined by the number of P-frames per I-frame (`blackbox_p_denom`). So if the p-denom is 16, then a blackbox frame will be logged  32*16= 512 times a second.

**Comment by mikeller** [comment]
@martinbudden: Can I just say that this is a convoluted way to set frame rates at the moment:

https://github.com/betaflight/betaflight/blob/07d599039550fc35738d0e7a7e740d6badad5de5/src/main/blackbox/blackbox.c#L1703-L1708

Also, n.b. that `blackboxConfig()->p_denom` is now a denominator on period, as opposed to `gyroConfigMutable()->gyro_sync_denom` and `pidConfigMutable()->pid_process_denom` that are still denominators on frequency. I think it should be renamed to make it apparent that they now work in opposite directions.

**Comment by basdelfos** [comment]
In 3.2.0 official release the blackbox_p_denom value is not there anymore (at least in cli). Is the BFC also changes for that or is that not necessary?

**Comment by McGiverGim** [comment]
@etracer65 I think this is and old issue. I suppose it is fixed and we can close it?

**Comment by etracer65** [comment]
Not sure if it's resolved but since we don't support 32KHz sampling anymore I guess it's no longer an issue. Closing.
