### ISSUE TITLE
Feature request: Show battery status in GUI

### ISSUE THREAD

**Issue by mikeller** [betaflight/betaflight-configurator#662]
Battery state is currently sent by MSP, but not used in the configurator:

https://github.com/betaflight/betaflight/blob/aae4d143bf96dfd973e543c4fa17933dd997a9b9/src/main/fc/fc_msp.c#L482

Add a 'battery state' icon / label to the top bar.

**Comment by HThuren** [comment]
@haslinghuis maybe this can be marked as solved, seems to be solved in msp.js and BatteryIcon.Vue

**Comment by haslinghuis** [comment]
Seems to be solved in #19
