### ISSUE TITLE
Improper Labeling of Min/Max Check and RC_MID is Reciever Tab

### ISSUE THREAD

**Issue by waltr1** [betaflight/betaflight-configurator#665]
The new config receiver tab has labels "Stick Min", "Stick Center" & "Stick Max".
This is VERY CONFUSING and many have set these to stick End Point values.

Please correct the labels to what these actually are: MIN_CHECK, RC_MID & MIN_CHECK.
A note stating these are the Stick Command thresholds would also be a good idea.

**Comment by mikeller** [comment]
MIN_CHECK, RC_MID, and MIN_CHECK are also not understandable per se. I think 'Stick Center' is actually good for RC_MID, how about 'Stick Down Threshold' / 'Stick Up Threshold'?

**Comment by waltr1** [comment]
How about Stick Command Min and Stick Command Max?
This is then pretty clear as to what the values are for.

Stick center ok. Still would like Note in the GUI as to what the CLI Command name actually is. This way when one reads docs and watches videos about Min_check, max_check, RC_MID they will know what the GUI setting is.
Do remember betaFlight docs (wiki) ONLY cover changes and all basics are referred to CleanFlight and BaseFlight docs and videos.
