### ISSUE TITLE
MATEK FC's not in firmware list?

### ISSUE THREAD

**Issue by Stavr0s91i** [betaflight/betaflight-configurator#672]
Hello,seems that matek fc's are not in the firmware list?

**Comment by mikeller** [comment]
You need to enable 'Show unstable releases'.

**Comment by mosvov** [comment]
I can see BF 3.2.0 in list 
![matek](https://user-images.githubusercontent.com/2290361/31585820-87cbb0ca-b1c8-11e7-8dc1-d4cbd37e5640.png)
