### ISSUE TITLE
Copy rateprofile doesn't work anymore

### ISSUE THREAD

**Issue by basdelfos** [betaflight/betaflight-configurator#678]
Coping rateprofile doesn't work anymore.
Using BFC 3.2.2, BF 3.2.0 and BF 3.2.0RC5, both combinations don't work anymore.

Steps to reproduce:
1. Start BFC
2. Select PID & Profiles tab
3. Click on button Copy rateprofile.
4. Select rateprofile 2 in the popup window
5. Click button Copy
6. Change active rateprofile to selected rateprofile in step 4. Rateprofile values are unchanged.

**Comment by mikeller** [comment]
Is it broken only in configurator, or in CMS as well?

**Comment by basdelfos** [comment]
It does seem to work with official 3.2.0 release, probably something in a RC was broken for a while.
