### ISSUE TITLE
Frsky receiver bound, no response in receiver tab

### ISSUE THREAD

**Issue by seanmc86** [betaflight/betaflight-configurator#681]
My quad was bound and flying perfectly using BF 3.1.7. After updating to 3.2, doing a reset to defaults, and setting up the correct UART, receiver modes in configuration and channel map, there is no response to the sticks in the receiver tab.

Equipment: Taranis QX7, Frsky XM+, HGLRC F428 FC. Also tested with Frsky X4R-SB with the same result. Firmware is the latest on both receivers.

Tried:
- Full flash/chip reset on upgrade/downgrade BF versions
- Tried BF configurator 1.9.4 with BF 3.1.0, 3.1.7, 3.2.0 after trying these firmwares on configurator 3.2.1.
- Triple checked that correct UART was set under Serial RX, that Serial-based and SBUS was selected in configuration, and that the correct layout was used on the receiver tab (I even tried every single UART with all of these adjustments individually just because)
- Rebound the receiver to the transmitter
- Tried setting sbus_inversion, both ON and OFF produce no different result
- Tried switching receiver protocols on configuration tab to something else and then back to serial/SBUS again
- Checked my wiring and 100% sure it isn't an issue (redid wiring when testing second receiver)

**Comment by jflyper** [comment]
@seanmc86 `diff` please.

**Comment by truespin** [comment]
I have the same issue: Taranis X9D, BF F3, Frsky X4R-SB
Have also tried all of the above, and now reverting to previous versions of BF also exhibits the no response to the sticks in receiver tab. I can see RSSI on the Taranis, so am sure I'm still bound correctly.
Here's my diff:
feature AIRMODE
feature ANTI_GRAVITY
feature DYNAMIC_FILTER
map TAER1234
serial 2 2048 115200 57600 0 115200
aux 0 0 0 1450 1550
aux 1 13 1 1550 2100
set gyro_sync_denom = 2
set motor_pwm_protocol = DSHOT600
set yaw_motors_reversed = ON
set pid_process_denom = 1
set osd_rssi_pos = 2081
set osd_tim_2_pos = 33
set osd_throttle_pos = 225
set osd_vtx_channel_pos = 2520
set osd_crosshairs = 200
set osd_ah_sbar = 200
set osd_ah_pos = 200
set osd_current_pos = 385
set osd_mah_drawn_pos = 2497
set osd_craft_name_pos = 2503
set osd_gps_speed_pos = 218
set osd_gps_lon_pos = 82
set osd_gps_lat_pos = 65
set osd_gps_sats_pos = 51
set osd_home_dir_pos = 302
set osd_home_dist_pos = 303
set osd_compass_bar_pos = 266
set osd_altitude_pos = 247
set osd_pid_roll_pos = 423
set osd_pid_pitch_pos = 455
set osd_pid_yaw_pos = 487
set osd_debug_pos = 1
set osd_power_pos = 321
set osd_pidrate_profile_pos = 345
set osd_avg_cell_voltage_pos = 76
set osd_pit_ang_pos = 257
set osd_rol_ang_pos = 289
set osd_battery_usage_pos = 392
set osd_disarmed_pos = 2282
set osd_nheading_pos = 311
set osd_nvario_pos = 279
set osd_esc_tmp_pos = 82
set osd_esc_rpm_pos = 2124
set osd_stat_max_spd = OFF
set osd_stat_bbox = OFF
set osd_stat_bb_no = OFF
profile 0

rateprofile 0

set rc_rate = 145
set roll_srate = 72
set pitch_srate = 72
set yaw_srate = 75

**Comment by seanmc86** [comment]
This is on the last one I stopped on, if you need the 3.2 diff let me know.

# diff

# version
# Betaflight / OMNIBUSF4 3.1.0 Jan 25 2017 / 09:45:27 (88693ca)

# name

# resources

# mixer

# servo

# servo mix


# feature

# beeper

# map
map TAER1234

# serial
serial 5 64 115200 57600 0 115200

# led

# color

# mode_color

# aux

# adjrange

# rxrange

# rxfail

# master
set serialrx_provider = SBUS
set osd_rssi_pos = 1046
set osd_gps_sats_pos = 1410

# profile
profile 0

rateprofile 0

# rateprofile
rateprofile 0


#

**Comment by rtaylo** [comment]
I'm having this same issue. 
FS-I6S transmitter bound to FS-iA6B receiver.
Everything else is working fine in Betaflight. I can use it to read accelerator and power motors. 
However, my receiver tab always shows 0. Even though my receiver is showing it's bound.

**Comment by rtaylo** [comment]
@seanmc86 Have you found a fix for this yet?

**Comment by jflyper** [comment]
I'm closing this, since this is a support request. Please redirect your issue statement to some other places on the net, that is intended for support, such as RCGroups.

https://www.rcgroups.com/forums/showthread.php?2936870-HGLRC-XJB-F428-TX20-Omnibus-F4-FC-28A-2-4S-ESC-and-25-100-250mW-VTX-Cube

That being said, from what's written in comments, I suspect the followings.

- Upgrading to 3.2 triggered the issue: Incorrect target firmware.
- Never worked with FrSky on UART6: Use UART1.
- FS-iA6B: Use DSMX signal pad for signal. UART is still UART1.

Please do not continue your conversations here. Thank you in advance.

**Comment by richard-scott** [comment]
Use ibus and not sbus

**Comment by Asantos1999** [comment]
@seanmc86 I recently started having nearly the exact same issue and I'm curious if you ever found the solution to this problem because I've tried all the previous suggestions and none have seemed to work for me.

**Comment by mfkenson** [comment]
i spent over an hour and finally found that d1-d8 should be changed to d1-d16.

**Comment by seanmc86** [comment]
@Asantos1999 I did find a solution, but I suspect something odd was happening with the receiver itself (the XM). When I desoldered the non-working XM, soldered on a new XM+ with the same type of firmware onto the board, tested this was working, and the resoldered the XM back on after taking the XM+ off, the XM then worked again. I didn't change any firmware during the process, other than the full firmware flash I did on the XM prior to starting. I didn't change any settings during this time so I can't reliably say what made it work.

**Comment by dantweez** [comment]
Ok i finally found out i dont no what im doing i bought it had it for
2monthes and never got it to start

**Comment by rodgerramjet** [comment]
thanks @mfkenson my ET125 with XM frsky receiver had the same thing. I was already on D16 mode but it only worked when i changed channels to 1-16 ....

**Comment by salavatov** [comment]
EMAX E6 TX is claimed to be Frsky D8
works fine with EMAX Tinyhawk
binds fine with Trashcan Crazybee F4 FC RX, but no signals. It possible to get some debug from spi RX in Crazybee F4 or may be known issue?
