### ISSUE TITLE
Seriously Pro F4 STM32 Virtual COM Port Driver

### ISSUE THREAD

**Issue by Davedigi1** [betaflight/betaflight-configurator#695]
Trying to connect to Cleanflight.
Installed the STM32 driver as instructed on page 8 of the F4 manual.
Get Failed to open comm port.
No comm port is present in the upper right.
Tried this on 2 Win10 pc's, same failure both times.
My SP F3 connects fine.

Anyone else having this issue and resolved it?

**Comment by mikeller** [comment]
@Davedigi1: GitHub is for questions and discussion around the **development** of Betaflight. For questions around the configuration and use of Betaflight, please visit [RCGroups](https://www.rcgroups.com/forums/search.php?searchid=62637789&query=betaflight%20connecting%20to%20configurator).
