### ISSUE TITLE
PID tab says "waiting for data"

### ISSUE THREAD

**Issue by Davhed** [betaflight/betaflight-configurator#70]
For the last couple of days the Betaflight Configurator won't load my PID tab on any of my quads. The Cleanflight configurator loads them just fine, and I can make changes with stick commands, so the FCs seems to be in fine shape. It's only a problem with the PID tab. Every other tab loads just fine.

**Comment by nathantsoi** [comment]
What version of betaflight are you running?

**Comment by borisbstyle** [comment]
install configurator 1.5
Op 1 jul. 2016 17:29 schreef "Nathan" <notifications@github.com>:

**Comment by Davhed** [comment]
I'm using configurator 1.5 and BF 2.8.1

**Comment by borisbstyle** [comment]
use 2.9....there was an msp bug in 2.8.1 for the new configurator
Op 1 jul. 2016 18:50 schreef "David Trounstine" <notifications@github.com>:

**Comment by Davhed** [comment]
Will upgrade now, thanks Boris.
