### ISSUE TITLE
BF 3.2.1 No Lost beeper switch working?

### ISSUE THREAD

**Issue by alanfj** [betaflight/betaflight-configurator#705]
What is wrong w/my lost beeper? Updated to 3.2.1 and beeper works only when powering up. I am new to all this and not very familiar w/ CLI commands. Please help? I am a newbie.

**Comment by mikeller** [comment]
@alanfj: GitHub is for questions and discussion around the **development** of the firmware and tools. For questions around the configuration and use of Betaflight, please visit [RCGroups](https://www.rcgroups.com/forums/search.php?query=betaflight%20cleanflight%20beeper%20config).
