### ISSUE TITLE
Can't install on ubuntu 

### ISSUE THREAD

**Issue by NullVoxPopuli** [betaflight/betaflight-configurator#71]
in the chrome store, after the package downloads, I get this error in a 'popup'

"Package is invalid. Details: 'Default locale is defined but default data couldn't be loaded.'."

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
```

```
$ uname -a
Linux Calypso 4.2.0-36-generic #42-Ubuntu SMP Thu May 12 22:05:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mikeller** [comment]
Hi @NullVoxPopuli.

I think the error you are getting might be related to the version of Chrome / chromium you are using. What language are the menu texts in your Chrome / chromium?

**Comment by NullVoxPopuli** [comment]
US English.
I'll check the version when I get home tonight. Good thinking!

**Comment by NullVoxPopuli** [comment]
I guess restarting chrome updated it, and betaflight works now! thanks!

**Comment by mikeller** [comment]
> I guess restarting chrome updated it, and betaflight works now! thanks!

Not that unusual with Chrome. Happy to see it works now.
