### ISSUE TITLE
Too much CPU usage warning [future request]

### ISSUE THREAD

**Issue by buzzcola3** [betaflight/betaflight-configurator#717]
It will be cool to add something that will say you to go lower when your CPU usage is too high on like 8k 8k.

**Comment by HThuren** [comment]
@haslinghuis maybe this can be marked as solved

**Comment by haslinghuis** [comment]
CPU load seems different between versions. We have cpuload in status bar. Dshot and PID loop frequency are already limited on F4 MCU's
