### ISSUE TITLE
Dterm Setpoint Transition help tooltip

### ISSUE THREAD

**Issue by Cleric-K** [betaflight/betaflight-configurator#719]
Dterm Setpoint Weight (SW) and Setpoint Transition (ST) have been notoriously misunderstood parameters. And trying to explain them with simpler analogies does not seem to help much.

Setpoint Weight is the more clear of the two and the help tooltip in the configurator is clear enough.
But I think that the help for the Transition must be reworked. Not only that is not very clear but it seems to me to be wrong.

Looking at cf/bf source code we have in pid.c, in `pidInitConfig()`:
```c
relaxFactor = 1.0f / (pidProfile->setpointRelaxRatio / 100.0f);
```
and then in `pidController()` we have:
```c
dynC = dtermSetpointWeight * MIN(getRcDeflectionAbs(axis) * relaxFactor, 1.0f);
...
const float rD = dynC * currentPidSetpoint - gyroRateFiltered;    // cr - y
```

Basically, ST weights SW according to stick position.
* If ST==1 (100 in raw units), then relaxFactor is 1 and as a result dynC moves linearly from 0 at stick centered, to the configured value of SW at full deflection.
* If ST is for example 0.5, relaxFactor becomes 2 and dynC moves from 0 at stick centered, to the configured SW value at halfway deflection (0.5). Above that point SW stays at its configured value (truncated by MIN).
* If ST is close to zero relaxFactor tends to infinity and as a result dynC reaches the configured SW value immediately - that is, there is no relaxation at all.

So I see two main problems with the current help tooltip. First:
> This parameter determines the transient behaviour setpoint weight on stick return

While practically correct, I find this a little misleading because it looks like there is some special dependence on whether the stick deflection is increasing or decreasing.

Second:
> The lower the value gets the more smooth end of flips or rolls will be.

This seems to be simply wrong. As we see from the code, the lower the value, the lower the stick point at which SW achieves its full value and at ST==0, SW is constant over the whole range of the stick, so we will get twitchy behavior even around the center of the stick (assuming SW is configured with high value).

I would suggest that in order to make the tooltip more helpful it should be something like this:
> With this parameter, Setpoint Weight can be reduced near the center of the sticks, which results in smoother end of flips and rolls. The value represents a point of stick deflection: 0 - stick centered, 1 - full deflection. When the stick is above that point, Setpoint Weight is kept constant at its configured value. When the stick is positioned below that point, Setpoint Weight is reduced proportionally, reaching 0 at the stick center position. Value of 1 gives maximum smoothing effect, while value of 0 keeps the Setpoint Weight fixed at its configured value over the whole stick range.

**Comment by mikeller** [comment]
@Cleric-K: Good suggestion! Would you mind opening a pull request to change this tooltip?
