### ISSUE TITLE
Esc issue

### ISSUE THREAD

**Issue by alexsvq** [betaflight/betaflight-configurator#751]
I mount on my quad the 4 dys 30a esc( blue ones) normally. I used a naze32 and I found that the esc 3 was forward the other three ( the normal value on motor test das 1040 and that 3rd esc was like 1096) . I reflashed al the esc to different firmwares but no one solve the problem. I change the "wrong" esc and the FC( now I used a Dys f4 AIO) and the issue still continue. One mate mounted the four escs on other quad and they worked fine. What's happening? :(

**Comment by mikeller** [comment]
@alexsvq: GitHub is for questions and discussion around the **development** of the firmware and tools. For questions around the configuration and use of Betaflight, please visit [RCGroups](https://www.rcgroups.com/forums/search.php?query=betaflight%20cleanflight%20esc%20programming).
