### ISSUE TITLE
Maximum ARM Angle disappeared 

### ISSUE THREAD

**Issue by spuder** [betaflight/betaflight-configurator#757]
In 10.0.0-rc3 the arming section is empty

<img width="579" alt="screenshot 2017-12-03 19 30 24" src="https://user-images.githubusercontent.com/242382/33533765-6b7e1278-d860-11e7-977d-d100cee3d9ec.png">

Same quad works on 3.2.2

<img width="534" alt="screenshot 2017-12-03 19 29 22" src="https://user-images.githubusercontent.com/242382/33533772-725b278e-d860-11e7-97fb-b91b5da1f71d.png">

It is entirely possible that it was moved, and I can't find it.

**Comment by mikeller** [comment]
Weird thing, I get the 'maximum arming angle' input on 10.0.0-rc3. What version of the firmware are you testing with? Could it be that it's too old to support UI entry of the maximum arming angle (the fact that it's showing an empty input field on 3.2.2 kind of suggests so).

**Comment by spuder** [comment]
Running 3.2.0 

    # Betaflight / BETAFLIGHTF3 (BFF3) 3.2.0 Sep 11 2017 / 06:30:07 (649ccd7c7) MSP API: 1.36

I can't remember if that was the 3.2.0 build that I compiled myself or not, so I flashed with the official 3.2.2 build and restored configs. I see the same result. 10.0.0-rc3 has missing Maximum ARM angle, and is present on 3.2.2 (Why the field is empty is another issue I'll need to look into)

**Comment by mikeller** [comment]
Mystery explained: It's only supported from 3.3 onwards.

**Comment by spuder** [comment]
Ah yes 🤦‍♂️.  Completely forgot about that.
