### ISSUE TITLE
Cfg freeze after saving on CLI

### ISSUE THREAD

**Issue by papayou66** [betaflight/betaflight-configurator#767]
I can not connect after cli comand and exit, I need to restart the cfg
Firmware 3.2.2 and 3.3
-- Running - OS: Windows64 bits, Chrome: 62.0.3202.94, Configurator: 10.0.0

**Comment by mikeller** [comment]
Confirmed with 10.0.0 (standalone) on Windows 10 (does not reproduce on linux). Firmware: 3.3 / 3.2.2.

**Comment by papayou66** [comment]
if i enable auto connect cfg work well:
in CLI After saving / exit FC reboot and connexion to the CFG is ok 

if i disable auto connect cfg do not work:
in CLI After saving / exit FC reboot but connexion failed 
I need to click disconnect and connect twice

**Comment by mikeller** [comment]
@papayou66: Can you please test https://drive.google.com/file/d/1HWhS0FFC9nxip1rntDriAfZaB7flQxHg/view?usp=sharing

**Comment by papayou66** [comment]
@mikeller perfect I could not reproduce this issue
