### ISSUE TITLE
New Standalone Configurator git pull?

### ISSUE THREAD

**Issue by richard-scott** [betaflight/betaflight-configurator#770]
I have a scheduled task that performs a "git pull" each time I boot my laptop to ensure that my Google Chrome Extension BF Configurator is running the latest codebase. 

I would like to be able to do the same with the new Standalone Configurator.
Is that possible?

**Comment by mikeller** [comment]
Sure. Just run an `npm install` and `gulp release` after pulling. You'll have to install node, and run `npm install gulp -g` as a one-off.
