### ISSUE TITLE
Windows Protected your PC Error

### ISSUE THREAD

**Issue by richard-scott** [betaflight/betaflight-configurator#771]
Are there any plans to get the required certification to remove this error?

![2017-12-06 10_42_46-smartscreen](https://user-images.githubusercontent.com/5149834/33658040-15710b1e-da73-11e7-8023-bdbb5462b541.png)

**Comment by mikeller** [comment]
I wasn't aware that this is showing at all. I run Windows defender, but it does not show for me. Will look into it, but not too keen to pay racketeering money to Microsoft for them to stop harassing the app. Also, this will make automated builds on CI difficult.

**Comment by dthubereng** [comment]
Happened to me this morning. Not a big deal to hit "Run anyway" the first time, IMO.

**Comment by fixmania** [comment]
In my case, that is appearing only in Windows 10 that has more powerful PC protection. But only about when you install the app.
