### ISSUE TITLE
OSD config page blank

### ISSUE THREAD

**Issue by fiveangle** [betaflight/betaflight-configurator#783]
Opening here but suspect a FW issue.

Running nightly:

Betaflight / OMNIBUS (OMNI) 3.3.0 Dec  7 2017 / 20:49:49 (bb79830) MSP API: 1.37

OSD page is blank:

![osdblank](https://user-images.githubusercontent.com/2219447/33798918-486dc5ce-dcd6-11e7-90e5-cb39ad7984b1.png)

Tested on 2 separate OMNIBUS targets that were working correctly on 12/2 nightly.

-=dave

**Comment by wind0r** [comment]
nightly firmware needs nightly configurator

**Comment by mikeller** [comment]
@wind0r: Good one! We should stick this one at the top of the configurator help page.
