### ISSUE TITLE
Tethered Logging using CLI?

### ISSUE THREAD

**Issue by helpmelearnplease** [betaflight/betaflight-configurator#785]
Hello,
Is it possible to initiate Tethered Logging feature in the betaflight-configurator using the CLI?

**Comment by mikeller** [comment]
Not really. The problem is that tethered logging uses MSP to  poll the logging information, and MSP and CLI cannot run at the same time. What is your use case?

**Comment by helpmelearnplease** [comment]
@mikeller I was looking for a way to use tethered logging option in the betaflight configurator to log the data rather than using the SD card.
I know there is an option to initiate tethered logging in betaflight configurator interface, I was looking if we have any CLI command to initiate the Tethered Logging.
