### ISSUE TITLE
"No configuration received within 10 seconds, communication failed"

### ISSUE THREAD

**Issue by tayaubuchon30** [betaflight/betaflight-configurator#787]
I have a Naze32 flight controller and it connected to betaflight and worked well on a previous user's computer - but now with an older PC and all but the Zadig drives downloaded, I keep getting the communication error and cannot connect.

**Comment by mikeller** [comment]
@tayaubuchon30: GitHub is for questions and discussion around the **development** of the firmware and tools. For questions around the configuration and use of Betaflight, please visit [RCGroups](https://www.rcgroups.com/forums/search.php?query=betaflight%20cleanflight%20driver%20install).
