### ISSUE TITLE
Not Entry Point Found Error - Betaflight Configurator 10.0.0

### ISSUE THREAD

**Issue by RoughRiderFPV** [betaflight/betaflight-configurator#788]
Hello, My issue is stemming from a startup error. Error Window Entry Point Not Found says "The procedure entry point QueryUnbiasedInterruptTime could not be located in the dynamic link library KERNEL32.dll." I've Redownloaded this file 4 times and am stuck at the moment. What should I do?

**Comment by mikeller** [comment]
What platform are you running, and on what hardware?

**Comment by RoughRiderFPV** [comment]
windows 7 32bit

**Comment by mikeller** [comment]
I could not find any information about Windows 7 being supported by NW.js, but the error message, and the fact that support for Windows 7 has ended, suggest that might not be supported any more.

You'll probably have to update your operating system to one that is supported, or look into building the configurator with a legacy version of NW.js.

**Comment by basdelfos** [comment]
I have a Windows 7 VM (64-bits) laying around, will try tonight if I get the same error.

**Comment by basdelfos** [comment]
Confirmed that the configurator does work on Windows 7 64-bit, I'm running SP1, probably very old. I did some testing and everything seems to work correctly.

**Comment by mikeller** [comment]
Ok. That still does not mean that it runs on Windows 7 32 bit. Google has been rather progressive in dropping support for older platforms in Chrome.

**Comment by basdelfos** [comment]
I have no Windows 7 32-bits available to test

**Comment by mikeller** [comment]
Might be hard to find these days.

**Comment by mikeller** [comment]
Duplicate of #813.
