### ISSUE TITLE
Prearm in Modes tab doesn't change colour when activated.

### ISSUE THREAD

**Issue by richard-scott** [betaflight/betaflight-configurator#790]
I've noticed that when testing Modes the Prearm Mode doesn't change colour when you enable the switch on your TX. This is different to all the others which change to orange when activated.

**Comment by mikeller** [comment]
This is not a configurator bug. The status of the modes is reported by the firmware, and it looks like it is not reporting the way it should for PREARM.

**Comment by richard-scott** [comment]
In the CLI the NOPREARM status is removed when PREARM is activated so the FC is showing the correct status... that is assuming this status is read from the FC and not derived by BFC from looking at the signals being sent by the RX.

**Comment by richard-scott** [comment]
ah, I see its already been fixed in the [Firmware ](https://github.com/betaflight/betaflight/pull/4759) :-)
