### ISSUE TITLE
Resizing window smaller can make the save and reboot button disappear.

### ISSUE THREAD

**Issue by CrazyMonkeyCM2** [betaflight/betaflight-configurator#798]
Resizing window smaller can make the save and reboot button disappear.
Should not be possible to do so.

**Comment by mikeller** [comment]
What tab is this happening for, @CrazyMonkeyCM2?

**Comment by CrazyMonkeyCM2** [comment]
Sorry, should have mentioned, all of them.
I am running my screen at 3840x2160 with DPI scaling at 350%.
Also its only the window width that causes it, not height.

**Comment by mikeller** [comment]
- there isn't a 'Save and Reboot' button on all tabs;
- tried with one, works fine.

Closing this as 'not enough information'.

**Comment by CrazyMonkeyCM2** [comment]
Ill provide pictures if you don't believe me.
here is it happening on 2 tabs, but it happens on every tab save is supposed to show.
![p1](https://user-images.githubusercontent.com/1240785/34088208-6a791b9e-e36d-11e7-9c46-bb61fc251d2f.JPG)
![p2](https://user-images.githubusercontent.com/1240785/34088212-70a105f4-e36d-11e7-87d4-2c31a1cf4ab3.JPG)

![p3](https://user-images.githubusercontent.com/1240785/34088217-755d3eb4-e36d-11e7-96f1-11a86a75fbb6.JPG)

![p4](https://user-images.githubusercontent.com/1240785/34088218-78232ec4-e36d-11e7-9518-bcf460fd9db5.JPG)
