### ISSUE TITLE
Target reset requires close/restart of Configurator

### ISSUE THREAD

**Issue by MotoLab** [betaflight/betaflight-configurator#80]
MOTOLAB target with Configurator on Linux consistently fails to reopen the serial port after device save/reset. Seems to be timing related, may be attempting to reopen the serial port too quickly after reset. Tested with Configurator V1.5.

**Comment by MotoLab** [comment]
On further examination, this seems to be something in the firmware startup. A few seconds after the reset, Configurator will connect. I'll look into that further.

**Comment by mikeller** [comment]
I think this is caused by the 'high load on startup' issue that 3.0 is having: https://github.com/betaflight/betaflight/issues/539

**Comment by MotoLab** [comment]
I think it's the same issue, but USE_SDCARD isn't defined on the MOTOLAB target so that's not the problem.
