### ISSUE TITLE
WinXP Sp3 32 support?

### ISSUE THREAD

**Issue by mstkpimp** [betaflight/betaflight-configurator#800]
I know it's old but when I click the BF icon I get this message "The procedure entry point ReleaseSRWLockExclusive could not be found in the dynamic libray link Kernel32.dll"

I know Chrome ended support for XP but it would be awesome if I could use my WinXP system with this standalone version of BF.

**Comment by mikeller** [comment]
No, sorry, the train for XP has definitely left. You should stop using it anyway, having it connected to the internet in any way shape or form is posing a risk to all other users as a propagation vector for malware.
