### ISSUE TITLE
Rework 'Receiver' tab

### ISSUE THREAD

**Issue by mikeller** [betaflight/betaflight-configurator#81]
Ideas that were brought up so far:
- move / add all settings pertaining to the receiver config to the receiver tab #36, #75;
- add 'check receiver settings' button #75;

**Comment by haslinghuis** [comment]
Two problems while moving stuff. 

![Screenshot from 2021-01-14 01-44-09](https://user-images.githubusercontent.com/8344830/104529488-28da7800-560a-11eb-80d3-93543a3bf95a.png)

**Comment by haslinghuis** [comment]
Two problems while moving stuff.
About the first the feature is filled with the RX stuff. second, don't comprehend why the i18n is not working

![Screenshot from 2021-01-14 01-44-09](https://user-images.githubusercontent.com/8344830/104529488-28da7800-560a-11eb-80d3-93543a3bf95a.png)
