### ISSUE TITLE
Wrong extra commas

### ISSUE THREAD

**Issue by lokanaft** [betaflight/betaflight-configurator#815]
At:
https://github.com/betaflight/betaflight-configurator/blob/398228bf45e9a67befd2d7dd42e5b17bbc5cc5f8/js/Features.js#L69
https://github.com/betaflight/betaflight-configurator/blob/398228bf45e9a67befd2d7dd42e5b17bbc5cc5f8/js/Features.js#L95
With it, work only CLI.

**Comment by mikeller** [comment]
Interesting. How did you run the configurator when these caused problems for you? Both chrome and NW.js seem to be ignoring these syntax errors when running on linux.
