### ISSUE TITLE
Windows 10 pinned task bar icon

### ISSUE THREAD

**Issue by richard-scott** [betaflight/betaflight-configurator#847]
Over the last 3 days the pinned icon on windows 10 has changed from the BF logo to a white box.

I build from master, and the run the exe in the apps folder. I then right click the working BF icon on the task bar and choose to pin it and the icon goes to a white box.

**Comment by McGiverGim** [comment]
It seems to work right for me. The icon has changed in this PR https://github.com/betaflight/betaflight-configurator/pull/832 but I don't think that this is the problem.

It worked for you before?

**Comment by richard-scott** [comment]
odd, after a reboot its now working again.
