### ISSUE TITLE
Win10 sometimes unreadible fonts - looks like a 'clearfont' issue?

### ISSUE THREAD

**Issue by RipperDrone** [betaflight/betaflight-configurator#864]
![image](https://user-images.githubusercontent.com/12601105/35007017-8e538b56-faf8-11e7-889d-1a95985e410d.png)

**Comment by RipperDrone** [comment]
Fonts scaling seems to cause dithered / unreadible fonts sometimes...

**Comment by McGiverGim** [comment]
I'm not too sure that this is a bug. The configurator uses "web fonts", when the connection is slow, or it is not a connection at all, it will fall back to a font with less quality. Maybe this is the problem. When this happens, do you have a good internet connection?

**Comment by RipperDrone** [comment]
would think so, DSL16k...

**Comment by basdelfos** [comment]
May be this has something to do with the global font size in Windows. Can you tell us what your font size is?

![image](https://user-images.githubusercontent.com/334779/35086612-6510a23e-fc2d-11e7-9494-91e99a2807b6.png)

Sorry...Dutch locale on this laptop, but the menu items are in the same place.

**Comment by RipperDrone** [comment]
It’s @ 100% on 1920x1080 res. Is this what you were asking? :)

 



 

 

Von: Bas Delfos [mailto:notifications@github.com] 
Gesendet: Donnerstag, 18. Januar 2018 08:57
An: betaflight/betaflight-configurator <betaflight-configurator@noreply.github.com>
Cc: Reinhard <reinhard.plietsch@web.de>; Author <author@noreply.github.com>
Betreff: Re: [betaflight/betaflight-configurator] Win10 sometimes unreadible fonts - looks like a 'clearfont' issue? (#864)

 

May be this has something to do with the global font size in Windows. Can you tell us what your font size is?

 <https://user-images.githubusercontent.com/334779/35086612-6510a23e-fc2d-11e7-9494-91e99a2807b6.png> 

Sorry...Dutch locale on this laptop, but the menu items are in the same place.

**Comment by basdelfos** [comment]
Yes, that's what I meant. Strange, nothing unusual with those settings.
Now I look at your image again, it looks like that the whole inner part of the app is blurry and not only the fonts?

**Comment by McGiverGim** [comment]
Yes, the images are blurry too (the `donate` button for example...) Maybe a problem with the graphic card?

**Comment by basdelfos** [comment]
I don't think it is hardware related, I think it is chromium (part of nw.js) releated. 
Do you have the same issue with the standalone Blackbox Explorer?

**Comment by RipperDrone** [comment]
No, BBE is crystal clear: 
![image](https://user-images.githubusercontent.com/12601105/35165359-5fb99382-fd4e-11e7-891b-dd4a1738e239.png)

**Comment by RipperDrone** [comment]
Comparison: 
![image](https://user-images.githubusercontent.com/12601105/35165421-8ea57cd8-fd4e-11e7-8d0c-4d378e6fe2f9.png)

**Comment by RipperDrone** [comment]
When pressing some buttons (minimizing/maximizing app window, it looks normal again... <noideawtfisgoingonhere>

**Comment by RipperDrone** [comment]
crazy... 
![image](https://user-images.githubusercontent.com/12601105/35181870-905e8ec6-fdca-11e7-9f26-19065c087bc3.png)

**Comment by RipperDrone** [comment]
resolved - NVidia Antialiasing (FXAA) needs to be switched off
