### ISSUE TITLE
shawnb

### ISSUE THREAD

**Issue by boutit84** [betaflight/betaflight-configurator#870]
flash firmware keeps on reading STM32 communication failed,wrong response,expected;121 (0+79) receiver:0 (0+0)

**Comment by mikeller** [comment]
@boutit84: GitHub is for questions and discussion around the **development** of the firmware and tools. For questions around the configuration and use of Betaflight, please visit [RCGroups](https://www.rcgroups.com/forums/search.php?query=betaflight%20cleanflight%20serial%20port).
