### ISSUE TITLE
GPS Position is not shown

### ISSUE THREAD

**Issue by jstremmler** [betaflight/betaflight-configurator#874]
In the new Betaflight Configurator 10.1. GPS position is not shown on the GPS Page anymore
![gps_position](https://user-images.githubusercontent.com/15327312/35145349-ce3640d6-fd07-11e7-89f1-4547d500b59f.jpg)

**Comment by McGiverGim** [comment]
Some time ago this problem happened and was solved, I can find the BF PR but I found the CF one: https://github.com/cleanflight/cleanflight-configurator/pull/485 

Maybe the NW is ignoring the `manifest.js`? Can you build yourself the configurator in debug mode and take a look to the console to see if there's some error?

**Comment by McGiverGim** [comment]
I've tried and this is the error in the console:
```
extensions::webViewEvents:294 <webview>: The load has aborted with error -20: ERR_BLOCKED_BY_CLIENT.
```

**Comment by McGiverGim** [comment]
I think that I've fixed it in https://github.com/betaflight/betaflight-configurator/pull/875, only need is to declare the partition.

**Comment by mikeller** [comment]
> Maybe the NW is ignoring the manifest.js? Can you build yourself the configurator in debug mode and take a look to the console to see if there's some error?

Yes, NW does not use `manifest.json`, and gets the metadata from `package.json` instead.
