### ISSUE TITLE
betaflight 10.2.0

### ISSUE THREAD

**Issue by Peppelill** [betaflight/betaflight-configurator#889]

**Comment by Peppelill** [comment]
![img_20180126_120515](https://user-images.githubusercontent.com/35837309/35438226-f8b1b6ea-0295-11e8-94ce-f75a7b3b9957.jpg)

**Comment by McGiverGim** [comment]
Please, don't open issues for this. The 10.2.0 italian version is not oficial. You can post it here: https://github.com/betaflight/betaflight-configurator/issues/859

Can you close this issue? Thanks!

**Comment by McGiverGim** [comment]
@Peppelill You only have deleted the content. If you want to close it, next to the "Comment" button you will find a "Close issue"
