### ISSUE TITLE
OSD issue: PAL cossshairs not center

### ISSUE THREAD

**Issue by Gorilla-1983** [betaflight/betaflight-configurator#890]
The crosshairs for a PAL camera are not in the centre of the OSD, in the Configurator or in the goggles. The crosshairs remain in the centre of what was the NTSC display, according to the Configurator preview.
I have tried to adjust the crosshairs in the OSD tab but they are in a fixed position (unmovable) and in the CLI using the command "set osd_crosshairs = 2318" but they still remain in the same off centre location.
Is there a command I am missing?

**Comment by McGiverGim** [comment]
If I'm not wrong, the number of columns is pair, so it is not possible to find a column in the center: or we change the cross to use two columns, or it will always be in the left/right of the center.

**Comment by Gorilla-1983** [comment]
I didn't describe well enough when I said off centre; the crosshairs are in the centre left to right but not up and down. They sit roughly 2/5ths from the top of the screen

**Comment by DanNixon** [comment]
There is planned work to make the position of the crosshairs configurable.

**Comment by Gorilla-1983** [comment]
Brilliant, thanks for getting back to me so quick.

**Comment by Gorilla-1983** [comment]
G'day, DanNixon said in a previous post that the crosshair position is to be made configurable. Does any one know if this is available yet?

**Comment by McGiverGim** [comment]
It has been planned for 3.4 https://github.com/betaflight/betaflight/pull/5326

**Comment by Gorilla-1983** [comment]
Brilliant 😀, thanks for responding so quickly

**Comment by mmakam2** [comment]
hi there, I am experiencing this issue in version 3.4 DALRCF405. Any plans for a fix?

**Comment by mmakam2** [comment]
![image](https://user-images.githubusercontent.com/25559970/40881575-4f376a16-668f-11e8-8fdc-059a1d629851.png)

**Comment by mikeller** [comment]
@mmakam2: It is fixed. Adjust `osd_crosshairs_pos` to make your crosshairs centered. The (soon to be released) configurator 10.3.0 will allow you to do this in the GUI.

**Comment by mmakam2** [comment]
thank you sir
