### ISSUE TITLE
Firmware Flasher not working

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/betaflight-configurator#893]
since #879 the Firmware Flasher is broken ... @McGiverGim please can you check whats wrong

using win64 installer from [http://andwho.sytes.net:8080](http://andwho.sytes.net:8080/job/BorisB_BetaFlight_Configurator/) ... `#125` last working

**Comment by McGiverGim** [comment]
Strange. Yes, I will look at it tomorrow at first hour.

**Comment by McGiverGim** [comment]
Thanks! Problem found and solved ;)

**Comment by TheIsotopes** [comment]
tested and it's fixed ... thx 👍
