### ISSUE TITLE
Nightly builds on ci.betaflight.tech 

### ISSUE THREAD

**Issue by richard-scott** [betaflight/betaflight-configurator#910]
Would it be possible to add a build of the Configurator on ci.betaflight.tech for all supported platforms?

**Comment by AndersHoglund** [comment]
Depends on the availability of Linux, Win and Mac build hosts.  Real or virtual.

Until that is solved, use my slooow site: 
http://andwho.sytes.net:8080/job/BorisB_BetaFlight_Configurator/

The other two utils are also available: 
http://andwho.sytes.net:8080/job/Borisb_Blackbox_Log_Viewer/
http://andwho.sytes.net:8080/job/DieHertz_BlHeli_Configurator/
