### ISSUE TITLE
Configurator 1.6.3 - 3d model - Yaw input.

### ISSUE THREAD

**Issue by FasaArg** [betaflight/betaflight-configurator#92]
The 3d model does not responde to the yaw input from the receiver.

**Comment by mikeller** [comment]
What version are you using?

**Comment by FasaArg** [comment]
1.6.3 , but apparently is a momentary error, after restart the configurator is working fine (strange)
Before, the signal slider worked ok, but the model does not responded.

**Comment by FasaArg** [comment]
Could you reopen this issue?? The problem persist...

**Comment by FasaArg** [comment]
@mikeller 
I found the problem!
If you go to PID tab after connect, works always fine.
If you go to receiver tab, does not work.
If you go back to receiver after using PIDtab, start to work ok.

**Comment by mikeller** [comment]
Ha, thanks for doing the testing, @FasaArg.

@antstorm: I think this is because `currentRates` only gets initialised when the PID tab is loaded. Can you look into this?

**Comment by FasaArg** [comment]
@mikeller Thanks to you, let me know if i can help with anything.

**Comment by antstorm** [comment]
@mikeller sure, I'll look into this

**Comment by antstorm** [comment]
Here's a PR ^. `MSP_SPECIAL_PARAMETERS` didn't get loaded, which has `RC_RATE_YAW`.

**Comment by mikeller** [comment]
@antstorm: Saw that, thanks.

@FasaArg: If you are comfortable enough with GitHub to clone the betaflight-configurator repo, you can clone it, and then 'Load unpacked extension' in 'Extensions' in chrome, to verify that the fix works.

**Comment by FasaArg** [comment]
@mikeller Thanks, but i'm registered since today to be honest... I have no idea.

Anyway, i will try to read about how to use it.

**Comment by FasaArg** [comment]
@mikeller Today i learned how to use the clone and tested the fix, Working ok without any issue.
Thanks again.

**Comment by mikeller** [comment]
@FasaArg: Thanks for testing, and well done!
