### ISSUE TITLE
Cant find com port on windows 10

### ISSUE THREAD

**Issue by asm7100** [betaflight/betaflight-configurator#924]
Hi
It cant find comport on windows 10.
It says Port: /dev/rfcomm0??
And iam running on windows 10 64bit.

**Comment by mikeller** [comment]
@asm7100: GitHub is for questions and discussion around the **development** of the firmware and tools. For questions around the configuration and use of Betaflight, please visit [RCGroups](https://www.rcgroups.com/forums/search.php?query=betaflight%20cleanflight%20configuration%20use).
