### ISSUE TITLE
Returning to motors tab resets safety switch and disarms quad

### ISSUE THREAD

**Issue by etracer65** [betaflight/betaflight-configurator#933]
Maybe this is by design, but it's kid of confusing.

Enabling the safety switch on the motors tab allows the quad to arm.  You can then switch to other tabs and the quad stays armed (useful to look at receiver, battery state, etc.).  If you then return to the motors tab the safety switch is reset and the quad is disarmed.

https://github.com/betaflight/betaflight/pull/5185 is partially to blame in that it now causes a disarm when the safety switch is turned off.  But the real problem is that the safety switch shouldn't turn off when entering the tab.  Should be initialized to off on connect and then controlled by the user thereafter.

**Comment by mikeller** [comment]
Looks like a regression, it was fixed already in #713.
