### ISSUE TITLE
map.js reference is not correct

### ISSUE THREAD

**Issue by JManDoo** [betaflight/betaflight-configurator#938]
When using GPS, the MAP.js is not referenced correctly
I moved the map.js from the /js/tabs/map.js to the /tabs/ folder and this corrected the issue

**Comment by McGiverGim** [comment]
Good find. Is better to change the html to reference the right direction of the js file. I can make a PR tomorrow if nobody makes it before.

**Comment by McGiverGim** [comment]
@JManDoo if you can, please post you the PR but it's better to change it here:
https://github.com/betaflight/betaflight-configurator/blob/e14f75015a6697471685c1db2143d2423007331b/src/tabs/map.html#L14

**Comment by JManDoo** [comment]
I tried that, but it would reference it correctly for me
I edited the main.html to ref it, as well as the html
But the only way it would work was to move it
`<script src="\js\tabs\map.js"></script> `

**Comment by McGiverGim** [comment]
The slash must be in the other direction: /

**Comment by JManDoo** [comment]
Grr

**Comment by McGiverGim** [comment]
You pushed it to the wrong repository 😋

**Comment by JManDoo** [comment]
I noticed, I am new to this 😶

**Comment by JManDoo** [comment]
is the correct slack link, listed in main.html http://betaflight.tk/slack
When i go there its a squatter site

**Comment by McGiverGim** [comment]
No, to register you can use http://betaflight.ch/ after that the chat is here http://betaflightgroup.slack.com

**Comment by McGiverGim** [comment]
I had no much time to look into it. You must change here too:
https://github.com/betaflight/betaflight-configurator/blob/d27c10d63ac126b9307d7922d7303af5bc1434e3/manifest.json#L48
But I tried and didn't work neither.

**Comment by JManDoo** [comment]
https://github.com/betaflight/betaflight-configurator/pull/940

**Comment by McGiverGim** [comment]
I think that this issue can be closed. It has been merged and released in the new version ;)
