### ISSUE TITLE
dterm_setpoint_weight has a max of 254, configurator goes to 255

### ISSUE THREAD

**Issue by colorex** [betaflight/betaflight-configurator#944]
The slider in the configurator PID tab goes from 0 to 2.55. The max allowed by BF code is apparently 254. When entering 2.55, saving and refreshing (BF 3.3.0 RC2) the value goes to 2.54.

**Comment by mikeller** [comment]
@colorex: Can you be a bit more specific about which of the sliders does have the wrong range? An annotated screenshot would help.

**Comment by EGParadox** [comment]
![untitled](https://user-images.githubusercontent.com/36385043/36639872-fe405608-1a1d-11e8-890d-2bf3aee0be47.png)
 So it can bee replicated if scroll to 2.55 value hit save>refresh and you get 2.54

**Comment by colorex** [comment]
Looks like there was enough information in the OP :)

Yes that’s how you can replicate it. It’s a minor bug without bad
consequences but should be an easy fix anyway.

**Comment by mikeller** [comment]
@colorex: Hehe, my bad, reading the text of an issue **and** the title helps.

**Comment by colorex** [comment]
I’m new to github. Do I close this issue now that there are commits in place? Or when it’s released? Or will an admin close it?

**Comment by mikeller** [comment]
@colorex: Yes please. And thanks for reporting this.
