### ISSUE TITLE
[Feature Request] - Make Release Notes pretty.

### ISSUE THREAD

**Issue by richard-scott** [betaflight/betaflight-configurator#954]
I've noticed that the Release notes are hard to read. Maybe this could be changed to use the markup provided to format the text better?

![2018-02-26 19_40_44-betaflight configurator](https://user-images.githubusercontent.com/5149834/36694458-6349d236-1b36-11e8-9e0a-c25fdcdb8518.png)

**Comment by McGiverGim** [comment]
Good idea! I'm pretty sure there must be a library that helps with that.

**Comment by mikeller** [comment]
@richard-scott: See #926.

**Comment by richard-scott** [comment]
@mikeller  Great minds think alike 😀
When will that be working? Last nights  from master gave the screenshot in this issue and the issue you reference says that was meres into master 8 days ago?
