### ISSUE TITLE
10.2.0 MSP RX control stick emulation broken

### ISSUE THREAD

**Issue by jflyper** [betaflight/betaflight-configurator#961]
It begins with this
<img width="792" alt="betaflight-configurator_ _betaflight_configurator" src="https://user-images.githubusercontent.com/14850998/36878371-062b50e2-1e02-11e8-9030-b5c3ab2e979d.png">

Sticks don't work, sliders do.
<img width="795" alt="betaflight-configurator_ _betaflight_configurator" src="https://user-images.githubusercontent.com/14850998/36878426-4d75fa6a-1e02-11e8-9484-91517450cc28.png">

**Comment by McGiverGim** [comment]
I will take a look into it. I think it worked when I solved it but maybe I break it later.

**Comment by McGiverGim** [comment]
Fixed. If you can test it it will be great, but it seems to work at least for me.
