### ISSUE TITLE
Incorporate Velocity and Position. 

### ISSUE THREAD

**Issue by NeilGaede** [betaflight/betaflight-configurator#987]
It would be nice to add the new Velocity and Altitude variables to the "Sensors" tab at some point. Thanks!

**Comment by mikeller** [comment]
Neither of them are actually sensor values, and in particular for velocity, I can't quite see how you would get a useful readout from this while the craft is tethered. Maybe you can describe what you'd like to use these graphs for?

**Comment by NeilGaede** [comment]
True, Perhaps a Velocity and/or Altitude value then next to the X,Y,Z values in the tab that shows the quad orientation when you move the board. It might give a general idea how stable the altitude indication is going to be when using the alt-hold function. Just a thought.

**Comment by mikeller** [comment]
@NeilGaede: Yeah, having it as part of the model orientation view makes sense I think.

**Comment by NeilGaede** [comment]
Thanks for listening...
