### ISSUE TITLE
Debian package says licence is proprietary when installing on Ubuntu 17.10

### ISSUE THREAD

**Issue by infil00p** [betaflight/betaflight-configurator#989]
When opening the deb in the package manager, I get the following:

![screenshot from 2018-03-24 18-50-30](https://user-images.githubusercontent.com/2313/37870844-41bb433a-2f94-11e8-9b1b-04bc5cec660c.png)

**Comment by mikeller** [comment]
Are you referring to the 'Proprietary' listed as license?

**Comment by McGiverGim** [comment]
I don't know if this has changed, but some time ago this info was taken from the repository from which the package is installed, so I don't know if this has solution:
https://bugs.launchpad.net/ubuntu/+source/software-center/+bug/435183/comments/5

**Comment by McGiverGim** [comment]
Our copyright file (https://github.com/betaflight/betaflight-configurator/blob/master/assets/linux/copyright) does not conform the standard: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

But I've tried to conform the standard format and the result is the same. I don't know if I did it wrong or not.
